### ISSUE TITLE
Pan to coordinates

### ISSUE THREAD

**Issue by befreestudios** [mpetroff/pannellum#100]
It would be nice to be able to pan to specific coordinates via helper method. I'd like to have a button that when clicked will pan (and animate) to a specific hot spot. 

For example: ```<button onclick="panTo(x, y)"></button>```

Thoughts? I'll be taking a stab at it, if I have time, but I'd like to know your thoughts and how easy you think it would be to implement?

**Comment by mpetroff** [comment]
Added in c17ba06ad96b5ddca318c40c73b16df5662213ed as `lookAt` function.
