### ISSUE TITLE
How to change the loading page？

### ISSUE THREAD

**Issue by Asura1211** [mpetroff/pannellum#1003]
hi mpetroff!
Pannellum has really helped me a lot but now I have a confusion.
I use pannellum with Vue to realize the function of clicking different pictures to switch scenes. But each scene is an object instance, so there will be an initial loading page when switching. How can I remove or change the effect of loading the page?
（I have tried sceneFadeDuration，but this can only reduce the speed of picture switching in the same object instance ）

**Comment by mpetroff** [comment]
I don't know what you're asking. What do you mean by "initial loading page"? By "object instance" do you meaning calling `pannellum.viewer()` to create a new viewer instance? If so, I'd strongly discourage using such a pattern, since it creates a new WebGL context each time.

**Comment by Asura1211** [comment]
I am sorry for my expression. The "initial loading page" looks like the “Initial display page” in [pannellum.org](https://pannellum.org/documentation/examples/simple-example/). It will always appear when create a new viewer instance.

**Comment by SleepyShark709** [comment]
You can use events such as pannellum.loadScene () to switch scenes without having to create a new instance for each scenic spot

**Comment by Asura1211** [comment]
The problem has been solved. I’m grateful for your help！

**Comment by 016886611529a** [comment]
> The problem has been solved. I’m grateful for your help！


how did you solve it? can you share it with me ? i use div and  I want to click on the “div” list rendered at the bottom with vue to switch scenes. 
Thanks you
