### ISSUE TITLE
The clickHandlerFunc parameter dont work

### ISSUE THREAD

**Issue by Asura1211** [mpetroff/pannellum#1009]
Hi, mpetroff. Sorry to bother you again. 
My question now is how to use clickHandlerFunc correctly. I have use 

```javascript
hotSpots: [
              {
                pitch: -10,
                yaw: 0,
                type: "scene",
                sceneId: "place-three",
                cssClass: "custom-hotspot",
                createTooltipFunc: this.hotspot,
                createTooltipArgs: "someplace",
                clickHandlerFunc: this.clickHotspot,
                clickHandlerArgs: "args",
              },
            ],
```

to create the viewer instance, and the "clickHotspot" defined as follows(I am using Vue):

```javascript
clickHotspot(hotSpotDiv, args) {
      console.log(args);
 },
```
 
 but when I click the hotspots, I can't see any information on the console.

I have been struggling with this problem for a day, I want to know what went wrong. Thank you in advance for your help！

**Comment by mpetroff** [comment]
Are you sure `this.clickHotspot` is defined? I would recommend trying `clickHandlerFunc: function(d, a) {console.log(d, a)}`, and seeing if that works.

**Comment by Asura1211** [comment]
Thank you! I have known where the problem is. 
I set the sceneId so when I click to switch scene, the 'clickHandlerFunc' is not triggered. If I don’t use sceneId, the 'clickHandlerFunc' works.

**Comment by Asura1211** [comment]
Thank you! I have known where the problem is. 
I set the sceneId so when I click to switch scene, the 'clickHandlerFunc' is not triggered. If I don’t use sceneId, the 'clickHandlerFunc' works.

**Comment by mpetroff** [comment]
I'm not sure why having both defined doesn't work for you. You should end up with two different click handlers on the hot spot, and both the scene change handler and the custom handler should be called.

**Comment by Asura1211** [comment]
Thank you, I will try it again.
