### ISSUE TITLE
SHToolsError: Improper bounds for input variable. (For some input images (of uneven height?))

### ISSUE THREAD

**Issue by strarsis** [mpetroff/pannellum#1010]
@mpetroff: Trying out the latest pannellum (and its multires generator) for the amazing new preview feature.

It works in most cases, but for some input images this error at the end of the generation is thrown, 
with no `config.json` being outputted:
````
 File "\utils\multires\generate.py", line 301, in <module>
Traceback (most recent call last):
    shtHash = img2shtHash(np.array(Image.open(args.inputFile)))
  File "\utils\multires\generate.py", line 85, in img2shtHash
    r = pysh.expand.SHExpandDH(img[..., 0], sampling=2, lmax_calc=lmax)
  File "C:\Users\[redacted]\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\pyshtools\shtools\__init__.py", line 210, in wrapped_func
    raise SHToolsError(_shtools_status_message(returned_values[0]))
pyshtools.shtools.SHToolsError: Improper bounds for input variable.
````
All these input images got the correct `2:1` ratio (equirectangular projection).

From experience with previous multires generator-related issues I looked first at 
the resolutions of the input images as a possible reason for this error:

****Input images that work fine:****
- 12584 x 629**2**
- 12568 x 628**4**

****Input images that cause this error:****
- 12582 x 629**1**
- 12574 x 628**7**

And indeed, it appears that input images with an uneven height `[px]` cause this error.

Edit: Maybe uneven input image widths could also cause this issue? IMHO two additional tests should be added for testing the multires script: One for uneven input image heights and for uneven input image widths.

**Comment by mpetroff** [comment]
I just made a change to resize the image before calculating the SHT. This ensures the image dimensions are always even and probably speeds up the calculation, since the input image is smaller. The [documentation for the SHExpandDH() function](https://shtools.github.io/SHTOOLS/pyshexpanddh.html) states that the image height must be an even number, but I didn't notice that, and all the images I tested it apparently had an even height.
