### ISSUE TITLE
16bit vs 8bit input image

### ISSUE THREAD

**Issue by strarsis** [mpetroff/pannellum#1011]
Would using 16bit image files yield better results, when generating the cube faces or resampling these to lower resolution for tiling?

**Comment by mpetroff** [comment]
No, it would only cause problems. I would also consider the behavior of the multires `generate.py` script with a 16-bit input image to be undefined.

Higher bit depth images are meant for storing images with increased dynamic range but need to be converted to 8-bit images for web viewing (and viewing on non-HDR displays in general). The projection resampling is in regard to spatial dimensions, so the input and output images have the same bit depth. In theory, you'd have less rounding errors if you resampled a 16-bit image with the same dynamic range as an equivalent 8-bit image, but, in practice, you shouldn't be able to tell the difference.

**Comment by strarsis** [comment]
Thanks for your explanation. Will 16bit images become important when HDR is sufficiently supported in the web?

**Comment by mpetroff** [comment]
If you want to display HDR images (which is a personal preference), then yes. Both hardware and software support will be required. To the best of my knowledge, software support is still in the discussion and prototyping stage, so I suspect it will be a few years before we see widespread support on the web.
