### ISSUE TITLE
Change cursor to pointer over info hotspots

### ISSUE THREAD

**Issue by epignosis567** [mpetroff/pannellum#1013]
Hi. Is there a way to change the cursor to a pointer (little hand with index finger) when hovering over custom 'info' hotspots? It does it automatically for 'scene' types but it just remains an arrow for 'info' types.

I dug through the css file and found these classes but this did not work:

```
.pnlm-info-box,
.pnlm-info-box a, 
.pnlm-info-box p,
.pnlm-author-box a,
.pnlm-panorama-info,
.pnlm-hotspot.pnlm-info {
    cursor: pointer !important;
}
```

**Comment by mpetroff** [comment]
This will change the cursor for an `info` hot spot to a pointer:
```css
.pnlm-hotspot.pnlm-info {
    cursor: pointer;
}
```

**Comment by epignosis567** [comment]
Hmm... still doesn't work... any ideas? Here's an example of a hotspot I'm trying to get it to work on:

```
                        "type": "info",
                        "cssClass": "bird",
                        "pitch": 19,
                        "yaw": 155,                        
                        "createTooltipFunc": showTextAndPlaySound, 
                        "createTooltipArgs": ["L'Eve Future", "sounds/spectacle.mp3"]
```

**Comment by mpetroff** [comment]
As stated in the documentation for the `cssClass` parameter, the specified class is used instead of the default CSS classes. Thus, the `pnlm-info` class isn't used on the hot spot. You need to specify `cursor: pointer;` on your own class.

**Comment by epignosis567** [comment]
Thanks. But why do the scene hotspots retain their pointer cursor but not the info hotspots? I can go through and add a mouse pointer class to all the hotspots, just wondering if there's an easier way.

**Comment by mpetroff** [comment]
> But why do the scene hotspots retain their pointer cursor but not the info hotspots?

Scene hot spots have a click action and act as a button, so they are always given a pointer cursor by default (the class specified by the `cssClass` parameter replaces the `pnlm-scene` class, not the `pnlm-pointer` class). Info hot spots don't act as a button by default, so they aren't assigned a cursor.

> Also, how could I add a second class to the cssClass parameter? I tried this but it didn't work

The documentation clearly states that the `cssClass` parameter must be a string, so of course it's not going to work if you provide an array. Only adding one CSS class is officially supported.

**Comment by epignosis567** [comment]
Thanks. I have so many hotspots, what if I just changed all the info hotspots to scenes in order to retain the pointer? Could that cause any serious problems?

**Comment by mpetroff** [comment]
The pointer is dependent on the the existence of `URL` or `sceneId` attributes on the hot spot. The `type: scene` attribute only affects the icon shown.
