### ISSUE TITLE
Protect hotspot elements from outside CSS perspective property

### ISSUE THREAD

**Issue by strarsis** [mpetroff/pannellum#1014]
After loading a pannellum panorama viewer in a lightbox (iframe), I noticed that all hotspot elements disappeared. 
They can still be found at their correct position when inspecting them - but they are invisible.

The reason is that this particular lightbox also adds a `perspective` CSS property to itself, 
which also affects the hotspot elements inside the pannellum standalone HTML inside the iframe element.
This also seems to happen only with Chrome, the issue doesn't happen in e.g. Firefox.

Minimal reproducible test case (no iframe necessary, just setting the 
CSS `perspective` property with any non-unset value to a parent:
https://codepen.io/strarsis/pen/wvdyYge

A simple solution is setting `transform: ` on a parent of the hotspot elements, e.g. the pannellum viewer container element:
````
.pnlm-container {
  transform: translateZ(0);
}
````

Would it therefore be a good idea to add this style by default to Pannellum so it is ensured that the hotspot are visible even if somewhere outside of it the CSS `perspective` property has been set?

Edit: Apparently this fix only works with non-iframed elements. When an iframe is used with `perspective` set, the issue still persists, even with this fix.
Minimal reproducible test case for iframe embed issue:
https://codepen.io/strarsis/pen/BaRrQwR

**Comment by mpetroff** [comment]
The issue with the `<iframe>` is a bug with Chrome, since CSS on the parent page should not affect the contents of the `<iframe>`. You should probably report it on Chromium's issue tracker.

The issue without the `<iframe>` is possibly also a browser bug, since it works fine in Firefox and since setting the `perspective` property also breaks the display of Pannellum's controls, which don't use transforms. Regardless, there are countless obscure ways to break Pannellum using outside CSS, so we're never going to avoid all conflicts. In this particular case, I worry if there might be unintended side effects (such as performance regressions) to setting `transform: translateZ(0);`, so I don't want to include it by default.

**Comment by strarsis** [comment]
I created a new issue on the Chromium issue tracker: https://bugs.chromium.org/p/chromium/issues/detail?id=1234479

Yes, I agree with your opinion on adding extra workaround styles for this very browser-specific bug.

**Comment by strarsis** [comment]
I just revisited the test case and now both `iframes` correctly show the hotspot element, despite the 2nd `iframe` having `perspective` applied on it.
The bug in the Chromium issue tracker hadn't changed though and its status still being `Available (Open)`.

@mpetroff: When you view the test case, does the hotspot (red rectangle) now also appear in both `iframes` now?

**Comment by mpetroff** [comment]
I ran the test case through a series of Chrome versions with Sauce Labs. The first version where it was broken was Chrome 75, and it seems to have been fixed in Chrome 97. While it finally works again, it was broken for ~2.5 years.

**Comment by strarsis** [comment]
@mpetroff: Thanks for the efforts! Can I mention you and these results in the chrome issue tracker (https://bugs.chromium.org/p/chromium/issues/detail?id=1234479)?

**Comment by strarsis** [comment]
@mpetroff: Thanks for the testing efforts! Can I mention you and these results in the relevant [Chromium issue](https://bugs.chromium.org/p/chromium/issues/detail?id=1234479)?

**Comment by mpetroff** [comment]
I just commented on the issue with what I said here.
