### ISSUE TITLE
how to customize right mouse button event ?

### ISSUE THREAD

**Issue by HellsingMatt** [mpetroff/pannellum#1016]
i want show something like context menu when click right mouse button, or longpress on touchscreen, 
but when i do so, "pannellum 2.5.6" labal show up,

then what should i do to stop or customize this ?

i tried: 
```
viewer.on('mousedown', e => {
  e.preventDefault()
}
```
but didnt work

**Comment by mpetroff** [comment]
While disabling the right-click attribution is allowed by the license as long as you don't remove the license information from the JavaScript file, I'm not going to tell you how to remove it.

**Comment by mpetroff** [comment]
Your snippet doesn't work since it only disables the default `mousedown` action (which is already done), not the previously installed event handlers.

**Comment by HellsingMatt** [comment]
😂😂😂okey, anyway, thx for reply,

i will try add some buttons on surface to add/remove/edit hotspot and so on
