### ISSUE TITLE
Does this work with Ricoh Theta S images?

### ISSUE THREAD

**Issue by tenold** [mpetroff/pannellum#102]
Looking for an open source solution for embedding and controlling images from a Ricoh Theta S.

They produce equirectangular images.

**Comment by befreestudios** [comment]
I have done the exact same thing for a demo.... hit me up.

**Comment by mpetroff** [comment]
Yes. The development version (soon to be a new release) even supports the Theta's pitch and roll metadata, so Ricoh's desktop software doesn't need to be used to level the panorama beforehand.

**Comment by kvandivo** [comment]
Hi.

Based on my testing the current version does not work with pitch and roll if a multres image is created via generate.py.

On   https://github.com/mpetroff/pannellum/issues/113   you mention that for some things you can copy the metadata from the jpg into the config.json file.  A couple of things....

1) Can generate.py just create a config.json file that already has those parameters set?
and
2) what config.json parameters do we need to set to have the 

  horizonPitch: getTag('GPano:PosePitchDegrees'),
  horizonRoll: getTag('GPano:PoseRollDegrees')

set as they should be?

Thanks!

Kirby

**Comment by mpetroff** [comment]
I'm somewhat hesitant to introduce a new dependency to `generate.py` (although, I probably could just port my JavaScript implementation to Python directly). The code that corrects the pitch and roll is part of the WebGL shader for displaying equirectangular panoramas and therefore doesn't work with multires or cubemap panoramas. You also can't set the parameters in the JSON configuration (I probably should fix this for equirectangular images). For now, you need to correct the horizon before passing the image to `generate.py`, e.g. with Ricoh's utility or Hugin.

**Comment by kvandivo** [comment]
OK.  Out of curiousity, anyone know if there's a hugin command line to do
this step?  I'm creating a workflow for real estate and since it appears
that all that is happening is that a exif tag is being used, seems like
that could be quite automated..  It's been a while since I've used hugin
and thought I'd ask before digging.


Kirby Vandivort

**Comment by kvandivo** [comment]
Paul Dunning had written a mac/windows program to autolevel theta images (  http://www.worldofpaul.com/theta/  ) and he was quite helpful in providing me with the steps he was calling.  Here's a quick little shell script to do the leveling that his program does:

> #!/bin/sh
> 
> ifile=$1
> ofile=$2
> 
> pitch=\`exiftool  -s -s -s -ricohpitch $1\`
> roll=\`exiftool  -s -s -s -ricohroll $1\`
> 
> pto_gen $1 --projection=4 --fov=360 -o tmp.pto >| /dev/null
> pano_modify --canvas=AUTO --rotate=0,$pitch,$roll tmp.pto -o tmp.pto >| /dev/null
> 
> pto2mk -o tmp.mk -p $1 tmp.pto >| /dev/null
> 
> make -f tmp.mk all clean  >| /dev/null
> 
> convert $1.tif -quality '100' $2 >| /dev/null
> 
> rm tmp.mk
> rm tmp.pto
> rm $1.tif

**Comment by mpetroff** [comment]
Here's how to use Hugin for this:
```bash
pto_gen image.jpg
pano_modify --canvas=AUTO --rotate=0,PITCH,ROLL -o image.pto image.pto
nona -m JPEG -z 90 -o image_corrected.jpg image.pto
```
where `PITCH` and `ROLL` are the panorama's pitch and roll offsets, respectively.

If you're using Linux, here's a shell script that will do it:
```bash
#!/bin/bash

if [ $# -gt 0 ]; then
    pto_gen $1
    FILE=$1
    BASE=${FILE%%.*}
    pano_modify --canvas=AUTO --rotate=0,`exiftool -XMP:PosePitchDegrees -s -s -s $1`,`exiftool -XMP:PoseRollDegrees -s -s -s $1` -o $BASE.pto $BASE.pto
    nona -m JPEG -z 90 -o "$BASE"_corrected.jpg $BASE.pto
    rm $BASE.pto
else
    echo "Usage: $0 image.jpg"
fi
```

**Comment by mpetroff** [comment]
Apparently I should have reloaded the page before replying.

**Comment by kvandivo** [comment]
I like aspects of yours as it chops out a few commands.  nona -m JPEG
doesn't work for me.  That might be a hugin 2015 option.  Strangely, when I
do nona help it tells me JPEG is a supported output option, but under the
specifics for -m it lists:

      -m str     set output file format (TIFF, TIFF_m, TIFF_multilayer,
EXR, EXR_m)




Kirby Vandivort
