### ISSUE TITLE
get nearby hotspots by camera orientation

### ISSUE THREAD

**Issue by vlkpa** [mpetroff/pannellum#1020]
Hello, do you think, it is possible to create something like [this](https://www.kamp.galeb.hr/EasyEdit/UserFiles/virtualna-setnja/index.html?s=pano3277&tour_language=en) in pannellum?  How to get center of the camera orientation on mouse move?(It should work on mobile) I want to show description of hotspot, when orientation of camera is nearby the hotspot.

**Comment by mpetroff** [comment]
You can use the `getPitch()` and `getYaw()` API methods to get the camera orientation. You'd then need to get the list of hot spots from the configuration using the `getConfig()` API method and calculate the angular distance to each hot spot to find the closest one. If you assign a different CSS class to each hot spot using the `cssClass` attribute, you can then change the appearance of the closest hot spot.
