### ISSUE TITLE
Make Panorama one large link

### ISSUE THREAD

**Issue by L00ncan** [mpetroff/pannellum#1021]
I need to use tens of thousands of panoramas and looking for the simplest solution, my tours are on my website on thumbnails like a sports section page (really science though) and when you click the panorama you go to /page-1, /page-124 or /page-589.html

My issue only seems complicated due to the vast numbers i'm using, but! all i'm wanting is the entire Panorama to be a link, can i do this?

All my worries solved with that one issue fixed, tours won't work for me due to the large numbers i'm dealing with. Can i do this?

**Comment by L00ncan** [comment]
They think they're on a google map tour, they try and click the Panorama for "google" to take em elsewhere and bam, they go to my website through the iframe code, it would be really perfect for me

**Comment by mpetroff** [comment]
I don't really know what you're asking.

**Comment by L00ncan** [comment]
So! i'm wanting the user to be able to browse the image while at the same time if they double click the image or force move the image similar to how you force scroll on google street view it'll nag them with a new window?  i need the Panorama being drag interactive yet at the same time if you click it it'll open a link. If your still wondering if my feature request is common its actually a very common feature in videogame mmo loots, you can drag stuff in mmo loots but if you remotely click your loot it'll open a whole host of popup windows.
.
I want them to be able to still browse the panorama but if they nag the screen it'll open a new window, is this possible?

**Comment by L00ncan** [comment]
I literally need to do this with 6 thousand+ hi-res panoramas so getting this correct is imperative to me, btw i love your panorama player its wonderfully simplistic compared to the bloatware out there :)

**Comment by mpetroff** [comment]
A `dblclick` event listener will only activate on double clicks, so you can interact with the viewer normally, as long as you don't double click.

**Comment by L00ncan** [comment]
How do i implement this into the player, i'm not a coder

**Comment by mpetroff** [comment]
Adding a `dblclick` event listener to a `<div>` element is not Pannellum specific. This isn't a introductory web development help forum, so it isn't the place to ask for that kind of assistance.

**Comment by L00ncan** [comment]
Okay i'll look around for an introductory forum if its an external problem, tnx
