### ISSUE TITLE
How can we use this in react 

### ISSUE THREAD

**Issue by h4riharan** [mpetroff/pannellum#1023]
While using react-pannellum package, we can able to display the pannellum but while using two or more pannellum in one page we are facing conflicts between the scenes and the scene's panorama is not opening even though we gave the sceneId and panaroma image source we are trying to solve this but it seems we can only use One ReactPannellum in one page. Is there any way to use multiple ReactPannellum in one page and add tour for each one of them.

Is there any solution for this, Kindly suggest us a right way to use the pannellum in react
Thank you

**Comment by mpetroff** [comment]
Please read the documentation. Per the readme:
> Mobile / app frameworks are not officially supported. They may work, but they're not tested and are not the targeted platform.

This is not the issue tracker for "ReactPannellum", which is unaffiliated with the development of Pannellum. If you have an issue with it, you can bring it up on its issue tracker.
