### ISSUE TITLE
Get x, y and z axis values for pitch and yaw of hotspot

### ISSUE THREAD

**Issue by bunny-vostro** [mpetroff/pannellum#1025]
I am trying to get x, y and z values of hotspot for which basically we need value of distance of hotspot and viewer?

if we get it value of z will be Sin(pitch)* distance of hotspot with camera ??

so is there anyway to calculate the distance of hotspot and viewer position for any hotspot ?

**Comment by mpetroff** [comment]
The hot spots are only defined in terms of angular position. The standard conversion between spherical coordinates and Cartesian coordinates applies, although the choice of radius is arbitrary. The Wikipedia page on spherical coordinates gives you the conversion formulas (in terms of the notation there, yaw is φ and pitch is θ): https://en.wikipedia.org/wiki/Spherical_coordinate_system#Coordinate_system_conversions

However, I'm not sure if that is what you're actually trying to do. If you're trying to calculate the angular distance, the [standard formulas](https://en.wikipedia.org/wiki/Angular_distance) apply. If you're interested in physical distance, i.e., distance on a map, this quantity is meaningless to Pannellum and can't be derived from hot spot coordinates. You'd have to keep a list of scene positions outside of Pannellum and use those to calculate the distances.
