### ISSUE TITLE
Horizon Pitch/Roll functions for each scene

### ISSUE THREAD

**Issue by T2brozz** [mpetroff/pannellum#1026]
Hey is it possible to use `setHorizonPitch` ,`getHorizonPitch` , etc. for individual scenes instead of overwriting the values in default?

**Comment by mpetroff** [comment]
The `setHorizonPitch` function (like `setPitch`, `setYaw`, etc.) does not overwrite the default value; it sets the current value. When you change the scene, the value is loaded from the configuration. Reloading the same scene after calling `setHorizonPitch` will reset the horizon pitch to that in the configuration. If you want to more permanently change a value, you need to replace the scene configuration using `addScene`.
