### ISSUE TITLE
Problem with fixed/sticky position

### ISSUE THREAD

**Issue by ghost** [mpetroff/pannellum#1031]
Hi. I tried to use pannellum, but fixed menu didn't allow to do it. 3D scene crashes, when I am scrolling (on PC). I think, that it is problem with pannellum? https://ramtrucks.kz/trx/

![image](https://user-images.githubusercontent.com/61416690/133791495-fc5d2777-040c-4c48-ac0a-45896fdccd95.png)

**Comment by mpetroff** [comment]
I have no idea what you're trying to say. What 3D scene? It took me a while to find the panorama since I can't read Cyrillic, but once I found it, it worked fine for me.
