### ISSUE TITLE
Status of the library

### ISSUE THREAD

**Issue by arnoldsi-vii** [mpetroff/pannellum#1035]
Is this library still maintained by the developers?  I saw that last release was almost 2 years ago.
Thank you

**Comment by mpetroff** [comment]
Did you bother to look at the commit history or issue tracker before opening this issue, or do you just like wasting my time? There have been two dozen commits this year, and I've made dozens and dozens of comments on the issue tracker.

**Comment by mpetroff** [comment]
Your question showed a complete lack of respect of my time, so you're entitled to nothing. You're already getting the library for free and are even getting a response. You don't need like my response, but you can't claim the moral high ground.
