### ISSUE TITLE
Failure to load under IE11 b/c it does not support readAsBinaryString method

### ISSUE THREAD

**Issue by ArturGajowy** [mpetroff/pannellum#104]
Hi!

The error seems to be [here](https://github.com/mpetroff/pannellum/blob/master/src/js/pannellum.js#L462):
```
    reader.readAsBinaryString(image);
```

or at least that's the place where IE11 blows up :)

Thanks for all the great work!

**Comment by mpetroff** [comment]
I think I fixed the bug, but I don't currently have access to a Windows machine to test on. Let me know if the fix works. Thanks for the report.
