### ISSUE TITLE
Change/update draggable and other parameters

### ISSUE THREAD

**Issue by FanManutd** [mpetroff/pannellum#1048]
Hi, thank you for this plugin, great job! 

Can i update draggable (or other boolean) parameter?

For example:

```
const plugin = pannellum.viewer(container, {
      type: 'equirectangular',
      panorama: '.example.jpg',
      autoLoad: true,
      mouseZoom: false,
      draggable: false,
});

plugin.setDraggable(true);

```
or 

`plugin.draggable = true;`

**Comment by mpetroff** [comment]
Not directly. If you add a new scene with new configuration parameters and then load it, you can change most of the parameters, but there are still some, e.g., `mouseZoom`, that can only be set during the initial initialization (event listeners are only added on initialization).

**Comment by FanManutd** [comment]
> Not directly. If you add a new scene with new configuration parameters and then load it, you can change most of the parameters, but there are still some, e.g., `mouseZoom`, that can only be set during the initial initialization (event listeners are only added on initialization).

Thank you)
