### ISSUE TITLE
Examples do not work in iOS 9.2

### ISSUE THREAD

**Issue by djSeverin** [mpetroff/pannellum#105]
Examples do not work in iOS 9.2.

Have tried both Safari and Chrome for iOS (47.0.2526.107).

How to reproduce for examples example.htm and example-tour.htm:
- Clone pannellum project master branch;
- Place files onto web server;
- Open local web server location in iOS browser (Chrome or Safari);
- Navigate to /examples
- Open example htm or example-tour.htm.

Outcome:
- 'Click to Load Panorama' mask displayed
- Tap 'Click to Load Panorama' mask;
- Image load progress moves to 100%;
- Mask does not vanish & panorama is not loaded.

I have tried converting examplepano.jpg to progressive encoding using jpegtran, however it has the same outcome.

====

example-cube.htm 'sometimes' loads. It will either begin loading and crash the browser, or it will load and function for < 30 seconds, and then crash the browser.

**Comment by mpetroff** [comment]
This bug was introduced two days ago while fixing #104. Safari has incomplete ECMAScript 6 support; specifically, it lacks an `indexOf` method for typed arrays. I just fixed this.
