### ISSUE TITLE
3d image as a spinning object

### ISSUE THREAD

**Issue by stefandjikic** [mpetroff/pannellum#1053]
Hi there!

I'm trying to create a 360-degree image, not as a panorama view but as a product view from different angles. An example would be a spinning car on mouse drag. Here is the example:  
[https://spins.spincar.com/vroommanheimnewengland/wddzf4kb9ha085539#hidecarousel!disabledrawer!disableautospin!disablewatermark!hidevehiclehits!stscolor=0F3A7B%2CFC4349%2CE7131A](https://spins.spincar.com/vroommanheimnewengland/wddzf4kb9ha085539#hidecarousel!disabledrawer!disableautospin!disablewatermark!hidevehiclehits!stscolor=0F3A7B%2CFC4349%2CE7131A)

Is this something that can be done with pannellum?
Many thanks!

**Comment by mpetroff** [comment]
No, that's outside the scope of Pannellum. See further discussion in #604.
