### ISSUE TITLE
[Q] Custom max zoom level

### ISSUE THREAD

**Issue by INF800** [mpetroff/pannellum#1056]
Hi, for multires view, can we change ```"maxLevel": 4,``` during runtime or is it harcoded?

References: 
- https://github.com/mpetroff/pannellum/issues/987#issuecomment-844405570
- https://github.com/mpetroff/pannellum/blob/308d86ecd9ba8da7210b3cf922fe38b4de976cd6/utils/multires/generate.py#L198
- https://github.com/mpetroff/pannellum/blob/308d86ecd9ba8da7210b3cf922fe38b4de976cd6/examples/example-multires.json#L12

**Comment by mpetroff** [comment]
That tells the viewer how many zoom levels are contained in the multires tiles. If you increase it, you'll cause the viewer to try to load tiles that don't exist when you zoom in all the way; if you decrease it, you won't load the highest-resolution tiles even if you zoom in all the way.

You can change the calculation in the `generate.py` script, which will cause a different number of zoom levels to be generated. However, the existing calculation should be optimal.

**Comment by INF800** [comment]
Thanks, will try different levels during generation process and drop issues here if I come across any.

**Comment by INF800** [comment]
Solved thanks.
