### ISSUE TITLE
Load image facing north

### ISSUE THREAD

**Issue by iFieldSmart-Tech** [mpetroff/pannellum#1057]
Hi, I am trying to look for a way to load the image facing north by default but am not able to find anything. It is for image comparison and I want to start both images facing north so that they are calibrated by default. Regardless of where the user is facing when the photo is clicked, if we load it facing north, it should automatically put both images in the same view as long as they were taken from the same spot. Any pointers?

**Comment by mpetroff** [comment]
The `yaw` configuration parameter sets the starting view direction when a panorama is loaded (except if changed by the hot spot `targetYaw` parameter or by the `yaw` argument of the `loadScene` function). However, if you have the `northOffset` parameter set, you'll need to account for it yourself when setting the `yaw` (the `northOffset` parameter only affects the compass display).

**Comment by iFieldSmart-Tech** [comment]
Okay. Thank you for the information. I will try setting it manually using yaw.
