### ISSUE TITLE
Android panorama size cap? 

### ISSUE THREAD

**Issue by PaulKsi** [mpetroff/pannellum#1061]
Hello, why there is a cap on panorama size on android? other libraries like panolens dont have this issue? its too much work to render everything for several devices.. has anybody find any solution, thanks!

[link panellum](https://codepen.io/AptusTim/pen/xMoqdW)

[link panolens](https://codepen.io/paulksi/pen/oNGQmww)

**Comment by mpetroff** [comment]
You're going to have to be a bit more specific as to your issue. In v2.5.6, equirectangular panoramas up to 8192px across should be supported by all devices.

**Comment by mpetroff** [comment]
Never mind. You're using an ancient release of Pannellum, v2.4.1, which was released almost four years ago. If you update to the current release, it should work.

**Comment by PaulKsi** [comment]
> Never mind. You're using an ancient release of Pannellum, v2.4.1, which was released almost four years ago. If you update to the current release, it should work.

wow, my bad, thank you so much!!! :clap:
