### ISSUE TITLE
WARNING: Too many active WebGL contexts. Oldest context will be lost. pannellum.js:12

### ISSUE THREAD

**Issue by samedadl** [mpetroff/pannellum#1068]
Hi,

I use Pannellum to show my panoramic images with the map. As a general logic, when I click on the point on the map, the panoramic viewer works. My code worked, but after clicking on the 16th point, I get a webgl error (WARNING: Too many active WebGL contexts. Oldest context will be lost. pannellum.js:12) and my map screen disappears. 

![image](https://user-images.githubusercontent.com/65896123/151299102-740bb504-14b2-4caa-a914-5b90a5fe27cd.png)
<p align="center"> figure1: Before The Error </p>

![image](https://user-images.githubusercontent.com/65896123/151301859-7474eaaf-497f-4666-88f4-632ace71811f.png)
<p align="center"> figure2: After The Error </p>

Every time I click on the point on the map, it creates a new viewer. What can I do about it? The relevant parts of the code are below. 

```javascript
async function getAttachments(featureLayer, objectIds) {
      const attachmentRes = await featureLayer.queryAttachments({
        objectIds
      });
      attachments = attachmentRes[objectIds];
    }

    function handleAttachmentNodes() {
      clearAttachmentNodes();
      generateAttachmentNodes();
    }

    function clearAttachmentNodes() {
      const sidePanel = document.getElementById("sidePanel");
      while (sidePanel.firstChild) {
        sidePanel.removeChild(sidePanel.lastChild);
      }
    }

    function generateAttachmentNodes() {
      attachments.forEach((attachment) => {
        const attachmentNode = createAttachmentNode(attachment);
        panorama = attachment.url
 });
      const pv = PanViewer(panorama)
      console.log(1)
}

    function PanViewer(panorama) {
      const viewer = pannellum.viewer('sidePanel', {
        author: "Samed Adalı",
        autoLoad: true,
        type: "equirectangular",
        panorama: panorama,
      })
}

    function createAttachmentNode(attachment) {
      const attachmentNode = document.createElement("img");
      attachmentNode.classList.add("attachment-item");
      attachmentNode.src = attachment.url;
      return attachmentNode;
    }

 ```
Thanks in advance for your help.

**Comment by mpetroff** [comment]
> What can I do about it?

You can create a single viewer the first time and then reuse it subsequently. You can do this by adding each subsequent image as a new scene with `addScene` and immediately switch to it with `loadScene` (and optionally then use `removeScene` to remove the previous scene configuration).

**Comment by samedadl** [comment]
Can you share with me a sample code of ```addScene``` and ```loadScene```? I haven't seen any examples. I read from the document, but I couldn’t succeed. I’m a kind of new to this stuff.

**Comment by samedadl** [comment]
Hi,

For anyone else reading this in the future, I defined an empty viewer and destroyed the previous viewer in the if loop.
```javascript
let viewer = '';
function PanViewer(panorama, att_id,scene) {
    if (viewer) {
      viewer.destroy();
    }
 const viewer = pannellum.viewer('sidePanel', {
        author: "Samed Adalı",
        autoLoad: true,
        type: "equirectangular",
        panorama: panorama,
      })
```

**Comment by mpetroff** [comment]
I wouldn't recommend doing that, since you can still end up with WebGL context issues that way. It's better to use something along the lines of (I'm assuming `panorama` is a URL, i.e., a string):
```javascript
let viewer;
function PanViewer(panorama) {
    if (!viewer) {
        // If viewer doesn't exist, create it in tour mode with the first panorama
        const config = {
            'default': {
                'autoLoad': true,
                'type': 'equirectangular',
                'firstScene': panorama,
            },
            'scenes': {}
        }
        config.scenes[panorama] = {panorama: panorama};
        viewer = pannellum.viewer('sidePanel', config);
    } else {
        // If the viewer already exists, add the new panorama as a new scene,
        // switch to it, and remove the old scene configuration
        const oldScene = viewer.getScene();
        viewer.addScene(panorama, {
            panorama: panorama
        });
        viewer.loadScene(panorama);
        viewer.removeScene(oldScene);
    }
}
```

**Comment by samedadl** [comment]
Hi Matthew,

Yes panorama is a url. I tried your code but it doesn't work. The else part in the code does not bring the new panorama.

![image](https://user-images.githubusercontent.com/65896123/153180091-eb903893-4aa3-4226-9f12-b8cac7241378.png)
figure1: clicked first point

![image](https://user-images.githubusercontent.com/65896123/153180164-43abb27d-edba-4ab0-a185-685e1d16fb1b.png)
figure2: clicked second point

**Comment by samedadl** [comment]
![image](https://user-images.githubusercontent.com/65896123/153700410-afde67f1-8c91-4636-8095-3b0af24ef2a3.png)
I use v2.5.6 and the latest development version and there are no error messages in the developer console. I try chrome and opera.

**Comment by jerryComo** [comment]
Yup - I couldn't get this working either . Loads up fine, but won't load a new scene (or the old screen either) . Not sure why.  Am integrating it with a Vue3 project.

```
 if(!viewer)
      {
        const config = {
            'default': {
                'autoLoad': true,
                'type': 'equirectangular',
                'firstScene': 'test',
            },
            'scenes': {}
        }

        config.scenes['test'] = 
        {
          panorama: props.image,
          haov: props.haov,
          vaov: props.vaov,
          autoLoad: true,
          showControls: false,
          hfov: 100,
          yaw: props.yaw,
        
        };

        viewer = window.pannellum.viewer('pano', config); // this loads up just fine :)
        viewer.setYawBounds(props.bounds);
    

      }else{ 

        const oldScene = viewer.getScene(); // this sees the correct scene Id
        viewer.addScene('newScene', {
            panorama: props.image,
            haov: props.haov,
            vaov: props.vaov,
            autoLoad: true,
            showControls: false,
            hfov: 100,
            yaw: props.yaw,
        });
        viewer.loadScene('newScene'); // this won't load anything up, even if I put in 'test' 
        viewer.removeScene(oldScene);

      }
```

**Comment by mpetroff** [comment]
> Am integrating it with a Vue3 project.

I'm sure Vue is doing something strange. As mentioned in the readme, frameworks like this aren't officially supported, because I have neither the time nor the motivation to try to debug these sorts of weird issues.

My guess is that there's probably some sort of asynchronous issue with `props` changing. You can try wrapping your scene configurations with `structuredClone()` and see if that helps, as it will create a deep copy.
