### ISSUE TITLE
flickering in full screen mode

### ISSUE THREAD

**Issue by kvandivo** [mpetroff/pannellum#107]
Hi.  On both mac os x and android, I'm experiencing flickering between two zoom levels when I go full screen.

https://youtu.be/Ffc9SUfrK_0

is an example of it.  The flickering is very quick switching between the two zoom levels (much faster than the video was able to capture).

I'm using the latest pannellum from git, with no real changes beyond a callback that I added (the flickering was there without the change, though).  I also experience the flickering on android.  On an android tablet (Project Tango tablet) it flickers in regular mode but not in fullscreen.

Anything else I can provide for additional information?  It doesn't seem to be tied to the existence of hotspots or anything like that.  Just a generic scene with "nothing" causes the problem as well.

Thanks much.

**Comment by hhkaos** [comment]
Hi guys, the right youtube link: https://www.youtube.com/watch?v=Ffc9SUfrK_0 ^_^

**Comment by kvandivo** [comment]
One other thing that I had thought of...  I wonder if it is related to the size of the original image.  It's from a ricoh theta m15 (so 3584x1792).  The reason I ask this is that the 'library' scene on pannellum.org does NOT flicker.  Only images from the theta m15.  The json file is at:  

https://www.aroundcu.com/getTour.php?num=2120987&scene=3023

(disclaimer:  There's a bunch of other text in there.  When I was creating the code for it I inadvertently had hotSpots as hotspots for a bit and caused some spurious text to show up there.)

**Comment by kvandivo** [comment]
One additional point I'll make, since Matthew had recently mentioned specific theta metadata support..  These images, while from a theta, have been created in photoshop by HDRing multiple source files.. so the theta metadata almost certainly is not there.

**Comment by kvandivo** [comment]
In fact.. here's the JPG that was fed to 'generate.py' in case anyone wants to play with it..

https://www.aroundcu.com/110downEntry.jpg

**Comment by Linwood-F** [comment]
When I first tried the released version I got something similar, but it went away when I compiled it from git.  I just tried yours, however, on my compilation and I see something similar to what you are seeing (running the server side on ubuntu, and client as Chrome on windows).   Definitely strange, and something I do not see on any of mine.   Sorry, nothing useful to offer except confirmation it doesn't work.   Perhaps something to do with being such low resolution and trying to use multi-res?

**Comment by mpetroff** [comment]
It turns out this bug was related to small multires panoramas (neither browser specific nor full screen related). There's a calculation done for the maximum zoom for multires, which would override the `config.minHfov` value. If the panorama was small enough compared to the viewer size, the maximum zoom would be less than the minimum zoom, causing the panorama to flipflop between these two zooms every other frame. In your case, switching to full screen triggered this as it made the viewer big enough.

I fixed this by changing Pannellum's behavior to only use the multires zoom calculation if it increases the maximum zoom (instead of decreasing it). I also added a check that will disable zooming if the zoom bounds don't make sense.

**Comment by kvandivo** [comment]
Hi,

Thanks so much.  Your fix definitely seems to have fixed the flickering
zoom level issue.  But, it appears to have introduced a different bug (or
exposed a different bug, at least).

Video:

https://www.youtube.com/watch?v=YdeuEdWSFU0

What is now happening... after I scroll around just a bit in a scene, non
full screen, the zoom level jumps.  Where it jumps seems deterministic.. On
of my scenes it zooms out about hfov: 5 and on another scene it zooms in
all the way.  I don't know to make of that...

Also, on my android project tango tablet after a bit of scrolling the
screen turned black.  I don't know how to get any debugging aids on the
tablet to help figure out why that is.. but I was able to get the black
screen on the desktop once as well.  (black screen being zoom
in/out/fullscreen showing, but no picture)

Thanks!


Kirby Vandivort

**Comment by mpetroff** [comment]
I can get small jumps in zoom when scrolling slowly, which have to do with when the browser fires the scroll event (I don't think there's anything I can do about this). However, I'm unable to reproduce anything as pronounced as your video. I can't reproduce the black screen either. Sorry.
