### ISSUE TITLE
Adsense

### ISSUE THREAD

**Issue by L00ncan** [mpetroff/pannellum#1070]
Is it possible to add adsense to my pano player, if people hotlink and use my popular images by throttling my resources it wouldn't be a problem if i could enable adsense, i use your amazing panorama player as a nasa nerd star guide, if one of my 20mb milkyway images becomes amazingly popular it'll slow my modest server resources. If i can enable adsense it would fund my modest resources instead of burdening my server.

**Comment by L00ncan** [comment]
update: - oh yeah! forgot to mention with an option to hide the adsense (x) so people can gaze at my nerdy 20mb images without visible obstruction.

**Comment by mpetroff** [comment]
You can add whatever you want to the page you're using it on. You can also overlay content on the viewer, e.g., as is done in [the custom controls example](https://pannellum.org/documentation/examples/custom-controls/).

**Comment by L00ncan** [comment]
i can't find a file labelled Overlay content or Custom Controls, i'm not a coder.
.
I'll probably add an infolinks instead of my adsense cause infolinks has a neat close ability, i don't know which file to edit to add my javascript so it shows on my player.
.
Trying to add this
```
<script type="text/javascript">
var infolinks_pid = 3356228;
var infolinks_wsid = 0;
</script>
<script type="text/javascript" src="//resources.infolinks.com/js/infolinks_main.js"></script>
```

**Comment by mpetroff** [comment]
There's nothing named "overlay." The custom controls in that example are overlaid on the viewer. You can overlay other content in the same manner that that was done.

**Comment by L00ncan** [comment]
That tutorial is very limited it doesn't tell you what file to edit, i don't know which file to edit

**Comment by mpetroff** [comment]
It's an example, not a tutorial. You can overlay content on the viewer the same way you'd overlay it on any other `<div>` element.

I've pointed you in the direction of what you need, but I have neither the time nor the motivation to explain basic HTML / CSS, so the rest is up to you. Unless you formulate a concrete question specific to how such content interacts with Pannellum, there's not much more for me to do.

**Comment by L00ncan** [comment]
Okay fine, i was just a little confused with the Pannellum 50 kb version VS the 12mb version. So i uploaded both onto my server and forgot which one i was linking too in my spaghetti code. So i messed around with the 50kb version first and it seemed to work fine. I need to ask this however, i'm freelancing for a large known big brand, would i be correct on telling them that they can place advertisements on your creation or is that illegal from your optics

**Comment by L00ncan** [comment]
They're now asking for ad html placements i hope i'm not breaking your copyrights, i am sincere which is why i ask.

**Comment by mpetroff** [comment]
Your client's attorneys are free to review the license, but it allows for commercial use:
https://github.com/mpetroff/pannellum/blob/master/COPYING
