### ISSUE TITLE
Inverse viewer controls

### ISSUE THREAD

**Issue by paulks-software** [mpetroff/pannellum#1073]
Hello, i am making a hybrid app between panellum & babylon and i need inverse controls in pannellum, how to achieve this? maybe there is a parameter to a pannellum viewer? thank you
babylonjs sample [https://playground.babylonjs.com/#14KRGG#3](https://playground.babylonjs.com/#14KRGG#3)

**Comment by mpetroff** [comment]
There's no such parameter, since I want to keep the user experience consistent. I wrote more about this several years ago (and my opinion on the matter hasn't changed): https://github.com/mpetroff/pannellum/issues/83#issuecomment-122928499
