### ISSUE TITLE
Logic behind generate.py

### ISSUE THREAD

**Issue by tokidoki11** [mpetroff/pannellum#1077]
Hi, It will be very nice if the logic behind generate.py is written somewhere
I saw only how to use it

Thanks

**Comment by mpetroff** [comment]
It projects the panorama to a cube map using `nona` and then tiles the cube map faces into image pyramids. This is the same method that was used by the Flash-based panorama viewers that existed when Pannellum's multi resolution support was added.

If you want more details, you should just look at the script itself (not the most satisfying answer, sorry). It's only ~350 lines and includes comments that describe the purpose of each step.
