### ISSUE TITLE
convert coord(x,y) in percentage from the image TO yaw and pitch positions

### ISSUE THREAD

**Issue by ghost** [mpetroff/pannellum#108]
Hello
First of all, thank you very much for your awesome work !

I would love to know how to convert (x%,y%) coordinates (in percentage, to adapt this function to any image resolutions, because equirectangular images have always the same format) from an equirectangular image
TO 
yaw and pitch positions in degrees from equirectangular projection.

for example, i would like to have a function like that :

function convertXYtoYawPitch(xPercentage, yPercentage) {
    ..................
    return yaw and pitch positions;
}

**Comment by thomz6** [comment]
or something like that :

function convertXYtoYawPitch(x, y, imageWidth, imageHeight) {
..................
return yaw and pitch positions;
}

**Comment by mpetroff** [comment]
For xPercentage, yPercentage [0,1]; measured from the top left of the image:
```
function convertXYtoYawPitch(xPercentage, yPercentage) {
    yaw = xPercentage * 360;
    pitch = (yPercentange - 0.5) * -180;
    return [yaw, pitch];
}
```

It's pretty simple because equirectangular projection is based on angles.

**Comment by thomz6** [comment]
ahah yes pretty simple actually ^^
thank for your answer :)

**Comment by thomz6** [comment]
Ok I have tested some values etc,
I think the function should be better like that :
function convertXYtoYawPitch(xPercentage, yPercentage) {
    yaw = (xPercentage - 0.5) * 360;
    pitch = (yPercentange - 0.5) * -180;
    return [yaw, pitch];
}
^^

**Comment by nobutsta** [comment]
Will this?
    xPercentage =yaw  / 360;
    yPercentange = (pitch + 0.5) / -180;

**Comment by aaalsh** [comment]
what about cubemap?

**Comment by aaalsh** [comment]
or multires ?

**Comment by mpetroff** [comment]
@nobutsta @aaalsh Your comments are off-topic and somewhat incoherent, so I'm locking this issue.
