### ISSUE TITLE
No display when I try to create a panorama viewer with the API

### ISSUE THREAD

**Issue by thomz6** [mpetroff/pannellum#109]
Hello,
Still me ! 

I dont understand why, but i haven't any display when I try to create a panorama viewer with the API.

I simply have a file index.php hosted in a wamp server. (url : http://localhost/test/index.php)

The code is : 
![code](https://cloud.githubusercontent.com/assets/16935000/12671846/96f68c52-c672-11e5-9097-43218b1f31a2.PNG)

**Comment by thomz6** [comment]
Furthermore
There is no error in the log console
and
When I inspect the source code of the website, i can see there are added codes in the panorama div.

![code2](https://cloud.githubusercontent.com/assets/16935000/12671970/61aa7878-c673-11e5-8669-3af7b511f224.PNG)

**Comment by mpetroff** [comment]
It's a bug in the documentation that I just fixed. You need to add the following to the `<head>` section:
```html
<style>
#panorama {
    width: 600px;
    height: 400px;
}
</style>
```
Otherwise, the panorama viewer is displayed with a height of 0px.

**Comment by thomz6** [comment]
thanks :)
