### ISSUE TITLE
Completely dispose Pannellum Viewer

### ISSUE THREAD

**Issue by TillCity** [mpetroff/pannellum#1095]
If this has been explained somewhere in the documentation I have been unable to find it.  I am using Pannellum in a hybrid mobile app - to great success.  The thing that concerns me is this - in the app the panorama gets loaded and is displayed on one page of the app.  What happens when the user navigates away to another page.  The panorama will no longer display since its container control has been destroyed.  However, what about the previously configured Pannellum.Viewer?  Isn't there something that needs to be done to tell it to stop and dispose of all resources prior to unloading its hosting page?

**Comment by mpetroff** [comment]
There's a `.destroy()` method you can call on the `viewer` instance, which should dispose of most of its resources.

**Comment by TillCity** [comment]
Thanks!
