### ISSUE TITLE
how to add scene and add hotspots

### ISSUE THREAD

**Issue by Aboozii** [mpetroff/pannellum#1096]
Hello. THX for the code for the TOUR.
I used the TOUR code to see the panorama view.
but now I want to know how to add scenes and hotspots. I tried to add hotspots and scenes more than 2 but I'm still have no idea.
PLz help...

**Comment by mpetroff** [comment]
There are examples for both [tours](https://pannellum.org/documentation/examples/tour/) and [hot spots](https://pannellum.org/documentation/examples/hot-spots/).
