### ISSUE TITLE
how to add value from php fetch 

### ISSUE THREAD

**Issue by anuragsingk** [mpetroff/pannellum#1098]
hii i'm getting value from datbase for image with php

  `<iframe width="600" height="400" allowfullscreen style="border-style:none;" src="https:/domain.com/pannellum.htm#panorama=<?php echo url("/public/storage/".$img); ?>&amp;autoLoad=true"></iframe>
`
but it's not working image added in dom but not working and all dom not loading can anyone hlep

**Comment by anuragsingk** [comment]
https://stackoverflow.com/questions/72589595/dom-html-got-messed-when-using-dynamic-image-in-pannellum

**Comment by mpetroff** [comment]
This is an issue with you incorrectly using PHP, not an issue with Pannellum. It is thus out-of-scope of this issue tracker. If you check the HTML output, you'll find that something is not properly escaped, or that it's mangled in some other way.
