### ISSUE TITLE
Standalone: Support for external JSON config

### ISSUE THREAD

**Issue by strarsis** [mpetroff/pannellum#110]
The standalone pannellum html expects the options directly passed as GET parameters.
It would be very useful if the standalone pannellum.html could also support a path to a configuration JSON file instead.
One could argue that the _non_-standalone pannellum may be used, but the standalone pannellum also got everything minified and inlined.

Thank you and
with best regards

**Comment by mpetroff** [comment]
This has existed for a long time via the [`config`](https://github.com/mpetroff/pannellum/blob/master/doc/url-config-parameters.md#config) parameter.
