### ISSUE TITLE
(NPM) Release plans

### ISSUE THREAD

**Issue by eyecatchup** [mpetroff/pannellum#1102]
Hi, would you mind creating a new release version and publish that on npm?

72 commits have been pushed to master since the 2.5.6 release, which is the latest [available on npm](https://www.npmjs.com/package/pannellum). A lot of issues have been fixed since then. However, in order to actually benefit from these bug fixes and improvements, we (have to) maintain a private npm package for our company, which is build from your git source. But we'd prefer to use the official library package instead. 

Any chance you could publish a new (NPM) release soon?

**Comment by mpetroff** [comment]
At this point, I've given release estimates several times and missed them, so I'm not going to do that again. I've been meaning to get a new release out for a while, but I haven't found the time necessary to do the required testing and QA involved with pushing a release. It will happen when it happens. Sorry I can't be any more precise.

**Comment by eyecatchup** [comment]
I don't really see, what prevents from simply bumping the _minor_ version number every time bug fixes or improvements are being incorporated (I guess these get reviewed and QAed before being pushed / merged). It's not about finding a stable state for a new major release, right?

For sure, do whatever fits best for you. I just want to highlight again, that the latest release includes _several_ known bugs which have been fixed during the last 2.5 years. And any project that wants to include these bug fixes can currently not rely on the most common distribution channels. And this is not limited to NPM only but also includes CDN users.

Thanks for your feedback anyway, @mpetroff!

**Comment by mpetroff** [comment]
> what prevents from simply bumping the minor version number every time bug fixes or improvements are being incorporated

That would require branching off a release branch and back porting fixes. It still requires testing across multiple browsers and devices, and it become more difficult as the branches diverge. We're up to 2.5.6 because I did make point releases until more major changes were made to Git `master`. It's quite a bit more work than just making releases less often, and I don't have the time or motivation to do it. Yearly releases are a goal, but that simply hasn't happened.
