### ISSUE TITLE
Image Size Problem: "Your browser does not have the neccessary WebGL support to display this panorama"

### ISSUE THREAD

**Issue by Lightfoe1** [mpetroff/pannellum#1105]
I have a folder of panorama images, there are 4096x2048 sized ones which seem to work fine.
There are also 2068x1034 sized images(Same aspect ratio:2), and they give this webgl error.
Are there any fixes I can apply?
Thanks.

**Comment by mpetroff** [comment]
You haven't given me much to go on. What version of Pannellum are you using? What browser, browser version, OS? Do you have a link to a demo that shows this issue?

**Comment by Lightfoe1** [comment]
It was a server side issue, when I downloaded the image and used it in the panorama there were no problems.
