### ISSUE TITLE
Can Pannellum read 3 * 180 degree fisheye images ? To get a 360° panoramic projection ?

### ISSUE THREAD

**Issue by thomz6** [mpetroff/pannellum#111]
Hello, 
Pannellum can read 1 Equirectangular image or 6 Cubics images to get a 360° panoramic projection.
Is there a way for pannellum to read 3 x 180 degree fisheye images ?

Or maybe, do you know a way to convert 3 * 180 degree fisheye images to 1 Equirectangular image thanks to JS or PHP languages ?

**Comment by mpetroff** [comment]
There are lots of different fisheye lenses; Pannellum does not, and will never, support them. You can stitch your images into a proper panorama with something like [Hugin](http://hugin.sf.net/).
