### ISSUE TITLE
the file could not be accessed 

### ISSUE THREAD

**Issue by tonywangvu** [mpetroff/pannellum#1113]
Hi,
I got an error message when I try to load the image: 
"The file http://3.106.140.99/wp-content/uploads/2022/08/IMG_20220609_113215_00_merged.jpg could not be accessed" 

My image was uploded to my own Wordpress site, I can directly open this image but I cannot use it here, can anyone let me know the reason?

Thanks
Tony

**Comment by mpetroff** [comment]
I'm not sure what you mean by "cannot use it here." Regardless, check your browser's developer console. The most likely causes of this are mixed content (using HTTPS for Pannellum but HTTP for your image [as you're doing]) issues or CORS issues (loading Pannellum and your image from different domains).
