### ISSUE TITLE
Hover effects Howto's

### ISSUE THREAD

**Issue by Panorama360s** [mpetroff/pannellum#1115]
I'd love to hover simple animated Gifs over our Panorama360s adding a simple 900kb animated gif ontop a 14mb panorama could make it appear as a **12Gb VR 8k video**. Answers on this forum are wildly overly complicated, i looked for similar answers but all the answers are insanely obscure on their solutions. It seems with every answer the response is an abrupt solved, with end of the thread discussion and zero clues or paths to completion. If people were really truthful on their solved threads the responses would be more akin with the joomla / wordpress responses and they would share the successful path codes with everyone else like Joomla forums do. I put it to you that most of the solved responses are just people too afraid to say they do not understand. When Joomla forums help out folks the recipent posts the recipe + hints, when hubs like these places do they never post followups. Leads me on my conclusion that rarely is anything understood let alone solved

My current problem is how to hover animated Gifs over our Panorama360s to give the illusions of 100Gb video files with only a few mb's i believe it might be possible with your software but most searches appear with the abrupt "solved" leading me to believe that 90% of the solutions are invalid. Anychance of manuals, hints or cheat sheets

**Comment by mpetroff** [comment]
I have absolutely no idea what you're talking about. Pannellum has nothing to do with Joomla or Wordpress, so I don't know why you keep mentioning them. I have no idea what GIFs have to do with 8k video or massive video files.
