### ISSUE TITLE
renderHotSpot

### ISSUE THREAD

**Issue by tungUAS** [mpetroff/pannellum#1116]
Hallo Mpetroff,

i am currently working on a small project which should builds a Virtual Service Center. Pannellum is sofar the best choice i have gotten. It is so powerful and plugin easy. I have done almost everything i need.

However, i am quite unfamiliar to the whole techinique and want to ask if you can help me out with the function renderHotSpot ? I want to change the way HotSpots rotate/transform!

Whenenver you could, please email me: tung.tt133@gmail.com.

I will be very thanksful!

Best regards.

**Comment by mpetroff** [comment]
If you want help, you can ask here where the responses can potentially help others. I'm not going to email you.

Please elaborate on what you mean by "change the way HotSpots rotate/transform."

**Comment by mpetroff** [comment]
Closing due to lack of response.
