### ISSUE TITLE
Firefox issue after exit from fullscreen

### ISSUE THREAD

**Issue by aferrato** [mpetroff/pannellum#1118]
Hi, I'm having a problem, after exiting the fullscreen with Firefox the panorama is reduced to a corner and no longer occupies 100% of the canvas.
Anyone else have this problem?

I have tried with Firefox 104, 103 and 102 on various windows versions, 11, 10, 8. The problem does not seem to be present in the versions of FF 101 and earlier.

below is one of the examples on the site.

![image](https://user-images.githubusercontent.com/1253268/190660874-23bb91a0-8774-4d95-96d1-a1266f0a273e.png)

**Comment by mpetroff** [comment]
I can reproduce this under Linux, but only with Nvidia graphics, so it might be tied to that somehow. What type of GPU are you using?

It's definitely a browser bug, which had already been report to Mozilla:
https://bugzilla.mozilla.org/show_bug.cgi?id=1779753

I just commented on the bug with more information.

**Comment by mpetroff** [comment]
@aferrato Are you still seeing this issue? I can no longer reproduce it with newer versions of Firefox.

**Comment by mpetroff** [comment]
The Firefox bug has been closed, so I'm also closing this issue.
