### ISSUE TITLE
Deprecation Warning: `ANTIALIAS is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.LANCZOS instead.`

### ISSUE THREAD

**Issue by strarsis** [mpetroff/pannellum#1119]
When using recent Pillow, a deprecation warning occurs:
````
DeprecationWarning: ANTIALIAS is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.LANCZOS instead.
````

It is `PIL.Image.Resampling.LANCZOS` but not `PIL.Image.LANZCOS`, this is a relatively new feature, so changing it may break the tool for older Pillow versions.

**Comment by mpetroff** [comment]
I added a conditional check in 7d42e49d1024d65a75ebae5df708f19f42dce711, which will use the new syntax but only if `Image.Resampling` exists.

**Comment by strarsis** [comment]
@mpetroff: Awesome! This not only fixes the issue in the future, but also fully preserves backwards-compatibility.

**Comment by akejit** [comment]
/tmp/ipykernel_12/754382997.py:10: DeprecationWarning: ANTIALIAS is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.LANCZOS instead.
food_image_resized = final_image.resize((550, 550), Image.ANTIALIAS)

**Comment by mpetroff** [comment]
@akejit This isn't a Python help forum. You've posted an error message from your own code, with no context, that appears to have nothing to do with Pannellum.
