### ISSUE TITLE
how does cubemap projection work ?

### ISSUE THREAD

**Issue by thomz6** [mpetroff/pannellum#112]
How does cubemap projection work ? 
Is there a function in the source code that converts 6 cubemap images to 1 equirectangular image ? 
Because the cubemap projection seems to be very fluid, i mean there is no border.

Actually, i'm looking for a way to convet 6 cubemap images to 1 equirectangular image in JS.

**Comment by mpetroff** [comment]
Pannellum is a viewer, not image processing software. I you want to learn about cube maps, you can read [Wikipedia](https://en.wikipedia.org/wiki/Cube_mapping).
