### ISSUE TITLE
Accessibility tabbing to hotspots causes a partial or fully white screen

### ISSUE THREAD

**Issue by patrickgates** [mpetroff/pannellum#1120]
In my test case I'm using a multiRes, and anytime I tab and it focuses a on a hotspot that is just out of frame, anything that wasn't previously loaded is no longer visible, and if it goes fully white, the grab container is gone as well.

It even happens right on the front page of pannellum.org. If you load that site and tab, the second tab when focused on the Panorama will reveal half of the image loaded on the left, and the other half showing the loading/null texture.

This is in Chrome v105.0.5195.125

<img width="1040" alt="Screen Shot 2022-09-20 at 2 15 49 PM" src="https://user-images.githubusercontent.com/2575898/191366109-ee35a314-6eda-468e-a53b-3dcfea3f5c76.png">

**Comment by mpetroff** [comment]
This was a Chrome-specific issue (it wasn't worth the effort of tracking down which Chrome version introduced the issue, but I think it started relatively recently).

I disabled tabbing to the hot spots in 929ec8f11c123870a95a3706b348f13722543727 to fix this. This isn't a great fix, but as mentioned in #628, I don't have a good idea as to how to handle hot spots with tab.
