### ISSUE TITLE
pannellum click list hotspot

### ISSUE THREAD

**Issue by 016886611529a** [mpetroff/pannellum#1123]
I want to add list hotspot at right browser. 
![image](https://user-images.githubusercontent.com/90632819/192751059-a5c4e538-ad10-4aab-9dc0-9ce389c00899.png)
and when I click each item hotspot then change scene 
can you help me ?

**Comment by mpetroff** [comment]
You'd have to add custom HTML over the viewer, as is done in the [custom control example](https://pannellum.org/documentation/examples/custom-controls/). You'd then need to add a `click` event listener to each of your buttons, which would call Pannellum's [`loadScene`](https://pannellum.org/documentation/api/#loadscene) method to change the scene.

**Comment by 016886611529a** [comment]
@mpetroff you can example for me .... 
I just started writing javascript. 
Thanks

**Comment by mpetroff** [comment]
I'm happy to answer specific questions, but I'm not going to write code for you.

**Comment by 016886611529a** [comment]
i had add custom HTML add a click event listener to each of your buttons, which would call Pannellum's [loadScene] method to change the scene. but unsuccessful 
![image](https://user-images.githubusercontent.com/90632819/195313588-34d2235e-6fb5-43ef-8fbe-b52cb1e58e9e.png)

**Comment by 016886611529a** [comment]
thanks you bro. I made it work
