### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by swiss-go-to** [mpetroff/pannellum#1129]
I have seent that your last release was in 2019 but you have beeen committing new codes. Is there a 2022 version coming up?

**Comment by eyecatchup** [comment]
See https://github.com/mpetroff/pannellum/issues/1102

**Comment by swiss-go-to** [comment]
Thanks! Hope he will make a release soon!

**Comment by mpetroff** [comment]
I am currently on my way to Antarctica for the austral summer and will have extremely limited internet access while there, so there's no chance of a release until after I get back.
