### ISSUE TITLE
How to make repeated 180 degree panorama?

### ISSUE THREAD

**Issue by 007weilun** [mpetroff/pannellum#1142]
So I use this code to make 180 viewers however I can't find a way to make them loop or seamless, it will look something like this: http://blog.n42designs.com/pano/

`    pannellum.viewer('panorama', {
        "type": "equirectangular",
        "panorama": "./images/test2.jpg",
        "vaov": 60,
    "hfov": 70,
    "haov": 180,
    "maxHfov" : 100,
    "avoidShowingBackground": true,
    "horizonPitch" : 0,
    "minYaw": -90,
    "maxYaw": 90,
    "minPitch" : -20,
    "maxPitch" : 20,
        "autoLoad": true,
    });
`

**Comment by mpetroff** [comment]
You linked to a viewer that displays a 360 deg panorama and only allows horizontal panning. I fail to see how that has anything to do with a 180 deg panorama or what you're asking.
