### ISSUE TITLE
The file file:///C:/Users/X/../../asset.jpeg could not be accessed.

### ISSUE THREAD

**Issue by Bereky** [mpetroff/pannellum#1143]
I can access the asset when the app is served on local server like vs code live server. But when I try to open the file directly in the browser I get this error.

**Comment by mpetroff** [comment]
Quoting from the readme: "Due to browser security restrictions, a web server must be used locally as well."

Browsers don't allow JavaScript access to local files for security reasons, so you need to run a local server.
