### ISSUE TITLE
Morph transition between scenes

### ISSUE THREAD

**Issue by aproni34f** [mpetroff/pannellum#1148]
This is more of a feature question. If you navigate this tour example below by cliking anywhere (not on hotspots), you will see it moves around (and changes scenes) with almost no transition (like it morphs in the next image). You think pannelum would be able to do something similar?

https://matterport.com/discover/space/sigmund-freuds-house-london

**Comment by mpetroff** [comment]
Such transitions require a 3D model of the environment with known camera positions in the model. It's outside the scope of Pannellum, although I've previously discussed the possibility of a simpler method in https://github.com/mpetroff/pannellum/issues/781#issuecomment-955593780.
