### ISSUE TITLE
Cannot drag to move in vue.

### ISSUE THREAD

**Issue by S-N-O-R-L-A-X** [mpetroff/pannellum#1149]
I'm using pannellum in vue. The panorama rendered well and fullScreen ran well. However, I could not use mouse to drag to move the view.
The console raised this error.
I used this to initialize and render
`<div ref="panorama"></div>`

```
const viewer = pannellum.viewer(this.$refs.panorama,
            {
                "default": {
                    "firstScene": "first",
                    "orientationOnByDefault": false,
                    "autoLoad": true,
                    // "autoRotate": -2,
                    "friction": 0.15,
                    "showZoomCtrl": true,
                    "showFullscreenCtrl": true,
                    // "touchPanSpeedCoeffFactor": 1,
                    "yaw": 0,
                    "pitch": -60,
                    "minPitch": -60,
                    "maxPitch": 60,
                    "roll": 0,
                    "hfov": 60,
                    "draggingMouseButtons": "all",
                    "minHfov": 10,
                    "maxHfov": 60,
                    "crossOrigin": "anonymous"
                },
                "scenes": {
                    "first": {
                        "type": "equirectangular",
                        "panorama": this.src,
                        "preview": this.src,
                        "hotSpots": [

                        ]
                    }
                }
            })
```

![image](https://user-images.githubusercontent.com/60914359/227476882-165884e3-4c63-4874-89df-05c977ee3eb1.png)
![image](https://user-images.githubusercontent.com/60914359/227476284-8497943c-d261-4aec-b6c2-4caf66128e58.png)

Any help will be appreciated, thanks.

**Comment by mpetroff** [comment]
Other than `draggingMouseButtons`, which isn't a configuration parameter (but shouldn't hurt anything), your configuration looks fine. The console messages are entirely unrelated to Pannellum.

I'm pretty sure the dragging issue has something to do with Vue, but the code snippet you provided isn't sufficient to diagnose this. I suspect there's another event handler that is preempting Pannellum's; I can't be sure, but that's the avenue I'd start with investigating. If possible, a live example to look at that displays the issue would be ideal; if not, I'd recommend using your browser's developer tools to look at the mouse event handlers.

**Comment by S-N-O-R-L-A-X** [comment]
> Other than `draggingMouseButtons`, which isn't a configuration parameter (but shouldn't hurt anything), your configuration looks fine. The console messages are entirely unrelated to Pannellum.
> 
> I'm pretty sure the dragging issue has something to do with Vue, but the code snippet you provided isn't sufficient to diagnose this. I suspect there's another event handler that is preempting Pannellum's; I can't be sure, but that's the avenue I'd start with investigating. If possible, a live example to look at that displays the issue would be ideal; if not, I'd recommend using your browser's developer tools to look at the mouse event handlers.

I have checked the event listner in  developer tools and find these listeners.
![image](https://user-images.githubusercontent.com/60914359/230117985-474691ea-d7c9-4f97-9ef7-efcab4193f12.png)
I checked the file and it read like this.
![image](https://user-images.githubusercontent.com/60914359/230119043-34639d31-3b84-4347-adb8-9f70379c6e34.png)
I tried removing listener in mousedown and mouseup from index but it still didn't work. By the way, keyboard control works fine.

**Comment by S-N-O-R-L-A-X** [comment]
I have found the problem. It seems that the pnlmui css is lost.

**Comment by S-N-O-R-L-A-X** [comment]
![image](https://user-images.githubusercontent.com/60914359/230523637-971a6259-810b-488c-b6f4-95439b46e163.png)
I have found the problem. It seems that the pnlmui css is lost so the height of pnlm-ui pnlm-grab box is 0. When I add css manually as follows, it works.
```
.pnlm-ui {
    position: absolute;
    width: 100%;
    height: 100%;
    z-index: 1
}
```

But I still wonder why this happens. I imported pannellum in index.html as follows 
```
<head>
  <meta charset="UTF-8">
  <link rel="icon" href="/favicon.ico">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <!-- this should not be deleted -->
  <link rel="stylesheet" href="https://cdn.pannellum.org/2.3/pannellum.css" />
  <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/pannellum@2.5.6/build/pannellum.js"></script>
  <title>Vite App</title>
</head>
```
The styles of hotspots work fine, but the css of class pnlm-ui pnlm-grab are lost.

**Comment by mpetroff** [comment]
You should be using:
```html
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/pannellum@2.5.6/build/pannellum.css" />
```

You were using the CSS for v2.3.2 of Pannellum, which, not unsurprisingly, doesn't work with v2.5.6.

**Comment by S-N-O-R-L-A-X** [comment]
> You should be using:
> 
> ```
> <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/pannellum@2.5.6/build/pannellum.css" />
> ```
> 
> You were using the CSS for v2.3.2 of Pannellum, which, not unsurprisingly, doesn't work with v2.5.6.

Yeah, that's the key.
