### ISSUE TITLE
Publish to NPM

### ISSUE THREAD

**Issue by cheapsteak** [mpetroff/pannellum#115]
Such a great library, please make it possible to install from npm

**Comment by befreestudios** [comment]
@cheapsteak @mpetroff 
+1

**Comment by mpetroff** [comment]
I wrote a `package.json` file for Pannellum a while back but never got any further than that. I can go look at it again.

**Comment by mpetroff** [comment]
I just published it to NPM:
https://www.npmjs.com/package/pannellum

**Comment by cheapsteak** [comment]
thanks!
