### ISSUE TITLE
Images loading optimisation required

### ISSUE THREAD

**Issue by codex5** [mpetroff/pannellum#1151]
Hi team,
we're currently load the big image file at the first step to use the 3D view, but it's not good for the user experience.
People have to wait for awhile to start exploring the scenes.
Look how KRPano is processing the assets, it split the big image to the smaller ones for every angles.
Then users can start using the viewer without waiting for loading.
Please check if it's possible
Thanks

**Comment by mpetroff** [comment]
> Please check if it's possible

This is demonstrated on the [pannellum.org](https://pannellum.org) homepage and the [multiresolution example](https://pannellum.org/documentation/examples/multiresolution/). It's mentioned in the [readme](https://github.com/mpetroff/pannellum#using-generatepy-to-create-multires-panoramas) and the [utils/multires/readme.md](https://github.com/mpetroff/pannellum/tree/master/utils/multires) file. Yes, it's possible.

**Comment by codex5** [comment]
omg it's cool!
Thank you so much @mpetroff 
I may have to find a way to convert generate script to PHP language, but at least it's possible.

Thanks
