### ISSUE TITLE
hotspot behaviour on mobile devices

### ISSUE THREAD

**Issue by almarass1** [mpetroff/pannellum#1158]
Hi,
I have tried to use hotspots on mobile devices.
As known, hovering is not applicable on mobile; if you want to read the hotspot associated text, you have to keep your finger on the hotspot, but when you stop the hotspot associated action (open a new link, load another image,...) is immediately executed.
Is it possible to, let's say, tap once in order to read the text and tap twice to execute the action? Or something like that?

Thanks,
Alex

**Comment by almarass1** [comment]
Hi,
I succeeded in opening an alert window using clickHandlerFunc.
Unfortunately I could not find any documentation.
Is there any example to show how to properly use clickHandlerFunc?

Thanks,
Alex

**Comment by mpetroff** [comment]
There isn't currently a full example for it, but the following code snippet should hopefully help:
```javascript
function aCustomClickHandler(event, handlerArgs) {
    console.log(event, handlerArgs);
}

pannellum.viewer('panorama', {
    "type": "equirectangular",
    "panorama": "./examplepano.jpg",
    "hotSpots": [
        {
            "pitch": -0.9,
            "yaw": 144.4,
            "type": "info",
            "clickHandlerFunc": aCustomClickHandler,
            "clickHandlerArgs": "example string"
        }
    ]
});
```
When the hot spot is clicked, the click event itself followed by the string `example string` will be logged to the developer console. Instead of a string, you can pass whatever else you need, such as an array or object.

**Comment by mpetroff** [comment]
> Is it possible to, let's say, tap once in order to read the text and tap twice to execute the action? Or something like that?

You seem to have the right idea. The way to do something like this would be to implement your own logic using `clickHandlerFunc` / `clickHandlerArgs`.

**Comment by almarass1** [comment]
Hi,
I succeeded in implementing a clickHandlerFunc/clickHandlerArgs to click once in order to read the text and tap twice to execute the action.

The text appears/disappears setting visibility visible/hidden in div.pnlm-tooltip span {visibility: visible !important;}.
This setting causes all the hotspots text to appear/disappear. 

Is it possible to make visible just the clicked hotspot text, letting all the others unchanged?
Thanks,
Alex
