### ISSUE TITLE
configurable 'icon' displayed for hotSpots

### ISSUE THREAD

**Issue by kvandivo** [mpetroff/pannellum#116]
It would be very useful for me if I could specify an (optional, of course) icon for the hotspots.

For my use case, I'm using this for a real estate website, and it would be nice to have something beyond the 'up arrow' to go from space to space.  I could imagine, for instance, wanting a 'down arrow' to indicate going to a lower level in the property.  Or, I might want use something other than an 'up arrow' in general, such as one of those little 360 ovals that you see these days.  I can't even imagine all of the possibilities, of course.

I can see that they are currently svg files that are compiled in the css file, and if it makes things considerably easier I'd be happy to compile my own svg files in, but it seems a much more generic way would be to have the images defined in the config.json file and then each hotspot could specify which image/icon is to be displayed for the hotspot.

Any interest in something like this?

**Comment by mpetroff** [comment]
It's something I've thought about. I would need to change the hot spot positioning logic first, to not use hard-coded sizes.

**Comment by lodestarops** [comment]
Hey Matt, I was interested in this feature too. I'm currently running pannellum-2.2.1 on my test server, so far I gotta save I <3 it

**Comment by MmmDee** [comment]
Matthew, such great work on this.... here's another vote for custom hotspot icons!

**Comment by jcc10** [comment]
Assuming the size of the icon is the same, could it work by adding a option to overwrite the default .class to a different one and then having each image be in a different .svg file with only that icon?

Just until you get around to un-hardcoding the sizes.

**Comment by strarsis** [comment]
The icons could be centered using CSS by their own center (not upper left corner, e.g. using CSS transform).
Then the icon can have any width/height (and shape) and still be at the right place.

**Comment by mpetroff** [comment]
I added this in 81c506e842c3540530e08aaccb09f67a67dd4ab3. There's now a `cssClass` parameter for hot spots that specifies the CSS class that should be used for the hot spot. There's also a `createTooltipFunc` that's used for creating the tooltip and a `createTooltipArgs` that specifies arguments that should be passed to the tooltip function, in addition to the hot spot `div`, which is the first argument.

Here's a very rough example:
```html
<!DOCTYPE HTML>
<html>
<head>
    <meta charset="utf-8">
    <title>Test Example</title>
    <link rel="stylesheet" href="../src/css/pannellum.css"/>
    <script type="text/javascript" src="../src/js/pannellum.js"></script>
    <script type="text/javascript" src="../src/js/libpannellum.js"></script>
    <style>
    #panorama {
        width: 600px;
        height: 400px;
    }
    .testcss {
        height: 50px;
        width: 50px;
        background: #f00;
    }
    div.custom-tooltip span {
        visibility: hidden;
        position: absolute;
        border-radius: 3px;
        background-color: #fff;
        color: #000;
        text-align: center;
        max-width: 200px;
        padding: 5px 10px;
        margin-left: -220px;
        cursor: default;
    }
    div.custom-tooltip:hover span{
        visibility: visible;
    }
    div.custom-tooltip:hover span:after {
        content: '';
        position: absolute;
        width: 0;
        height: 0;
        border-width: 10px;
        border-style: solid;
        border-color: #fff transparent transparent transparent;
        bottom: -20px;
        left: -10px;
        margin: 0 50%;
    }
    </style>
</head>
<body>

<div id="panorama"></div>

<script>
// Create viewer
viewer = pannellum.viewer('panorama', ﻿{
    "panorama": "./examplepano.jpg",
    "hotSpots": [
        {
            "pitch": -12,
            "yaw": 170,
            "type": "info",
            "text": "This is Jordan Pond, located in Acadia National Park.",
            "cssClass": "testcss",
            "createTooltipFunc": hotspot,
            "createTooltipArgs": "Test text"
        },
        {
            "pitch": -10,
            "yaw": -50,
            "type": "info",
            "text": "This is a link.",
            "URL": "https://github.com/mpetroff/pannellum"
        },
        {
            "pitch": 20,
            "yaw": -60,
            "type": "scene",
            "text": "Pond",
            "sceneId": "pond"
        }
    ]
});

function hotspot(hotSpotDiv, args) {
    hotSpotDiv.classList.add('custom-tooltip');
    var span = document.createElement('span');
    span.innerHTML = args;
    hotSpotDiv.appendChild(span);
    span.style.width = span.scrollWidth - 20 + 'px';
    span.style.marginLeft = -(span.scrollWidth - hotSpotDiv.offsetWidth) / 2 + 'px';
    span.style.marginTop = -span.scrollHeight - 12 + 'px';
}
</script>

</body>
</html>
```
