### ISSUE TITLE
How to use the device direction control function on the default mobile phone after entering the Panorama

### ISSUE THREAD

**Issue by guohuayu** [mpetroff/pannellum#1169]
The example on the official website has the function of enabling device direction control on the mobile phone. But I don't have this directional control feature in version 2.5.6 of CDN, and I set orientationOnByDefault to true. No response on the phone

**Comment by mpetroff** [comment]
For `orientationOnByDefault` to work, the user has to have already granted the site access to device orientation. You seem to have already granted pannellum.org permission, but you haven't granted permission wherever it isn't working. Additionally, browsers only allow device orientation to work over HTTPS, and prompts for device orientation permission must be initiated by user interaction, so `orientationOnByDefault` won't prompt for it when `autoLoad` is also set to `true`.
