### ISSUE TITLE
Panaroma Image not rendering on Android 4.2.1

### ISSUE THREAD

**Issue by avs20** [mpetroff/pannellum#117]
I am using this library to create a panorama viewer on Android. It works out of the box on Android 5 above in the inbuilt WebView component. On below Android 5 I have used a fallback to show on Google Chrome Browser as below Android 5 there is no WebGL support in the WebView component. 

This works on 4.4.2 and above but on 4.2.1 it doesn't show the image. What I get is a blank canvas and some white patches. There is no error thrown on the js side also. 
Attached is the screenshot for this 
![screenshot_2016-03-02-20-20-58](https://cloud.githubusercontent.com/assets/9055117/13545500/23c7406a-e2b4-11e5-81d1-7a7d2a5d050e.png)

**Comment by mpetroff** [comment]
The fallback CSS 3D renderer is being used, but the device doesn't properly implement CSS 3D transforms. It is likely impossible to fix this. Android 4.2 is more than three years old and has ~1% browser market share. While a pull request that fixes this would be accepted, I am going to spend no time on it due to the very low return on investment and my lack of an Android 4.2 device with which to do testing.

**Comment by avs20** [comment]
Thanks for your insight. I understand that it is an old device and has very less browser share. Another question the panorama image that I am using is not split into 6 images with generator.py as then storing different images on the server and getting through api was getting too complicated. Hence I went through the browser route as chrome is updated.

**Question** : Even if the source image is not splitt can it be shown with css 3d transformatiom?

**Comment by mpetroff** [comment]
The CSS 3D renderer will sometimes display weird artifacts on certain older devices, but if you're using a single, equirectangular image, this isn't the case, as the CSS 3D renderer only supports cube map and multires panoramas. If you're using an equirectangular image, the device is trying to render it with WebGL but is clearly having issues.
