### ISSUE TITLE
center

### ISSUE THREAD

**Issue by aliMurtaja** [mpetroff/pannellum#1170]
How will I get the center pitch and yaw value?

**Comment by mpetroff** [comment]
The `getPitch()` and `getYaw()` [API methods](https://pannellum.org/documentation/api/).

**Comment by aliMurtaja** [comment]
No, actually I want if I click any hotspot in 360Image, it should automatically be centered, so that hotspot can't be hidden if hotspot is placed just near by corner.

**Comment by aliMurtaja** [comment]
I achieved it by using `lookAt` method.

`viewer.lookAt(parseInt(hs.pitchValue), parseInt(hs.pitchYaw))`
