### ISSUE TITLE
Add onclick JS function in Hot Spots

### ISSUE THREAD

**Issue by HassanMatloob** [mpetroff/pannellum#1173]
There is a URL option in Hot Spots but I think if there is onclick option added in Hot Spots then it should be more easier to increase its usability.

**Comment by mpetroff** [comment]
The [`clickHandlerFunc`](https://github.com/mpetroff/pannellum/blob/6391a28a31e9c259fda765fbc3a3a04ec11897fa/doc/json-config-parameters.md#clickhandlerfunc-function-and-clickhandlerargs-object) hot spot parameter already exists to add a `click` event handler.
