### ISSUE TITLE
photo quality issue 

### ISSUE THREAD

**Issue by JoChaa1205** [mpetroff/pannellum#1174]
Hi, I encountered an issue in that my image seems to be misplayed, and the quality is bad. 

This is my photo source:  https://ibb.co/3pbVDhp
and this is my output: https://ibb.co/TRDMSSS 

Please let me know why, much thanks  :)

**Comment by mpetroff** [comment]
I'm pretty sure you're not actually displaying your claimed source photo. It looks like you're displaying some sort of thumbnail; in addition to the extremely low resolution, the image you're displaying in Pannellum appears to be cropped.

I can't provide any more assistance with the information you've provided. If you post your Pannellum configuration, that would be helpful.

**Comment by mpetroff** [comment]
Closing due to lack of response.
