### ISSUE TITLE
How the yaw value is calculated?

### ISSUE THREAD

**Issue by SuhaibMaraqa** [mpetroff/pannellum#1177]
I have a drone 360 images that I display with the pannellum viewer, when the yaw is 0 the image should be looking exactly to the north, but it's not the case as it might be looking the any of the four directions. So how does the yaw value get calculated in the pannellum viewer?

**Comment by mpetroff** [comment]
A yaw of zero is when the viewer is looking at the center of the equirectangular image (or the front face of a multires image). The `northOffset` parameter, either set directly or from the image's XMP data, only adjusts the compass display.
