### ISSUE TITLE
Library loades less tiles in both direction x and y 

### ISSUE THREAD

**Issue by farshaadmahmoudi** [mpetroff/pannellum#1178]
the problem is that in every zoom level that I try to load Pannellum, it loads one tile less than exist tile count in both x and y direction 
for example i have to 2*2 matrix tile for zoom level 1 but it loads only (0,0) tile
and for zoom level 2 that has 5*5 matrix it loads like
....    0 1 2 3 4
0 [ *    *    *   *    _ ]
1 [ *    *    *   *    _ ]
2 [ *    *    *   *    _ ]
3 [ *    *    *   *    _ ]
4 [ _    _    _    _   _ ]
I will attach my configuration and code sample 
thank you for this powerful library
[test1.zip](https://github.com/mpetroff/pannellum/files/12584406/test1.zip)

**Comment by mpetroff** [comment]
I don't know how you generated your tiles, but they don't match the output of Pannellum's `generate.py` script or Pannellum's expected input format.

For starters, Pannellum expects five zoom levels for your cube resolution of 4736px, with a single tile of 296px width for the first zoom level. You're providing two tiles with a total width of 640px, instead. The resolution of each zoom level changes by a factor of two, but that isn't the case for your tiles.
