### ISSUE TITLE
explanation of the formula in "Pannellum Equirectangular Projection Reference"

### ISSUE THREAD

**Issue by zeleamaaa** [mpetroff/pannellum#1180]
hello Matthew, is there an explanation of the formula in the document "Pannellum Equirectangular Projection Reference" in the doc folder?

**Comment by mpetroff** [comment]
It's based on the [pinhole camera model](https://en.wikipedia.org/wiki/Pinhole_camera_model), viewing the unit sphere.

Equation (1) is the mapping [from spherical coordinates to Cartesian coordinates](https://en.wikipedia.org/wiki/List_of_common_coordinate_transformations#From_spherical_coordinates) assuming the horizon is level, equation (2) is the [rotation matrix](https://en.wikipedia.org/wiki/Rotation_matrix) that pitches the camera view up and down, and equation (3) is the result of applying the rotation matrix to the Cartesian coordinates. Equation (4) uses the pinhole camera model to map the coordinates to a 2D image plane, i.e., the film / image sensor of the virtual camera, and equations (5) and (6) are algebraic simplifications, which give image plane coordinates that result from a set of spherical coordinates. Solving the system of equations for the spherical coordinates results in equations (7) and (8), which inverts the projection; this gives the spherical coordinates as a function of image plane position, which is what's needed for rendering a view in the panorama. Finally, equations (9) and (10) follow from the definition of the [equirectangular projection](https://en.wikipedia.org/wiki/Equirectangular_projection) and map the spherical coordinates from equations (9) and (10) onto the input panorama image.

Pannellum uses equations (7) and (8), combined with (9) and (10), to directly display equirectangular panoramas with a fragment shader. This is mathematically exact and produces better results than mapping the image onto a geometric mesh approximation of a sphere, which is a technique used in many other panorama viewers.

**Comment by zeleamaaa** [comment]
thank you very much for the explanation it was very helpful
