### ISSUE TITLE
"type": "cubemap"  pattern， Whether to support network pictures？

### ISSUE THREAD

**Issue by FED-Noob** [mpetroff/pannellum#1187]

**Comment by mpetroff** [comment]
What's a "network picture"?

**Comment by FED-Noob** [comment]
Do not load local images, use https network resources

**Comment by FED-Noob** [comment]
> What's a "network picture"?什么是“网络图片”？
Do not load local images, use https network resources,

**Comment by mpetroff** [comment]
> use https network resources

That's the typical usage. The cube map example loads images over HTTPS:
https://pannellum.org/documentation/examples/cube-map/

**Comment by FED-Noob** [comment]
Okay, thank you. I've taken care of that
