### ISSUE TITLE
Avoid MC Escher effect 

### ISSUE THREAD

**Issue by erdmann040** [mpetroff/pannellum#1188]
Hi,

If I use the example for the multiresolution panorama on the desktop in a maximised browser window, everything works as desired, but if the height and width of the viewport differ greatly (as with most smartphones) and you then scroll back, you get a very distorted image that reminds me of the paintings by the Dutch artist MC Escher.

![pannellum org_documentation_examples_multiresolution_(Samsung Galaxy S8+)](https://github.com/mpetroff/pannellum/assets/23019850/889a2ae9-2496-4214-8b13-4587bef50ef7)

There must be a way to prevent this and let the stage look more natural, right? 

Which configuration parameter lets me limit the scrolling back and can I perhaps set this parameter in relation to the viewport? 

Thanks in advance for your help

**Comment by mpetroff** [comment]
> There must be a way to prevent this and let the stage look more natural, right?

You can limit the maximum horizontal field of view with the `maxHfov` configuration parameter, or programmatically using the `setHfovBounds` API method. Panoramas are inherently a horizontal format, so the unnatural part is the absurdly tall aspect ratio (>2:1) you're showing.

**Comment by erdmann040** [comment]
Thank you for your answer! You have helped me a lot.
