### ISSUE TITLE
Panning on desktop bumps out hfov

### ISSUE THREAD

**Issue by shaunrajewski** [mpetroff/pannellum#119]
In the implementation we are currently using, when we set a lower "hfov" value, when panning left and right, it appears after a few click and drags (on desktop), it reverts / kicks out to a higher "hfov" value, which gives too much of a fish eye.

http://www.epicwebstudios.com/tests/lecom/?tour=tours/dental-offices/classroom/tour.json

Is there something we are doing wrong that is causing this? It appears to happen with any custom "hfov" value.

Thank you!

**Comment by mpetroff** [comment]
I'm not exactly sure what you're asking. How are you setting the `hfov` value? What do you mean by "it appears after a few click and drags"? What browser, browser version, OS, and OS version are you using? I don't see any jumps in the `hfov` in either Firefox or Chromium on Linux.

**Comment by shaunrajewski** [comment]
We actually just figured out the problem, it appears that setting the hfov value in the json configuration works when encasing it in "", however, on panning, it seeming pops it back out to the default hfov value.

Setting it to `"hfov": "50"` creates a jump when panning (on every browser we tested)

Setting it to `"hfov": 50` works as it should / as intended.

Essentially it comes down to us setting the value incorrectly, but having it work originally when encasing it was throwing us off. Setting any other numeric value with encasing "" doesn't create this effect, only the hfov value.

Thanks for your work on this, we are very happy with the entire framework of Pannellum. It works amazingly!

**Comment by mpetroff** [comment]
JavaScript's type coercion can lead to some strange results. Due to the way `hfov` is used, setting it to a string apparently leads to some strange results. Since I'm already handling `hfov` separately when processing the configuration, I just added in an explicit cast to make sure it's a number.
