### ISSUE TITLE
animatefinished event

### ISSUE THREAD

**Issue by 1051897274** [mpetroff/pannellum#1196]
After rotating more than 180 degrees, the event does not execute, cannot enter the event again, can only be re-rendered

**Comment by mpetroff** [comment]
> After rotating more than 180 degrees, the event does not execute

Can you provide an example that demonstrates this behavior? It works for me.

> cannot enter the event again, can only be re-rendered

I don't know what you mean by this.

**Comment by 1051897274** [comment]
I use the animatefinished event. When I rotate the view more than 180 degrees horizontally, the animatefinished event will no longer execute and the animatefinished event will fail

**Comment by mpetroff** [comment]
It's still not clear to me what you're doing, and I can't reproduce an issue with the information you've provided.

Please provide an example that demonstrates the issue. I can't provide much help if I can't reproduce the issue.

**Comment by 1051897274** [comment]
I found out that other code was causing the problem,thank you
