### ISSUE TITLE
Setting the viewing angle of the image when displayed

### ISSUE THREAD

**Issue by zeleamaaa** [mpetroff/pannellum#1199]
Is it possible to make 2 settings (hfov, pitch, yaw) on one image?  For example, if we want to click the button to move forward (hotspot), the initial viewpoint of the image remains forward, and if we want to return to the previous image, the viewpoint of the image is from behind the image, such as when accessing Google Street View. Thank you in advance

**Comment by mpetroff** [comment]
You can use the `targetPitch` / `targetYaw` / `targetHfov` parameters on your hot spots. By setting these, you'll override the defaults for the scene. Or if you're using the API, `loadScene` method has optional parameters for setting the `pitch`, `yaw`, and `hfov`.
