### ISSUE TITLE
Problem with old LG LG-R105 images on Pannellum

### ISSUE THREAD

**Issue by DeBruynM** [mpetroff/pannellum#1203]
Hi, as a geriatric Radio Station Manager, I need to use Pannellum to display our developments and I have used this camera on Theasys, but at this time, impossibly expensive.
Images from the LG do not display as 360, on Pannellum, they display as flat quadrilateral images and I have tried as much as I can within my pay grade, including passing images through Exif Fixer to no avail.
Please, what am I doing wrong.

**Comment by mpetroff** [comment]
> they display as flat quadrilateral images

I'm not sure what you mean by this. Best I can tell, the LG-R105 outputs full equirectangular images. Without metadata, these should display fine.

Do you have a screenshot of the behavior you're describing or an example image?

**Comment by mpetroff** [comment]
Closing due to lack of response.
