### ISSUE TITLE
Can I use a normal image (not panorama or photosphere) in pannellum?

### ISSUE THREAD

**Issue by lborgman** [mpetroff/pannellum#1209]
I have both photosphere images and "plain images" that I want to use to show hotspots.

Is there a simple way to use "plain images" in pannellum?

Any hint about what I need to change in pannellum if I want to use "plain images"?

**Comment by mpetroff** [comment]
The short answer is no, or at least I wouldn't recommend it. Pannellum is only designed to work with panoramas.

You could take a regular image and reproject it as an equirectangular image with a narrow field of view and use it as a [partial panorama](https://pannellum.org/documentation/examples/partial-panorama/), but, again, I wouldn't recommend it.

**Comment by lborgman** [comment]
Ok, thanks. then I know where to start.
