### ISSUE TITLE
black squares when using multiple resolutions

### ISSUE THREAD

**Issue by TodayCG** [mpetroff/pannellum#1219]
Hi，I encounter the problem of black squares when using multiple resolutions, but everything works fine when I don't use multiple resolutions. Why is this? I would like to know how many resolutions and above are recommended to use multi resolution?

![image](https://github.com/mpetroff/pannellum/assets/40811490/affc4e4c-90b0-4f8e-a9b8-e464a20c602d)

**Comment by mpetroff** [comment]
What version of Pannellum are you using?

Do you get any 404 errors when loading tiles?

Can you provide a link to an example that exhibits this behavior or at least provide the Pannellum configuration?

**Comment by mpetroff** [comment]
Closing due to lack of response.
