### ISSUE TITLE
Add typescript definitions on DefinitelyTyped

### ISSUE THREAD

**Issue by zhirzh** [mpetroff/pannellum#1220]
Hi @mpetroff. I have added [pannellum types on DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/69762) and would like you to review them. If any changes are needed, I'd be happy to patch things up.

**Comment by mpetroff** [comment]
I don't use TypeScript, but I'm not sure you properly captured the `panorama` option when the `dynamic` option is set to `true`. In this case, the `panorama` option accepts anything that the [`pixels` argument to `texImage2D` ](https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/texImage2D#pixels) accepts. It looks to me that you're forcing the `panorama` option to be a string.
