### ISSUE TITLE
how to set custom hotSpots arrow rotation 

### ISSUE THREAD

**Issue by himadri-housiey** [mpetroff/pannellum#1223]
![Screenshot 2024-07-11 180920](https://github.com/mpetroff/pannellum/assets/156512391/c61119d7-4635-4ebf-8b3a-b33fe41315a9)

but i want like this 
![Screenshot 2024-07-11 131550](https://github.com/mpetroff/pannellum/assets/156512391/7708107e-c40e-4556-93ac-e4950d255ed4)

this is my code.
![image](https://github.com/mpetroff/pannellum/assets/156512391/034bb62f-6746-458c-99b9-56cb9ca65443)

what can i add for this.
I want to add  rotate(---deg) rotateX(---deg) rotateY(---deg) rotateZ(---deg); each of the **custom hotSpots** rotation arrow angles separately. How can i do it?

**Comment by mpetroff** [comment]
The simplest&mdash;although less elegant&mdash;method would be to create a separate CSS class for each hot spot. The `cssClass` parameter can be a space-separated list of classes, so you could have a shared class and then only have separate classes for the rotation.

You could also use `createTooltipFunc` / `createTooltipArgs`. In this case, the hot spot `<div>` and the value of `createTooltipArgs` are both passed to the function assigned to `createTooltipFunc`, so you could assign the rotation values to `createTooltipArgs` and write a function to set the rotation on the hot spot `<div>`.
