### ISSUE TITLE
Simple Panorama Example can't load my image?

### ISSUE THREAD

**Issue by cuixing158** [mpetroff/pannellum#1225]
I got it through https://pannellum.org/documentation/overview/tutorial/
To prepare a simple example, my panoramas are hosted in some folder in other github public repositories, such as this panorama at (html warpper URL, https://github.com/Experience-Monks/360-image-viewer/blob/master/demo/pano_2048.jpg)

But when I put this raw address(https://raw.githubusercontent.com/Experience-Monks/360-image-viewer/master/demo/pano_2048.jpg) into the Panorama URL section, it can't read in my image?
As far as I know, github repository images support the Cross-origin_resource_sharing protocol, so why can't they be loaded?
![unload](https://github.com/user-attachments/assets/d5bbd684-1625-4221-bd60-5bac49de1f2f)

**Comment by mpetroff** [comment]
What's shown in your browser's developer console, and what browser, browser version, and OS are you using? The raw image address you provided works fine for me in Firefox 128 and Chromium 126 on Linux Mint.

**Comment by cuixing158** [comment]
Problem solved, my system is windows 10, I also tried before in ubuntu22.04, finally upgraded the latest version of chrome browser and solved it!
Thank you for your answer!
