### ISSUE TITLE
Why there is no LOADING system for MRES pano ? 

### ISSUE THREAD

**Issue by Nytsee** [mpetroff/pannellum#1226]
I am using Pannellum with multiple scenes and hotspots, and I have opted for multi-resolution (mres) panoramas. However, I am experiencing flickering when switching between scenes because the new scene's tiles load on top of the previous scene's image. This flickering significantly detracts the UX. Is there a way to work around this issue?

**Comment by mpetroff** [comment]
Can you provide an example? I'm not entirely sure what the flickering you're describing is or what you mean by "the new scene's tiles load on top of the previous scene's image."

**Comment by mpetroff** [comment]
Closing due to lack of response.
