### ISSUE TITLE
How to turn the azimuth values of nearby points to the hotspot view inside the panoramic view.

### ISSUE THREAD

**Issue by OlivierLeal** [mpetroff/pannellum#1227]
Helllo there, how are you doing?
I'm currently facing an issue: I have a GIS system, in which i've installed 360º  view with Panellum. When using a tool and clicking a point in the mapp it shows up the picture related to that specific point, but I intend to create a hotspot of views to navigate between other pictures. Currently I can return the points within 5 meters of the middle point and the azimuth needed to know their positions.
![Captura de tela de 2024-07-26 09-51-51](https://github.com/user-attachments/assets/07c6ac04-c9eb-4147-b5c9-518ce39cc6ee)

My top point according to my azimuth calculation is at 46º and my bottom point is at 208º in relation to my middle point. I wish it to set the hotspots in this position as soon as I enter the panoramic photo. The yaw value is 0 by default, since its centered in the direction of the car so I don't know if it's possible to transfer the "world's" position to the 360º view.

In my PostGIS database, I have yaw, roll and pitch of each picture according to real North, as you can check in the following screenshot.
![Captura de tela de 2024-07-26 09-55-35](https://github.com/user-attachments/assets/70d9eb8b-1c79-439f-badc-91e8f74ea750)

![Captura de tela de 2024-07-26 10-11-20](https://github.com/user-attachments/assets/7dc2f9c6-f0ac-4805-871c-4b5d772192a8)
![Captura de tela de 2024-07-26 10-11-41](https://github.com/user-attachments/assets/31363fbb-057d-439b-ad44-44a13bf97483)

Thank you in advance :)

**Comment by mpetroff** [comment]
This sounds like a question for the developer of whatever GIS software plugin you're using. I have no idea what GIS software you're using, what plugin you're using, or how they work together. Combining the panorama's yaw value and the hot spot's azimuth should be simple arithmetic.

**Comment by OlivierLeal** [comment]
Do you have any idea about this arithmetic question? It's just GIS-WEB software with Postgis database and openlayers for layer visualization.

**Comment by mpetroff** [comment]
> Do you have any idea about this arithmetic question?

It's probably `point heading` &minus; `panorama yaw`, but that makes assumptions about sign convention and assumes that the panorama yaw is referenced to the center of the image. The general form is `point heading` + `panorama yaw` + `offset`; if an offset is required, it's probably 180&deg;, and it's possible that either the point heading or panorama yaw need a sign flip.

**Comment by mpetroff** [comment]
Working under the assumption that the center of your panorama corresponds to your car's heading, the center of your panorama would be facing due north if your car was driving due north, i.e., it had a heading of 0&deg;. In this case, hot spot yaw values would correspond directly to headings, e.g., a point at a heading of 5&deg; would be to the right, and a point at a heading of 355&deg; (&minus;5&deg;) would be to the left.

Now assume your car is heading due east, so it has a heading of 90&deg;. Now the point to the right would have a heading of 95&deg;, and the point to the left would have a heading of 85&deg;. These points would still be &pm;5&deg; from the center of the panorama, so the hot spot yaw values would again be 5&deg; for the point to the right and 355&deg; (&minus;5&deg;) for the point on left, i.e., `point heading` &minus; `panorama yaw`, as previously stated.

For the example you gave, with a car heading of 206&deg; and points at 46&deg; and 208&deg;, the hot spot yaw values would be 46&deg; &minus; 206&deg; = &minus;160&deg; (mod 360 = 200&deg;) and 208&deg; &minus; 206&deg; = 2&deg;, respectively.

**Comment by OlivierLeal** [comment]
Good morning friend, how are you? Yesterday, after several tests, I ended up discovering that my equation was only working incorrectly when the yaw is negative, I will check your comment and try to correct this today. I also encountered another problem, I was trying to iterate to make a hotspot for each point present within 5 meters but when using the hotspot view it breaks, I will show it in the following image.

![image](https://github.com/user-attachments/assets/3aee073c-e117-48bb-9d8b-726fa326894b)
For each value present in my array, it would create a new hotspot.

![image](https://github.com/user-attachments/assets/df366aa9-7074-4c6f-9eb1-5ea241b4c66c)
But in fact it happens that he doesn't add the points and ends up with this + symbol in yaw 0.

I'm programming in CoffeeScript.

`carregarFoto: (url) =>
    yaw_hotspot = [10, 20]
    pannellum.viewer 'panorama',
    title: '07/2024'
    type: 'equirectangular'
    panorama: "http://localhost:8000/#{url}"
    autoLoad: true
    compass: true
    hotSpots: [
      for yaw in yaw_hotspot
        {
          pitch: 2,
          yaw: yaw,  
          type: 'scene',
          text: "Azimuth 182",
          URL: "http://localhost:3000"
        }
    ]
`

**Comment by mpetroff** [comment]
The plus symbol appears when the `hotSpotDebug` parameter evaluates as `true`. I'm not familiar with CoffeeScript, so I have no idea why your code is doing this. If you run the viewer's `getConfig()` method, it will return the configuration. I assume there's something malformed about it.

**Comment by OlivierLeal** [comment]
Okay friend, I've managed to solve my problem. I'm trying now to show the yaw value on my screen, like this:
![image](https://github.com/user-attachments/assets/ac87f020-56e3-4834-a982-12f23412e15c)
