### ISSUE TITLE
some android  browser  throw  maxWidth  error 

### ISSUE THREAD

**Issue by JohnnieFucker** [mpetroff/pannellum#1228]
the  gl.getParameter(gl.MAX_TEXTURE_SIZE)  returns  0 as the maxWidth, is there any idea for this problem?
![Screenshot_2024-08-03-11-39-22-966_com tencent wework](https://github.com/user-attachments/assets/cac36047-feaa-4dae-bbfe-d662dc70ce31)
and another problem is in some android  browser,it can loading the image, but it comes to white backgroud when tap on the screen.
![afbc72beb6e042fcd6b329959402cd10_compress](https://github.com/user-attachments/assets/750ea6c1-fc90-4518-9358-c1dbb0a260af)

the test url is https://aichat.cgboiler.com/static/pan_index.html

**Comment by mpetroff** [comment]
> the gl.getParameter(gl.MAX_TEXTURE_SIZE) returns 0 as the maxWidth, is there any idea for this problem?

Your browser doesn't properly support WebGL. I'm not sure what else to tell you.

> and another problem is in some android browser,it can loading the image, but it comes to white backgroud when tap on the screen.

The sad face icon in the top left of the canvas apparently means that Chrome's rendering process crashed:
https://superuser.com/questions/1440281/sad-face-with-x-for-eyes-in-chromeos-kiosk

Given the lack of a URL bar, neither of the screenshots look like a browser to me.
