### ISSUE TITLE
problem with image hotspot (bug)

### ISSUE THREAD

**Issue by Cyrille37** [mpetroff/pannellum#123]
Hi,
There're little problems with image hotspot.
(item number match those on joined screenshot)
1 - black rectangle background could be smaller than the image
2 - other hotspot are renderer on top of image
![bug hotspot image](https://cloud.githubusercontent.com/assets/368965/13727874/8d03ef50-e904-11e5-9686-c54666a6a520.png)

But some time there is no problem (_a third hotspot is well under the image_)
![bug hotspot image some time not](https://cloud.githubusercontent.com/assets/368965/13727951/47f4613a-e907-11e5-8be2-dd95583d370a.png)

Cheers

**Comment by mpetroff** [comment]
As mentioned in #122, they're not officially supported and need some work.
