### ISSUE TITLE
Multiple images

### ISSUE THREAD

**Issue by TrippleDelta** [mpetroff/pannellum#1236]
How can I embed multiple images on one webpage with the API?

**Comment by mpetroff** [comment]
Do you want multiple images in one viewer or multiple viewers? For the former, look at the [tour example](https://pannellum.org/documentation/examples/tour/). For the latter, you'd make multiple `<div>` elements and initialize a viewer for each of them.

**Comment by TrippleDelta** [comment]
I needed multiple viewers. Multiple <div> felt more like a workaround so I tested iframe instead.
I'll go for different id though. Thanks.

**Comment by TrippleDelta** [comment]
My fix for this excellent software:
CSS:
`[id^=panorama] {
}`
And html:
` <div id="panorama_1"></div>
    <script>
        pannellum.viewer('panorama_1', {`

` <div id="panorama_2"></div>
    <script>
        pannellum.viewer('panorama_2', {`
