### ISSUE TITLE
html in hotspot text

### ISSUE THREAD

**Issue by Cyrille37** [mpetroff/pannellum#125]
Hi,
Do you see some problem to permit html in hotspot text? XSS problem could be processed in another layer (hotspot configuration generator like web backend or else)?

**Comment by mpetroff** [comment]
I could potentially revisit this when I eventually rework the hot spot system, but HTML is forbidden for now due to XSS concerns.

**Comment by Cyrille37** [comment]
Thanks for all your answers!
I a nice sunday ;-)
Cheers
