### ISSUE TITLE
more with hotSpotDebug

### ISSUE THREAD

**Issue by Cyrille37** [mpetroff/pannellum#128]
Hi,
the option `hotSpotDebug` is nice but should be better with a little cross on center of image to "see" where pitch and yaw values are ;-)
Cheers.

**Comment by mpetroff** [comment]
That's an interesting idea. I might see about implementing it when I have some time.

**Comment by lodestarops** [comment]
This is a great idea!

**Comment by mpetroff** [comment]
Added in 0879a61bd48ad9e08852a4cc9dde8722f0e38e20.
