### ISSUE TITLE
getScene() only on first scene, on next scene it return "undefined"

### ISSUE THREAD

**Issue by Cyrille37** [mpetroff/pannellum#130]
Hi,
the getScene() return the scene's Id at first scene (after load) but in next scene calls to getScene() return "undefined".
Cheers.

**Comment by Cyrille37** [comment]
sorry ...

**Comment by Cyrille37** [comment]
Yep, I found the place.
in ` loadScene()` before `mergeConfig()` call `config.scene` is well defined, but just after it's came 'undefined'

**Comment by mpetroff** [comment]
Apparently `config.activeScene` had been there for a while but wasn't being used. When I added the API function, I added three lines to set `config.scene` when the location that set `config.activeScene` would have sufficed. I removed the three lines I added to set `config.scene` and changed the line that set `config.activeScene` to set `config.scene` instead.
