### ISSUE TITLE
Support for JPEG 2000 format.

### ISSUE THREAD

**Issue by Hfawad** [mpetroff/pannellum#137]
Is there any support for displaying panorama in JPEG2000 format? 
I am trying but it is not showing any image, It just keep loading.

**Comment by strarsis** [comment]
I am also interested in using JPEG 2000 because of better compresion abilities, do modern browsers/WebGL texturing support this?

**Comment by mpetroff** [comment]
Image files are read by the web browser. Web browsers don't really support JPEG 2000: http://caniuse.com/#feat=jpeg2000.
