### ISSUE TITLE
Help with generate.py

### ISSUE THREAD

**Issue by Where-Solutions** [mpetroff/pannellum#138]
Hi, I am getting these errors when attempting to try generate.py

```
Jamess-Mac-mini:multires james$ python generate.py -n nona test.jpg
Processing input image information...
Generating cube faces...
Traceback (most recent call last):
  File "generate.py", line 101, in <module>
    subprocess.check_call([args.nona, '-o', os.path.join(args.output, 'face'), os.path.join(args.output, 'cubic.pto')])
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 535, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

I do get an output directory with a cubic.pto file inside. I noticed they have read only permissions.

**Comment by mpetroff** [comment]
Do you have `nona` on your system path?

**Comment by Where-Solutions** [comment]
Hi, nona was in the same directory, but now moved it to another folder and added to system path. The current error is:

```
Jamess-Mac-mini:multires james$ python generate.py /Users/james/Where.Solutions/Main\ Website/IRIS360/LocalMapViewer/images/test.jpg 
Processing input image information...
Generating cube faces...
dyld: Library not loaded: @executable_path/../Frameworks/libpano13.3.dylib
  Referenced from: /Users/james/Developer/Hugin/nona
  Reason: image not found
Traceback (most recent call last):
  File "generate.py", line 101, in <module>
    subprocess.check_call([args.nona, '-o', os.path.join(args.output, 'face'), os.path.join(args.output, 'cubic.pto')])
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/Users/james/Developer/Hugin/nona', '-o', './output/face', './output/cubic.pto']' returned non-zero exit status -5
Jamess-Mac-mini:multires james$ 
```

**Comment by mpetroff** [comment]
The `nona` binary you are using is dynamically linked, but you don't have all the required libraries on the library search path; `libpano13` can't be loaded.

**Comment by Where-Solutions** [comment]
Hi, I work on a Mac, so I rarely have to fiddle with command line stuff. You may consider making your instructions/process easier for us that have no idea how to add libraries to the search path.

The goal is to make web viewable images from the output of this new 360 Panorama Camera:

https://www.nctechimaging.com/iris360/

Which are 8000 x 4000 pixels. As this camera becomes more popular, more regular programmers are going to need tools to play with the output.

I simpler solution may to write a Bash script for ImageMagick???

**Comment by mpetroff** [comment]
It works just fine on Linux; Debian-based distros just require `sudo apt-get install hugin-tools python-pil`. I have no interest in teaching people how to use their computers, particularly operating systems I don't use; there are plenty of existing resources on the topic.

While it might be possible to write a script for ImageMagick in theory, it certainly wouldn't be simple. Reprojecting a panorama from equirectangular projection to cubic projection isn't something that is built in to ImageMagick.
