### ISSUE TITLE
autoRotateInactivityDelay not working

### ISSUE THREAD

**Issue by praefectius** [mpetroff/pannellum#139]
Hi, thanks a lot for that great tool.

I've got a problem with autoRotateInactivityDelay. The rotation doesn't start after the inactivity delay time. 

Maybe I just made a simple mistake. 

[config.json](http://klagstein.de/output_0/config.json)

[Website with pano on it](http://www.klagstein.de)

Frank

It would be awesome to switch hotspots on and off with a button...not how I did it :-)

**Comment by mpetroff** [comment]
It's a known bug (someone emailed me about it yesterday). I'm working on fixing it.

**Comment by mpetroff** [comment]
It should be fixed now.
