### ISSUE TITLE
OnImageLoaded, OnComplete, OnPannellumReady

### ISSUE THREAD

**Issue by lodestarops** [mpetroff/pannellum#140]
Hey Matt,

I was wondering if if there was an onImageLoaded, OnComplete or OnPannellumReady callback available once Pannellum has finished loading or is ready for user interaction. The reason is I'm wanting to animate in some UI elements in HTML after the event. 

I saw in one of your other tickets that you had an addon Plugin, is there a preview version available I could check out? I'm really excited to use your application to do a little virtual tour.

Thanks!

**Comment by mpetroff** [comment]
See #30 and #126. While there is an API, there's no event system yet. It's something I'm working on.

**Comment by lodestarops** [comment]
Oh Sweet! Thanks Matt I'm looking forward to it. So far, gotta say I'm loving your app. Let me know if you need an extra pair of eyes. =)

**Comment by mpetroff** [comment]
An initial event framework was added in a1461bb6ecdfa860e527fd32c62bc3fd5af3aee9. After instantiating a viewer with `viewer = pannellum.viewer(...);`, events can be added with `viewer.on('eventtype', listener)`. A `load` event is fired once the panorama has finished loading and is ready for user interaction. A listener for this event can be added with `viewer.on('load', loadListener)`.
