### ISSUE TITLE
Broken example on pannellum.org

### ISSUE THREAD

**Issue by lodestarops** [mpetroff/pannellum#141]
Sorry Matt,

I was checking out the following:
https://pannellum.org/documentation/examples/hot-spots/
https://cdn.pannellum.org/2.2/pannellum.htm?config=https://pannellum.org/configs/hot-spots.json

And noticed I get the following error:
The file https://cdn.pannellum.org/images/bma-1.jpg could not be accessed.

https://cdn.pannellum.org/2.2/pannellum.htm?config=https://pannellum.org/configs/hot-spots.json
https://cdn.pannellum.org/images/bma-1.jpg

I was able to get it working locally by downloading the entire source, so I'm good... 
Just thought you should know =)

Keepin' it awesome!

**Comment by mpetroff** [comment]
Thanks. I just fixed the example.

**Comment by Kumaresh-Rajalingam** [comment]
Hello mpetroff
I am trying to access the Tour: https://cdn.pannellum.org/2.3/pannellum.htm#config=/configs/tour.json
But it showing the error

**Error:**
The file https://cdn.pannellum.org/configs/tour.json could not be accessed.

Thanks

**Comment by mpetroff** [comment]
Thanks for reporting the issue. I just fixed it.

**Comment by Kumaresh-Rajalingam** [comment]
Hello @mpetroff 
Thanks..How can I use my own images in Tour walk through
