### ISSUE TITLE
error compass undefined

### ISSUE THREAD

**Issue by nemoin** [mpetroff/pannellum#143]
Hello, 
I am trying to use pannellum in an iframe :
`<iframe width="800" height="450" style="border:none;" allowfullscreen src="my_website_pannellum.com"></iframe>`

Then i would like to export this iframe in a website that i dont own like https://jsfiddle.net/ for example...

BUT I really dont understand why but i have the following error in my browser console :

Uncaught TypeError: Cannot set property 'className' of undefined

pannellum.js:178 

![error_here](https://cloud.githubusercontent.com/assets/18738541/14916963/e0b40710-0e1c-11e6-8db6-98fb0bb91e79.png)

**Comment by nemoin** [comment]
it seems that var compass has not value after calling :
`var compass = document.createElement('div');`

**Comment by mpetroff** [comment]
Do you have an example that displays this behavior? What browser, browser, OS, and OS version are you using? It seems to me like it might be a browser bug. As far as I know, `document.createElement()` should always return a defined value.

**Comment by mpetroff** [comment]
Closing due to lack of response.
