### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by agrimpard** [mpetroff/pannellum#147]
Hi,

I can see the different text strings in the JS source code; it would be great to add translation options so we don't have to alter the source code.

Off topic: really good work on this Pannellum; I'm discovering it and looking forward to make some nice stuff with it :)

**Comment by mpetroff** [comment]
Implemented as a configuration dictionary in 93f3df1431fbd9b3eb5a6467b86b1f03e7afbf0d.

**Comment by outOFFspace** [comment]
I'v tried:
"strings" : {
    "loadingLabel": "Завантаження"
}

But nothing was changed

**Comment by mpetroff** [comment]
Are you using the a copy from the current development branch or the 2.3.2 release?

**Comment by outOFFspace** [comment]
2.3.2

**Comment by mpetroff** [comment]
Since 2.3.2 was released last November and this feature was implemented a month ago, it's obviously not in the 2.3.2 release. You need to use the development branch or wait for the next release (probably before the end of the year).

**Comment by vollyimnetz** [comment]
can't find a development branch, is it in the master?

**Comment by mpetroff** [comment]
Yes

**Comment by jakedex** [comment]
@mpetroff Any idea when the next release will land? It'd be great to have translation strings without having to use the development branch.

**Comment by mpetroff** [comment]
I had wanted to get a release out by the end of the year, but I'm a bit busy at the moment, so that's not going to happen. Maybe January.
