### ISSUE TITLE
[Q] markup overlays in the viewer

### ISSUE THREAD

**Issue by peterlitvak** [mpetroff/pannellum#149]
Is there a way to add markup overlays in the viewer?
I'm looking for something similar to the way openseadragon handles this (https://openseadragon.github.io/examples/ui-overlays/).

**Comment by mpetroff** [comment]
Sort of, but not like the OpenSeadragon ones. One can add information hot spots: https://pannellum.org/documentation/examples/hot-spots/.

**Comment by peterlitvak** [comment]
thank you
