### ISSUE TITLE
Docker container for generate.py

### ISSUE THREAD

**Issue by quadeare** [mpetroff/pannellum#150]
Hi,

For a work, I had to create a Docker container to create multiresolution panoramas with `generate.py`.

You can get the project here: https://hub.docker.com/r/quadeare/docker_multiresolution_pannellum/

This example creates a multiresolution of "my_image.jpg" in the folder where you are.

```sh
$ docker run --rm -it -v $(pwd):/opt/output \
quadeare/docker_multiresolution_pannellum:latest my_image.jpg
```

Bye bye ;)

**Comment by mpetroff** [comment]
Looks interesting. Thanks!

**Comment by jifeon** [comment]
@mpetroff what do you think about adding docker file to the repo and building some kinda official docker image and mention it in the docs? It would be very useful for other uses to not search this info inside issues IMO. Maybe @quadeare can create a PR with Dockerfile?
