### ISSUE TITLE
Disable mouse zoom (to be able to scroll page)

### ISSUE THREAD

**Issue by ragcsalo** [mpetroff/pannellum#151]
Hi,
Could you please add an option to disable mouse zoom?
I have a big (almost fullscreen) viewer on the opening page, and visitors can't scroll the page down, because the mouse scroll activates the zoom...
Thanks in advance! :-)
Benke

**Comment by jannecederberg** [comment]
Hey @ragcsalo ! This request is now addressed and you can set a `mouseZoom` as either `true` or `false` in config.

**Comment by ragcsalo** [comment]
Thank you very much!! :-)
