### ISSUE TITLE
Fade-in effect instead of "Loading..." text?

### ISSUE THREAD

**Issue by ragcsalo** [mpetroff/pannellum#152]
Hi,
Another enhancement request... :-)
It would be nice to have an option to replace the "Loading..." text with a fade-in effect!
If there is no preview image defined, the default starting image should be a black screen... and the panoramic image could fade in from that.
Thanks!
Benke

**Comment by mpetroff** [comment]
What happens if the user has a slow connection and it takes a minute to load the panorama? I don't think this is a good idea, so I'm not going to implement it.
