### ISSUE TITLE
Slideshow (automatic change of panoramic images)

### ISSUE THREAD

**Issue by ragcsalo** [mpetroff/pannellum#153]
Hi there,
Another suggestion: a slideshow option would be nice, with a fade-in-out effect between images. :-)
The setup could be similar to scenes, but here no user interaction would be needed...
Thanks for the hard work!!!! :-)
Kind Regards, Benke

**Comment by IHaveNoIdeaWhatIAmDoingHere** [comment]
would love that too! 
Like a "autoRotateInactivityDelay" -> autoNextSceneInactiveDelay

Kind regards

**Comment by SaschaV313** [comment]
<up>
Actually I need such a feature too. autoNextSceneInactiveDelay would be perfect.
Any chance this will work in the newar future?

Alternatively how can I switch to the next scene in the tour w/o hotspots using JS?

**Comment by mpetroff** [comment]
Scenes can be switch using the API's `loadScene` method, allow such functionality to be implemented using external code. I don't plan on integrating something like this.
