### ISSUE TITLE
Is it possible to use Deep Zoom format with Pannellum?

### ISSUE THREAD

**Issue by tomas-nz** [mpetroff/pannellum#154]
I am currently using Deep Zoom panoramas projected with SaladoPlayer (Flash based). I would love to use Pannellum as a fall-back when Flash is not available in the client browser. I would ideally reuse my existing Deep Zoom files to avoid their duplication. Pannellum's multiRes format seems similar to Deep Zoom but files are organized differently. I have attached examples of the structure for the same original panoramic image. Reading documentation about parameter "path" for multiRes images, I don't see a way to achieve the mapping using only this parameter. Would you consider adding support for Deep Zoom panoramas into Pannellum?

[DeepZoom example.txt](https://github.com/mpetroff/pannellum/files/265757/DeepZoom.example.txt)
[multiRes example.txt](https://github.com/mpetroff/pannellum/files/265758/multiRes.example.txt)

151026_mt_titiroa_f.xml:
```xml
<?xml version="1.0" encoding="utf-8"?>
<Image TileSize="512" Overlap="1" Format="jpg" ServerFormat="Default" xmnls="http://schemas.microsoft.com/deepzoom/2009">
<Size Width="5632" Height="5632" />
</Image>
```

config.json:
```json
{
    "type": "multires",
    
    "multiRes": {
        "path": "/%l/%s%y_%x",
        "fallbackPath": "/fallback/%s",
        "extension": "jpg",
        "tileResolution": 512,
        "maxLevel": 5,
        "cubeResolution": 5496
    }
}
```

**Comment by mpetroff** [comment]
It's not possible directly, but it probably would be possible using symbolic links on the server side. I'm not all that familiar with the Deep Zoom file format, but it seems the biggest issue is that the zoom levels are numbered differently. If you were to link the directories to match Pannellum's zoom level numbering scheme, you probably could get it to work. I'm not really interested in adding support for specific alternative tiling formats.

**Comment by tomas-nz** [comment]
Thanks, Matthew! This was a hint in the right direction. I managed to re-map my example panorama and make it work in Pannellum by adding symbolic links for each zoom level directory:

```
cd panoramas/dz_151026_mt_titiroa
for x in * ; do
  if [ -d "$x" ]; then
    cd $x
    for y in * ; do
      if [ -d "$y" ]; then
        ln -s $y pannellum_$((10#$y - 10#8))
      fi
    done
    cd ..
  fi
done

```
Then my config changed a bit - using cube size from DeepZoom xml file and different paths. I am not sure if the fallbackPath would work like this but I don't know how to test it: 

```
    "multiRes": {
        "basePath": "/panoramas/dz_151026_mt_titiroa",
        "path": "/151026_mt_titiroa_%s/pannellum_%l/%x_%y",
        "fallbackPath": "/151026_mt_titiroa_%s/pannellum_1/0_0",
        "extension": "jpg",
        "tileResolution": 512,
        "maxLevel": 5,
        "cubeResolution": 5632
    }

```

**Comment by mpetroff** [comment]
The fallback isn't going to work well since it needs a single, higher resolution image for each cube face. If you want to test it, you need to temporarily disable WebGL in your browser (set `webgl.disabled` to `true` in Firefox's `about:config`; Chrome used to have a option in `chrome://flags` but it doesn't seem to be there anymore).

**Comment by tomas-nz** [comment]
When I tried to disable WebGL I got following error message instead of fallback images in Firefox 46.0, Mint 17.3 (I copied in fallback folder from multiRes version and fixed the fallbackPath before testing):
![no_webgl](https://cloud.githubusercontent.com/assets/18735837/15347816/fa0738da-1d18-11e6-942f-8a93dc654e19.png)

**Comment by mpetroff** [comment]
I forgot that Firefox doesn't render the CSS 3D transforms properly, so the fallback renderer is disabled for it. Since Google seems to have removed the flag to disable WebGL, you have to disable it by launching the browser from the terminal, e.g. `chromium-browser --disable-webgl` or `google-chrome --disable-webgl`.

**Comment by tomas-nz** [comment]
Thanks a lot! I managed to put it all together:
- Reusing bulk of the tiles with help of symlinks (and adding fallback folder from multiRes)
- Using SaladoPlayer if Flash is available
- Otherwise using Pannellum

My first panorama that has it all implemented is here: https://tomassobekphotography.co.nz/pano36.php

**Comment by tomas-nz** [comment]
I was celebrating too soon. I noticed that on the most detailed zoom level there was a subtle inconsistency in one part of the panorama. I guess the slightly different cube sizes add up somewhere (even though the original image and tile sizes are identical). So I just have to include the whole multiRes tree.

Thanks anyway for a brilliant piece of software!

**Comment by kaefert** [comment]
Hello @tomas-nz !
I did for one of my panoramas the same as described here:
Link separate renumbered level directories from my SaladoPlayer format for each wall to use in a Panellum config.json.

I did not find any inconsistencies but before I implement the same way for many panoramas I wanted to ask you to please describe the problems you found that made you decide to include a whole separate multiRes tree for Panellum.

**Comment by tomas-nz** [comment]
Hi @kaefert ,
I cannot say I remember exactly. I _think_ there were slight misalignments between tiles on the most detailed level. But I don't use SaladoPlayer any more, since I found a way to include background music in Panellum. Just in case it interests you, here is more info - https://tomassobekphotography.co.nz/articles/how-to-create-spherical-panoramas.php#website

**Comment by kaefert** [comment]
So I found some of my older lower resolution panoramas have the default SaladoConverter generated tile overlap too...

I'm gonna try and experiment with specifying a smaller tile size in the panellum config json to maybe correct for the misallignment. If the artifacts are too bad I'll have to regenerate those tiles without overlap..

**Comment by indus** [comment]
#997 would allow the use of the deep zoom format (and others). Path would look like:
```
"path": "/%l0/%s%y_%x",
```

**Comment by kaefert** [comment]
My Salado Layers are numbered different somehow. They start around 9 or 10 with the lowest resolution and go up to something around 16 for the highest resolution.

To workaround this issue in 2019 I've written a script that creates softlinks from the lowest level to "panellum_1" and incrementing the number for each following level.
