### ISSUE TITLE
Hotspots misplaced in fullscreen mode in Safari on OS X

### ISSUE THREAD

**Issue by mzoeller** [mpetroff/pannellum#155]
When switching to fullscreen mode in Safari (9.0.3) on OS X hotspots are misplaced and aspect ratio is skewed. Non fullscreen mode works fine. 

Example: http://www.panoheld.de/portfolio-item/ferienwohnung-studio44/

**Comment by mpetroff** [comment]
I think this is fixed. Can you please test the fix?

**Comment by mzoeller** [comment]
It is! Working fine now.
