### ISSUE TITLE
minPitch, maxPitch not working

### ISSUE THREAD

**Issue by orb51** [mpetroff/pannellum#157]
when I try to set minPitch or any other min/max values in the example.htm, an error occurred with that value? Do not know what I'm doing wrong. Other parameters work

**Comment by mpetroff** [comment]
It doesn't work because it's not on [the list on valid URL configuration parameters](https://github.com/mpetroff/pannellum/blob/master/doc/url-config-parameters.md). It can only specified in a JSON configuration as the documentation says.
