### ISSUE TITLE
Black screen although sceneFadeDuration is set

### ISSUE THREAD

**Issue by mzoeller** [mpetroff/pannellum#158]
When moving from on scene to another there is a short interval where a completely black screen is shown. After about 500ms the two views are correctly faded.

**Comment by mpetroff** [comment]
What browser, browser version, OS, and OS version are you using?

**Comment by mzoeller** [comment]
Sorry forgot to mention. I don't think it is browser or OS related. Same behavior with Firefox on Linux and Windows, EDGE on Windows, etc. Example: http://api.panoheld.de/b5b2ec20c9fda9c64e44164af63d491897195c96/

**Comment by mpetroff** [comment]
It was multires related (although the issue was with the fade portion, not the multres portion). The renderer for the first scene was being removed slightly before the image data finished loading into the fade placeholder image, causing the flicker. I fixed this.

**Comment by mzoeller** [comment]
Confirmed fixed. Great! The tours feel much smoother now :)
