### ISSUE TITLE
Event System / Error

### ISSUE THREAD

**Issue by boredom2** [mpetroff/pannellum#164]
Hi there,

first of all, thanks for your really amazing library.
Do you think it might be possible to extend the new Event System to also let any external Framwork now, when there is an error? Currently, I am monitoring the display state of the error-box, but thats not really elegant :)

Thanks!

**Comment by mpetroff** [comment]
I just added a `error` event that is fired whenever an error occurs, which passes the error message to the listener as the first argument.
