### ISSUE TITLE
Device Orientation Support

### ISSUE THREAD

**Issue by boredom2** [mpetroff/pannellum#165]
Hi,

the Device Orientation works really nice.
What might be confusing though is the button - if only has a role for the first click. Afterwards, it does not really serve any purpose (until you manually drag). Wouldnt it be usefull to let him work like the "fullscreen" button, meaning: enable and disable device orientation support.
Currently, if I manually drag the image, Device Orientation Listeners seems to be deactivated again. Two states for this button (maybe just an alpha value) would make the idea behind that button more intuitive.

Thanks.

**Comment by mpetroff** [comment]
I just added this in 3e99ecbb397a8992f00eb7bef0b0648706c34c8d.
