### ISSUE TITLE
AutoRotate issue and possible improvements

### ISSUE THREAD

**Issue by tomas-nz** [mpetroff/pannellum#170]
In current master, if autoRotate is a positive number, the feature works as advertised. However if autoRotate is a negative number (i.e. rotate in the opposite direction), following happens:

1. Upon page/panorama load it starts rotating in correct direction.
2. When interrupted by user action, autorotation starts after correct interval (as per autoRotateInactivityDelay) however in the _wrong direction_.

Also, here is a couple of possible improvements:

- Restart of autorotation after user action has an initial "jump" or perhaps better described as a quick slide before dropping back into regular rotation speed.
- If user changed tilt or hfov they stay at their current values. It would be more visually pleasing to slowly glide back into initial tilt and hfov (zoom level).

**Comment by mpetroff** [comment]
I fixed the bug portion; not only was the direction being ignored, so was the speed. I'll leave this issue open to track the suggested improvements.

**Comment by mpetroff** [comment]
I fixed the rotation speed jump when restarting in bf9c6f50730ae0d30223dec9d2603617f47bc34b. I'll add the horizon centering after #162 is implemented.

**Comment by mpetroff** [comment]
Horizon centering and return to initial HFOV was added in f5edaf09617dbb6d89c192d27e1525ef179853de.

**Comment by tomas-nz** [comment]
Hi @mpetroff,
Thank you for implementing this. I noticed two issues with the current code:
1) If I set pitch <> 0, the autorotation after a pause and resume goes to 0 degrees, not the original pitch value.
2) I don't know how to reproduce this one at will, but I caught the autorotation once going the other way round at some point (in a panorama with autoRotate: -1). This happened after a number of stops, zoom in/out, minimize browser window... If I find a reproducible pattern I will update.
Cheers, Tomas

**Comment by mpetroff** [comment]
I had originally programmed it to go to zero pitch, but I just changed it to go to the original pitch in 5228f48f3087e75227ee37aa6b4cf074d7ea97ac.

Although I never reproduced it, I think I fixed the direction bug as well (it was getting the direction from a calculation instead of the auto rotate value directly, so I suspect there was sometimes a rounding error that would cause a sign flip and thus change the direction).
