### ISSUE TITLE
Hotspot's targetYaw ignored when 0

### ISSUE THREAD

**Issue by MmmDee** [mpetroff/pannellum#172]
In my "tour", there are two photos with hotspots pointing one to the other.
1) Porch and Foyer were taken with a Ricoh Theta S, inadvertently oriented 180 degrees apart. 
2) FIrst scene is Porch (yaw at 180) looking toward Foyer with a hotspot (yaw at 180) linking to Foyer. Clicking this hotspot transitions to the Foyer ((yaw at 0). Using the mouse and rotating the Foyer picture 180 degrees reveals a hotspot linking back to the Porch. Clicking that hotspot with targetYaw set to 0 should transition to Porch with orientation at 0, but it remains at 180. If the targetYaw is set to 0.1 (non-zero), then it works as expected.

I don't believe this is related to recent changes as my copy of Pannellum 2.2 is from June 15th, but I confirmed the behavior is present this morning in the CDN. Below is the example.

```
pannellum.viewer('panorama', {   
    "default": {
        "firstScene": "porch",
        "author": "Bob",
        "sceneFadeDuration": 1000,
		"ignoreGPanoXMP": true		
    },

```
    "scenes": {
        "porch": {
            "title": "Porch",
            "hfov": 120,
            "pitch": 0,
            "yaw": 180,
            "type": "equirectangular",
            "panorama": "http://somewebsite.net/images/frontporch.jpg",
            "hotSpots": [
                {
                    "pitch": 0,
                    "yaw": 180,
                    "type": "scene",
                    "text": "Foyer",
                    "sceneId": "foyer"
                }
            ]
        },

        "foyer": {
            "title": "Foyer",
            "hfov": 120,
            "yaw": 0,
            "type": "equirectangular",
            "panorama": "http://somewebsite.net/images/foyer.jpg",
            "hotSpots": [
                {
                    "pitch": 0,
                    "yaw": 170,
                    "type": "scene",
                    "text": "Porch",
                    "sceneId": "porch",
                    "targetYaw": 0,
                    "targetPitch": 0
                }
            ]
        }
    }

**Comment by mpetroff** [comment]
Thanks for reporting the bug; I just fixed it. There was a conditional that was checking the value, and JavaScript evaluates `0` as `false`, so it wasn't being applied; it's now explicitly checking if the value is defined (`if (value !== undefined)` instead of `if (value)`).

**Comment by MmmDee** [comment]
I emptied the cache on my development system, but no change in behavior. I don’t think your server caches the js. Do I need to do something else?

 

Bob

**Comment by MmmDee** [comment]
Thanks Matthew, I updated Pannellum on my server and can confirm the "fix" indeed resolves the issue.
