### ISSUE TITLE
Question: Compass

### ISSUE THREAD

**Issue by MmmDee** [mpetroff/pannellum#177]
Using the CDN, the compass works well; however, when using the latest (commit 38250c1d15) compiled sources on my webserver, the compass no longer works (but everything else appears to) and I'm at a loss to figure out why. Quite likely it's an error in the way I compiled/uploaded pannellum.  Thoughts from you Matthew or anyone else? Here's a link using the source:  http://bobwells.net/dorimckinney/muni/compass.html or another link using compiled: http://bobwells.net/dorimckinney/muni/compass4.html

**Comment by mpetroff** [comment]
It appears b0c2f03511c09f1b140079b5cf99281bca46d023 introduced a regression. I fixed it in b719ace20a709f5f4bf55684015ece69a29de999.

**Comment by MmmDee** [comment]
Thanks Matthew, I confirm the fix.
