### ISSUE TITLE
deviceorientation event is deprecated on insecure origins [Chromium v50]

### ISSUE THREAD

**Issue by Cyrille37** [mpetroff/pannellum#180]
Hi
While running on Chromium (opensource Chrome version) over HTTP the console say:
> The deviceorientation event is deprecated on insecure origins, and support will be removed in the future. You should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details.

Cheers.

**Comment by mpetroff** [comment]
It's been deprecated for a while for HTTP, but Google doesn't seem to have timeline for when it will be blocked. When it does get blocked, the device orientation button just won't show up on HTTP connections but will continue to work fine when load over HTTPS.
