### ISSUE TITLE
Hotspot from image in cube map

### ISSUE THREAD

**Issue by perusopersonale** [mpetroff/pannellum#182]
Hi,
Thanks for the great library.

I'm using for a project the cube map option, I would like to know if there is a simple way to calculate hotspot information, from face image coordinates.

Thanks anyway.

**Comment by mpetroff** [comment]
I would recommend setting the [`hotSpotDebug` option](https://github.com/mpetroff/pannellum/blob/master/doc/json-config-parameters.md#hotspotdebug) to `true`, which will print coordinates to the console on mouse clicks. This makes it easy to find coordinates to place hot spots.

If you want to determine coordinates directly from cube map images, you'd have to work out the math yourself.
