### ISSUE TITLE
Multires with partial equirectangular panorama

### ISSUE THREAD

**Issue by Eroic** [mpetroff/pannellum#184]
Hi, 

I try to use our project with some of my partial equirectangular panorama. Can I use multires format ?
I tried with generate.py but it not support partial panorama.  The reason why I want to use multires format is the size of my panorama, 200 Mpixel and over...

Thanks

**Comment by Eroic** [comment]
I found an way, I insert my image inside a bigger black image.   the black image have the good ratio to cover 360x180 deg when my image have 163.97 x 44.16 deg.  This is limitating because I need to resize down my original image of 574 Mpixel becaune nona.exe crash a this size...

My exemple at 41 Mpixel image plus black pixels, total of 330 Mpixel
http://photoericlaplante.com/pano/

Thanks

**Comment by mpetroff** [comment]
As the multires format is cube map based, there isn't a simple way to have it support partial panoramas. The partial panorama needs to be padded into a full 360 x 180 degree equirectangular image to work.

**Comment by DDvO** [comment]
I meanwhile managed to adapt the Python and JavaScript sources to support partial panoramas without wasting space and communication bandwidth on tile files that represent areas never shown. I can share the details if you're interested.

Here is [an example partial cylindrical pano](http://gallery.davoh.de/Seebensee/dsc_3927-3933.html) generated this way.
