### ISSUE TITLE
Should inertia cease during loadScene

### ISSUE THREAD

**Issue by MmmDee** [mpetroff/pannellum#186]
When rotating an image there is "inertia". If, during the inertia motion, a `loadscene` is done into that frame, the new scene undergoes the balance of inertia left over from the prior scene. Is this appropriate? Or should `loadScene` cancel a current inertia?

**Comment by mpetroff** [comment]
I think the motion should stop. This only became an issue recently when I added API functions to change the scene, since clicking on hot spots would stop the motion. I fixed it in 6cf5532ba16a1af97400c366b925a1cfb0c1f473.
