### ISSUE TITLE
bug - config's "basePath" not used when loading via URL Configuration Parameters

### ISSUE THREAD

**Issue by Cyrille37** [mpetroff/pannellum#188]
Hi,

When using pannellum with url config file, the config "basePath" is ignored, that results on not found images.

Cheers

**Comment by Cyrille37** [comment]
Forget my fixe, it not resolves the bug...

**Comment by Cyrille37** [comment]
I try to put "basePath" in root's config or in "default" section but steal not change ; the basePath is not used ...
I read the pannellum.js code but do not understand why...

**Comment by mpetroff** [comment]
The path was being overridden in `standalone.js`. It should be fixed now.
