### ISSUE TITLE
Absolute URL doesn't work with basePath 

### ISSUE THREAD

**Issue by strarsis** [mpetroff/pannellum#190]
When specifying an absolute URL for basePath, 
the absolute URL is appended to the path where the config json is loaded from, 
instead as an absolute URL.

Example:
config from: http://example2.com/test/config.json
basePath in config: http://example.com/pano
Resulting request URL: http://example2.com/test/http://example.com/pano/1/l0_0.jpg
Expected request URL: http://example.com/pano/1/l0_0.jpg

**Comment by MmmDee** [comment]
Adding on to this... `basePath` seems to be global and not specific to a viewer. If I set-up a viewer in, for example, a `div` with `id="panorama"`, then setup another viewer in a different `div` with `id="panorama2"`, the `basePath` established for the second viewer becomes the `basePath` for the first viewer.  If further viewers are set-up, then those `basePath` definitions interfere with the other viewers.

Is this intended?

**Comment by mpetroff** [comment]
There are two different `basePath` options: a configuration-wide one and a multires one. If the configuration-wide one is not specified when the standalone viewer (`pannellum.htm`) is used, it is set to the location of the JSON configuration file. The multires base path is then appended to the regular base path. Since this isn't desirable behavior when an absolute URL is used, I changed it to use only the multires base path if it's an absolute URL in 794f74fad24fcc6b8ccca5568b7afa215967da4f.

**Comment by mpetroff** [comment]
@MmmDee: Are you sure there aren't references in your own code that are causing the linkages. Pannellum is wrapped in a [closure](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Closures), so different viewers are completely separate and can't access each other's variables.

**Comment by strarsis** [comment]
The configuration-wide basePath option is to be directly passed as GET parameter to pannellum.html?
I tried basePath option as sibling of multiRes option and also as first level option in config.json, 
but there was no effect.

**Comment by MmmDee** [comment]
@mpetroff: I have no doubt it's an error on my part. As I said, I'm trying to autoload a multires into `<div id="panorama">`. Then I have a series of buttons to `loadScene` into the same `div`. I initially tried this by specifying a multires definition and scene definitions into the same viewer which has led me down several paths. I then have 3 additional viewers into separate div's. The latter div's had a `basePath` that seemed to interfere with the first div. The console message I got when loading the first div said in effect, can't find (simplified) basePath/url-to-multires.  The `basePath` Chrome was looking for was from another viewer.

I'll attach code fragments later this evening. If you have an example of combining multires and scenes in the same viewer, that would be most helpful... but I don't expect you to work out my code ideas.

**Comment by mpetroff** [comment]
@strarsis: The difference between the configuration-wide `basePath` and multires `basePath` can be seen in this example configuration file.
```json
{
    "type": "multires",
    "basePath": "https://example.com/panorama/",
    "multiRes": {
        "basePath": "multires",
        "path": "/%l/%s%x%y",
        "fallbackPath": "/fallback/%s",
        "extension": "png",
        "tileResolution": 256,
        "maxLevel": 4,
        "cubeResolution": 2048
    }
}
```

With regards to using an absolute path, are you sure you pulled the latest changes? With the last commit, it works for me (it didn't before).

**Comment by mpetroff** [comment]
@MmmDee: The example on the pannellum.org homepage combines multiple multires scenes: https://github.com/mpetroff/pannellum.org/blob/master/layouts/index.html.

**Comment by strarsis** [comment]
With build from master it works, apparently the CDN release is quite outdated.

**Comment by mpetroff** [comment]
I only changed the behavior an hour ago, so it obviously isn't in a release yet.

**Comment by strarsis** [comment]
Thanks! This solves the issue for me.

**Comment by MmmDee** [comment]
Aaarrrrggghh, I've seen that example before I believe but forgot about it. I'm sure that will help me out, but I can't try it right now (I'm busy trying to be a good husband). Thanks again so much. I'll get back to you if I can reproduce the global basePath problem I encountered.

**Comment by MmmDee** [comment]
@mpetroff: I got it to work using the example you cited. Here's my website directory hierarchy:

http://bobwells.net/dorimckinney/muni/
http://bobwells.net/dorimckinney/muni/
http://bobwells.net/dorimckinney/muni/

**Comment by MmmDee** [comment]
I'm quite happy now knowing multires `basePath` can be an absolute URL. That frees up the configuration-wide `basePath` for the other scenes.
