### ISSUE TITLE
Add crossOrigin option

### ISSUE THREAD

**Issue by strarsis** [mpetroff/pannellum#191]
For loading the viewer/content across domains, 
it would be helpful to be able to set the crossOrigin for the image requests.
````
Failed to execute 'texImage2D' on 'WebGLRenderingContext': The cross-origin image
````

**Comment by mpetroff** [comment]
The regression was introduced a week and a half ago when I refactored the multires texture loading; it should be fixed now.

**Comment by strarsis** [comment]
Thanks for the fast response.

There is a different error now:
````
Image from origin 'http://example.com' has been blocked from loading by Cross-Origin Resource Sharing policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://example2.com' is therefore not allowed access.
````

**Comment by mpetroff** [comment]
The server isn't configured to allow [CORS](http://www.test-cors.org/), which is needed to load the images via JavaScript from a page on a different domain.
