### ISSUE TITLE
Compass defaults to True if XMP heading present.

### ISSUE THREAD

**Issue by MmmDee** [mpetroff/pannellum#192]
Per the title... I believe the compass should truly default to false unless specifically set true, or the documentation should state it will be true if heading is present in XMP data. You might consider adding that compass uses "true" north (same as Google maps) as opposed to "magnetic" north. In my area of the country, the two differ by 12+ degrees.  Further info [here](http://www.ngdc.noaa.gov/geomag-web/#declination) and [here](http://googlecompass.com/GoogleMapsProjection.htm).

As an aside, you may wish to update documentation to state pitch, yaw are degrees (since you mentioned that in` horizionPitch` and `horizonRoll`).

**Comment by mpetroff** [comment]
I see no reason not to use heading information if it's present, so I think the compass should appear if the XMP metadata contains heading information. I did however clarify this in the documentation (and added "in degrees" to the parameter descriptions that were missing it).

With regards to magnetic declination, I'm not sure why anyone would assume a panorama viewer would correct for the offset. The compass display uses neither "true" north nor "magnetic" north&mdash;it uses whatever it's given. For example, the heading information reported by the Ricoh Theta S is magnetic north, while smartphone panoramas taken with the Google Camera app probably record true north (I don't actually know).

**Comment by MmmDee** [comment]
The magnetic declination issue only came up when my panoramas didn't match Google Street View, due to, as you note, the Ricoh Theta S (and my iPhone by default), uses "magnetic" north (12 degrees isn't a whole lot of difference, but it can be to some people). I haven't pursued which reporting the Google Camera app uses, but I will now that my interest is raised. The iPhone has a setting as to "which north" to use.
