### ISSUE TITLE
IE 11 & multires incompatibility with loadScene

### ISSUE THREAD

**Issue by MmmDee** [mpetroff/pannellum#194]
Pannellum  (development) and IE 11 work well with equirectangular images and the combination also works "acceptably" to display `multires` (subject to IE's use of software rendering) when invoking the viewer initially with a `multires` image as the `default`/`firstScene`), but the combination does not work, or works very slowly (minutes-to-load) when loading `multires` image via `loadScene`.

Is there a difference in the manner pannellum loads `multires` during initial load vs `loadScene`? 

Should we use Renderer.getCanvas/getExtension/getParameter/UNMASKED_RENDERER_WEBGL to make allowances for IE? Doing so seems to expose an unnecessary low-level detail.

Test computer is running Windows 10, hardware is an Intel Core 2 duo processor and an Nvidia GPU.

**Comment by mpetroff** [comment]
The only difference is that the WebGL context is reused between scenes. This was introduced in 38250c1d15d4ee3c792ae442336c53f637893f7f, so can you please test the revision prior to this change, 53c6cf85f7eb7c1accf07ab5fd2e23d6251c5151?

**Comment by MmmDee** [comment]
I'm not an expert at git, but this is what I did...
```
git clone <repository> p4
cd p4
git reset --hard <536cf8...>
cd utils/build
./build.sh
```

Ftp'd new files to new server directory, changed html file to point to newly uploaded version.  Using Edge and IE 11, the black "artifacts" and the continued "inertia" on loadScene have returned, but the `multires` `loadScene` now works.  This console message is displayed on page load:

    WEBGL11135: getContext: Context attribute depth:false is not currently supported
    pannellum.js (10,266)

**Comment by mpetroff** [comment]
As far as I can tell, this is a bug in Microsoft's software WebGL rendering. I was not able to reproduce it in a Windows 10 VM, although I did manage to crash IE 11. I'm not sure there's much I can do about it; the change to reusing the WebGL context is important enough not to roll back, since WebGL contexts can't be deleted, which caused issues after too many scenes were loaded back when a new context was created for each scene.

**Comment by MmmDee** [comment]
Interesting that in IE you can load regular **_equirectangular_** images into the same context repeatedly, but you then can't load a **_multires_** image into that same context (but you can then continue returning to load **_equirectangular_** images into that context). I do recall the issue with creating new contexts for each image, eventually WebGL would hang (after about 20 `loadScenes` into the same div/canvas in my case--I figured that was due simply to a memory leak).  I wonder how, after all this time, ANGLE and MS Basic Render Driver could be so different (no different than Trident/EdgeHTML vs Webkit/_et al_ compatibility I suppose).

**Comment by MmmDee** [comment]
Hmmm, the issue is **not** present in commit 38250c1. I'll walk up the commits to see when it first appears.

**Comment by MmmDee** [comment]
The issue surfaces on July 3, between 794f74f (issue not present) and f057406 (issue starts to show). This is a time when the roll was being addressed.

**Comment by mpetroff** [comment]
I haven't been able to reproduce the issue with IE 11 in a Windows 7 VM or a Windows 10 VM nor with Edge in a Windows 10 VM.

**Comment by MmmDee** [comment]
Well, it may be a combination of my hardware, ISP and/or server. I was leaning toward a server etiology because crossOrigin wouldn't seem to have any (local) hardware dependency. Just something to tuck away in the back of your mind. I'll patch my copy of the repository as I've noted above.

**Comment by MmmDee** [comment]
Interestingly, I had to [delete line 986](https://github.com/mpetroff/pannellum/compare/794f74...f05740#L986), not simply sett crossOrigin = '' in order for it to work.

**Comment by mpetroff** [comment]
"The empty string is also a valid keyword, and maps to the Anonymous state."

**Comment by MmmDee** [comment]
Thanks, I misinterpreted that statement the first time I read it.  Unfortunately, while that patch fixes the issue I was having with a page I hosted on my server and accessed directly (similar to the testmultires5.html file I sent you the link for), it breaks the page I have hosted on another server (essentially with a similar page embedded), stating "Your browser does not have the necessary WebGL support to display this panorama." For now, I'll have give up on `loadScene` to reload a multires image on that other server.

**Comment by MmmDee** [comment]
More info... I added .htaccess to my working directory and have this server response from a testing website (I don't yet know if that's correct for my needed CORS access):

HTTP/1.1 200 OK => 
Date => Sat, 16 Jul 2016 21:52:51 GMT
Server => Apache/2.4.18
Access-Control-Allow-Origin => *
Last-Modified => Sat, 16 Jul 2016 21:47:18 GMT
ETag => "40001b6-a1f-537c7addd6514"
Accept-Ranges => bytes
Content-Length => 2591
Vary => Accept-Encoding,User-Agent
Access-Control-Allow-Headers => origin, x-requested-with, content-type
Access-Control-Allow-Methods => GET, POST, OPTIONS
Connection => close
Content-Type => text/html

I also noticed IE 11 task manager network access reporting continued I/O long after the page was loaded.  First arrow is IE 11 "at rest, nothing loaded". Second arrow is "long after" test page loaded, note continued network I/O, memory footprint (varied 130-175MB) and CPU usage (varied). Third and 4th arrows compare Chrome and IE 11 sitting at the same test page (several minutes after the page is loaded and displayed).

![image](https://cloud.githubusercontent.com/assets/934483/16897605/5077caa6-4b6b-11e6-9716-5c47bb2c3d4c.png)

**Comment by MmmDee** [comment]
This is the output of the IE 11 Network Performance Monitor (click on image for full size). The GET of d0_0 is repeated _ad infinitum_ and accounts for IE's continued network I/O reported above..

![image](https://cloud.githubusercontent.com/assets/934483/16897690/e8da5d2a-4b6d-11e6-89cc-c69cb12f3631.png)

**Comment by MmmDee** [comment]
The HTTP headers and responses:

   Request URL: http://mywebsite/multires/foyer/1/d0_0.jpg
   Request Method: GET
   Status Code: 200 / OK
   
 - Request Headers
   Accept: image/png, image/svg+xml, image/jxr, image/*; q=0.8, */*; q=0.5
   Accept-Encoding: gzip, deflate
   Accept-Language: en-US, en; q=0.5
   Cache-Control: no-cache
   Connection: Keep-Alive
   Host: bobwells.net
   Origin: http://mywebsite.net
   Referer: http://mywebsite/testCORS.html
   User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; rv:11.0) like Gecko
   
 - Response Headers
   Accept-Ranges: bytes
   Access-Control-Allow-Headers: origin, x-requested-with, content-type, origin, x-requested-with, content-type, origin, x-requested-with, content-type, origin, x-requested-with, content-type, origin, x-requested-with, content-type
   Access-Control-Allow-Methods: GET, POST, OPTIONS, GET, POST, OPTIONS, GET, POST, OPTIONS, GET, POST, OPTIONS, GET, POST, OPTIONS
   Access-Control-Allow-Origin: *, *, *, *, *, *
   Connection: Keep-Alive
   Content-Length: 21135
   Content-Type: image/jpeg
   Date: Sat, 16 Jul 2016 23:05:43 GMT
   ETag: "4000a99-528f-536b399f9ac9b"
   Keep-Alive: timeout=5
   Last-Modified: Sun, 03 Jul 2016 04:24:53 GMT
   Server: Apache/2.4.18

**Comment by MmmDee** [comment]
One of the **Chrome** HTTP headers and responses. Chrome does _not_ repeat the file GET forever:

Request URL:http://mysite.net/muni/multires/foyer/1/l0_0.jpg
Request Method:GET
Status Code:304 Not Modified
Remote Address:107.180.58.62:

- Response Headers
view source
Connection:Keep-Alive
Date:Sun, 17 Jul 2016 17:46:52 GMT
ETag:"4000a9a-5b46-536b399fa393b"
Keep-Alive:timeout=5
Server:Apache/2.4.18

- Request Headers
view source
Accept:image/webp,image/*,*/*;q=0.8
Accept-Encoding:gzip, deflate, sdch
Accept-Language:en-US,en;q=0.8
Cache-Control:max-age=0
Connection:keep-alive
DNT:1
Host:mysite.net
If-Modified-Since:Sun, 03 Jul 2016 04:24:53 GMT
If-None-Match:"4000a9a-5b46-536b399fa393b"
Origin:http://mysite.net
Referer:http://mysite.net/muni/testCORS2.html
User-Agent:Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36

**Comment by mpetroff** [comment]
It seems IE doesn't cache CORS-requested files:
https://social.msdn.microsoft.com/Forums/ie/en-US/98bcdf4c-4a55-4243-a2ea-2064ed9d8568/xmlhttprequestcors-doesnt-use-local-cache?forum=iewebdevelopment
https://connect.microsoft.com/IE/feedback/details/806034/xmlhttprequest-cors-doesnt-use-local-cache

**Comment by MmmDee** [comment]
Not caching CORS-requested files, would that explain why it goes into an "infinite loop" requesting the same file(s)?

**Comment by MmmDee** [comment]
Seems to be a MS issue dating back a couple years. Though, I'm not sure it's a cache issue as the infinite GET is being done even when the image is "static"/not-moving/not-animated. I would think once the tile/texture is loaded, it would not need to be re-loaed.

**Comment by MmmDee** [comment]
These functions keep getting "called" in libpannellum, lines 994-104 with the same src, so I suspect something in the logic is amiss (race condition with cacheTop?):

```
        TextureImageLoader.prototype.loadTexture = function(src, texture, callback) {
            this.texture = texture;
            this.callback = callback;
            this.image.src = src;
        };

        function PendingTextureRequest(src, texture, callback) {
            this.src = src;
            this.texture = texture;
            this.callback = callback;
        };
```

**Comment by MmmDee** [comment]
The same infinite GET issue occurs when using IE 11, the development pannellum (hosted on my server) and the multires example from the [pannellum website](https://pannellum.org/documentation/examples/multiresolution/). I wanted to test using a multires image from an https website.

**Comment by mpetroff** [comment]
It seems this issue is definitely related to network speed. I was finally able to reproduce it by [simulating](http://www.dallaway.com/sloppy/) a 56kbps connection. When a tile took too long to load, the browser would try to load it multiple times at once. While this was a bug, it didn't cause a problem in most browsers, since once the first request finished loading, the other requests would immediately complete. However, since IE and Edge don't cache CORS requests, they would continue loading the other requests; since the requests were being created faster than the images were being loaded, the number of requests would keep increasing until something crashed. I fixed this bug, which should hopefully fix the issue.

**Comment by MmmDee** [comment]
On limited testing, it appears to have solved the issue...  While my development systems are "wireless"(actually, in-house Ethernet over powerline), the rate is not as bad as 56kbps (I remember those days, and before that, 110 baud teletype, 300 baud acoustic couplers, 1200 baud Hayes modems). The issue was quite reproducible and I'm sure exacerbated by no-cache for CORS images..

Thanks again for the fix, you're the best.

**Comment by MmmDee** [comment]
Testing shows the issue resolved in both IE 11 and Edge. Interestingly, in IE 11 the mutlires/CORS images continue to be fetched from the server, rather than cache **BUT** Edge now fetches multires/CORS images from cache :+1:

**Comment by MmmDee** [comment]
Sigh, I spoke too soon. Another gremlin has reared its head. While the webpage loaded correctly in IE/Edge when I went straight to my server containing the images, it doesn't work when it's embedded into another server which is accessing images on my server.  It fetches the first tile (l0_0.jpg), but then goes no further (it doesn't display that tile which may be out of view). The console reports no errors.

**Comment by MmmDee** [comment]
The hangup, at least for IE11, is a SecurityError at [line 968](https://github.com/mpetroff/pannellum/blob/master/src/js/libpannellum.js#L968) at the first `gl.texImage2D`.  There is no error when using _pannellum.org_ as the image source, only when using a non-https website.

```
    function processLoadedTexture(img, tex) {
        gl.bindTexture(gl.TEXTURE_2D, tex);
        gl.texImage2D(gl.TEXTURE_2D, 0, gl.RGB, gl.RGB, gl.UNSIGNED_BYTE, img);
        gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MAG_FILTER, gl.LINEAR);
        gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MIN_FILTER, gl.LINEAR);
        gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_WRAP_S, gl.CLAMP_TO_EDGE);
        gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_WRAP_T, gl.CLAMP_TO_EDGE);
        gl.bindTexture(gl.TEXTURE_2D, null);
    }
```
The first image is obtained without problem, the issue arises when trying to load it.

**Comment by MmmDee** [comment]
Um, nevermind.... I fixed the server .htaccess file and it now works again.
