### ISSUE TITLE
Turn off mouseZoom

### ISSUE THREAD

**Issue by michaelalockett** [mpetroff/pannellum#200]
I have added "mouseZoom": false to my config but it doesn't seem to be turning off the mouseZoom function. Is there something I am missing? All other configurations I have set up seem to be working as expected, so I don't think I have set it up wrong.

Thanks

**Comment by mpetroff** [comment]
Are you using the latest development version or the 2.2 release? The option was added last month in 3e0250eb72580b06de70a8f1c2de36648ec58a3a, after the last release.

**Comment by michaelalockett** [comment]
Thanks. I was using the CDN version before but am now using the latest development version and it is working.
