### ISSUE TITLE
getScene 

### ISSUE THREAD

**Issue by kimara66** [mpetroff/pannellum#201]
Hi,
I am using the cdn "https://cdn.pannellum.org/2.2/pannellum.js" in my code but getScene is returning undefined. Do I need to download the 2.2.1 version in order to be able to use it?

Thank you!

**Comment by strarsis** [comment]
Yes, you have to use something recent like a build from master.

**Comment by mpetroff** [comment]
The CDN is the 2.2.1 version. The function was added since the last release.
