### ISSUE TITLE
How do we add and use getScene()?

### ISSUE THREAD

**Issue by awktopus** [mpetroff/pannellum#203]
I'm confused as to how to call getScene() . I set var = pannellum.viewer(...) but when I write viewer.getScene() it still doesn't work.

Thanks!

**Comment by MmmDee** [comment]
Take a look at issues #196 and #201 and be sure you're using the latest development branch and not the latest "release".

Here's a sample of using `getScene` that's invoked upon a scene change event:

```
viewer = pannellum.viewer('panorama', {your config is in here})

function sceneChangeListener() {
        console.log("Scene changed");
        console.log("Scene " + viewer.getScene());
        console.log("Yaw " + viewer.getYaw());
        console.log("Pitch " + viewer.getPitch());
        console.log("Hfov " + viewer.getHfov());
};

function sceneLoadListener() {
        console.log("Load done");
};

viewer.on('scenechange', sceneChangeListener);
viewer.on('load', sceneLoadListener);

```

**Comment by awktopus** [comment]
Wow, this is perfect. Thank you so much for your help and patience! (I'm new to coding haha)

**Comment by barkgj** [comment]
Hi, I tried to use the "dev" branch to be able to use the getScene function, and the "on" function to hook to the event, but that one fails to initialize, saying : "Uncaught ReferenceError: libpannellum is not defined". Any advise? Is there a workaround for that? Thanks

**Comment by mpetroff** [comment]
You're not including `libpannellum.js`, which is needed when using the (non-minified) development copy.

**Comment by barkgj** [comment]
Ah, perfect, thanks, working now :)

**Comment by ner00** [comment]
Sorry, but I'm having difficulties using this with the minified version of pannellum.
How do I call getScene()? Or more importantly, with which object do I call it?
I am using a single html file and loading different panoramas from the url, can someone throw an example for the standard minified version? Thanks!

**Comment by aproni34f** [comment]
I have just tested the code above using develop files and the scenechange does not fire on load.  I guess this event only fires when you manually call loadScene? 

Also in load event getScene is undefined so you can get scene on first load?

**Comment by mpetroff** [comment]
The `scenechange` event is triggered by scene changes, either from calling the `loadScene` method or by clicking on a tour hot spot; it is not triggered on initial load.
