### ISSUE TITLE
adding images to hotspots

### ISSUE THREAD

**Issue by neta-kedem** [mpetroff/pannellum#204]
Hi,
I love your library, and I have a question- I want to replace the hotspots with costume images, and I want those images to move as I move in the panoramic view. so I pushed them in the hotspot div, but when the image is in the side, it moves correctly but won't stretch the right way, so it looks quite bad.
I want it to look like a part of the background.
So, is there a way to replace the hotspots with an image and make it look like a natural part of the panorama?
I'm using the cube multires view.
thanks!

**Comment by mpetroff** [comment]
This isn't possible at the moment. I plan to make it easier to use custom styles for hot spots fairly soon, but support for background-type hot spots is much further out.

**Comment by neta-kedem** [comment]
Good to know. thank you for the quick answer
