### ISSUE TITLE
Gyroscope

### ISSUE THREAD

**Issue by charlesravndal** [mpetroff/pannellum#205]
#Hi! I'm just wondering if there's a demo or example in pannellum.org with deviceorientation. Is there a simpler way to implement the deviceorientation? Can't seem to find an instruction for it. Also, is it possible to use the preview image as a load button? Thanks!

http://bt.kreateam.io/demo/pan4/

**Comment by mpetroff** [comment]
The development version supports device orientation control, but the feature hasn't made it into a release yet. Once a new release is made, the [pannellum.org](https://pannellum.org/) demos will support it. With the development version, a button automatically appears under the zoom buttons on supported devices to activate device orientation control; there's also a `orientationOnByDefault` configuration option that when set to `true` will automatically turn on device orientation control on supported devices when the panorama is loaded.

It's not possible to use the preview images as a load button.

**Comment by charlesravndal** [comment]
Thank you very much!

**Comment by MmmDee** [comment]
@charlesravndal Regarding the "click a preview", you might take a look at issue #206 for a "workaround".

**Comment by charlesravndal** [comment]
@MmmDee  - Thank you!

**Comment by schroef** [comment]
@mpetroff ,

question you talk about dev versions. Are there repos of this :)

**Comment by mpetroff** [comment]
Yes, it's this Git repository. Also, this feature is in versions >= 2.3.

**Comment by schroef** [comment]
Is there more explained details on how to use it. Im not really sure i understand how to use that part. I tried adding at the JSON declarations, but noticed errors in the dev console

**Comment by schroef** [comment]
Still not very clear where i should add it then?

Is this the correct location?
![screen shot 2018-04-17 at 11 58 11 am](https://user-images.githubusercontent.com/6923008/38881800-adf66548-4236-11e8-8ea0-73882357f8e1.png)

**Comment by schroef** [comment]
Well it also seems my phone doesnt support it, i got a very old one now. I thought it had Accelerometer and gyroscope. Need to check it with different device
