### ISSUE TITLE
set{Pitch;Yaw;Hfov} with animate gets stuck

### ISSUE THREAD

**Issue by strarsis** [mpetroff/pannellum#212]
When setting the pitch/yaw/hfov using the setPitch(...)/setYaw(...)/setHfov(...) setter methods 
and with second argument 'animate' passed not as false (defaults to animate), 
subsequent calls to 
loadScene(sceneId, pitch!=='same', yaw!=='same', hfov!=='same') 
will ignore sometimes 
the passed pitch/yaw/hfov arguments to loadScene and 
the previously set pitch/yaw/hfov became stuck - 
the scene itself will be changed though.

If this is a race-condition with the animation-done handler, 
it may be really helpful, when loadScene(...) is called during the animation, 
to either cancel the current animation or 
set the passed pitch/yaw/hfov as the new animation target parameters instead.

**Comment by mpetroff** [comment]
The animation parameters weren't cleared when changing scenes, so they would immediately overwrite the new scene's parameters. It should be fixed now.
