### ISSUE TITLE
AutoRotate spins at abnormal speeds

### ISSUE THREAD

**Issue by randypng** [mpetroff/pannellum#213]
Hello

I'm having an issue here, after where autorotate is set and the panorama is loaded. When I switch the browser tab to another site, if I switch back to the panorama page after a while, the panorama spins really fast before slowing down back to the autorotate speed initially set.

**Comment by mpetroff** [comment]
This has already been fixed in the development version, in bf9c6f50730ae0d30223dec9d2603617f47bc34b. The fix will be in the next release.
