### ISSUE TITLE
Default Zoom

### ISSUE THREAD

**Issue by randypng** [mpetroff/pannellum#214]
Hello

I've noticed that when the panorama is loaded, it's zoomed in. Is there anyway to have the default zoom to be 0?

**Comment by mpetroff** [comment]
There's no such thing as a default zoom of zero. The "zoom" is set by setting the horizontal field of view. If you don't like the default, `100` degrees, you can set it wider to something like `120` using either `&hfov=120` as a URL configuration parameter or by adding `"hfov": 120,` to your JSON configuration file.

**Comment by apwall** [comment]
Before
Portrait - 80
Landscape - 100

Current dev version
Portrait-100
Landscape-100
