### ISSUE TITLE
Device Orientation and Hotspots

### ISSUE THREAD

**Issue by ghr022480** [mpetroff/pannellum#217]
Hi,
I'm using pannellum with device orientation support, and it's amazing!
There's just one small issue that I'd like help with: Hotspots aren't staying in place when orienting the phone in one of its 3 axis, see attached image for what I'm experiencing.

Any suggestion on this?
Thanks so much.

![image](https://cloud.githubusercontent.com/assets/20959041/17575017/d86c49e2-5f33-11e6-824a-ef9c3b7d7b17.png)

**Comment by mpetroff** [comment]
I forgot to implement roll transformations for the hot spots. This might take a bit to fix, since I need to work out the calculations first.

**Comment by mpetroff** [comment]
This should work now.

**Comment by ghr022480** [comment]
Thanks so much!
