### ISSUE TITLE
[question] pannellum will  auto set image resolution low down on mobile platform

### ISSUE THREAD

**Issue by sonygod** [mpetroff/pannellum#218]
pannellum will  auto setset resolution low down on mobile platform,my image size is 2048X2048,and autoset lower than 2048 on mobile platform.
is there any parm I missing?
cubeResolution or tileResolution ?

**Comment by mpetroff** [comment]
I'm not really sure what you're asking. There's nothing special done for mobile devices.

**Comment by sonygod** [comment]
when I use android opera to open pannellum ,the cube image resolution will become smaller than the original 。maybe opera's  bug.
