### ISSUE TITLE
Dynamic Tours via AJAX

### ISSUE THREAD

**Issue by amenk** [mpetroff/pannellum#219]
I want to make one massive tour - actually a GXXgle StrXXtView clone.

Basically it should be a tour of a whole city, but I think it is a bad idea, to put all data in the initial `scenes {} ` array. Is there a way to build scenes dynamically via AJAX when they come "close by" ?

**Comment by mpetroff** [comment]
Not yet.

**Comment by Aykelith** [comment]
I would also want be happy to see this feature. Also to be able to add hotspots dynamic. I already tried by modifying `initialConfig` and `config` but it doesn't work.

**Comment by mpetroff** [comment]
This was just added. See #241.
