### ISSUE TITLE
Issue with retrieving Files Directly from Azure BLOB

### ISSUE THREAD

**Issue by ParthKansara** [mpetroff/pannellum#221]
I am getting error from fetching files directly from BLOB to pannellum.

> XMLHttpRequest cannot load https://inspecttv.blob.core.windows.net/inspectimagefiles/agency13/7b74357d5f2b4246b253760fa96703b8.jpg. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://localhost:44300' is therefore not allowed access.`

For e.g. https://inspecttv.blob.core.windows.net/inspectimagefiles/agency13/7b74357d5f2b4246b253760fa96703b8.jpg

I want to display file with this kind of URL , but I am getting CORS issue for xmlhttprequest. 

Please suggest me the way so that I can use files from BLOB without any issue.

**Comment by strarsis** [comment]
This issue may be relevant: https://github.com/mpetroff/pannellum/issues/191

**Comment by ParthKansara** [comment]
I read #191 But I don't think that suggest any solution.

**Comment by strarsis** [comment]
The fix is in master, not in the latest release (yet).

**Comment by ParthKansara** [comment]
Thanks for Quick Reply , but sorry I am not getting you regarding master ?

can you please let me know the steps you have taken to solve that

**Comment by strarsis** [comment]
Clone this repository.
Check out master.
Run build utility.
Use the built pannellum artifacts.

**Comment by ParthKansara** [comment]
Thanks , Let me Check that. I will ask further support if needed. Thanks in advance

**Comment by mpetroff** [comment]
CORS is not enabled on the remote server; it needs to be.

**Comment by ParthKansara** [comment]
Thanks for reply. You mean to Say CORS should enable at Azure BLOB ?

**Comment by mpetroff** [comment]
Azure Blob is the remote server, so yes.

**Comment by ParthKansara** [comment]
ok. Thanks I guess. I need to check out with BLOB for this resolution

**Comment by ParthKansara** [comment]
Thanks for support . CORS issue for Azure BLOB is resolved. 
Just for reference to other developers:
http://stackoverflow.com/questions/28608859/how-to-configure-cors-setting-for-blob-storage-in-windows-azure
