### ISSUE TITLE
WebGL: INVALID_VALUE: uniform4fv: invalid size

### ISSUE THREAD

**Issue by MmmDee** [mpetroff/pannellum#223]
New error message with commit 1bbbb67. Your message is:

_Error: Something went wrong with WebGL!_

Error occurs in libpannellum.js [line 338](https://github.com/mpetroff/pannellum/blob/master/src/js/libpannellum.js#L338), reported at line 400.

I can supply a demo link to illustrate the error, but the synopsis is:
1) load tour with first scene
2) click button to `loadScene` in a new scene
3) on click of another button to `loadScene` another scene, the error message is displayed

**Comment by mpetroff** [comment]
The bug was already there. The changes just made it happen a lot more often.
