### ISSUE TITLE
system memory (eating RAM)

### ISSUE THREAD

**Issue by lehmannwebdev** [mpetroff/pannellum#224]
I used pannellum to view panorama on map by map clicking. 
System eat many of memory because ptotos was 8k x 4k [px].
I add some code to free memory, maybe can halp someone.

...
var gc = panorama.obj.getRenderer().getCanvas()
    , gl = gc.getContext("webgl");
gl.getExtension('WEBGL_lose_context').loseContext();
...

You can add this to destroy method.

**Comment by strarsis** [comment]
Relevant issue?: https://github.com/mpetroff/pannellum/issues/174

**Comment by mpetroff** [comment]
The `WEBGL_lose_context` extension _simulates_ losing the WebGL context, nothing more. It's only a debugging tool; it's not designed to be used to free memory.

**Comment by lehmannwebdev** [comment]
I tested this solution and it realy works. Without this loseContext my browser frozen when open and remove some panoramas - in windows manager all ram is used. When using this, memory is realy released. 
I tested it more. Works on Chromium 47, Google Chrome 52 and Opera 39. On Firefox 43  it not working. My OS is Windows 7 x64. 

For testing create and destroy some panoramas +-5MB 8000x4000 px.

**Comment by mpetroff** [comment]
Okay, so Blink incorrectly implements the spec. I'm not adding in something that the spec describes as a debugging tool.

**Comment by mgrubinger** [comment]
You, Sir @lehmannwebdev just saved my life. 
Adding 
````
if(gl) gl.getExtension('WEBGL_lose_context').loseContext();
````
to the destroy() method resolved our memory issues on Android with Cordova (+Crosswalk) for repeatingly opening a new viewer.

**Comment by mpetroff** [comment]
I revisited this, and other libraries appear to be using the extension in this manner. Since it can't hurt, I added it.

**Comment by mgrubinger** [comment]
Sounds like a reasonable approach, @mpetroff. Thanks!
