### ISSUE TITLE
orientation detection and auto rotate

### ISSUE THREAD

**Issue by seansan** [mpetroff/pannellum#225]
Hi, maybe this was asked before. But is it possible on say an iPhone or laptop with orientation support to auto-rotate the image based on my orientation : similar to how Facebook 360 works when I move and holee my iphone

thanks, Sean

**Comment by mpetroff** [comment]
This was added in b0c2f03511c09f1b140079b5cf99281bca46d023 but isn't in a release yet. See #131.

**Comment by seansan** [comment]
Cool

Will it be THE next release?






Sent from my iPhone.

On 17 Aug 2016, at 15:54, Matthew Petroff <notifications@github.com> wrote:

Closed #225.

**Comment by mpetroff** [comment]
Yes.
