### ISSUE TITLE
Equirectangular Mobile Error

### ISSUE THREAD

**Issue by timsayshey** [mpetroff/pannellum#226]
I get the error on Android saying that my panorama jpg is too big and it suggests splitting it up.

Is there a way to configure pannellum to accept multiple image files for a Equirectangular viewer? (For example, I split the panorama into 4 images)

Maybe there is another type that would support this?

Here is my current single image viewer (which doesn't work on mobile)
http://propertylure.com/assets/pannellum/tour.htm

Help appreciated!

**Comment by strarsis** [comment]
You can use the multires tool to generate a multires panorama:
https://github.com/mpetroff/pannellum#how-to-use
