### ISSUE TITLE
Is it possible update rendered view manualy with external JS?

### ISSUE THREAD

**Issue by pvlptr** [mpetroff/pannellum#229]
Is it possible to update Pannellum rendered view after manually changing viewer properties (viewer.setYaw(...) and so on…)?
For example:

```html
<!DOCTYPE HTML>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.pannellum.org/2.2/pannellum.css"/>
   // <script type="text/javascript" src="js/pannellum.js"></script>
   // <script type="text/javascript" src="js/libpannellum.js"></script>
   // <script type="text/javascript" src="js/RequestAnimationFrame.js"></script>
    <script type="text/javascript" src="https://cdn.pannellum.org/2.2/pannellum.js"></script>
    <style>
        #panorama {
            width: 600px;
            height: 400px;
        }
    </style>
</head>
<body>

<div id="panorama"></div>
<script>
    myViewer = pannellum.viewer('panorama', {
        "type": "equirectangular",
        "panorama": "https://pannellum.org/images/lascar.jpg",
        "compass": true,
        "autoLoad": true
    });

    function rotate() {
        myViewer.setYaw(myViewer.getYaw() + 10);
        // need posibility to update view (ar maybe view can be updated automaticaly?
        //workaround A:
        /*document.getElementById('panorama').dispatchEvent(new Event('mousedown'));
        document.dispatchEvent(new Event('mouseup'));*/
        //workaround B:
        /*myViewer.getRenderer().render(myViewer.getPitch() * Math.PI / 180, myViewer.getYaw() * Math.PI / 180,  myViewer.getHfov() * Math.PI / 180);*/
    }
</script>
<button onclick="rotate()">Rotate</button>
</body>
</html>
```

One of the possible workarounds is to simulate user interaction: `document.getElementById('panorama').dispatchEvent(new Event('mousedown')); document.dispatchEvent(new Event('mouseup'))`.
Or to call renderer directly: `myViewer.getRenderer().render(myViewer.getPitch() * Math.PI / 180, myViewer.getYaw() * Math.PI / 180,  myViewer.getHfov() * Math.PI / 180);` , but of course hot spots and compass positions are not updated. 

Both workarounds creates unnecessary coupling with internal Pannellum implementation.
So maybe Pannellum library can provide API for such interactions, for example viewer can expose some currently private methods like render()?

**Comment by mpetroff** [comment]
Are you running the latest release, 2.2.1, or the Git master version? As far as I know, this works in the Git master copy.

**Comment by pvlptr** [comment]
Yes, the view was not refreshed because I was using 2.2.1 release.
It looks in current newest version problems is solved.
Are there any plans for pannellum release from current master version?

**Comment by mpetroff** [comment]
There will be a new release, hopefully sooner rather than later. I can't say for sure exactly when, though.
