### ISSUE TITLE
maxPitch issue depending on viewport width

### ISSUE THREAD

**Issue by wojciechkoszyk** [mpetroff/pannellum#230]
Hello,

I've got a partial panorama - without sky - and I don't want user to see it. I've set maxPitch value when I was displaying panorama on wide screen and it works fine. But if I've opened the same pano on mobile, user can scroll further to the top.

Please look at the example: http://foto-koszyk.pl/pano/plaza-zrebce-wapiennik/ when viewing in fullscreen you can't see the black area on the top, then open on mobile and you'll be able to see black sky.

Am I doing something wrong? How can I fix that?

Thanks,
WK

**Comment by MmmDee** [comment]
You may wish to checkout the documentation [here](https://pannellum.org/documentation/examples/partial-panorama/). Particularly `haov` and `vaov`. `MaxPitch`/`MinPitch` are probably not the way to do what you want since those change depending upon zoom.

**Comment by mpetroff** [comment]
This behavior has been changed in the Git development copy to do what you want. In the last release, the `minPitch` and `maxPitch` values applied to the center of the viewer, so different viewer sizes and aspect ratios resulted in different results. In the development copy, the limits apply to the edge of the viewer, so they are no longer dependent of the viewer size and shape. See #92.

**Comment by MmmDee** [comment]
@wojciechkoszyk 

Great [picture](http://foto-koszyk.pl/pano/wapiennik/), and you appear to have solved your sky issue. Was that a drone shot?

**Comment by wojciechkoszyk** [comment]
@mpetroff how can I get development copy? 
@MmmDee thank you, yeah it's a drone shot

**Comment by MmmDee** [comment]
Here's what I did to set up a brand new installation of Linux Ubuntu 16.04 to have full build/multires capability (of course you need do this whole thing only once, then the latter part when there are updates ):

$ sudo apt-get install icedtea-8-plugin (gets OpenJDK)

$ mkdir ~/Development
$ cd ~/Development
$ git clone https://github.com/mpetroff/pannellum.git
$ cd pannellum
$ cd utils/build
$ ./build.sh

```
=========================
compling pannellum.js
=========================
=========================
compling pannellum.css
=========================
=========================
compling pannellum.htm
=========================
```

$ cd ../../build
$ ls
pannellum.js pannellum.css pannellum.htm

$ (ftp files to server)

On known updates by Matthew
$ cd ~/Development/pannellum
$ git pull
$ cd utils/build
$ ./build.sh
$ cd ../../build
$ ./upload.sh                (my script to curl files to my server)


When you know there's been a new commit to the master branch, you can update your local branch as follows:

$ cd ~/Development/pannellum
$ git pull                  (tells you if there's an update and retrieves it)
$ cd utils/build
$ ./build.sh
$ cd ../../build
$ ./upload.sh             (or however you upload files to your server)

/*******************************************************************************************************/
On Windows 10, it's sufficient to download Python3 from [here](https://www.python.org/downloads/) .
Download git for Windows [here](https://git-scm.com/download/win).

In a DOS window, do the same git clone as per Linux.
C:\Development> git clone https://github.com/mpetroff/pannellum.git
C:\Development> cd pannellum
C:\Development> cd utils/build
C:\Development> build
C:\Development> cd ..\\..\\build

Copy the files in this new build directory to your server. I used Linux to make my multires tiles.

**Comment by MmmDee** [comment]
@wojciechkoszyk I tried playing with your image yesterday or the day before, but you don't have CORS enabled on your server, so I couldn't access the multires image.

**Comment by strarsis** [comment]
@MmmDee: https://crossorigin.me/
