### ISSUE TITLE
[question] inline video in iOS

### ISSUE THREAD

**Issue by ChoeJeongEun** [mpetroff/pannellum#232]
Hello,
I'm using pannellum with video.
In case iOS device,  pannellum video is not inline.
I'm just wondering if there is a plan to support inline video for iOS.

**Comment by mpetroff** [comment]
Blame Apple: https://9to5mac.com/2016/06/15/ios-10-inline-video-playback-safari/

It might be possible with iOS 10, once it's released, but it's not possible with older versions.
