### ISSUE TITLE
How to get coordinates

### ISSUE THREAD

**Issue by s1mar** [mpetroff/pannellum#243]
Is there any other way or inbuilt feature to get the Pitch and yaw onClick ???

**Comment by mpetroff** [comment]
This is supported in the development version:

```javascript
viewer = pannellum.viewer(...);
viewer.on('mousedown', function(event) {
    // For pitch and yaw of center of viewer
    console.log(viewer.getPitch(), viewer.getYaw());
    // For pitch and yaw of mouse location
    console.log(viewer.mouseEventToCoords(event));
});
```

**Comment by s1mar** [comment]
I tried on the hotspot example but couldn't get the above to work,I'm pretty green when it comes to jScript,if it isnt much of a trouble,can you please show me how to store the pannellum.viewer(..) reference and then add the event listener ??


<!DOCTYPE HTML>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hot spots</title>
    <link rel="stylesheet" href="https://cdn.pannellum.org/2.2/pannellum.css"/>
    <script type="text/javascript" src="https://cdn.pannellum.org/2.2/pannellum.js"></script>
    <style>
    #panorama {
        width: 600px;
        height: 400px;
    }
    </style>
</head>
<body>

<div id="panorama"></div>
<script>
var viewer=pannellum.viewer('panorama', {
    "type": "equirectangular",
    "panorama": "https://pannellum.org/images/bma-1.jpg",
    /*
     * Uncomment the next line to print the coordinates of mouse clicks
     * to the browser's developer console, which makes it much easier
     * to figure out where to place hot spots. Always remove it when
     * finished, though.
     */
    //"hotSpotDebug": true,
    "hotSpots": [
        {
            "pitch": 14.1,
            "yaw": 1.5,
            "type": "info",
            "text": "Baltimore Museum of Art",
            "URL": "https://artbma.org/"
        },
        {
            "pitch": -9.4,
            "yaw": 222.6,
            "type": "info",
            "text": "Art Museum Drive"
        },
        {
            "pitch": -0.9,
            "yaw": 144.4,
            "type": "info",
            "text": "North Charles Street"
        }
    ]
});

viewer.on('mousedown', function(event) {
    // For pitch and yaw of center of viewer
    console.log(viewer.getPitch(), viewer.getYaw());
    // For pitch and yaw of mouse location
    console.log(viewer.mouseEventToCoords(event));
});
</script>

</body>
</html>

**Comment by mpetroff** [comment]
As I said previously, you need to use the development version, not the release version as you're doing.

**Comment by s1mar** [comment]
Unable to build 
![buildfail](https://cloud.githubusercontent.com/assets/16931768/18223075/f42d514c-71c8-11e6-93ec-c3a785c4f69d.png)

**Comment by MmmDee** [comment]
I see that you're building this on Windows, maybe this will help...

On Windows 10, it's sufficient to download Python3 from [here](https://www.python.org/downloads/) . Make sure python is in your PATH. I renamed python.exe to python3.exe (and also edited the very simple _build.bat_ script) since I also have python 2.7 installed, but you could simply change the PATH order.

Download git for Windows [here](https://git-scm.com/download/win).

In a DOS window, do the same `git clone` as in Linux.
```
C:\Development> git clone https://github.com/mpetroff/pannellum.git
C:\Development> cd pannellum
C:\Development> cd utils\build
C:\Development> build
C:\Development> cd ..\..\build
```

Copy the files in this new build directory to your server. On Windows, I use either FileZilla or the NppFTP plugin within Notepad++. 

I use Linux to make my multires tiles, but you can download the Hugin tools for Windows, [here](http://hugin.sourceforge.net/download/).

**Comment by s1mar** [comment]
@MmmDee : Can't I use the Pannellum.js file in the src directory directly ??

Also,I'm just trying to accomplish to get the mouse coords(yaw and pitch ) and store them in a variable but since I'm pretty new to jscript,I'm unable to use the functions in the Pannellum.js file in my own html file.

**Comment by s1mar** [comment]
TypeError: viewer.on is not a function; 
I always get this error

**Comment by MmmDee** [comment]
As Matthew noted, you have to use the development branch. 

1) After you copy the development branch in the fashion I noted above, build it on your system (Windows or Linux). 

2) Then copy the resulting built files onto your server (assuming you have one). 

3) Refer to your copy of the files on your server to "include" them into your webpage. (I'll add an example when I get on another computer.) You really don't want to modify and use the pannellum.js file directly in the fashion I think you're trying.

**Comment by s1mar** [comment]
I downloaded it from the master branch and then I copied the .css and .js from the src into a proj folder in my wamp directory.

Specs:
Python 3.5.2
Wamp 3.0.4 
Windows Server 2012

**Comment by s1mar** [comment]
Thanks @MmmDee ,But how to add a mouse click event or mousedown event in my webpage that will call the mousecoords function inside pannellum.js and give me the return value,so that I can manipulate it.

I tried adding a listner to just the div that holds the pannellum.viewer and call the mousecoords function but I always get "not defined" or function doesnt exist,aslo tried the approach suggested by matthew,

viewer = pannellum.viewer(...);
viewer.on('mousedown', function(event) {
    // For pitch and yaw of center of viewer
    console.log(viewer.getPitch(), viewer.getYaw());
    // For pitch and yaw of mouse location
    console.log(viewer.mouseEventToCoords(event));
});

But then the console show's me that viewer.on isnt a function 

Please help!!!

**Comment by MmmDee** [comment]
I suppose you can copy the two js files (pannellum.js and libpannellum.js) and 1 css file (pannellum.css) from the repository directly into the appropriate directories else where, but you'll also need the 5 image files (*.svg) from the css/img directory too and place that under your local/moved css directory.

**Comment by MmmDee** [comment]
Here's an example...

```
<!DOCTYPE HTML>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Event Test</title>
               
 
    <link rel="stylesheet" href="http://mysite.net/pannellumSRC/css/pannellum.css">
    <script type="text/javascript" src="http://mysite.net/pannellumSRC/js/pannellum.js"></script>
    <script type="text/javascript" src="http://mysite.net/pannellumSRC/js/libpannellum.js"></script>
  
    <style>
    .panorama {
        width: 600px;
        height: 400px;
    }
    </style>
                   
</head>
<body>
 
<div id="panorama1" class="panorama"></div>
<div id="panorama2" class="panorama"></div>
 
<script>
viewer1 = pannellum.viewer('panorama1', { });
 
viewer2 = pannellum.viewer('panorama2', { });
 
function sceneChangeListener1() {
        console.log("v1: Scene changed");
                                console.log("v1: Scene " + viewer.getScene());
        console.log("v1: Yaw " + viewer.getYaw());
        console.log("v1: Pitch " + viewer.getPitch());
                               
                               
        // do something else with sceneid, yaw and pitch here
 
        sceneId = viewer.getScene();
        yaw = viewer.getYaw();
        pitch = viewer.getPitch();                   
};

function sceneChangeListener2() {
        console.log("v2: Scene changed");
                                console.log("v2: Scene " + viewer2.getScene());
        console.log("v2: Yaw " + viewer2.getYaw());
        console.log("v2: Pitch " + viewer2.getPitch());

        // do something else with sceneid, yaw and pitch here

        sceneId = viewer2.getScene();
        yaw = viewer2.getYaw();
        pitch = viewer2.getPitch();                 
};
 
function sceneLoadListener() {
        console.log("Scene change done");
};
 
viewer1.on('scenechange', sceneChangeListener1);
viewer1.on('load', sceneLoadListener);
viewer2.on('scenechange', sceneChangeListener2);
 
</script>
 
</body>
</html>
```

**Comment by s1mar** [comment]
I still get that viewer1.on isn't a function,I just can't seem to fathom what I'm doing wrong

TypeError: viewer.on is not a function

**Comment by MmmDee** [comment]
Assuming there's not a typo in your html source file, then it it's likely something particular to your server setup and the way you're copying the pannellum files to it.  Is your html file short enough to post here, or provide a link to it?

**Comment by MmmDee** [comment]
I changed the example above to use the mousedown event. I confirmed it worked with the latest commit.

**Comment by s1mar** [comment]
@MmmDee Thanks,I'm away from my console but I'm going to try this first thing come monday and let you know how it goes.Also,can you guide me to some online resource where I can learn and master Jscript and learn more about server-client interactions and best practices,I want to write some awesome web apps and thank you once again for your guidance and assist
