### ISSUE TITLE
Problem with Pannellum and Ionic on mobile device

### ISSUE THREAD

**Issue by burkhardtroeper** [mpetroff/pannellum#245]
Hello,

using Pannellum with the Ionic-Framework (which is build on Angularjs) works great - as long as not switching from scene to scene. The first scene loads perfectly, but when switching to another scene for the first time, it simply does not show the new image. Crazy though: The new hotspots are shown, one can click on then, even switch to another scene. What will happen then, is the following: It will load the image of the scene you were into (instead of the new one), who were not shown when entering the scene. So there is always a lag of one image. This is really weird. To make it even more confusing: This only happens on a mobile device. In a desktop browser everything works perfect. 

I know, this must be a special issue with the ionic framework. So I am not expecting any help. But maybe someone has made the same experience or has some knowledge, why things like that happen with ionic.

Ionic is really a great framework. And Pannellum is simply amazing. Combining both would be a dream.

Greetings from Germany

Burkhardt

**Comment by mpetroff** [comment]
Per the change in d51ade0, mobile app frameworks are not officially supported.
