### ISSUE TITLE
[question] Adapting existing multires panorama to Pannellum

### ISSUE THREAD

**Issue by ner00** [mpetroff/pannellum#249]
I'm having a bit of a difficulty transitioning a multires panorama to Pannellum due to the cube resolution not being proportional across all levels of zoom. It seems to me that I can't implement the current multires into Pannellum without scaling cubes up or down, and re-splitting them into new tiles, depending on the tile resolution wanted. But let's assume that I want to use the current tiles with maximum size of 512px. Please give me an opinion on the best way to handle it giving the current multires panorama details:
<br>
**1. level1**
   * f0_0 *(512x512)* + f0_1 *(256x512)*
   * f1_0 *(512x256)* + f1_1 *(256+256)*
   * level1_total_tiles = 24
   * level1_tileResolution = 512
   * level1_cubeResolution = 768

**2. level2**
   * f0_0 *(512x512)* through f2_2 *(512x512)*
   * level2_total_tiles = 54
   * level2_tileResolution = 512
   * level2_cubeResolution = 1536

**3. level3**
   * f0_0 *(512x512)* through f5_5 *(512x512)*
   * level3_total_tiles = 216
   * level3_tileResolution = 512
   * level3_cubeResolution = 3072

**4. level4**
   * f0_0 *(512x512)* through f10_10 *(512x512)*
   * f11_0 *(512x256)* through f11_10 *(512x256)* + f11_11 *(256x256)*
   * level4_total_tiles = 864
   * level4_tileResolution = 512
   * level4_cubeResolution = 5888

<br><br>
Both of the solutions I came up with involve this:

1. Assuming the level 1 cube resolution of 768px, I need to rescale every cube to:
`((tilesNeeded/6)*768)/2^(zoomLevel-1)`
Applying this to level 4, for example, would mean rescaling a cube from 5888px to 6144px:
`((384/6)*768)/2^(4-1) = 6144`
And then I could split every cube into 384 tiles of 768px.

2. Assuming the current maximum tile size of 512px, I would need to rescale the level 1 cube to 512px and on other levels rescale every cube to:
`((tilesNeeded/6)*512)/2^(zoomLevel-1)`
Applying this to level 2, for example, would mean rescaling a cube from 1536px to 1024px:
`((24/6)*512)/2^(2-1) = 1024`
And then I could split every cube into 24 tiles of 512px.

I don't know what else can be done and honestly that's why I submitted this issue (question), I can't figure out any sensible approach that would let me use the current tiles as they are without any kind of transformation.

Thanks for your suggestions.

**Comment by mpetroff** [comment]
The multires renderer is built using the assumption that each subsequent zoom level has four times the number of tiles as the previous zoom level; when the zoom level increases, each tile is replaced with four new tiles. As such, the renderer would need major changes to be able to support tiles such as yours.

**Comment by ner00** [comment]
Yes, that's what I figured, but thought that I wasn't seeing the full picture (no pun intended).
In retrospective, it was a silly question but thank you for clearing it up anyway.
