### ISSUE TITLE
OpenGL in Chrome Version 39.0.2171.71 (64-bit) Mac and Android

### ISSUE THREAD

**Issue by wmoindrot** [mpetroff/pannellum#25]
Really nice VR viewer, thanks for developing it.

I've tried to put it together on my site but finding that my own work will not show in Chrome Version 39.0.2171.71 (64-bit) Mac or on my Android phone Version 39.0.2171.93. Does show in Safari.

I have embedded an example from a fellow user to try and troubleshoot, and find that this other persons example does work, even alongside my non-working example. Cannot see anything different in code used. Image is hosted on my same server as holding the pannellum.htm

The page I've been working on is here: http://www.vraccess.co.uk/?p=29

The code is:

<iframe style="border-style: none;" title="pannellum panorama viewer" src="http://www.vraccess.co.uk/vr_files/pannellum.htm?panorama=http://www.vraccess.co.uk/vr_files/images/bees_nest_vr.jpg&amp;autoload=yes" width="640" height="360" allowfullscreen="allowfullscreen"></iframe>

And the Javascript console reports problems:

pannellum.htm?panorama=http://www.vraccess.co.uk/vr_files/images/bees_nest_vr.jpg&autoload=yes:8 WebGL: INVALID_VALUE: texImage2D: width or height out of range
pannellum.htm?panorama=http://www.vraccess.co.uk/vr_files/images/bees_nest_vr.jpg&autoload=yes:10 Error: something went wrong with WebGL!

Any ideas? thanks very much, Will (Liverpool UK)

**Comment by gbarmus** [comment]
First of all, I'm not a techhead by any stretch but I absolutely love Pannellum. I'm done with using flash and this is perfect. So I've been working with a few spheres on my website... turning into tours and having fun. I grabbed my ipad but the images are actually loading but rendering them skewed. At first I thot it was just my own panos and started looking into resolution and sizes and resizing issues etc but then i came upon this thread. The example above... http://www.vraccess.co.uk/?p=29 works perfectly on computer but on ipad the image has grainy lines (http://pianopricepoint.com/pannellum-ipad-screen.png) and is viewing what appears to be the sky from the image. Any thoughts around this? Cheers

**Comment by wmoindrot** [comment]
I get the same on a works iPad Air 2 - I think these are moire pattern. And
also there is no ground! You just end up exploring a sphere of sky so don't
know whats happening there! ok on android
