### ISSUE TITLE
Add hotspot to scene

### ISSUE THREAD

**Issue by ninjaonsafari** [mpetroff/pannellum#250]
I saw that there is the function addHotSpot(). But is there a possibility to add the hotspot to a scene?

Something like viewer.addHotSpot("sceneId", options")

**Comment by Aykelith** [comment]
Yes, there is a possibility to add a hotspot to another scene. 

It should work: https://github.com/Aykelith/pannellum/tree/hotspot_to_another_scene
Use the function: `hotSpotToScene(sceneId, hs)`.

**Comment by ninjaonsafari** [comment]
I removed the hotSpots from the config. 
            "default": {
                "author": "Matthew Petroff",
                "sceneFadeDuration": 1000,
                "showZoomCtrl": false,
                "showFullscreenCtrl": false,
                "autoLoad": true,
                "hotSpotDebug": true
            },
            "scenes": {},
            //"hotSpots": [] // <-- this

Now it adds the hotSpot to the current scene.

**Comment by mpetroff** [comment]
I extended `addHotSpot` in b3123271124c5338554a408cb61ca7a52b153107 to have an optional sceneId parameter so it can be used to add hot spots to either the current scene or any other scene.
