### ISSUE TITLE
Use ObjectUrl as image src

### ISSUE THREAD

**Issue by mararzu** [mpetroff/pannellum#253]
Hi !

First i want to say that english is not my natal language, hope you get my problem :)
Second good work with Panellum !! 

im making a web that load 20k images from the user pc, and display (in left) a map with the images geolocation and one image in pannellum (in right of the screen). And oc if the user click on a marker in the map i want to panellum load the image.

Iam trying to achieve this by creating an array with all the ObjectUrl to images (window.URL.createObjectURL(image)) from the set that the person select (using a <input>)

But.... when i pass this ObjectUrl as the parameter "panorama" to pannellum this happens:

CALL("panoViewer" its the id for the iframe of pannellum): 
**document.getElementById("panoViewer").src = "/pannellum?panorama="+imgObjectUrl+"&config=./pannellum-config"**

Error showed in screen by pannellum:
[Image hosted in puu.sh](https://puu.sh/rdtPG/e85c8f4c4c.png)

I tried to modify/understand the code (cause this great tool its open source :D) but i am very new to javascript, even to programing, and could take days or even i would not be able to do it at all.
But for what i see, pannellum use ObjectUrl internally, so i dont know if i can pass it as my image src at all...

Maybe, in best scenario, iam doing something wrong..

If not, it would be great that someone could point me the funcion/s i need to modify in pannellum code to achieve this :)

Thanks in advance !
Martin

**EDIT:**
My bad with the example, it is one with a modified ObjectUrl (was trying to make it work)

The call to Pannellum with full ObjectUrl would be:
document.getElementById("panoViewer").src = "/pannellum?panorama=blob:http://127.0.0.1:8080/eb5848c5-c714-4d96-b3de-aebeb04d39ad&config=./pannellum-config"

The error showed is:
[new link to error](https://puu.sh/rduAa/47c661a7c2.png)

**Comment by mararzu** [comment]
I achieve it, i add 1 line to the code:

[code modified. Added line 281](https://puu.sh/rdyBi/1b2d078b0e.png)

Basically i remove de "./" added to the image url.. probabbly this will make that pannellum only work with ObjectUrl's... but its fine for me, cause it is what iam using.

If there is a easier way or something please tell me :)

Great work again !! :)
Martin

**Comment by mpetroff** [comment]
I just added a check for blob URLs in 9b3ef1ee22bf0c76e9502b61fb245018294d3765, which should fix this.

**Comment by mararzu** [comment]
Good to know !
Thanks !
