### ISSUE TITLE
Use Base64 string as source

### ISSUE THREAD

**Issue by ChristianLJ** [mpetroff/pannellum#256]
Hi,

Is it possible to use a base64 string a source?

**Comment by mpetroff** [comment]
Yes. See this [example](https://cdn.pannellum.org/2.2/pannellum.htm?panorama=data:image/jpeg;base64,/9j/4AAQSkZJRgABAQEASABIAAD/2wBDABALDA4MChAODQ4SERATGCgaGBYWGDEjJR0oOjM9PDkzODdASFxOQERXRTc4UG1RV19iZ2hnPk1xeXBkeFxlZ2P/2wBDARESEhgVGC8aGi9jQjhCY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2P/wAARCACAAQADAREAAhEBAxEB/8QAGgAAAgMBAQAAAAAAAAAAAAAAAAMBAgQFBv/EAD0QAAIBAgQCBwUGBQMFAAAAAAECAAMRBBIhMUFRBRMiYXGRoQYyUoGxFEKSwdHwIzNicuEWNIJUY5PC8f/EABgBAQEBAQEAAAAAAAAAAAAAAAABAgME/8QAHxEBAQEAAwADAAMAAAAAAAAAAAERAiExEjJBImFx/9oADAMBAAIRAxEAPwBEwIgEAgEoIBICAQCAQCAQCAQC8AgEAgEAgEAgEAgTAIBAIBAIBAqHVqnVoGqVD9xFLN5CWS0bqHQ3SlexTBmmp41nCemp9JfiNtP2Xx7fzMThqf8AarP+kuQPX2Tf7/SH4aNv/YxkFv8ASa/9fV/8ax0Kt7Jn7vSDD+6iD+YjIFP7KYsfy8bQf+6kV/MxkGSr7P8AStEXFGlWH/aq6+TASYrm1s+GcJiaVSgx2FVSt/A7H5RZUTMggRAIBAIBAIEwC8CLwJvAIBAmAQCBEAgTAIBAmB77CYPDYKl1WFopSQcEFr+PObDoBAiAQJgEAgVqU0qoUqoro26sLg/KB57pL2WpkGr0Wwovv1LH+G3h8P07per6PNEstR6VVGp1aZs6NupmLMEyAgEAgEAgFoEwCBMAgFoBaBBDDax7oEK4Y22YcDvAm8AvAPlAIEPUWmhZr2AvtA7HQ/s+/SFNcTjqhp4dtUo027TD+pht4CbkwWwXtJiqNlxAGIp8wAHH5H96zOq9Fhek8HisO1anXUInv5zlKeN9ppGet090bSNvtAqHh1algfmNPWDGR/anCDRMPiG8QoH1k2LhZ9q6fDCN+MfpGwxZfavD/fwtcf2lT9SI2GNVH2i6NqWDVXpE8HQ/UXHrKjpUMRRxKZ6FanVXmjBh6QMOP6dwWBZkNTrao0NOnqQe87D56wODivafG1SRQWnhl5++3mdPSTRx8TXfF1+vxFVqtXLlznly00kt0UUqBotpBOccoBmHKQTmHOBI84EgwC8AgTuLQKogQWW9t9TeUXgECYBAWzJf4iO7aBXrr7AfLX6QKNWdRcg2PdGUWBrEX6up+EQDNVXdWHiB+sCBXI3HoYU2jiTTbPSd6bfEjEeojRq6Y6Gr9EjrOuSrTO1jZvKasRy0rJUINhmG1+Ew0aHvAm8CGzHYgQJ1lQXgQHKMHVijDQMpsfMS6EmsF7K+QEAHWNwC+MJp1PCV6h7KVG0v2VO3OQTUwT0lRqlMgOLqTxhCXpbWv5wLdUBtpAMrDZvODRmddx5SGrpVVuMKuD5QJHjCJhVrQCVBCqPUCDW14C8z1SALAHa+npxgbcJh8OtVWxKmugOqXtLE17LAYbo40FqYShSy88tyO4neb1XM9scOr4GlXHvK4U94sf385PwcK9rDumENw9I4iutMG19za9hxMB7dHFlDB6b5myoGBBbwhW2h7KUqlNmxDtTqHbqzt4zeQcU1TiTUNRi7FSSSbk6TKOPiaJRgV0nL5du2dIp19QraNwmvWfGlWgWzQAtKmFPWVTYnU7CUVys+rGw5CVNP+yPTBLUnSwB1UjTXXwlxFqdR6LdYhII4yI6+CxyYsKrMBVT3SWvbu32hdejwWGwGKwyk4WkSp7Ssl7HjvNDj+02Bw9DqWoUadIMrXCIFva3Lxko4FOi1SoERczMbKANSeUzO2XqaXsvhvsqCtUcVrXZkItf5jabyLjzHS9PD4Ot1eFxH2gcSFsB3DXWZsiOSrl3u2nz1EitFOtl1vmXmOHjINCvcArqDAuDAsLwJgUepYhV1Y6ACUdNPZ45MPUfFUalSq+Tq1N1U5SRdhvqOU3OJWfH4GvgWyYhFHeGDA/n5gSYjH13V9oMCOV4DsN0/UwZbqKjIWGumh84VNbpev0kvV1arOt81uEDNXx3V1nQoeyxG3fJg6XRmJHUu5BHWGxNr2Ub7fvSRY3t0umDbrbgVLWVb+6OWvrKKP7T4p6RUCmjHZgNQI1HKfDDC1M6FgjK1ldgW24wsZa4DKZ579q7TxhKLfVwJuFaMMRlDVWOTNlLATTLWTgwNKlY+CD9ZekZqzU9eqYkD4hY+V4VkVczqxa7H0iXtLOm1EqowdGOYagg6iaYbcP0vi8E/X5usqEZDn17Ok1pjLjcdR6QfMcNSpG+6Agn1t6SW6mLJRelRFRFsg1zB7j66SZUasNjsWqNUp1XRdiynSOw7EPimpP8AaazVdOzepmtof8R2SkUBi8JbFopp5Nmawtw2MTYmqY72kxtekaL186ncAAX8bRquK1SrUJLEAnSBegqk9o3PE90g1I2GQAMzNbgNoUokU2vSuVbUKZB1cB09SwVE0XwVCqwJszIL/PnNSq0f6pS/+ww1uWWPkrJjemVx5WnSwtGm179hQCfnJuo0YWh0fSUvUxNXORe/VjXmBrNZEKqYimXQ0WbMrEjyMQWxGHxpp9aArIdS6sH87E+sqF4XA4GoxGPxNZL8aai3z4yarLUwFKmXNEGtSUnt5SB8xwj/AAaMHUpLgnpiimZiCHyDMPn4WghjU1DBjhwA/avbfv2ko0YGhTw6fa6uCFfDqxAz2UE303Gto/sUxlZMdVvQwSUUUe7RS3mQI9Gahh8AWcV6ldHH3aSXPmTpAirizXoarbLcb3+6ZFjOWus8/L7V2njEQQxvbfS01x7GxQrYNFNzZ72vpuZ0/Gf1bNZlTq07RsDpLqSdK4cBUxBIGYpa/nFIz00y1KR5kScfV5eO1QKBdbTo4stbq6ldlFrEXA+QlX8ZTRSmnZG7GYrVC01HASIhwA9igIyk7eEsZaqFMCi4Gzgb/OUZMTQQVAGY9o2tIFUgjuKNnKZc4BY6XtsIoYKIW4XS/cD9ZNGdSUr1U+FCfQfrLFYzWccYGyhUY1MPc6FTfzMCvSt1xtQLoL/kJG5GQu1uGkiul0KubElm4D9JqM11qtNWBFtAV+srCK1JU6uw3e3oYipXCo9VluQBrcH0gaFpKgKXJXvsdfKRF6WSgyuoawYFlFzm8QI0IxWRhUrBAhfXLb3ddvIyrBTVGwymwDbkkQIFJcmTISw+8Ra8BVPIModRm1BttIGVmAsy27PDnBHMRVK1Wv2lvxiKgG6icOX2duPhRXtb3k4hqZimUkAZridZ4y0fZWzrUL7Ha81naS9YRZgHsbX4R+k8KT30PhM8PV5eNuYlSAxF/SdXIsECsdb2FgfKFqqrlQLcmxOpN5mkXAkFKlxV7spljNOp1hkbgFsJQis4eqpB2IPqJAugD9o4fywPpJQ/LqZBzyScdihwCH6CanisR/OUbKHvUP7T+cgt0lrinPM/kJmt8Sqro/W5aQXMwItbsjXT1muXKXchx42Ztbehzkq3ty+oiJXQep2nNtLjSVhjpVXJ6t9Qrg3J12N5VO6MJTH4oFhYtYC/eZeX1jE9rpk6zm0hbBi1hc6E/vxgJxgBosbC42PzERVqBBwyAi4tFDLyDl4iuKOaowJC3Ok3ERSxwxKjINCbXPz/AEkqlL0ccPUrVjVLZgdCLcYVC+6Jw5eu3HxQjURFSyGoiKptZrnwvOkYbM5tNIRU0Zj8QkUlRqpk4ery8MFTXKuvPXUTo54qKjM5yC5PPSEplNai36wrrwElDgJAuuCaoUbkSxmqCxoVgL2lUhFsMwzaEC3zioZhBfFMDfSmv0El8GwrMjmOlsZijzpt9BNTxWSlQq1f5YJA3OwHzlVspqVamCQxA3G3GREY1XfEtYbGZrcpBovb/EYutfR6sGKnQ6Sxmt+V+2GOml2tp8+U0yo1BqQBY7kHQ8LGAzBVCcdXTJTFibFVsxF+J4zVn8ZWZe20CxJ3J4zmoTMCcxB5WHef8QpWKzmk+2X8v/ssFaJf7OmS2x1PpJQ98xQ5bBraXkVRqauCCB3gzUQhsHTv2boeYgTXZnpNkQhObaekKwKOyJx5euvHxVtO88BJI00UaRSn2tTuZ1YNCacIQtqWZCp8NN5RnVCHCMNR6ycZ2cr0eKC5sxS5tabZ1NNWzvltw0MqJbLcX7B79R5yUMWkze7Zu4G58pMFK9KrTY1GpsAFsuljfWWRkikL0G31NvpL+qSjMH0VmGxA4iMRqw+Hq08S7FCKZUZSfzmaHsLe8wEmDN1VMVGYBmZgb5trSqhkNRcpHZGwAsBAqaWXKF1bYD5wNJw3FvePKRUnCgrYDwhUHCsB1lH3xqAePdKjZhWWvmdOIFxyMrKmJpBaYKadr3fu/wCIVYsKZBq0ylvvDUH5/rLiGKQxurqVt+9ZMFsrZrW0te95MCsT/KIsTceUKrQ0woNibX28ZKHWJ4SKrkZtSQp4GaxEMQg/inL48fDnAMSn8JjA5IsF1nLlO3bj4bRoHN1lTfgOU1JiWnlVNhpqZUN6uUVyqr2NtYRNSilRQBow90iUKVyGyVBlfnzmmRTS9R/GAxgQLEXvwkRUUl4qR4QHIopDs1GBPJrQirEtiRd2Om5a584U1jsOsYg82hFDTVufykFMmXTKB3wKPT/iL3g/lAGQjQC5O1oU2lhxT7T+/wDSFXyAsLcNZBcL3wIRbXHI2lC2RqFQ1qIzA++g498sDa9RK2GDobi4lRoyEcflwlQl8PSLX6uz800+kCooMvuVyD/UoJkEVkrCmwLI2h53+sKXhRWNHsCkVufevf0kDsta5F6a8dAT9TCp6tj71d/+AC38oRCUaabIAeZ4wM9XE9aDToKXvxOwgZ6WECNmrNcjYWsB+szY3rVlgQmrk8BoPzgX05DygQwuNNCNpQIcwuIRFSmlUZXNyOW4lQhaVahcoMy+soYtSm57V1bvhMPVQw7Pa8NZBXITUNjov1hFB/uj3CFOZbruAeEILdkGxA7xIKsy7Gx7t7xghaJcggWA2JlU5USnzB4kyKlrAXJ0gQlPcsoud4Fsg+EeUCpQK4NhY6HTy/fhAYL3gZq2GBu9FgGO6jY/pLAxMYLhKwNJ+8aHwlTGhSpW6kEHiNbwgIgKKhkc2GoIEgTgADRNwDZoWtDoBZgouO6EXFiNNYC6jIq3cgDvhWZbLoBYd0irXvClOovkQWY8RpYczAlaYQWUkDzgTlPxH0gGU8WNoFTSAOZRfmCd/wDMC6MCLDhw5ShggQyK3vKDCF9TSZrKDpuQdB/mUN6o27NeoPnIKdSQ5YVDc8eMqLim3Gu/nJpiDQVe12m5840MQJa6AW7oVa8ghnCi5NhAoEDtmZbAbDY+J/T9gHCw2JHrAn/kfSFVZQwsSbeUIWtgcj6twvxlDCYFXs62dQw74CDhqa3am70ueUyiFGJIOWqGX+pbXhFs2MAt1dIjuJgwuicRQBApqb8zIpvW4pvu0h8zCYW3XiwetlU7ZVtbuvC4qcPTvmctUbmxjRAc/Ax7xqIwXBLbnIO/eFMRVt2LH1kFssCMsAyyiCLanSBUhDxF+46wI/iD3Rcd+kA7Z94ED+n93gXUgCwBsOSmBOdfiA8TaEGdfiXzgHWLwYHwN4E9YP6vwmQVNySVVgTxFtfGUVvWvrktxy7/ACvAspUG5DZuZF/ptAv1i/EB3HSQHWJ8a+cCesX4h5wDrU+NfOBDNTYWLKR4yimZl2uw5EWPnAOsJ3GX+79/nAsArak5iPSBe8AzQKEwIvIKk30gKIybMAORlD7SKmBBF9xeAZR8I8pQZR8I8oBlHwjygACjYAfKAXgEgIE3gF5QXkQXgF4BAIBAIE3POAXgTcwC8CJQQIIB3F4EZF+EeUAyDv8AxGBGQc2/EYB1Y7/xGFHVL8I8oEhANgBIP//Z). I didn't want to make the URL enormous, so the image is very low resolution.

**Comment by mpetroff** [comment]
I would not recommend specifying an image as a URL parameter (as I just did), at least with the current release, since the entire image is sent to the server. I just [added support](https://github.com/mpetroff/pannellum/commit/c90dcb2283b128229e85f91f4045f0a1af2540f4) for using the fragment identifier, which isn't sent to the server, instead of the query string (`#` instead of `?`), so it will at least be feasible to do with the next release, although I still wouldn't recommend it.

Using a base64 encoded image in a JSON configuration file or with the API should be fine with the current release.

**Comment by ChristianLJ** [comment]
@mpetroff when looking at your example i only see the following:
![capture](https://cloud.githubusercontent.com/assets/3056379/18699778/960750cc-7fd3-11e6-8f6f-2a254b183fa1.PNG)

**Comment by mpetroff** [comment]
Apparently it works fine on Firefox but doesn't work with Chrome. Making it work on Chrome would require restructuring how images are loaded, which I don't really want to do, since I generally don't think using base64 encoded images is a good idea. [Blob objects](https://developer.mozilla.org/en-US/docs/Web/API/Blob) are better suited for passing around image data client-side.

**Comment by mostafaghanyomar** [comment]
I used a work around for this, Hope it helps:

        var imageToUse = angular.copy(base64Image);//Here you get the image
        var base64DataPrefix = imageToUse.substring(0, imageToUse.indexOf(',')+1);
/*Getting the browser prefix for parsing the image in case it's retrieved, in case not use the atob function directly on the retrieved data*/
        var binaryStringData = imageToUse.substring(imageToUse.indexOf(',')+1, imageToUse.length);
        var binaryString = window.atob(binaryStringData);
        var binaryLen = binaryString.length;
        var fileContent = new Uint8Array(binaryLen);
        for (var i = 0; i < binaryLen; i++) {
            var ascii = binaryString.charCodeAt(i);
            fileContent[i] = ascii;
        }
        var blob = new Blob([fileContent], {type: 'application/octet-stream'});
        var fileURL = window.URL.createObjectURL(blob);

        setTimeout(function() {
          pannellum.viewer('panorama', {
            "type": "equirectangular",
            "target":"_blank",
            "panorama": fileURL,
            "title": 'hello image',
            "multiRes":{
              "tileResolution": 512,
              "cubeResolution": 8432
            }
          });
        }, 250);

**Comment by elliotsabitov** [comment]
Hello, and thank you in advance for your time. 

If I create a new image with JS and then set the image source, how would I set this image in pannellum? Otherwise, if I have a blob, then how do I set the image of pannellum to be a blob? I only see a way to set the panorama which has to be a string, which seems like the base64 is the only other option along with the URL. I see that you mentioned Blob objects in the two tickets concerning this, but I cannot find an example of getting this accomplished, and the documentation seems to only support a string. 

I saw that the renderers init configuration allows you to pass an Image object, would this be the only way to get it done? Can you provide more information for getting this accomplished, or at least point me in the right direction please. Thank you.

**Comment by mpetroff** [comment]
You need to create a blob URL from the blob object, e.g. `var url = URL.createObjectURL(blob);`, where `blob` is the blob object. The returned URL will start with `blob:`. This URL can then be passed to Pannellum.

**Comment by StruanMclean** [comment]
How do i do this if i am self hosting it on a different server. My website interiorpup.com requests 360.interiorpup.com via iframe to do this.
