### ISSUE TITLE
Clamping issue in setNorthOffset

### ISSUE THREAD

**Issue by snawbel** [mpetroff/pannellum#257]
In [this line](https://github.com/mpetroff/pannellum/blob/master/src/js/pannellum.js#L2333) it looks like you switched the min and max functions so `config.northOffset` always ends up as 360.

I think 

`config.northOffset = Math.max(360, Math.min(0, heading));` 

should be

`config.northOffset = Math.min(360, Math.max(0, heading));`

**Comment by mpetroff** [comment]
You're correct. I just fixed it.

**Comment by snawbel** [comment]
Thanks for a great library!

On a side note, I'm thinking about using Pannellum to update my software for displaying panoramas on iPads in [Parascope viewers](http://www.unsworn.org/parascope/). In this use case the panoramas must align with the the absolute compass heading. It seems the current Pannellum implementation of `deviceorientation` changes slowly drifts from its original heading. In a prototype I'm using the `webkitCompassHeading` of the `deviceorientation` event to re-align the panorama. 

Perhaps this kind of kind of functionality - the ability to align to a true compass heading - could be interesting for Panellum?

**Comment by mpetroff** [comment]
I never realized that it didn't align to north. After reading into it, it appears that the `deviceorientation` event heading was with regards to north on Android prior to Chrome 50 and relative to an arbitrary reference on iOS. Chrome 50 changed the Android behavior to match that of iOS, using only the gyroscope and accelerometer. It also added support for the `deviceorientationabsolute` event, which incorporates the magnetometer as well; it would be nice if Apple would implement this event as well.

Properly combining iOS's `webkitCompassHeading` with the rest of the `deviceorientation` event requires a complementary filter at the very least, which I think might be a bit much to add for a limited use case that's iOS specific.

**Comment by snawbel** [comment]
Sounds reasonable. At the moment I can get around the issue by manually setting `northOffset` to accommodate for the diff between the yaw and the compass heading.
