### ISSUE TITLE
Fullscreen support in IE11

### ISSUE THREAD

**Issue by evpaassen** [mpetroff/pannellum#258]
In the readme Internet Explorer 11 is listed under *Full support*. However, in Internet Explorer 11 there is no fullscreen button. Edge works fine though. This is also the case when I view the example pano at the [pannellum.org](http://pannellum.org) homepage.

Internet Explorer 11 should support the Full Screen API using the `ms` prefix, according to [caniuse.com](http://caniuse.com/#feat=fullscreen).

Could you please indicate whether this is a bug, or that the readme is wrong?

**Comment by mpetroff** [comment]
It's a bug in the current release. It was fixed in d5282e1fece62db9695a9b7d4875aa376ce82587.

**Comment by evpaassen** [comment]
Okay, I see. Thanks for your response. Just wondering, are there currently any plans to release the fixed version? Otherwise I'll probably build from master and use that.

**Comment by mpetroff** [comment]
Yes&mdash;when it's done. There are a few other bugs I need to get around to fixing first.
