### ISSUE TITLE
non-projected hotspots (e.g. for a floor map)

### ISSUE THREAD

**Issue by PhilippKochBerlin** [mpetroff/pannellum#259]
Hej Matthew,

what a fantastic project! Thanks a lot for making it freely accessible to everyone! 

I recently started trying Pannellum out and I am wondering - is there currectly a way (or do you plan to add such a thing in the future) to display non-projected (flat, with fixed positions) images that could act as hotspots? This would be useful to display a floor map, being overlaid on top of the panorama (like the compass or the navi buttons), consisting of a number of individual parts that together would act as a navigation help / floor plan. If so, it would be most helpful to be able to distinguish three states (i.e. provide three images) per hotspot: active (= last clicked), inactive (= another hotspot is active), mouse-over.

Kind regards, Ph.

**Comment by mpetroff** [comment]
I think this is something that's probably best left to the API. You can use the `loadScene` method to change the scene when a custom button is clicked. For an example of overlaying custom controls, see https://github.com/mpetroff/pannellum/issues/168#issuecomment-227605139.

**Comment by PhilippKochBerlin** [comment]
Hej Matthew,

thanks for your reply and sorry that it took me so long to answer - I didn't realize you had answered before a minute ago.

Thanks for pointing me to that solution. I wasn't aware it could be done like this. I'll have to experiment a little with CSS/API calls, but it look very promising :-)
