### ISSUE TITLE
Which files need to be hosted?

### ISSUE THREAD

**Issue by pvnr0082t** [mpetroff/pannellum#261]
Hi @mpetroff ,
We are [cdnjs](https://github.com/cdnjs/cdnjs) team, we want to host this project in cdnjs.
But I'm not sure which files in this repo need to be added, could you please help up find out the main files?
Thank you.

https://github.com/cdnjs/cdnjs/issues/8992

**Comment by mpetroff** [comment]
The two files needed are `pannellum.js` and `pannellum.css` from the [release archive](https://github.com/mpetroff/pannellum/releases/download/2.2.1/pannellum-2.2.1.zip).

**Comment by pvnr0082t** [comment]
@mpetroff Thank you for help. :facepunch:
