### ISSUE TITLE
Variant pitch and yaw coordinates for different zoom levels

### ISSUE THREAD

**Issue by tordah** [mpetroff/pannellum#262]
Hello,
I got a little problem with the angle coordinates for my hotspots. In a research project where I want to link on site pictures directly to their position within a panorama by referring to the local coordinates from where they were taken, your application proves highly useful to me. However, right now I got stuck with a little problem: In the process of validating our formula that turns the local coordinates to the equivalent angle values for the respective panorama, I want to improve the calculated angles by comparing them with their actual yaw and pitch values according to the developers console (using mouseEventToCoords).
It occurs that depending on the zoom level, these coordinates vary (see image, where I clicked on the same hotspot at 3 diff. zoom levels and each time, the angles changed).
I don't really understand, why the angles for the same spot should change depending on the zoom, and I could swear that it used to not be the case as I did this kind of validation before without the problem. This happens on Firefox and Chrome by the way. 

Maybe there is some sort of trick to overcome this? Many thanks in advance!

![winkelproblem2](https://cloud.githubusercontent.com/assets/3492359/18971016/d5bbd6ae-8693-11e6-8765-1d68de672174.png)

**Comment by mpetroff** [comment]
It appears you have the page zoomed in. This doesn't work properly in the current release version but has been fixed in the development copy (hi-DPI displays weren't handled properly either). If my guess is correct, the easy fix is to reset your browser's zoom to zero.

**Comment by tordah** [comment]
That caused the problem indeed, thanks alot! Now that also explains why I used to have this problem exclusively on Chrome as I guess I had that browser zoomed in for a longer time already and just recently also used the zoom function on Firefox too!
