### ISSUE TITLE
pannellum.js:65 Uncaught TypeError: k.appendChild is not a function

### ISSUE THREAD

**Issue by tkdan235** [mpetroff/pannellum#263]
I am just getting started with the pannellum javascript API and have run into the following error: `pannellum.js:65 Uncaught TypeError: k.appendChild is not a function`.  pannellum seems to find my div by `id` without issue (although the div looks to be unmodified with no children), but I just keep getting the same error and am not sure how to debug the issue.

My code is essentially identical to the API area of the preview example: https://pannellum.org/documentation/examples/preview-image/

Any ideas?

**Comment by tkdan235** [comment]
With some more debugging I figured it out.

This essentially was my code:
```
pannellum.viewer(divID, {
    "type": "equirectangular",
    "panorama": "https://pannellum.org/images/tocopilla.jpg",
    "preview": "/images/tocopilla-preview.jpg"
});
```

In my case divID was a `number` not a `string` and thus I got the error `pannellum.js:65 Uncaught TypeError: k.appendChild is not a function`. :tired_face:

**Comment by mpetroff** [comment]
It checks if the specified container is a `string` and uses the element with that ID if it is. Otherwise, it assumes the container is an `HTMLElement` and proceeds. Since you passed a `number`, which isn't a `string`, the code tried to use it as if it was an `HTMLElement`.
