### ISSUE TITLE
Is there a fixed release cycle or a road map for the next release?

### ISSUE THREAD

**Issue by dmstern** [mpetroff/pannellum#268]
Hi Matthew,

we are using the Pannellum Viewer in a client project. For more flexibility, we need to use config attributes like `clickHandlerFunc` or API functions like `loadScene()`, so we decided to use the current developer revision instead of the latest stable release. Can you foresee, when the next stable version will be released or how much the API can change regarding functions that have already been added?

Best regards,
Daniel

**Comment by mpetroff** [comment]
I hope to push a new release this coming weekend. On Saturday I fixed #217, which was the one remaining blocker. I just need to finish up a few more new examples and do some more testing.

**Comment by dmstern** [comment]
Thank you very much for this pleasing news! 👍 :)

**Comment by mpetroff** [comment]
I just pushed [the release](https://github.com/mpetroff/pannellum/releases/tag/2.3.0).
