### ISSUE TITLE
[Question] Generated preview image for equirectangular panoramic images.

### ISSUE THREAD

**Issue by SvetaSR** [mpetroff/pannellum#270]
I am looking for a tool or library that will allow me to generate a preview image for an equirectangular panoramic image.  The idea is to serve a lightweight preview images while the main image loads. I would like to have a small sized preview image that does not look warped. Does such a tool/library/script exist?

Thank you!

**Comment by mpetroff** [comment]
I'd recommend looking at [Hugin](http://hugin.sourceforge.net/). It includes an assortment of command line tools, such that you could write a script to generate preview images to your liking. There's also a GUI, if that's preferable.
