### ISSUE TITLE
Zoom with Touch Screen

### ISSUE THREAD

**Issue by raffaelecolleo** [mpetroff/pannellum#271]
Hi Petroff,
I am working on a gallery and I have a all in one PC with touch screen. when I try to zoom using the touch screen it increases the size of Firefox. But it works on Chrome. 

Any Idea?

Thanks for Your time.

**Comment by mpetroff** [comment]
It seems that touch events are disabled by default in the desktop version of Firefox: http://stackoverflow.com/questions/29059589/why-is-the-touchstart-event-not-firing-in-firefox

**Comment by mpetroff** [comment]
Closing due to lack of response.
