### ISSUE TITLE
"Object doesn't support property or method 'sign'" IE11 Error

### ISSUE THREAD

**Issue by dmstern** [mpetroff/pannellum#272]
When I call `viewer.startAutoRotate()`, the whole script stops and in the console shows the error message **`Object doesn't support property or method 'sign'`**.

The function seems to be not supported by Internet Explorer.

In my project I solved this by extending the `Math` object:
`
if (typeof Math.sign === 'undefined') {
  Math.sign = function (x) {
    return x > 0 ? 1 : x < 0 ? -1 : x;
  }
}
`

**Comment by mpetroff** [comment]
Thanks. I didn't realize `Math.sign` was ES6 and is only supported by recent versions of Firefox and Chrome. I just removed the only use of it.

**Comment by SavkaTaras** [comment]
You could use polyfill:
https://polyfill.io/v3/polyfill.min.js?flags=always&features=Math.sign

**Comment by luchomatic** [comment]
> When I call `viewer.startAutoRotate()`, the whole script stops and in the console shows the error message **`Object doesn't support property or method 'sign'`**.
> 
> The function seems to be not supported by Internet Explorer.
> 
> In my project I solved this by extending the `Math` object:
> `if (typeof Math.sign === 'undefined') { Math.sign = function (x) { return x > 0 ? 1 : x < 0 ? -1 : x; } }`

This works like a charm, thank you so much.
