### ISSUE TITLE
VR compatiblity 

### ISSUE THREAD

**Issue by s1mar** [mpetroff/pannellum#274]
Hi, will there be a VR mode for this awesome library. I need to create a tour but in VR; if not, then does anyone know any alternatives!?

**Comment by mpetroff** [comment]
"VR" is such a generic term that I don't really know what you're asking.

**Comment by s1mar** [comment]
stereoscopic 3d view compatible with google cardboard

**Comment by mpetroff** [comment]
In that case, this is a duplicate of #82. The answer is currently no.
