### ISSUE TITLE
Browser get hang after continue or heavy use

### ISSUE THREAD

**Issue by rajendra1502** [mpetroff/pannellum#275]
Hi,
Thanks for great library. 
I m creating a application using library, it works fine for some 5-10 scene, after heavy uses it goes hang browser. 
in my function it call following code on every click on hotspot, hotspot are dynamical created on scene.
so thats by i need to call a function on click. is there any other approach to render next scene after click on like poi icons.

       function foo(scene) {
                var panoObject = {
                        "type": "multires",
                        "autoLoad": true,
                        "sceneId": scene,
                        "compass": $rootScope.compass,
                        "arrowdiv": true,
                        "northcompass": true,
                        "multiRes": {
                               "basePath": scenepath,
                               "path": "/%s/z_%l/%y%x",
                              "fallbackPath": "/fallback/%s",
                              "extension": "jpg",
                              "tileResolution": 512,
                              "maxLevel": 3,
                              "cubeResolution": 2600
                          }
              };
           pano = pannellum.viewer(currentContainer, panoObject);
       }

**Comment by mpetroff** [comment]
What browser, browser version, operating system, operating system version, and Pannellum version are you using?

It appears you are creating a new instance of Pannellum each time and not destroying the previous instances. Of course your browser is going to start having issues; you're not freeing resources. Have you looked at using the [`addScene`](https://pannellum.org/documentation/api/#addscene) API method?

**Comment by rajendra1502** [comment]
Thanks for your quick & helpful answer.

i am working with your suggestion, but now i have one more issue  it is possible to mange black tiles image  
in my application every scene is dynamically, when the scene will load its corresponding image fetch from other server, also it a very huge size of image, so it render black tile image in place of panorama tile image.
after that it showing blur tile image, than after it load  actual image, so can it be possible to replace black tile image to blur tile image.

**Comment by mpetroff** [comment]
I don't understand what you're asking. Sorry.

**Comment by rajendra1502** [comment]
Hello, is this possible to print or write some text on scene like google street name.
![Uploading labels.png…]

**Comment by mpetroff** [comment]
I don't see how this is related to this issue. You can add annotations using [hot spots](https://pannellum.org/documentation/examples/hot-spots/). To make it look like the annotations in that image, you'd have to add the text directly to your panorama image using other software.

**Comment by rajendra1502** [comment]
Thanks for your valuable support, it is really very helpful for me. thanks
