### ISSUE TITLE
full screen button doesn't work on android 

### ISSUE THREAD

**Issue by vincelandd** [mpetroff/pannellum#276]
The fullscreen button doesn't work on my Android smartphone.
Is it normal?

**Comment by mpetroff** [comment]
What version Android are you using? What browser? What browser version? Just saying "Android" doesn't tell me much.

**Comment by vincelandd** [comment]
you're right.
my phone is on android 5.1
my browser is only named "browser" ("navigateur" in french) 
it s icon is an earth and the version is 5.1-1-464009553.
i'm stupid, i was sure it was a chrome browser. 
so i install chrome and firefox to test and it's OK for the 2 !!
conclusion : use a standard and common browser !!
thanks a lot.
