### ISSUE TITLE
how to add personal menu/navigation buttons on ui ?

### ISSUE THREAD

**Issue by vincelandd** [mpetroff/pannellum#277]
how to add personal menu/navigation buttons on the ui ?
can we simply delete the fullscreen button only when we are on android smartphone (because the button doesn't work) ? 
how to customise the menu buttons ?
thanks for your answers.

**Comment by mpetroff** [comment]
Take a look at the [custom controls example](https://pannellum.org/documentation/examples/custom-controls/).

**Comment by vincelandd** [comment]
i don't see this part.
thanks a lot.
