### ISSUE TITLE
video doesn't work on my android smartphone

### ISSUE THREAD

**Issue by vincelandd** [mpetroff/pannellum#278]
impossible to watch a 360° video on my android (5.1) smartphone. 
error message :" your browser does not have the necessary webgl support to display this panorama". 
how to fix this problem ?
Thanks.

**Comment by mpetroff** [comment]
It suggests that the video's resolution is too big for your phone. Does a still image panorama of the same resolution work? If you use Chrome's remote debugging, what's logged to the developer console?

**Comment by vincelandd** [comment]
my phone is on android 5.1
my browser is only named "browser" ("navigateur" in french) 
it s icon is an earth and the version is 5.1-1-464009553.
i'm stupid, i was sure it was a chrome browser. 
so i install chrome and firefox to test and it's OK for the 2 browsers !!
conclusion : use a standard and common browser !!
thanks a lot.
