### ISSUE TITLE
loadScene

### ISSUE THREAD

**Issue by raffaelecolleo** [mpetroff/pannellum#279]
Hi All,
I have created a button that will be able to load a scene from outside of the panorama div.
the problem is that all the links I have inside that scene are no longer available.

Was I clear on the question?

Cheers,
Raffaele Colleo

**Comment by mpetroff** [comment]
I think what you're saying is that you're changing the scene using the API's `loadScene` method but when you do, the new scene's hot spots are missing. If this is correct, it's behavior I've never seen before. Do you have an example that demonstrates this?

**Comment by raffaelecolleo** [comment]
Yes I have.
You can check here at http://360.rcr-macau.com

Thanks a lot
Raffaele Colleo

**Comment by mpetroff** [comment]
You're not using the `loadScene` method. You're instead using your `myLoadScene` function which destroys the renderer (but not the viewer) and creates a new viewer with only your new scene; of course the hot spots are missing&mdash;they're not in the new configuration.

You should be calling `viewer.loadScene('sceneid');` to change the scene.

**Comment by raffaelecolleo** [comment]
Hi Petroff,
I have change it but, on click does not load the scene.
