### ISSUE TITLE
fullscreen style bug in internet explorer

### ISSUE THREAD

**Issue by dmstern** [mpetroff/pannellum#283]
hi @mpetroff ,

I recognized a styling bug in internet explorer when entering fullscreen mode. The .pnlm-container has a too small height. This could be fixed by adding a -ms-prefixed style rule (as you have already done for firefox, chrome etc.):

`.pnlm-container:-ms-fullscreen {
  height: 100% !important;
  width: 100% !important
}
`

Regards,
Daniel

**Comment by mpetroff** [comment]
Thanks. I just fixed it.
