### ISSUE TITLE
Issue on mobile?

### ISSUE THREAD

**Issue by PTthe13** [mpetroff/pannellum#284]
Hey,

I'm having an issue implementing the **Pannellum** on **Ionic framework**.

I'm calling the pannellum information on a certain view _(the idea is for each view to have a different 360 image)_.

My problem is whenever I open the view I want, it returns the following error in the console: **_"Uncaught TypeError: g.addEventListener is not a function"_** and it never shows the pic (even though It apparently loads it).

![screen shot 2016-11-14 at 12 21 46](https://cloud.githubusercontent.com/assets/3495263/20264749/13fcf4bc-aa65-11e6-97ee-57ff3e4c5b84.png)
![screen shot 2016-11-14 at 12 21 40](https://cloud.githubusercontent.com/assets/3495263/20264751/14010994-aa65-11e6-84ca-7bc7b36b395e.png)
![screen shot 2016-11-14 at 12 22 08](https://cloud.githubusercontent.com/assets/3495263/20264750/13fdc00e-aa65-11e6-96fc-e5001b293529.png)

**_PS: I forgot to mention. While developing locally and testing on the browser, everything works fine. Only when I "push" to the devices (android and iOS) does it return that error._**

**Comment by mpetroff** [comment]
Are you trying to run it on some sort of ancient version of WebKit? The error says that the [FileReader](https://developer.mozilla.org/en-US/docs/Web/API/FileReader) object doesn't have an `addEventListener` method. This was implemented in WebKit [almost five years ago](https://bugs.webkit.org/show_bug.cgi?id=42723).

If you're using an actual modern browser, my guess is that the issue is being caused by an interaction with some other piece of code, such as a framework.

**Comment by PTthe13** [comment]
@mpetroff It's running on the most modern version of WebKit. 

It must be something to do with the Ionic framework, cus after I wrote that, I was testing around, and found out that if I "forced" the view to load no dynamic content and had the pannellum hardcoded, it worked fine.

I also found out that using the iframe mode instead of the API works fine.

It must be some kind of conflict with the Ionic framework. I'll be testing some more on this.

**Comment by mpetroff** [comment]
It seems Ionic [reimplements](https://github.com/driftyco/ionic-native/blob/71916a85ddbffbaac3967ec3ef45e1fa36c73df0/src/plugins/file.ts#L291) the FileReader object but doesn't fully implement the spec. This issue comment might be helpful: https://github.com/driftyco/ionic-native/issues/505#issuecomment-243434491

**Comment by einfochips1** [comment]
Hi All,

I am facing the same issue on pannellum.js version 2.4 on Ionic-3 app.

## **My project ionic info is as below:**
cli packages: (/usr/local/lib/node_modules)
    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:
    cordova (Cordova CLI) : 7.1.0 

local packages:
    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : android 6.3.0 ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2

System:
    Android SDK Tools : 26.1.1
    ios-deploy        : 1.9.2 
    Node              : v9.6.1
    npm               : 5.6.0 
    OS                : macOS High Sierra
    Xcode             : Xcode 9.2 Build version 9C40b 


##  **Sorce code:**
** root index.html file, head tag**

  
  <script src="https://cdn.pannellum.org/2.4/pannellum.js"></script>

  
  <link rel="stylesheet" href="https://cdn.pannellum.org/2.4/pannellum.css">

**vr-test.html file** 
<div id="panorama"></div>

**vr-test.ts file**
ngOnInit() {

 let url = "https://poquito-local.s3.amazonaws.com/uploads/vimeo_upload/file_name/74/8nx2daei.jpg";

  console.log('ngOnInit() ============');
  pannellum.viewer('panorama', {
    "type": "equirectangular",
    "panorama": url,
    "autoLoad": true,
    "title":"Swivel",
    "autoRotate":1.5
  });
}

![console error](https://user-images.githubusercontent.com/13536916/38621467-9596e440-3dbe-11e8-9446-d76a9e790d35.png)
![pannellum js source-code issue line](https://user-images.githubusercontent.com/13536916/38621468-960c2f0c-3dbe-11e8-96c6-3f21b9584ea0.png)

**Comment by clzola** [comment]
Hi all,

@einfochips1 I had same issue, and I have found this comment very useful: https://github.com/mpetroff/pannellum/issues/542#issuecomment-380513592 

It works for me, but I have only tested on **Huawei P9 Lite, Android 7.1.1**

**Comment by einfochips1** [comment]
Hi @clzola  yes, it works for me too. Actually, the issue was CORS issue on the server and because of that, this issue generated. Now it worked!
Thanks,
Punita

**Comment by mpetroff** [comment]
Per the change in d51ade0e2c147e347699dc3c85ff56cb661734e8, mobile app frameworks are not officially supported.
