### ISSUE TITLE
Canvas Bug?

### ISSUE THREAD

**Issue by ERMS** [mpetroff/pannellum#285]
I have a panorama with hotspots and tour and it works perfectly. But when I added autoLoad and set it to true on firstScene. The output was this, 

![image](https://cloud.githubusercontent.com/assets/7464917/20334466/2badc140-abf5-11e6-941a-d906491c0c8e.png)

Then I inspect element and look for its canvas, 

![untitled](https://cloud.githubusercontent.com/assets/7464917/20334467/2bdacdb6-abf5-11e6-9ec6-78dbf2c6f33a.png)

Its weird because the height and weight of the canvass is 0. But when I make some actions such as adjusting the panel, the values change.

![untitled2](https://cloud.githubusercontent.com/assets/7464917/20334474/3473a7c2-abf5-11e6-83ed-a37ee42136cc.png)

What could be the explanation for this?

Thank you and sorry for my grammar.

**Comment by mpetroff** [comment]
Are you using the latest version of Pannellum? Is there anything printed to the developer console?

**Comment by ERMS** [comment]
I am using the latest version sir. Only warning. 

![image](https://cloud.githubusercontent.com/assets/7464917/20373444/e181bd20-acac-11e6-85fc-238e324339fd.png)

**Comment by mpetroff** [comment]
I suspect there's something wrong with how you're initializing Pannellum, then. I can't reproduce this issue.

**Comment by ERMS** [comment]
Thank you :)
