### ISSUE TITLE
Hotspots that stay in place when moving the view left or right?

### ISSUE THREAD

**Issue by stacksavings** [mpetroff/pannellum#289]
This isn't an actual bug but instead a limitation in terms of how I am trying to use the framework so I'm wondering if anyone has any advice on how I could potentially accomplish this, I would be willing to attempt making changes for this in my own fork if it would be possible so any advice, etc is appreciated.

I am trying to build a UI with icons, using hotspots, that are along the top of the view (based on the starting view that the user initially sees). As hotspots are tied to locations in the image, they obviously move around a bit in terms of their "vertical placement" within the image box like in my example screenshot the hotspots are both at the same pitch setting of 30, but one shows vertically higher than the other as it is not in focus fully.

![screenshot_2016-11-16-08-11-05](https://cloud.githubusercontent.com/assets/14384619/20354958/96eec376-abd4-11e6-8f7e-babdd8e4e3f2.png)

I realize that this is how hotspots are supposed to work, since they are tied to spots on the actual image.. however, for the purposes I am trying to build a set of UI icon elements that would stay within the same vertical line as the user moves left or right, rather than having them tied to specific spots on the page, as I feel this would give the user a better experience. 

Interested to get any feedback, etc on this. Thanks

**Comment by mpetroff** [comment]
You'll have to modify the code to fix the Y translation: https://github.com/mpetroff/pannellum/blob/d30335fd55b8073101494dceddad0568f77d7494/src/js/pannellum.js#L1701

If you change that line to
```
var transform = 'translate(' + coord[0] + 'px, 10px) translateZ(9999px) rotate(' + config.roll + 'deg)';
```
where `10px` can be whatever offset you want, the hot spots should be fixed along the top edge.

**Comment by stacksavings** [comment]
Awesome thank you, much appreciated, I tested this now and it is working great!
