### ISSUE TITLE
Accidental IE10 support lost

### ISSUE THREAD

**Issue by bikubi** [mpetroff/pannellum#291]
This is more of a FYI / For The Record :)
I know you officially and understandably don't support IE10, but it used to work nicely, until 2.2.1.
Somewhere on the way to 2.3.0 mouseDown/Drag stopped working - Keyboard control still works.

**Comment by mpetroff** [comment]
IE10 doesn't support WebGL, so most of Pannellum never functioned anyway. I didn't realize the CSS 3D transform based fallback renderer even worked in it...
