### ISSUE TITLE
addScene add scenes dynamically

### ISSUE THREAD

**Issue by saidmoya12** [mpetroff/pannellum#293]
Pannellum no work if no have scenes when start.
If posible add scenes dynamically without prev scenes?

Thanks

I have
```
this.viewer = pannellum.viewer('Space-pano', {
    scenes: {}
}
```

Then
```
this.viewer.addScene('space_0' {
	type:		"equirectangular",
	panorama:	'path_to_my_image.jpg',
	autoLoad:	true
})
```
And finally
```
ctx.viewer.loadScene('space_0', ctx.viewer.getPitch(), ctx.viewer.getYaw(), ctx.viewer.getHfov());
```

**Comment by mpetroff** [comment]
Use a placeholder for the viewer and don't create the viewer until you're ready to load the first scene. If you don't have a configuration, the load button isn't going to work anyway.

**Comment by saidmoya12** [comment]
That isn't a pretty solution for dynamic loaded content, I add a default scene with a grid image to solve it.

Thanks
