### ISSUE TITLE
Mobile scrolling, is it possible to be able to scroll over hotspots?

### ISSUE THREAD

**Issue by stacksavings** [mpetroff/pannellum#294]
I have run into a bit of an issue as I have tried making some panoramas for mobile that have hotspots that happen to be in the middle of the panorama and some are fairly large, so this can disrupt a user's scrolling (when they are using their thumb to scroll left to right, for example, to look around the scene). I still want these hotspots to be clickable, but the scroll action is distinct from the click action so I'm not sure exactly why they aren't able to scroll when their thumb movement lands on a hotspot but I have noticed, in my testing, it can disrupt the flow of a user's use of a layout. Any info / advice on this would be appreciated, I can look into the code more as well.

**Comment by mpetroff** [comment]
The touch event handler is on the canvas, not the hot spots. The hot spots only have click handlers.

**Comment by stacksavings** [comment]
I edited the source to add the touch event handler to hotspots.. if anyone has an interest in this I can make it so that this is a config option when creating a hotspot and do a pull request.
