### ISSUE TITLE
Flickering in mobile

### ISSUE THREAD

**Issue by stacksavings** [mpetroff/pannellum#295]
I've been working on a layout and it seems that an issue has started occurring where there is a lot of flickering when moving left or right on mobile (I have tested in Android Chrome). I'm wondering if anyone has an idea of what I should look into regarding potential causes of this?

The layout is below, I am only seeing the issue on mobile:

http://stacksavings.com/connect/reading_premier/panellum/connect.stacksavings.com/layout2/

**Comment by mpetroff** [comment]
It seems related to your `menu-container-hotspot` hot spot.

**Comment by stacksavings** [comment]
I'm guessing this is because it is wider than what can be fit into one screen view? I'm hoping to have a way to have a background like this on a menu, where it stretches longer than what can be seen all at once on mobile but it seems that won't work with hotspots?

⁣

Sent from BlueMail

​

**Comment by stacksavings** [comment]
Also, if you don't mind, could you share how you were able to determine that it is related to that hotspot? I would like to debug myself, etc to learn more about the issue but honestly I'm not sure where to start, also it only occurs on my mobile, not my laptop so I can't, for example, use my web debug tool in chrome.

**Comment by mpetroff** [comment]
You can use the debugging tools in the desktop version of Chrome with the Android version:
https://developers.google.com/web/tools/chrome-devtools/remote-debugging/

Since there isn't normally flickering, I guessed the issue was with something you added. The large hot spot seemed like the mostly like candidate, so I hid it, and the flickering stopped.

**Comment by stacksavings** [comment]
Actually, for me, that didn't seem to be the case, it seems it was the .svg images that were causing this.. I had 3 svg images there, one was this:

<img height='20%' width='20%' src='icons-reading/ereader.svg'>

Once I removed those it seemed the flickering has stopped. I guess this is somehow related to .svg images, I can just use .png's instead then, as it seems it works fine with those.
