### ISSUE TITLE
Option to hide "Click to Load Panorama" caption?

### ISSUE THREAD

**Issue by thenrich2009** [mpetroff/pannellum#296]
Is there an option to hide the "Click to Load Panorama" caption? I have a preview image and the caption is blocking most of the image.

**Comment by mpetroff** [comment]
No, there isn't. How is the user going to load the image if the button's there (and auto load isn't turned on, which would hide the button anyway)?

**Comment by thenrich2009** [comment]
I don't understand your question. What button? 
Isn't that just a static text? I see you're setting innerHTML with it so I should be able to use an empty text or remove that code.

The users know that they click on an image to view the full image. That's why for me there's no need to have the same text on every image.

**Comment by mpetroff** [comment]
The translucent black box that has the "click to load panorama" text is a button. If you want to remove the text, you'll have to edit the source.

**Comment by emaglic** [comment]
Is there a way to tap into the event that fires when you click the load panorama button? 
I'd like to create my own button somewhere else on the page, outside of Pannellum, and basically trigger the load functionality when the user clicks that button. 

I know I could in theory grab the button element and call .click() on it, but is there a more elegant solution than this?

Thanks!

**Comment by mpetroff** [comment]
There's no built-in support for what you're describing, so the method you suggested is probably best.
