### ISSUE TITLE
An option to auto create and display a preview image

### ISSUE THREAD

**Issue by thenrich2009** [mpetroff/pannellum#297]
I would like to see an option to auto create and display a preview image based on the panorama image without loading the whole image. The preview image file would be a file and has a size of the size of the preview div.

So if I have a web page of 30 images previews, the page initially loads and displays 30 smaller files.

**Comment by mpetroff** [comment]
You need to make the preview image with other software, e.g. [Hugin](http://hugin.sf.net/).

**Comment by mpetroff** [comment]
Closing due to lack of response.
