### ISSUE TITLE
Code example with getConfig or how to get the current configuration?

### ISSUE THREAD

**Issue by Soeren321** [mpetroff/pannellum#298]
Hello, 

I am trying to get the current configuration and store it into a hidden HTML field. I found the API getConfig but the result is empty:

obj = this.viewer.getConfig;
$("#currentconfig").text(Object.keys(obj));

Any suggestions?

Thanks!

**Comment by mpetroff** [comment]
It's a function&mdash;you need to call it, e.g. `viewer.getConfig();`.
