### ISSUE TITLE
event when scene is loaded

### ISSUE THREAD

**Issue by danielnaber** [mpetroff/pannellum#30]
I'd like to be notified when a scene is loaded. What about adding very simple events like this? I guess there's a better approach...

https://github.com/danielnaber/pannellum/commit/dec4ab95a171cc51ca3f1bdd1e34f349cbbfb73d

As a user, I can then do:

		$(document).ready(function() {
			document.getElementById('pannellumFrame').contentWindow.sceneLoaded = function(sceneId) {
				alert(sceneId);
			}
		});

**Comment by umbreak** [comment]
Is your plan about rewriting the pannellum code yet active?

It would be much easier to treat events and to extend functionality out of the actual pannellum code when the framework is not wrapped in an `iframe`

**Comment by mpetroff** [comment]
Yes, and I've been making progress. All the elements are now created dynamically. I still need to wrap everything in a constructor and make an API, though.

**Comment by mpetroff** [comment]
This was implemented in a1461bb6ecdfa860e527fd32c62bc3fd5af3aee9. After instantiating a viewer with `viewer = pannellum.viewer(...);`, events can be added with `viewer.on('eventtype', listener)`. For scene changes, this would be `viewer.on('scenechange', sceneChangeListener)`. The listener can retrieve the scene ID with `viewer.getScene()`.

**Comment by senolozgur** [comment]
Hi,
thank you for great library. 
It would be excellent if you include events in API documentation at pannellum website.
Regards.

**Comment by mpetroff** [comment]
It's already there: https://pannellum.org/documentation/reference/#api-events
