### ISSUE TITLE
Image seems pixelated in mobile

### ISSUE THREAD

**Issue by avi-stacksavings** [mpetroff/pannellum#301]
I have images from samsung gear 360, original resolution size is 7776 x 3888.
I am using original size for desktop view and using smaller image of 4000 x 2000 for mobile view because in mobile it not supports more than 4096 pixels.
The image I am using for mobile view it looks pixelated even when resolution is this big (4000 x 2000 )
Attaching mobile screenshot and original image along with the link where you can view.
working link: https://stacksavings-360-kanwal-avidayal91.c9users.io/stacksavings-360/fall-season-panellum/panellum/connect.stacksavings.com/layout2/index.html

Desktop view image (7776 x 3888) link: https://s3.amazonaws.com/stacksavings-360/360_0272_Stitch_YHC.JPG
mobile view image ( 4000 x 2000) link: https://s3.amazonaws.com/stacksavings-360/360_0272_Stitch_YHC+4000x2000.jpg

mobile screenshot: 
![screenshot_2016-11-21-09-27-39](https://cloud.githubusercontent.com/assets/20572760/20511552/484d50aa-b09f-11e6-939e-d1a84f3c596b.png)

**Comment by mboelter** [comment]
I ran into similar issues, try using the multires mode as a work around.

**Comment by mpetroff** [comment]
You're using a low-resolution image compared to the screen resolution. Of course it isn't going to look great. However, it appears to me that it's doing nearest neighbor interpolation even though Pannellum's code specifies linear interpolation, which looks better; if this is true, it's a browser / device bug, not a bug in Pannellum.
