### ISSUE TITLE
Can't find an "IsLoaded" variable

### ISSUE THREAD

**Issue by Arkas000** [mpetroff/pannellum#304]
Is there a way to know when pannullum has finished loading a media? More precisely, I'm looking for a way to generate and load hotspots based on the north of the photo. The problem is that pannellum seems to not set hotspots using north (Am I missing something?) and I can't get the north if the photo has not been loaded yet.

**Comment by mpetroff** [comment]
Hot spots are set using image coordinates; the `northOffset` parameter just sets the offset for the compass display.

You can add a listener for `scenechange` to see when this happens (or `load` if you want it to fire once the panorama finishes loading), e.g. `viewer.on('scenechange');`, where `viewer` is the Pannellum instance. See the [`on` method](https://pannellum.org/documentation/api/#on) API documentation and the [available events](https://github.com/mpetroff/pannellum/blob/master/doc/events.md).

**Comment by mpetroff** [comment]
Closing due to lack of response.
