### ISSUE TITLE
Low resolution on samsumg Galaxy Tab S2

### ISSUE THREAD

**Issue by andyz** [mpetroff/pannellum#305]
Great panorama viewer but I am finding on a Galaxy Tab S2 android tablet the textures are appearig low-res and pixelated. Not sure if poor webgl support or what - tried on android browser and chrome.
Is fine on s7 phone

**Comment by mpetroff** [comment]
It's probably a WebGL support issue. I don't have this device, so I can't test it.

**Comment by mpetroff** [comment]
Closing due to lack of response.
