### ISSUE TITLE
hotspot and popup problem

### ISSUE THREAD

**Issue by fedeDeb** [mpetroff/pannellum#308]
Hi! I've created a tour with pannellum and added some hotspots. I added to hotspots a click handler to show details of hotspot like an image, title and a description, with a popup. this work only when the fullscreen is disabled. I want to show details also in fullscreen mode. How can I do this?

**Comment by mpetroff** [comment]
How are you showing the popup? I'm guessing its DOM isn't a child of the element that's fullscreen (the Pannellum container).

**Comment by mpetroff** [comment]
Closing due to lack of response.
