### ISSUE TITLE
backgroundColor other than 0,0,0 always shows white color

### ISSUE THREAD

**Issue by thenrich2009** [mpetroff/pannellum#314]
Whatever color I use other than 0,0,0 for backgroundColor attribute, the background color is white

**Comment by mpetroff** [comment]
This works fine for me in both Firefox and Chrome. For example, `"backgroundColor": [0.5, 0.5, 0.5]` show a gray background.

**Comment by thenrich2009** [comment]
I was using rgb values between 0 and 255. I will try the 0-1 scale.

**Comment by mpetroff** [comment]
The [0,1] scale is specified in the [documentation](https://github.com/mpetroff/pannellum/blob/master/doc/json-config-parameters.md#backgroundcolor-number-number-number).

**Comment by thenrich2009** [comment]
I wasn't familiar with that scale so [0,1] didn't mean anything to me. Thanks.
