### ISSUE TITLE
Custom Controls + setYaw getYaw => Viewer "Jumping"

### ISSUE THREAD

**Issue by praefectius** [mpetroff/pannellum#315]
I was testing your new features when I noticed that by using customs controls (setYaw + getYaw) the viewer is jumping backwards the whole panorama when reaching its edges. It happens when you spin the whole 360° with the customs controls in one direction.

See: https://pannellum.org/documentation/examples/custom-controls/

Another one:
```
.ctrl 
{
   .
   .
   cursor: pointer;  <=== is missing under the API
}
```

**Comment by mpetroff** [comment]
I just fixed this. I also fixed the example in https://github.com/mpetroff/pannellum.org/commit/b36b4e17bb2ca038bc0c2b34adf3bc604ee9fae0; I'll push the changes to the website this evening. Thanks for reporting the issue.

**Comment by squadcar** [comment]
Great little viewer, exactly what I needed. That said, I'm currently having this issue using the cdn version. Whether I use 0/360, or -180/180

**Comment by mpetroff** [comment]
There hasn't been a new release since this was fixed.

**Comment by squadcar** [comment]
My apologies, I didn't read the original bug thoroughly. I'm running into a similar issue with setYaw, but it sounds a bit different. I'll see if I can reproduce the bug and I'll open a new ticket if so.
