### ISSUE TITLE
Glitches in IE11 / Win7

### ISSUE THREAD

**Issue by bikubi** [mpetroff/pannellum#316]
Multiple users have reported glitches with multires-panoramas in Internet Explorer 11 on Windows 7. Unfortunately I don't have good screenshots, but they roughly look as if tiles were wrongly/randomly referenced/mapped (which they were not) - like in level 1, you see the tile `x0_y1` instead of `x1_y1` etc. I guess this means that pannellum is in non-fallback/WebGL-mode, and not in [IE11's weird fallback software rendering mode](https://connect.microsoft.com/IE/feedback/details/805206/webgl-only-doing-software-rendering).
It looks different than #267, and textures are power-of-two-sized, so not #45, I guess.
Even more unfortunately I can't reproduce it in a VM, so I guess it's another almost-impossible-to-fix WebGL/driver/graphics card bug...

Since this issue was critical in our case, I applied the same workaround as in #267 (forcing fallback/non-multires cubemap) with adjusted [Browser](http://stackoverflow.com/questions/17907445/how-to-detect-ie11) / [OS](http://stackoverflow.com/questions/15710646/detecting-os-xp-vs-7) sniffings:
```js
var ua = navigator.userAgent.toLowerCase(),
  isWin7 = ua.indexOf('windows nt 6.1') > -1,
  isIE11 = (ua.indexOf('trident') > -1) && (ua.indexOf('rv:11') > -1);
if (isWin7 && isIE11) // then forceCubeMap() ...
```

**Comment by mpetroff** [comment]
I tried and failed to reproduce this.
