### ISSUE TITLE
Using getScene with minified version

### ISSUE THREAD

**Issue by ner00** [mpetroff/pannellum#319]
I'm unable to use `getScene`, I am using a single minified html file and loading different panoramas configs from the url. How do I call `getScene` properly?

This is what is present in the minified version: `this.getScene=function(){return c.scene};`
Several attempts at calling this function throw the error: `getScene is not a function`
Calling with `pannellum.viewer('container').getScene()` gives the following error: `Uncaught TypeError: Cannot read property 'firstScene' of undefined`

Can someone throw an example of the function's usage for the standard minified version? Thanks!

By the way, I'll just paste the config I'm using to make sure the issue doesn't come from there:
````
{
  "default": {
    "firstScene": "house",
    "sceneFadeDuration": 1000
  },

  "scenes": {
    "house": {
      "title": "House",
      "hfov": 130,
      "yaw": 210,
      "type": "equirectangular",
      "panorama": "https://pannellum.org/images/alma.jpg"
      "hotSpots": [
        {
          "pitch": -1.0,
          "yaw": 228.0,
          "type": "scene",
          "text": "Garden",
          "sceneId": "garden"
        }
      ]
    },

    "garden": {
      "title": "Garden",
      "hfov": 110,
      "yaw": 5,
      "type": "equirectangular",
      "panorama": "https://pannellum.org/images/alma.jpg"
      "hotSpots": [
        {
          "pitch": -0.6,
          "yaw": 37.1,
          "type": "scene",
          "text": "House",
          "sceneId": "house",
          "targetYaw": -23,
          "targetPitch": 2
        }
      ]
    }
  }
}

**Comment by ner00** [comment]
The only way I could get it to work was to add a variable to the minified script:

`viewer=pannellum.viewer("container",e)`
instead of originally:
`pannellum.viewer("container",e)`

Is this the correct approach for the minified version? Thank you.

**Comment by mpetroff** [comment]
That's the only correct approach, minified or not.

Calling `pannellum.viewer('container').getScene()` creates a new Pannellum instance, without a configuration, and then calls the new viewer's `getScene` method, which obviously doesn't work, since the viewer was just created with an empty configuration. Take a look at an example that uses the API, such as the [custom controls example](https://pannellum.org/documentation/examples/custom-controls/).
