### ISSUE TITLE
generate.py does not generate a proper script for nona + [fix]

### ISSUE THREAD

**Issue by gonciarz** [mpetroff/pannellum#32]
Distro: ArchLinux
Hugin: extra/hugin 2014.0.0-2
Version: pannellum-2.0.1_full and trunk (rev: 3d1f9344fb254c03d3f2f1d6e23dc79af38e6ca8)
When I call nona command it generates: 0, 1, 4, 5 faces files only (we are missing: 2 and 3). The current nona version accepts a different scripting syntax: '+p90' instead of 'p90' or '-p90' instead of 'p-90'.

```
diff --git a/generate.py b/generate.py
index faf086a..babee1d 100755
--- a/generate.py
+++ b/generate.py
@@ -72,8 +72,8 @@ text.append('p E0 R0 f0 h' + str(cubeSize) + ' n"TIFF_m" u0 v90 w' + str(cubeSiz
 text.append('m g1 i0 m2 p0.00784314')
 text.append('i a0 b0 c0 d0 e0 f4 h' + origHeight + ' n"' + origFilename + '" p0 r0 v360 w' + origWidth + ' y0')
 text.append('i a0 b0 c0 d0 e0 f4 h' + origHeight + ' n"' + origFilename + '" p0 r0 v360 w' + origWidth + ' y180')
-text.append('i a0 b0 c0 d0 e0 f4 h' + origHeight + ' n"' + origFilename + '" p-90 r0 v360 w' + origWidth + ' y0')
-text.append('i a0 b0 c0 d0 e0 f4 h' + origHeight + ' n"' + origFilename + '" p90 r0 v360 w' + origWidth + ' y0')
+text.append('i a0 b0 c0 d0 e0 f4 h' + origHeight + ' n"' + origFilename + '" -p90 r0 v360 w' + origWidth + ' y0')
+text.append('i a0 b0 c0 d0 e0 f4 h' + origHeight + ' n"' + origFilename + '" +p90 r0 v360 w' + origWidth + ' y0')
 text.append('i a0 b0 c0 d0 e0 f4 h' + origHeight + ' n"' + origFilename + '" p0 r0 v360 w' + origWidth + ' y90')
 text.append('i a0 b0 c0 d0 e0 f4 h' + origHeight + ' n"' + origFilename + '" p0 r0 v360 w' + origWidth + ' y-90')
 text.append('v')
```

**Comment by gonciarz** [comment]
Thanks for your help. I'm satisfied that we solved this problem. 

Regarding my panorama I workaround the issue by adding a black background and resizing the image. Then after I run your script it produced the proper set of images. I've also override some variables like minPitch/maxPitch to 0 and the result is much better. 

Google's panoramas are very wide but not so high and that's a problem when you want to initially present a static image and then switch to dynamic presentation - the size of frame should be different for both cases. Though I did a trick in pannellum.htm and after a clicking button I resize the hight of frame.. Is there any other way I can do that without touching your code?

**Comment by mpetroff** [comment]
No, not at the moment.

**Comment by ghenzhimura** [comment]
hi matt.. i had a problem with multires image when its in fullscreen mode. The panorama doesnt run smooth. i use image with 3000x1500 dimensions

**Comment by mpetroff** [comment]
The multires renderer could use some performance improvements. However, with an image that small, using multires is probably not needed. The image isn't that big, so it doesn't take that long to download, and 99% of devices support that resolution.

**Comment by ghenzhimura** [comment]
yes, i use it for safari and iphone due their lack webgl support. But with that small image, it doesnt running so well on desktop fullscreen.

**Comment by mpetroff** [comment]
Closing as this seems to be resolved.
