### ISSUE TITLE
JSON config file cannot be named "pannellum.json"

### ISSUE THREAD

**Issue by milankni** [mpetroff/pannellum#320]
Hi,

the pano does not load when the config file is called "pannellum.json". Changing to "pannellum-config.json" or alike works.

I tested only the iframe with ?config=... parameter.

**Comment by mpetroff** [comment]
This seems to work fine for me. Do you have an example that demonstrates this behavior?

**Comment by mpetroff** [comment]
Closing due to lack of response.
