### ISSUE TITLE
Adding a "onclick" to a hotspot?

### ISSUE THREAD

**Issue by Mvotre** [mpetroff/pannellum#327]
hi there. I got a lot of nice things working 

http://www.estudiojls.com.br/teste_marcel/JLS/index5.html

PS: ignore the pink border and crappy icons :P

however, I would like to make some invisible divs (and one iframe) to show when clicking on the hotspot link (I can make it work a url, as seen in documentation, but I would like to leave this panorama as the main menu on the site, always loaded). I believe the best method would be to add a id to .custom-hotspot class, but I can't acess it. Anyone has any idea on how to make it work? Just some guide on how can I make this work and I'm off to testing. Tried lots of things, but nothing actually work. 

PS: sorry for asking here. One more vote for a pannellum forum o/

thanks in advance;

**Comment by mpetroff** [comment]
You can add a custom click handler to a hot spot using the [`clickHandlerFunc` and `clickHandlerArgs`](https://github.com/mpetroff/pannellum/blob/master/doc/json-config-parameters.md#clickhandlerfunc-function-and-clickhandlerargs-object) hot spot configuration parameters.
