### ISSUE TITLE
V2.3 Tour Doesn't Work

### ISSUE THREAD

**Issue by chrusion** [mpetroff/pannellum#329]
Please view this tour (using API method): http://chrusion.com/tmp/RWR_Tour_EQ.html

Notice that SCENE hotspot links do not work. Cursor changes to an arrow, instead of a pointer finger on mouse over of the hotspot icon. The title of the next scene does appear on mouse over, but the arrow icon is not "clickable," as in, clicking it does nothing... the viewer does not load the next image defined in the scene (yes, the /path/filename is valid (all files are in the root folder).

I've reviewed and scanned over the json syntax in the <script> tags and do not see anything amiss compared to your various examples. So, I'm at a loss to know what to do, except ask here how to get it working. The only thing I've noted in your docs is that a json config file is required when using scenes, but isn't that what the script in the HTML builds, a json object?

Thanks.  Pannellum is a very fine "product" by the way!

PS: This is a work in progress and the first time I'm using Pannellum to do a tour. I will be using cubes for the final client deliverable. For now the panos are huge 10Kx5K pixel equirecs.

**Comment by mpetroff** [comment]
The correct key for specifying the hot spot scene ID is `sceneId` not `sceneID`; your capitalization is wrong (and JSON is case sensitive).

**Comment by chrusion** [comment]
Oh, Wow! How did I miss that? Thank you very much. Now works.

**Comment by chrusion** [comment]
Doh! Thanks for catching that... works perfectly now! Now that I have all 8 panos linked, the fun begins in getting coordinates for all the hotspots and implementing other features offered in the API.

**Comment by SimonEnvisionVR** [comment]
Just ran into this problem and found this thread, thanks for the answer!
