### ISSUE TITLE
panorama not displayed with ignoreGPanoXMP=false

### ISSUE THREAD

**Issue by danielnaber** [mpetroff/pannellum#33]
Something seems to have been broken(?) by this commit: https://github.com/mpetroff/pannellum/commit/e90d65b5bb6092f6de3e6e5598651704c9a9ec8b. I cannot get a simple equirectangular panorama to display anymore after that change. My test tour is this:

	{   
		"default": {
			"firstScene": "library"
		},
		
		"scenes": {
			"library": {
				"panorama": "R0010216-stacked.JPG"
			}        
		}
	}

Instead of the image (which is loaded correctly according to Firebug), I only see a grey area. Setting `ignoreGPanoXMP` to true makes everything work again - so maybe the default should be set to `true`? I can send you the affected image by email if needed.

**Comment by mpetroff** [comment]
I suspect the image contains XMP data. Looking back at my code, I'm trying to use the Google Panorama tags if an image has XMP data, whether or not it actually has the tags. Obviously, that ends badly when those XMP tags don't exist. I'll fix it tonight.

**Comment by mpetroff** [comment]
I think I fixed it.

**Comment by danielnaber** [comment]
I can confirm it's fixed, thanks.
