### ISSUE TITLE
lookAt callback

### ISSUE THREAD

**Issue by strarsis** [mpetroff/pannellum#330]
It would be great if lookAt also accepts a callback that is invoked when the animation finished.

**Comment by mpetroff** [comment]
I just added this in 1220065801db4a09dca8e1b39b1e6268084366d1.

**Comment by strarsis** [comment]
Thanks! Could this also be added to loadScene(...) when the fade-effect finished?
This would be also really helpful! There is the load event, it fires when the scene loaded, but not necessarily when the scene finished fading?

**Comment by mpetroff** [comment]
I justed added a `scenechangefadedone` event for this in 48408751867b02fa2a8a8405f508f01da8beb52c.
