### ISSUE TITLE
lookAt(...) without/with custom easing?

### ISSUE THREAD

**Issue by strarsis** [mpetroff/pannellum#331]
Current lookAt(...) uses an easing (ease), is there a way using a different easing (or linear for no easing)?
Edit: By easy swapping out the [timingFunction](https://github.com/mpetroff/pannellum/blob/1220065801db4a09dca8e1b39b1e6268084366d1/src/js/pannellum.js#L1224) per viewer or animation.

**Comment by mpetroff** [comment]
I added an `animationTimingFunction` parameter in ded506d22da02b3623f74dad52f4d763e9e07272 that allows the a custom timing function to be specified (this only works when the API is used).
