### ISSUE TITLE
"autoplay" option being ignored

### ISSUE THREAD

**Issue by alaughlin** [mpetroff/pannellum#332]
I'm trying to use `videojs` to play a panoramic video and autoplay is not working. Here's the important bits of code:

```
<link rel="stylesheet" href="https://cdn.pannellum.org/2.3/pannellum.css"/>
<script type="text/javascript" src="https://cdn.pannellum.org/2.3/pannellum.js"></script>
<link href="https://vjs.zencdn.net/5.8/video-js.css" rel="stylesheet">
<script src="https://vjs.zencdn.net/5.8/video.js"></script>
<script src="/assets/javascripts/thirdparty/videojs-pannellum-plugin.js"></script>
```

```
<video id="panorama" class="video-js vjs-default-skin vjs-big-play-centered"
  controls preload="none" style="width:100%;height:400px;"
  data-setup="{}" crossorigin="anonymous">
    <source src="foo.mp4" type="video/mp4"/>
    <p class="vjs-no-js">
        To view this video please enable JavaScript, and consider upgrading to a web browser that<a href="http://videojs.com/html5-video-support/" target="_blank">supports HTML5 video</a>
    </p>
</video>
```

```
<script>
    videojs('panorama', {
        loop: true,
        autoplay: true,
        plugins: {
            pannellum: {
            }
        }
    });
</script>
```

"loop" is working just fine, "autoplay" isn't. I still have to click play to get the video to load. Also, is there a way to use videojs's "clickAndDrag" option to disable click and drag and allow the viewer to follow the mouse cursor instead?

**Comment by mpetroff** [comment]
Try removing the `data-setup="{}"` part. I had never noticed it before, but apparently there's a race condition when that is specified and there's a separate initialization in JavaScript. Video.js tries to initialize itself on any video with a `data-setup` attribute&mdash;if the separate JavaScript executes first, everything works, but if the `data-setup` triggered initialization executes first, the JavaScript initialization isn't executed, so its options aren't applied.

I just updated the pannellum.org example to remove the `data-setup="{}"` part.

**Comment by mpetroff** [comment]
I have no idea what "clickAndDrag" option you're talking about. I can't find any reference to it in Video.js' documentation.

**Comment by alaughlin** [comment]
Ah, my bad. It's part of a plugin for videojs (https://github.com/yanwsh/videojs-panorama) and I got it mixed up with the videojs library itself
