### ISSUE TITLE
Preview showing first scene title

### ISSUE THREAD

**Issue by yogiderek** [mpetroff/pannellum#334]
In my test application I have the configuration (cut down version) as shown below. When the app starts, the preview page is displaying the title from the first scene which i think is incorrect. It is picking up the title from the default. Ideally what i would like would be a new configuration parameter, previewtitle, that would display a title for the preview page.

The other option that would be useful would be to have a parameter to change the titlle off the button (pnlm-load-button) i.e.  ``` "loadButton": "<p>Click to<br/>start<br/>tour</p>" ``` etc.

```javascript
pannellum.viewer('panorama', {
    "type": "equirectangular",
    "preview": "/images/streetview.png",
    "autoLoad": false,
    "default": {
        "firstScene": "Livingroom",
        "sceneFadeDuration": 2000
    },
    "scenes": {
        "Livingroom": {
            "title": "Livingroom",
        }
    }
});
```

**Comment by mpetroff** [comment]
I just added `loadButtonLabel`, `previewTitle`, and `previewAuthor` configuration options in 624c1c11244fc8ad3310a1315c944f94c915ef6e.

**Comment by yogiderek** [comment]
Thank you!
