### ISSUE TITLE
generate.py fails in certain conditions, but it really shouldn't

### ISSUE THREAD

**Issue by stevenbg** [mpetroff/pannellum#336]
In my setup I'm running generate.py via PHP's exec(). PHP is run by php-fpm which by default clears the environment variables for the worker processes and then doesn't set PATH.

In [generate.py you are using find_executable()](https://github.com/mpetroff/pannellum/blob/master/utils/multires/generate.py#L38) to look for the nona binary. That function throws an exception if PATH isn't found in the environment variables ([python bug 12420](https://bugs.python.org/issue12420)).

I'm getting:
> Traceback (most recent call last):
>   File "/home/steven/asd/src/vendor/pannellum/generate.py", line 38, in <module>
>     nona = find_executable('nona')
>   File "/usr/lib/python2.7/distutils/spawn.py", line 184, in find_executable
>     path = os.environ['PATH']
>   File "/usr/lib/python2.7/UserDict.py", line 23, in __getitem__
>     raise KeyError(key)
> KeyError: 'PATH'

I think you should catch that exception and assign nona = None. It is just a case of not finding the executable, which is be fine as long as the -n argument is supplied.

**Comment by mpetroff** [comment]
I just added handling for this exception in cd72d775b1385b1b308644f6950287e09fc81ee2.
