### ISSUE TITLE
"orientationOnByDefault":true sets pitch to -90 in Chrome and Opera on OSX

### ISSUE THREAD

**Issue by sief** [mpetroff/pannellum#337]
When setting the config parameter `"orientationOnByDefault":true` , the initial view in Chrome on OSX is always downwards.
Setting the pitch to 0 explicitly doesn't help.

Here is a testpage: https://s3-eu-west-1.amazonaws.com/test-playground/test.html

Reproducible in Chrome 56.0.2924.87 and Opera 42.0.2393.517 on OSX 10.11.6 

Safari and Firefox OK.
Chrome on Android works too, on devices with and without orientation support.

**Comment by mpetroff** [comment]
I believe I fixed this in 6178b1b41ca5801aa254345457517a2003911bd1; at least it now works properly in Chromium 55 on Linux (and didn't before).

Chrome advertises support for device orientation events even when they're not actually supported, so the event output needs to be checked to see if it makes sense; this was already being done to decide whether or not to display the device orientation button but wasn't being checked when `orientationOnByDefault` was set to true.

**Comment by joeyhagedorn** [comment]
Thanks for addressing this so swiftly! Are there any plans to tag a release with this fix included soon? I wanted to avoid building and deploying master just to deal with this issue. Thanks!

**Comment by mpetroff** [comment]
There's unlikely to be a release in the next few months.
