### ISSUE TITLE
The file could not be accessed

### ISSUE THREAD

**Issue by pegefounder** [mpetroff/pannellum#341]
Just changing from the no longer working PixAround solution to Pannellum.

My first test is at
http://politik.pege.org/2006-oekostrom-demo/parlament-panorama.htm

In the middle of the area for the panorama is a message

The file http://cgi.pege.org/pan/politik-parlament.jpg could not be accessed

But when I click on the link, the file opens well.
I checked this problem also with a modified pannellum.js,
where I added at the end of the message + f.status

The status was 0 instead of 200.

The problem is tested with Linux Ubuntu 16.04 and Google Chrome and Firefox

**Comment by mpetroff** [comment]
You seem to have gone through the effort of modifying `pannellum.js` without first looking at your browser's developer console; you have a [CORS](https://en.wikipedia.org/wiki/Cross-origin_resource_sharing) error:

`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://cgi.pege.org/pan/politik-parlament.jpg. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).`

**Comment by pegefounder** [comment]
On 2017-02-10 17:07, Matthew Petroff wrote:
>
> You seem to have gone through the effort of modifying |pannellum.js| 
> without first looking at your browser's developer console; you have a 
> CORS <https://en.wikipedia.org/wiki/Cross-origin_resource_sharing> error:
>
> |Cross-Origin Request Blocked: The Same Origin Policy disallows 
> reading the remote resource at 
> http://cgi.pege.org/pan/politik-parlament.jpg. (Reason: CORS header 
> ‘Access-Control-Allow-Origin’ missing).|
>

I did some reorganisation, panorama pictures now on d.pege.org

I implemented the CORS header in .htaccess of d.pege.org
Header set Access-Control-Allow-Origin: "*"

Testing with http://web-sniffer.net/ the Header is shown.
But still the same problem.

http://politik.pege.org/2006-oekostrom-demo/parlament-panorama.htm 
<http://politik.pege.org/2006-oekostrom-demo/parlament-panorama.htm>


best regards
-- 
<http://www.pege.org/>
Roland Mösl <mailto:founder@pege.org> - PEGE - Planetary Engineering 
Group Earth
Obmann Verein zur Förderung des Infinitismus <http://Paradigma.PEGE.org/>

Drachenlochstraße 1c/5
A-5083 Gartenau
+43 699 17343674 <tel:+43%20699%2017343674> Skype: roland.mosl

**Comment by mpetroff** [comment]
It loads for me.

**Comment by pegefounder** [comment]
On 2017-02-10 23:59, Matthew Petroff wrote:
>
> It loads for me.
>
Thank You,

it was a cache problem. F5 reload did not reload the jpg.

For unluck,
http://embed.plnkr.co/1E8ot9e1eVs23IrjzqKr/preview
had the same cache problem, stating always

ERROR fetching data, check CORS support


After deleting the browser cache, it loads.

Now on the work for all the rest of the parameters.

best regards
-- 
<http://www.pege.org/>
Roland Mösl <mailto:founder@pege.org> - PEGE - Planetary Engineering 
Group Earth
Obmann Verein zur Förderung des Infinitismus <http://Paradigma.PEGE.org/>

Drachenlochstraße 1c/5
A-5083 Gartenau
+43 699 17343674 <tel:+43%20699%2017343674> Skype: roland.mosl

**Comment by martinlombana** [comment]
If someone encounters this problem, while using nginx, the solution is to configure CORS, not only in your server-side (django, for instance) but also in your server.conf

Excerpt for a location inside your server, where you want to add CORS (works for sub-folders as well in that path).

```
	location /uploads/ {
		alias /srv/public/uploads/;

		if ($request_method = 'GET') {
			add_header 'Access-Control-Allow-Origin' '*';
			add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
			add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range';
			add_header 'Access-Control-Expose-Headers' 'Content-Length,Content-Range';
		}

	}

```

Best regards,

**Comment by avocadoras** [comment]
Is it normal to get this error when I'm importing from a local pannellum.js installation for testing?
