### ISSUE TITLE
Load button label not being set

### ISSUE THREAD

**Issue by mauricesnip** [mpetroff/pannellum#343]
First of all, thanks for such an amazing panorama viewer!

I've came across an issue when trying to set the load button label using the compiled and minified version of Pannellum 2.3.2. Setting it by config won't change its text.

**Simple test case**
```js
pannellum.viewer('panorama', {
    loadButtonLabel: 'New label here'
});
```

Though, when I include the source versions of libapannellum, rAF and pannellum, it works just fine.

This makes me wonder if more config options are affected by obfuscation. I'd say it worth testing!

**Comment by mpetroff** [comment]
That feature was just added, so it's not in the 2.3.2 release, which is why it doesn't work. For a list of parameters in the 2.3.2 release, look at the [corresponding version of the parameter documentation](https://github.com/mpetroff/pannellum/blob/2.3.2/doc/json-config-parameters.md).
