### ISSUE TITLE
Video played normal

### ISSUE THREAD

**Issue by diehummel** [mpetroff/pannellum#344]
Hi,

my video is played normal.
https://vr.hummel-web.at/pannellumx/index.html

It works on youtube upload and with Valiant360.

html file looks like.

```
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Pannellum Video Demo</title>
    <link rel="stylesheet" href="/pannellumx/pannellum.css"/>
    <script type="text/javascript" src="/pannellumx/pannellum.js"></script>

    <link href="https://vjs.zencdn.net/5.4.6/video-js.css" rel="stylesheet"
      type="text/css">
    <script src="https://vjs.zencdn.net/5.4.6/video.js"></script>
    <script src="/pannellumx/videojs-pannellum-plugin.js"></script>
</head>
<body>

<video id="panorama" class="video-js vjs-default-skin vjs-big-play-centered"
  controls preload="none" style="width:100%;height:400px;"
  poster="/overpass-clip.jpg" data-setup="{}">
    <source src="/overpass-clip.mp4" type="video/mp4"/>
    <p class="vjs-no-js">
        To view this video please enable JavaScript, and consider upgrading to
        a web browser that <a href="http://videojs.com/html5-video-support/"
        target="_blank">supports HTML5 video</a>
    </p>
</video>

<script>
videojs('panorama', {
    plugins: {
        pannellum: {}
    }
});
</script>

</body>
</html>
```

thanks
br

**Comment by mpetroff** [comment]
You're using the non-minified version (this isn't recommended); when doing so, `libpannellum.js` also needs to be included. Hence the `ReferenceError: libpannellum is not defined` error in the browser's developer console.

**Comment by diehummel** [comment]
oh.. non minified.. i downloaded it from here. i haven't read about minified version :-O
where do i get this?
With libpannellum its working now :) thank you !!! :+1:

**Comment by mpetroff** [comment]
On the GitHub downloads page, you need to select the `pannellum-x.y.z.zip` file instead of the source code download. Here's the latest release: https://github.com/mpetroff/pannellum/releases/download/2.3.2/pannellum-2.3.2.zip
