### ISSUE TITLE
Password protected panorama

### ISSUE THREAD

**Issue by maciek252** [mpetroff/pannellum#346]
Thanks for the excellent code, works really great!

Is it possible to protect a panorama with a password? I've managed to protect a page containing the pannellum script, but how to protect the panorama image?

**Comment by maciek252** [comment]
Easy to do: put a .htaccess file in the directory with the panorama and script files:

AuthUserFile /path/to/.htpasswd
AuthName "Please Log In"
AuthType Basic

require user pano

**Comment by hostage131077** [comment]
Unfortunately htaccess doesn't work well on ios devices in combination with safari (you have to enter username/password for every picture).

Is there a change to use something else to protect an panorama?
