### ISSUE TITLE
playback video on iphone not in 360 mode

### ISSUE THREAD

**Issue by diehummel** [mpetroff/pannellum#347]
Hello,

the playback of a video is not shown as a 360 degree video. its played back as normal 2D.

is there something i can do to make it playable on iphone?

thanks
br

**Comment by mpetroff** [comment]
This is a duplicate of #232. In theory it might be possible on iOS 10, but I haven't been able to get it to work. It's definitely not possible on older versions.

**Comment by diehummel** [comment]
ok thanks. i have latest os version and still not working. But i can use one of the vr player apps also. br
