### ISSUE TITLE
Click event not working in IE10

### ISSUE THREAD

**Issue by Dt-Sodium** [mpetroff/pannellum#350]
Hello,

Using IE11 in IE10 compatibility mode, i am unable to navigate in the 360 view.

Replacing line 411 
dragFix.addEventListener('mousedown', onDocumentMouseDown, false);
with
container.addEventListener('mousedown', onDocumentMouseDown, false);
seems to fix the problem, but i guess this is not a good solution.

**Comment by mpetroff** [comment]
It used to be like that, but I changed it in 3e99ecbb397a8992f00eb7bef0b0648706c34c8d to fix a different bug (changing it back would break things). As IE10 isn't a supported browser, I'm not going to try to fix this, but I would be happy to apply a patch if it doesn't cause other issues.
