### ISSUE TITLE
Viewer not loading, no errors

### ISSUE THREAD

**Issue by dmhwtn** [mpetroff/pannellum#351]
Hey Matthew,

I've managed to break the viewer and I can't work out why it's not displaying. I'm not getting any errors and my lack of experience has left me doing a lot of head scratching. Any advice would be appreciated.

Here's the live page:

https://www.shadowvisuals.com/timberland_flooring.html

**Comment by mpetroff** [comment]
The viewer height is zero. Your stylesheet sets the panorama `div` height to 40%, but the parent element doesn't have a height set, so 40% of zero is zero. You'll need to either give the `div` a fixed height or give the parent element a height.

**Comment by dmhwtn** [comment]
That was it. Thanks, much appreciated.
