### ISSUE TITLE
Change HTML title parameter of pannellum.htm

### ISSUE THREAD

**Issue by posfan12** [mpetroff/pannellum#352]
I am using the JSON API.

Example:

http://isometricland.net/panorama/pannellum.htm?config=pano-lego-carriagehouse.json

How do I change the HTML TITLE parameter that appears in the browser title bar dynamically? The TITLE parameter seems hardcoded as "pannellum".

Thanks.

**Comment by mpetroff** [comment]
You're using an outdated release. Starting with version 2.3, the document title tag, what appears in the browser's title bar, is set to match the panorama's title parameter.

**Comment by posfan12** [comment]
I installed version 2.3.2 but I see no difference. Could you check again please?

http://isometricland.net/panorama/pannellum.htm?config=pano-lego-carriagehouse.json

**Comment by mpetroff** [comment]
It only looks for the parameter in the top level of the JSON or as a URL parameter. This works:
http://isometricland.net/panorama/pannellum.htm?config=pano-lego-carriagehouse.json&title=Front%20Exterior

**Comment by posfan12** [comment]
Is the following not considered the top level of the json file?

```
{   
	"default":
	{
		"firstScene": "front",
		"title": "Carriage House",
		"author": "Some One",
		"sceneFadeDuration": 1000
	}
}
```

**Comment by mpetroff** [comment]
This is top level:
```javascript
{
  "title": "Some Title"
}
```

The standalone version is a simple page that parses URL parameters and then constructs a viewer using the API. The part that sets the page title is just in the standalone version, so it doesn't use the full configuration parser; it just looks for a top level `title` parameter.

**Comment by posfan12** [comment]
It works! Thank you.
