### ISSUE TITLE
Minimap

### ISSUE THREAD

**Issue by posfan12** [mpetroff/pannellum#353]
I would like to have a small area of the screen reserved for a miniature map of the area being rendered. For instance an overhead map of a building with several rooms in it. This picture should be locked in the same place on the user's screen even if they rotate the camera around in different directions. It would be great if you could add such functionality. Thanks!

**Comment by mpetroff** [comment]
Something like this can be built using the API. Since everyone seems to have his or her own opinion on what a scene map should entail, I don't plan on ever including this (at some point I might make an example, though).

**Comment by posfan12** [comment]
Well, I meant originally that there could be a static bitmap in the corner of the screen showing a map of the area. But you are right. It is more complicated than that. The map would have to rotate with your camera or risk getting users lost.
