### ISSUE TITLE
Modal Window on clicking Hotspot

### ISSUE THREAD

**Issue by vilav** [mpetroff/pannellum#354]
Hi there

Just getting started with Pannellum. Is there a way to launch a modal window inside the panorama view? The idea is to have hotspots and on clicking the hotspots to launch a modal box window inside the view as an overlay on top of the panorama view. Any tips / examples of how to accomplish this?

Thanks

**Comment by mpetroff** [comment]
You can use the API, specifically the `clickHandlerFunc` and `clickHandlerArgs` hot spot parameters. You can then write a JavaScript function that opens your modal window and use the `clickHandlerFunc` parameter to assign it to a hot spot (the `clickHandlerArgs` parameter can be used to specify arguments to pass to this function, such as for assigning content to the modal window). There's currently no example on using these parameters, but the [custom hot spots example](https://pannellum.org/documentation/examples/custom-hot-spots/) is similar, except it uses the `createTooltipFunc` and `createTooltipArgs` parameters instead.
