### ISSUE TITLE
Stopping autoRotate after clicking a button?

### ISSUE THREAD

**Issue by Mvotre** [mpetroff/pannellum#355]
I got this scenario (can put some link if needed) :

- pannellum working nice, with hotspots wich link to site sections
- autoRotate, wich starts after 6000ms 
- a button, wich return the panorama to starting position, with code like this:

document.getElementById('pan-up').addEventListener('click', function(e) {
    viewer.setPitch(0);
    viewer.setYaw(0);
});

works as expected. If the panorama is already autorotating, and I click anywhere on the page, it stops for the time I set in autoRotateInactivityDelay. BUT, if I click on said return button with the rotating in action, it will return to 0 position and immediately start rotating again, as if I never clicked on screen. I even tried to attach a trigger action on the code above, to try to emulate a click on the main screen, but it doesn't work :(

since I read that Pannellum won't check for yaw and pitch every time, is there any way I can work around this issue? I already got a option B in plan, but would like to know if it's possible to do with what I got now. Thanks in advance.

**Comment by mpetroff** [comment]
Have you tried the `stopAutoRotate()` function?

**Comment by Mvotre** [comment]
but if I use this (not shown on the configuration options in Pannellum site), would it stop the rotation but also start it back after 6000ms without user interaction as usual? I just need the autorotate to be turned off for a brief time. 

PS: thanks for the plugin and the fast answers :D

**Comment by Mvotre** [comment]
worked! Like this:

document.getElementById('pan-up').addEventListener('click', function(e) {
    viewer.setPitch(0);
    viewer.setYaw(0);
    viewer.stopAutoRotate();
    setTimeout(
            function() {
                viewer.startAutoRotate();
            },
            6000);
});

if I can make it work with a nicer solution, please show. But it works. You can close this issue :D
