### ISSUE TITLE
More events

### ISSUE THREAD

**Issue by ajorquera** [mpetroff/pannellum#356]
Hello, thanks for letting us using pannellum. It has been great in the time I've been working on it. I was wondering if I could listen to other events that are not listed in the API. At the moment I'm using mousedown to trigger some functionality when the user clicks in the panorama but when you are on mobile there is no event to listen to in case the user touches the screen. I tried to add a touchstart listener to the dom but I cant get the pitch and yaw from this event. Any ideas or advice? Thanks

**Comment by mpetroff** [comment]
I just added `touchstart` and `touchend` events in 1e61a22be633a5c297fceaa89fd81b969977a097.

To convert a `TouchEvent` to pitch and yaw, you'll need to get a [`Touch`](https://developer.mozilla.org/en-US/docs/Web/API/Touch) object from the [`TouchEvent`](https://developer.mozilla.org/en-US/docs/Web/API/TouchEvent)'s [`targetTouches`](https://developer.mozilla.org/en-US/docs/Web/API/TouchEvent/targetTouches) property. A `TouchEvent`, like a `MouseEvent` event, can be passed to Pannellum's `mouseEventToCoords` function to convert it to pitch and yaw.

**Comment by ajorquera** [comment]
jeje well that was quick. Thanks. I hope that in some point I can contribute to this project. Ill close this issue
