### ISSUE TITLE
MSIE9 doesn't give error message

### ISSUE THREAD

**Issue by danielnaber** [mpetroff/pannellum#36]
I know IE9 isn't supported, but it would be great if it displayed an error message plus fallback link (e.g. the IE10 I tried says that WebGL support is missing). Instead it's just stuck on the "Loading" screen. If you need a browser to test it, Open Source projects get free access to SauceLabs where you can select any browser/OS (https://saucelabs.com/opensauce).

**Comment by mpetroff** [comment]
I added in a specific check since IE 9 fails without throwing any JavaScript errors. Earlier versions of IE are just hopeless. I already had a Sauce Labs account but only test using it when specific bugs are reported since it's a bit of a pain due to the lag and poor framerate.
