### ISSUE TITLE
 deviceorientation event  have a small bug

### ISSUE THREAD

**Issue by lightsocks** [mpetroff/pannellum#363]
When I close the screen horizontal of the phone ,  start the  device orientation by click the button and  put the phone in horizontal position  ,the image  begin to shake. I think there is  some bug of the
 orientation Listener implements.

**Comment by mpetroff** [comment]
What device, OS version, and browser are you using?

What do you mean by "When I close the screen horizontal of the phone"? Are you locking the display in portrait orientation?

**Comment by lightsocks** [comment]
Samsung Galaxy S7  ,Android 6.0  ,the default Browser.  Other devices have the same problem.
Yes ,locking the display  in portrait orientation.

**Comment by mpetroff** [comment]
It's gimbal lock from the use of Euler angles. As changing this would require substantial work to fix an edge case on mobile devices, which aren't even the primary platform, I don't plan on doing so.

**Comment by lightsocks** [comment]
I think mobile platform it's more important  than PC

**Comment by mpetroff** [comment]
Good for you. I have very little interest in developing for, and do no web browsing on, mobile devices.
