### ISSUE TITLE
Is there in pannellum an effect stereo?

### ISSUE THREAD

**Issue by jogerq** [mpetroff/pannellum#365]
First off, excelent job with pannellum. Congratulations!

I would like to know if pannellum can do the effects stereo like threejs does in https://threejs.org/examples/#webgl_effects_stereo. I look in the documentation but I can't find something like effects stereo

Thank you!

**Comment by mpetroff** [comment]
No, it can't.

**Comment by risonsimon** [comment]
@mpetroff Can you perhaps write a doc on how to use custom shaders with Pannellum? It would be tremendously useful and anyone can extend Pannellum. What do you think?

**Comment by mpetroff** [comment]
Using custom shaders involves editing the internals, so it's not supported by the API (and probably never will be). If you want to write a custom shader, take a look at `libpannellum.js`. The code is fairly well commented; I don't know what you had in mind.

**Comment by risonsimon** [comment]
That is what I was looking for. I didn't expect pannellum to have API for it. 👍
