### ISSUE TITLE
Floorplan in Hotspot-Tour 

### ISSUE THREAD

**Issue by IHaveNoIdeaWhatIAmDoingHere** [mpetroff/pannellum#367]
Hello,

disclaimer: I have very little programming or scripting experience, I use github for the first time, also I am german, please tell me if am doing something fundamentaly wrong. Thank you ;-)

I  am figuring out a way to attach floorplans to every scene in a tour via the tour.json file.

I came as far as creating a new variable "floorplan" which will be used like the variable "author" or "title"
`   "scenes": {
        "flur": {
            "title": "Flur",
			"author": "007",
		    "floorplan": "Floorplan.jpg",
			"panorama": "5_Flur.jpg",
            "hotSpots": [
                {
                    "pitch": -1,
                    "yaw": -73,`

I also modified the  pannellum.js to accept this variable and show it in the title/author-Display.
The Floorplan.jpg is in the same folder as all the panoramas. 
My problem is, that I have no idea how to create a relative path to this Floorplan.jpg.
Right now, when I use the code below, it tries to load the Flloorplan.jpg from the same directory as the pannellum.js.
So what I need is the Code to load the Floorplan.jpg from the same directory as the panoramas. 

`	case 'floorplan':
                //MSCHANGE
				infoDisplay.floorplan.innerHTML = '<br>'+escapeHTML(config[key])+'<br><img src="'+escapeHTML(config[key])+'" alt="Grundriss" style="width:300px;">';                
				infoDisplay.container.style.display = 'inline';
                break;`

Thank you all for your help,
Martin

**Comment by mpetroff** [comment]
Have you taken a look at `config.basePath`?

**Comment by IHaveNoIdeaWhatIAmDoingHere** [comment]
you Rock! 
Awsome, that was the pointer I needed! 
Thank you so much, it works! I am very happy right now! 

Thanks!
