### ISSUE TITLE
Movements are not smooth on chrome 56.0.2924 (Android)

### ISSUE THREAD

**Issue by ashraffayad** [mpetroff/pannellum#370]
Great work. 

I've created a small video that displays this issue.
https://youtu.be/aUyjm5cvrKw

tested on: 
chrome 56.0.2924
    Samsung Galaxy S7 Edge
    Android 7.0.0
and
chrome 56.0.2924
    Samsung Galaxy Tab S
    Android 5.0.2

**Comment by mpetroff** [comment]
Mobile device performance issues tend to be device dependent and are extremely difficult to track down an fix. See #56.
