### ISSUE TITLE
Get a reference to pannellum when using video

### ISSUE THREAD

**Issue by immersive** [mpetroff/pannellum#371]
okay when using an image

```
pano = pannellum.viewer('panorama', _this.data);

video = videojs("panorama_vid", {
                sources: [
                  {
                    src: path,
                    type: type
                  }
                ],
                type: type,
                loop: true,
                autoplay: true,
                plugins: {
                  pannellum: _this.data
                }
```

pano = ????

**Comment by mpetroff** [comment]
I just changed the Video.js plugin in e0a108a50440ccbe095e46551657a13ee682280f to allow this. With the new version, you should be access the Pannellum instance using `video.pnlmViewer`.

**Comment by immersive** [comment]
Many thanks for your help. I do however now receive an error from video.js

VIDEOJS: ERROR: ReferenceError: libpannellum is not defined

video-js 5.4.6

if I reference video.js first and 

Uncaught ReferenceError: videojs is not defined
    at videojs-pannellum-plugin.js:53

If I reference the plugin first,

I was also unable to get the plugin to work with requirejs

**Comment by immersive** [comment]
Wait my mistake needed to reference libpannellum.js, idiot !

Thanks again for your help and sharing this project.

**Comment by Tetrakern** [comment]
When I try exactly this (everything is updated), I still get undefined. [Test page](http://infinitynet.de/lnu/test_1.htm).

**Comment by mpetroff** [comment]
You don't have everything updated. Your `videojs-pannellum-plugin.js` file is out-of-date, which is why it doesn't work.

**Comment by Tetrakern** [comment]
Thank you for the hint. After some very confusing minutes since I completely wiped the old version before, I noticed that I linked to an old file I had in the parent directory. Heh. Crap. That's how I waste my life...
