### ISSUE TITLE
Is Video 360 in iOS possible?

### ISSUE THREAD

**Issue by emaglic** [mpetroff/pannellum#373]
I Cannot get 360 video working on iOS in Safari (360 photos work fine). I have tried iOS (10.2 and 10.3)

I keep getting this error... 
“Your browser does not have the necessary WebGL support to display this panorama"

Even the Pannellum example video page https://pannellum.org/documentation/examples/video/ will not work for me. 

Has anyone gotten video 360 working on iOS with Pannellum or is there some compatibility issue because of iOS / Safari making it impossible to get working?

Thanks!

**Comment by mpetroff** [comment]
WebGL+video doesn't really work on iOS. See #232 and #347.

**Comment by aproni34f** [comment]
With new ios 16.4 its still the same error as above “Your browser does not have the necessary WebGL support to display this panorama" on your demo:  https://pannellum.org/documentation/examples/video/


But if I try like this, then this works on ios. (of course this doenst provide video controls like videojs can and support for other formats like hls) but what is the reason that this works and not your demo?


    `<div id="panorama_viewer"></div>

    <video id="panorama" preload="auto" loop muted autoplay crossorigin="anonymous" controls>
        <source src="03.mp4" type="video/mp4"/>
    </video>


    var video = document.getElementById("panorama");

    video.addEventListener('loadedmetadata', function() {
  
         video_viewer = pannellum.viewer('panorama_viewer', {
              "type": "equirectangular",
              "panorama": video,
              "dynamic": true,
              "dynamicUpdate": true,
              "autoLoad": true,
          })

    });`
