### ISSUE TITLE
need Information message like Bullets in Hotspot

### ISSUE THREAD

**Issue by pvvsridhar** [mpetroff/pannellum#378]
Hi all,

I have a requirement like below. In hotspots i am showing information message, but i need requirement like Bullets some points.  so i had used '\n\u2022' for bullets in my JSON file. but when displaying its displaying normal message. in element it's displaying as bullets. i have uploaded image below. can you please suggest here. thanks in advance.
![pnlm](https://cloud.githubusercontent.com/assets/27331965/24942901/7ecb9dee-1f71-11e7-9961-20df63818455.png)

**Comment by pvvsridhar** [comment]
above message in image, is it possible to display like this below?

Reception desk is your first point of contact. Do not forget to carry your essential documents like
•	ID/passport
•	Driver’s license
•	Photo
•	Residence permit
Also don’t forget to carry your great attitude!

**Comment by mpetroff** [comment]
This was a bug, which was fixed in ab3c3d9fe09da7b28dbf0f1997b33d8b3b7c7bb6. Before the fix, only the first line break would work. The fix hasn't made it into a release yet.

**Comment by pvvsridhar** [comment]
Thanks mpetroff...

when can i expect this release?

**Comment by mpetroff** [comment]
The next release will happen when it's ready.

**Comment by pvvsridhar** [comment]
Hi mpetroff,
Please let me know if it's released.
Thanks

**Comment by pvvsridhar** [comment]
Hi mpetroff,

is there any solution for this? can you please suggest me to get this?

Thanks in advance..
