### ISSUE TITLE
Adding attributes with script?

### ISSUE THREAD

**Issue by BetaStacks** [mpetroff/pannellum#379]
Hello, I am developing a pannellum addon for RapidWeaver and Stacks 3 users. Is it possible to dynamically add scenes and/or hotspots to the viewer using script? 

This would allow users to add a 'stack' to the page, edit the settings, and have a new scene or hotspot appear in their published project.

**Comment by mpetroff** [comment]
Yes, there is. Take a look at the `addScene` and `addHotSpot` methods.
