### ISSUE TITLE
Additional Mobile Controls

### ISSUE THREAD

**Issue by cometta** [mpetroff/pannellum#38]
on mobile screen, is it possible to add up, left, right ,down button (like google map) and disable dragging using touch ?  Currently, when embedded on a page, the page unable to scroll.

**Comment by video-internal** [comment]
Can this be done for browsers also? In addition of mouse control, navigational button can also be used. Is it possible to do and if yes, how?

**Comment by transpirman** [comment]
Hi, pannellum is really great !!
I would love to see direct support of gyroscope/accelerometers on mobile too.

I read about some tests with gyro.js in issue #82
but I think looking at the javascript code supporting the Bubb.li app for iPhone could be interesting: http://sdk.bubb.li/
It lacks a lot of features of Pannellum but it is designed for mobile and it is fast !

**Comment by selko** [comment]
this bubb.li lib seems better than gyro.js

**Comment by Cyrille37** [comment]
There is a "Device orientation API" pull request #131

**Comment by FrancoMeriles** [comment]
so that means it is impossible to implement the gyroscope in panellum ?

**Comment by mpetroff** [comment]
It just means something else needed to be implemented first.

**Comment by mpetroff** [comment]
Custom controls can now be added using the API. See #168 for an example.
