### ISSUE TITLE
Is there hotspot option to change scene's initial yaw and pitch?

### ISSUE THREAD

**Issue by marinkiss** [mpetroff/pannellum#380]
I wonder if there is a way to set yaw and pitch of a hotspot object so that the scene is loaded with these yaw and pitch, and not with the initial ones?

I need this mainly for my Go back hotspots where the scene should be rotated 180 degrees from the initial point of view, so that the user is facing the exit. and not the entrance when going back.

**Comment by mpetroff** [comment]
There are `targetPitch`, `targetYaw`, and `targetHfov` hot spot parameters that set the starting pitch, yaw, and HFOV of the target scene, respectively. See the [configuration reference](https://pannellum.org/documentation/reference/).
