### ISSUE TITLE
Is it possible to prevent scene loading by writing code in scenechange event?

### ISSUE THREAD

**Issue by abhijitdamle** [mpetroff/pannellum#383]

**Comment by mpetroff** [comment]
Take a look at the `clickHandlerFunc` and `clickHandlerArgs` parameters, which allow you to set a custom click handler for hot spots. Set the hot spot type to `info` instead of `scene`.

**Comment by abhijitdamle** [comment]
Setting hot spot type to info instead of scene didn't prevent navigation to that screen after hot spot is clicked. I have used clickHandlerFunc and added a handler but Don't know how to prevent default action on click of hot spot which at the moment is to navigate to another scene which still happens even after changing hot spot type to info

**Comment by mpetroff** [comment]
Don't include a `sceneId`; there won't be a default click handler then.

**Comment by abhijitdamle** [comment]
Thanks it works then
