### ISSUE TITLE
Maintaining pitch/yaw across scenes on hotspots

### ISSUE THREAD

**Issue by dotjsprogrammer** [mpetroff/pannellum#384]
Is this possible? I have all panoramas set in a specific orientation and I'd like to preserve the pitch/yaw so that the "camera" orientation is preserved across scenes (ie always facing the same direction) when transitioning to a different scene.
I was able to do it using the loadScene() function (I would grab the current pitch/yaw and pass it to this function) but I couldn't get the Hotspots to do the same thing.
Thanks!

**Comment by mpetroff** [comment]
Set the hot spot's `targetPitch` and `targetYaw` parameters to `"same"`. For more details see the [configuration reference](https://pannellum.org/documentation/reference/).

**Comment by mpetroff** [comment]
Closing due to lack of response.
