### ISSUE TITLE
How do I get hotSpotId

### ISSUE THREAD

**Issue by abhijitdamle** [mpetroff/pannellum#385]
removeHotSpot takes hotSpotId as input parameter. How do I obtain an Id of an hotspot? Is an id of a hotspot its index in array viewer.getConfig().hotSpots?

**Comment by mpetroff** [comment]
It's a property you assign the hot spot in your configuration, e.g.
```json
"hotSpots": [
    {
        "pitch": -9.4,
        "yaw": 222.6,
        "type": "info",
        "text": "Some hot spot",
        "id": "someHotSpotId"
    }
]
```
