### ISSUE TITLE
addHotspot(..) does not really add hotspot to scene - just temporary

### ISSUE THREAD

**Issue by DanielBiegler** [mpetroff/pannellum#387]
Hey @mpetroff !

I'm not sure if I'm missing something or pannellum doesn't do what it's told to. If you could check it out, that would be great.

I'm using the `.addHotspot` function to add hotspots of type "info" to the viewer `v`. 

`v.addHotSpot({"pitch":currentPitch, "yaw":currentYaw, "type":"info", "text":infoText});`

or 

`v.addHotSpot({"pitch":currentPitch, "yaw":currentYaw, "type":"info", "text":inputText}, v.getScene());`

This works. I'm seeing them and they stay put. 

But now when I call `.loadScene` on the scene where the hotspots were added, they disappear. 

I checked out `v.getConfig()["scenes"]` and saw that `.addHotSpot` does **not** add the needed `"hotSpots"` entry to the current scene. That explains why they don't show up when you `.loadScene` - but why doesnt `.addHotSpot` add them in the first place?

**1. Is this behaving like it should? 
2. Am I missing something? 
3. How do I make them persistent?** 

Do I have to manually add those entries? With something like this _(not tested yet, just figured. I know this just changes the returned object and not the current config)_:

`v.getConfig()["scenes"][v.getScene()]["hotSpots"] = [{"pitch":currentPitch, "yaw":currentYaw, "type":"info", "text":inputText}]` ?

**But I thought `.addHotSpot` will do that for me?**

Best regards, much love!
Daniel Biegler.

**edit: I'm using the latest version: 2.3.2**

**Comment by mpetroff** [comment]
The behavior you're expecting is the intended behavior, so I'm not sure why the hot spots aren't persisting for you. What browser are you using? It works fine for me in Firefox 53 and Chromium 57 on Linux Mint.

**Comment by DanielBiegler** [comment]
# I got it.
#### I was in the middle of writing my process down and I tested one specific scenario and it works now. I'll keep the not-working approach in this comment so others can see. 

### How to make it work:
You **have to** include this field **`"hotSpots"`** when you call **`.addScene`** like so:

`yourViewer.addScene("yourSceneName", {"panorama": "/path/to/img/img.jpg", "hotSpots":[]});`

If you dont include that, **`addHotSpot`** does NOT work. Now the newly created hotspots are persistent and work like they should.

**I didn't really dive into the source code yet so I'll just ask, should pannellum include a check for this scenario and if needed create the "hotSpots" field?**
___
## How it DOESNT work:
**Google Chrome Version 57.0.2987.133 (64-bit) on Ubuntu
Firefox Version 52.0.2 (64-bit) on Ubuntu**

Both dont work for me. Mhh if it works for you, I guess I'll try to be more specific in what I do exactly:

First I create a new viewer:

```
v = pannellum.viewer('panorama', {
            "default": {
                "firstScene": "default_scene_start",
                "title": "default_title",
                "author": "default_author",
                "sceneFadeDuration": 1000,
                "hotSpotDebug": true,
                "autoLoad": true,
                "compass": false
            },
            "scenes": {
                "default_scene_start": {
                    "title": "default_title",
                    "hfov": 120,
                    "pitch": -3,
                    "yaw": 117,
                    "type": "equirectangular",
                    "panorama": "img/" + this.files[0].name
                }
            }
        });
```
Now that he viewer `v` is initialized and displaying the first picture I add more scenes with this:

```
for (var i = 1; i < this.files.length; ++i) {
            var inFile = this.files[i];
            v.addScene(inFile.name, {"panorama": "img/" + inFile.name});
        }
```
This also works, I checked the config and the scenes get added and I can `.loadScene` them.

So now that I have multiple working scenes I want to do `.addHotSpot` with this:

```
$('body').on('click', '.btn-add-hotspot', function() {
        var inputText = "example hotspot text";
        var currentPitch = v.getPitch();
        var currentYaw = v.getYaw();
        v.addHotSpot({"pitch":currentPitch, "yaw":currentYaw, "type":"info", "text":inputText});
    });
```

Now the newly created hotspot is visible and it stays where it should when I rotate. Text also works correctly. But now, like I said, the hotspot is **not** inside the scene where it should be.

**Comment by mpetroff** [comment]
When there's a hot spots list in the scene's configuration, the hot spots array that's used for displaying the current scene is linked to the corresponding array in the overall configuration, so hot spots added to the current scene are also added to the overall configuration. When the array doesn't exist in the configuration, an empty array is created and used for the displaying the current scene, so added hot spots didn't make it back to the overall configuration. I just changed things in 8ae14374d838add318af8ab833b0796f0f15bf32 to add a hot spots array to the overall configuration when adding hot spots if it doesn't already exist, which should fix the problem; it also allows hot spots to be added to a not loaded scene without an existing hot spot configuration, which didn't work before.

My testing yesterday was with a configuration that already had hot spots, which is why I didn't see the issue before.

**Comment by DanielBiegler** [comment]
Awesome, glad to help. 

Also, thanks for the quick fix!
