### ISSUE TITLE
Destroy video

### ISSUE THREAD

**Issue by bite-your-idols** [mpetroff/pannellum#389]
I am loading a 360 video like this:

```
function videoPanorama(){
  videoPano=videojs('video-panorama', {
      loop: true,
      autoplay: true,
      plugins: {
          pannellum: { }
      }
  });
};

videoPanorama();
```

But I need to delete the video in some time, so I am trying with this script:
`videoPano.dispose()`

but I am getting this error:

> pannellum.js:25 WebGL: INVALID_VALUE: texImage2D: no video

So I wonder what is the proper way to delete pannellum when it is acting as a videojs plugin

**Comment by mpetroff** [comment]
You need to destroy the Pannellum instance first with `videoPano.pnlmViewer.destroy()`.

**Comment by bite-your-idols** [comment]
that works! 
thanks

**Comment by leonbaichi** [comment]
i got the same question!!
use the code 
`var v1 = videojs('pan1', {
        loop: true,
        plugins: {
            pannellum: {
            	"hfov": 120
            }
        }
    });`
i want to use the api 'toggleFunction', 
but i use
 `   v1.pnlmViewer.toggleFullscreen();
                	    				
     v1.pannellum.toggleFullscreen();
                 	    					
     v1.pnlm.toggleFullscreen();

     v1.pnlmViewer.toggleFullscreen(); `

all don't work! can the console output below

`Cannot read property 'toggleFullscreen' of undefined`

what‘s the right code to make the right reference。。。。need help!
