### ISSUE TITLE
videos height:100%  video is not shown 

### ISSUE THREAD

**Issue by arpu** [mpetroff/pannellum#390]
https://h5dash.vreen.live/index-videojs-360.html?mpd=//h5dash.vreen.live/chunks/f97321e0-bdb7-476a-add8-c5315c86eb2d.mpd

if i remove the height:100% i se ethe video but height is not on full page

**Comment by mpetroff** [comment]
This isn't an issue with Pannellum; it's an issue with your CSS. If you specify the height to be 100%, it's 100% of the height of the parent element, which is 0px tall in this case. You need to specify a height on the parent element if you want to do this.

**Comment by arpu** [comment]
ok thx a lot for this help 
so i think you mean i should add 100% height for the div with id fixures?  in the sample from me

**Comment by mpetroff** [comment]
Yes, as well as its parent elements, `body` and `html`.

**Comment by arpu** [comment]
thx a lot works fine now!
