### ISSUE TITLE
Installing Nona and using 'generate.py' with Pillow

### ISSUE THREAD

**Issue by rlingineni** [mpetroff/pannellum#391]
Not sure if I am doing this correctly. I am trying to use `generate.py` and get started using the examples. I have done a `pip install Pillow`, however, I do not know if `nona` has been installed. 

Running `generate.py alma.jpg` does not work because it says I do not have `nona` installed. 

Hugin seemed like a longer installation process. Is there any additional steps I have to do to use pillow and `generate.py`?

**Comment by mpetroff** [comment]
Since you don't get an import error, you have Pillow working correctly. As for `nona`, it needs to either be on your path (in which case you can call `nona` from a terminal window), or you need to specify the path to the `nona` executable with the `-n` flag.

**Comment by rlingineni** [comment]
yup, tried looking for that, but I don't think I see it. I assume it's not available globally? `which nona` does not work either. I do have Pillow in my python modules however.

I went to the module folder for Pillow, but I didn't see it in there either. Is there an intermediate step I'm missing.

**Comment by mpetroff** [comment]
`nona` is part of Hugin, not Pillow. You need to look where you installed Hugin.

**Comment by rlingineni** [comment]
Ah ok. I didn't get Hugin. Was a little confused with the docs:

> which is available as part of Hugin, as well as Python with the Pillow package.

So I thought it was either/or. I'll try getting up and running with Hugin. Thank You

**Comment by rlingineni** [comment]
Perfect it worked! Thank You. I'm running on MacOS For the next user who might need help with this:

1.) Get [Hugin](http://hugin.sourceforge.net/download/)
2.) Get the DMG and Move it to Applications
3.) You can find the `nona` package as part of the `HuginStitchProject`, right click and open package contents: the path is here `/Applications/Hugin/HuginStitchProject.app/Contents/MacOS/nona`
4.) run with `python generate.py -n /Applications/Hugin/HuginStitchProject.app/Contents/MacOS/nona <img_name>`

**Comment by hamuslee** [comment]
@rlingineni  Thanks for posting the steps, it is extremely helpful!

**Comment by chrysllercs** [comment]
The `Hugin` program for `Windows` uses `nona` as and an .exe extension when I try to run:
`python generate.py C: \Program Files\Hugin\bin\nona.exe  01.jpg`

erro

`generate.py: error: argument -n/--nona is required`

Or do you have multires panoramas on `Windows`?

**Comment by mpetroff** [comment]
The error is self-explanatory; you need to specify the path to `nona.exe` using the `-n` flag, which you aren't providing, e.g. `python generate.py -n C:\Program Files\Hugin\bin\nona.exe 01.jpg`.

**Comment by chrysllercs** [comment]
Get more, which is a copy of a bin folder from the `Hugin` program into the folder where the file is the image and generate.py getting like this

`python generate.py -n bin/nona.exe 01.jpg`

Everything went well, take the space here to thank for the excellent work @mpetroff

**Comment by jxsl13** [comment]
This should be added to the documentation.
