### ISSUE TITLE
Jump to specific scene in tour

### ISSUE THREAD

**Issue by SaschaV313** [mpetroff/pannellum#392]
When I generate a tour it starts always with the firstscene.
Now I have made a tour from a fair boot consisting of 15 panoramas. On the webpage, where I show the tour, there will also be an overview picture of the booth with markers from where the panoramas where shot. I would like to use this overview as an image map and give the user the possibility to jump to a specific scene in the tour by clicking a marker on the image map.
Is that possible in an easy way, or do I have to make 14 copies of the json file used with different firstscenes?

**Comment by mpetroff** [comment]
Use the `loadScene` method of the API.

**Comment by DanielBiegler** [comment]
If you view your overview-image inside pannellum, another option would be to use hotspots. Use the [**`.addHotSpot`**](https://pannellum.org/documentation/api/#addhotspot) function, but beware of #387 !
