### ISSUE TITLE
Possible to do simple zooming/panning?

### ISSUE THREAD

**Issue by chconnor** [mpetroff/pannellum#396]
Hi -- I have a semi-giant image (500 MP) and I was looking for a solution to show it on the web with zooming, panning, etc. Pannellum seems to have all the features I need, but it's not clear to me from skimming through the website if it can do something as simple as I describe.

Meaning: I don't want any three-dimensional projection/distortion/rotation, just a simple ability to scroll around in a 2D image, zoom deep in to it, etc.

And if Pannellum can't do this, I would welcome any tips for something that can.

Thanks!

Pannellum looks fantastic, by the way -- great work.

**Comment by mpetroff** [comment]
Pannellum only works with equirectangular / cube map panoramas, not flat images. I'd recommend looking at [OpenSeadragon](https://openseadragon.github.io/).

**Comment by chconnor** [comment]
Looks like exactly what I need, thanks for the reply.

**Comment by mms-** [comment]
Would it be hard to modify the code to support flat images with multi resolution? The reason is both flat and panorama images types will be viewed in succession, and loading another viewer just for flat images would introduce quirks in the UI and double JS payload.

**Comment by mpetroff** [comment]
I have no intention of adding such a feature.

**Comment by mms-** [comment]
I understand, just wondering what your advice is, given your knowledge of the code, is there a clean way to add this?

**Comment by mpetroff** [comment]
Not really. Everything is panorama-specific, so only rotations are handled, not panning.
