### ISSUE TITLE
pannellum.org example page doesn't work on FF 53.0.3 on Linux

### ISSUE THREAD

**Issue by chconnor** [mpetroff/pannellum#397]
Hi -- using Kubuntu 16.10 and FF 53.0.3 with nvidia drivers, the example page on pannellum.org does not work. It says "your device only supports images up to 1024px wide". If I open the same page in Chromium, it works. Same thing happens with the "standalone" version and all the other examples.

Happy to provide more info if desired. Thanks,
-c

**Comment by mpetroff** [comment]
Per the error message, the browser/OS/computer combination only works with WebGL textures up to 1024px wide. Since Firefox and Chromium handle interfacing with graphics drivers differently, they sometimes end up supporting different WebGL texture sizes.

**Comment by chconnor** [comment]
Ah, I see, thanks for the reply. Perhaps I could suggest changing the error message? If it's the browser/OS/computer combination that is the problem, calling it a problem with the "device" makes it sound like a bug (e.g. a bad user agent string parsing -- in my case I thought it might be a classic case of linux user agent being parsed as a mac). Perhaps: "Sorry, this panorama can not be displayed with your combination of browser, operating system, and computer. It's 4096px wide, but your combination only supports 1024px. Try another browser, or another computer. (If you're the author, try scaling down the image.)"
