### ISSUE TITLE
Tour direction continuity

### ISSUE THREAD

**Issue by jhall39** [mpetroff/pannellum#401]
Hi, I'm building a tour with each area crosslinked by hotspots. Currently the view reorients to yaw=0, pitch=0 on each scene load. I'd like to save the compass heading in order to restore that when the new scene loads. My intentions are to use the NorthOffset saved on the scene along with the Yaw in order to calculate a compass heading. From the reference section it looks like scenechange should fire before the new scene loads but it seems to be giving me the values from the new scene, rather than the one I'm coming from. Is that the way it should be operating? Can you tell me if there's another event I should listen to instead?

**Comment by jhall39** [comment]
Nevermind, I see that I can add a clickHandlerFunc to each of my hotspots that can get the current scene's information before switching to a new one.

**Comment by mpetroff** [comment]
If I understand correctly what you're trying to do, you don't need to use the API at all. Setting the `targetYaw` parameter on each hot spot to `sameAzimuth` will load the new scene with the same compass heading as the current heading in the old scene.

The `scenechange` event fires when the loading process starts, after the new parameters are set. Changing when it fires to before the new parameters are set would just cause a race condition on the event listener, similar to what your saw with the `clickHandlerFunc`. I do have a few ideas on how to change things to provide the information you want, so let me know if the `sameAzimuth` setting doesn't do what you need.

**Comment by jhall39** [comment]
Wow, the sameAzimuth setting is exactly what I wanted. I didn't know it existed even though I was all over the documentation, I must have skimmed over it. I've found a bug with it though. If the scene doesn't have a northOffset setting then it is giving me a view without loading the pictures. I get a solid color sky and a solid color land. Do you want me to open a separate issue for that? It works fine even if I set a northOffset of 0 on each scene.

**Comment by mpetroff** [comment]
I wasn't checking to see if `northOffset` was set before doing math with it, so the resulting yaw was `NaN`, hence the issue. I just fixed this in d9d216f2ae82a92b26a1e74d40b6a9db7ab39fbf.

**Comment by jhall39** [comment]
Thanks! 
Two questions: Which arrow on the compass is north; The white one or the black one?
Is the device orientation control relative or absolute? Absolute would be locked to the internal compass of the device, showing North when the device is pointing North. That seems to be the case but I'd like to confirm it. Relative would adjust the view in relation to the change with yaw rather than the absolute yaw of the device.

**Comment by mpetroff** [comment]
Black is north, and white is south, which is standard (well, red for north, but that becomes black when converting to monochrome).

The device orientation control is relative. See https://github.com/mpetroff/pannellum/issues/257#issuecomment-248727137 for more details.
