### ISSUE TITLE
Change horizonRoll with custom controls on the fly

### ISSUE THREAD

**Issue by earlotti** [mpetroff/pannellum#402]
Hi,
Is it possible to change the horizonRoll value on the fly ? I have noticed that the horizonRoll (and also horizonPitch) value can be set as an option but it seems that there is no function to change this value after the panorama is loaded.

I am trying to implement custom controls that would allow users to correct panoramas. I would like to give the possibility to set the initial yaw (which is possible now) and to correct non-leveled panoramas by changing the horizonRoll (and maybe horizonPitch) in a lively manner like it is done in the custom controls example.

Thanks and congratulations for this great tool.

**Comment by mpetroff** [comment]
I just added `getHorizonRoll`, `setHorizonRoll`, `getHorizonPitch`, and `setHorizonPitch` API methods in bda0aa7b3b6bbd1b1074df3839de366fcf962e89 to allow this to be done.

**Comment by earlotti** [comment]
Many thanks for considering my request so quickly !
I have tried the new setHorizonRoll method, it works well but it's seems there is an issue with hotspots : when horizon roll changes, hotspots don't move on the screen and find themselves above a different point as they are supposed to be. Shouldn't hotpots' yaw and pitch be updated to reflect horizon roll changes ?

**Comment by mpetroff** [comment]
The horizon pitch and roll only apply to the WebGL rendering, so they don't affect hot spots. In normal use, the horizon doesn't change, so there isn't any reason to do otherwise. The horizon parameters were only added to support Ricoh Theta images (and therefore only work with equirectangular images).

**Comment by DStillingfleet** [comment]
Hi Matthew, Ealotti

Hope you are both well.

I'm trying to create a similar tool that Ealotti opened this issue with, i.e. web page o which to change the horizon roll and pitch on the fly so that I can see which values best present the panorama correctly (the xmp data does not always seem to be correct).

However when I use the setHorizonRoll API, the pannellum div just turns grey. 

The pano is created using

```
Pano=pannellum.viewer('panorama', {
    "type": "equirectangular",
	"autoLoad": true,
	"hfov":120,
	"horizonRoll":0,
    "panorama": "475HiRes.jpg"
});
```
Loading the panorama with a different initial horizonRoll, say -5, works fine.

To change it on the fly I initially tried using the following code called in response to a button click.
`Pano.setHorizonRoll(Pano.getHorizonRoll()-1,0);`
No luck.

So I tried simply to set the horizon roll with
`Pano.setHorizonRoll(-10);`
but still the pannellum div goes grey.

What is the correct format I should be using?

Pannellum is version 2.5.6.

Best wishes to you both


Derek

**Comment by earlotti** [comment]
Hi Derek,

I simply call setHorizonRoll with a parameter value between -180 and 180 degrees and it just works fine.

I'm not sure of the version of Pannellum I use, I picked up an intermediate release when Matthew added the setHorizonRoll API (June 2017).

You can send me your code if you want so I can compare with mine and spot the differences.

Best regards.
Eric

**Comment by DStillingfleet** [comment]
Hi Eric

Here's the code I used...

```
<!DOCTYPE HTML>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>A tilt example</title>
	<LINK rel="stylesheet" href="pannellum.css">
	<SCRIPT src="libpannellum.js"></SCRIPT>
	<SCRIPT src="pannellum.js"></SCRIPT>
    <style>
    #panorama {width:600px; height: 400px;}
    </style>
</head>
<body>

<div id="panorama"></div>
<div id="Roll">Roll</div><div id="Pitch">Pitch</div>
<button onclick="displayRoll()">Display Roll</button>
<button onclick="displayPitch()">Display Pitch</button>
<BR><BR>
<button onclick="decreaseRoll()">Decrease Roll</button>
<button onclick="increaseRoll()">Increase Roll</button>

<script>
Pano=pannellum.viewer('panorama', {
    "type": "equirectangular",
	"autoLoad": true,
	"hfov":120,
	"horizonRoll":0,
    "panorama": "475HiRes.jpg"
});

function displayRoll()
{
   document.getElementById("Roll").innerHTML = Pano.getHorizonRoll();
}
function displayPitch()
{
   document.getElementById("Pitch").innerHTML = Pano.getPitch();
}
function decreaseRoll()
{
   Pano.setHorizonRoll(Pano.getHorizonRoll()-1,0);
   document.getElementById("Roll").innerHTML = Pano.getHorizonRoll();
}
function increaseRoll()
{
   Pano.setHorizonRoll(Pano.getHorizonRoll()+1,0);
   document.getElementById("Roll").innerHTML = Pano.getHorizonRoll();
}
</script>

</body>
</html>
```

If you can figure out where I've gone wrong, that would be great.

Thanks


Derek

**Comment by mpetroff** [comment]
As the horizon pitch / roll functionality was added to handle Ricoh Theta images, the case where only one of the two parameters was defined was never considered. I fixed this in 862cd450e5c74bdeeb469a6011f7ac91bd6b2a92, but the workaround is to simply set `horizonPitch` to `0`.

**Comment by DStillingfleet** [comment]
Hi Matthew

I've now defined the pannellum pano with a horizonPitch of 0 and all works as expected.

```
Pano=pannellum.viewer('panorama', {
    "type": "equirectangular",
	"autoLoad": true,
	"hfov":120,
	"horizonRoll":0,
	"horizonPitch":0,
    "panorama": "475HiRes.jpg"
});
```
Many thanks both of you.


Derek

**Comment by DStillingfleet** [comment]
Hi Matthew

I've now defined the pannellum pano with a horizonPitch of 0 and all works as expected.

```
Pano=pannellum.viewer('panorama', {
    "type": "equirectangular",
	"autoLoad": true,
	"hfov":120,
	"horizonRoll":0,
	"horizonPitch":0,
    "panorama": "475HiRes.jpg"
});
```
Many thanks both of you.


Derek

**Comment by T2brozz** [comment]
hey is it possible that `setHorizonPitch` , `getHorizonPitch` ... are not editing the default value? So that you can also change the HorizonPitch and Yaw for each scene separately
