### ISSUE TITLE
play/pause

### ISSUE THREAD

**Issue by ingenuous67** [mpetroff/pannellum#404]
hi
thanks for this plugin.
i have a question:
i want to put a button inside plugin.
by click on button user can play and pause plugin.
can you help me?

**Comment by mpetroff** [comment]
I assume you're referring to playing a video. You can add a button using standard HTML / CSS; take a look at the [custom controls example](https://pannellum.org/documentation/examples/custom-controls/) to see how this can be done. To play/pause the video, you'll need to set the click handler on the button to use the Video.js API.

**Comment by ingenuous67** [comment]
thanks a lot.
this is my code:
$('#btn_play').click(function(){
	viewer.startAutoRotate(10);
});
$('#btn_pause').click(function(){
	viewer.stopAutoRotate(10);
});
