### ISSUE TITLE
Chrome distorted on load and while moving.

### ISSUE THREAD

**Issue by BetaStacks** [mpetroff/pannellum#405]
I am using the latest version and have a distorted image in chrome desktop but not safari. 
![screen shot 2017-06-07 at 12 07 52 pm](https://user-images.githubusercontent.com/20682927/26891335-496e7d08-4b7a-11e7-89bc-c403d9c18850.png)

**Comment by mpetroff** [comment]
Does https://get.webgl.org/ work for you? This looks like a known bug with the CSS 3D transforms that are used by the fallback renderer when WebGL doesn't work. See https://github.com/mpetroff/pannellum/issues/248#issuecomment-245821078, for example.

**Comment by BetaStacks** [comment]
It looks like WebGL isn't working even though I have it enabled in Chrome. I'm running on a Hackintosh at the moment so that is problem causing a problem with the drivers. 

I'll close this thread and comment on #248 to I can keep an eye in the CSS bug. 

Thanks for the help!

Brandon
