### ISSUE TITLE
Questions: Change Scene W/ JS?

### ISSUE THREAD

**Issue by BetaStacks** [mpetroff/pannellum#406]
I'm looking at the API and having a little bit of a hard time translating it into code. I would like to be able to transition scenes via voice commands. Can someone provide an example how I would use JS to load a new scene?

Thanks!

Brandon

**Comment by mpetroff** [comment]
After instantiating a Pannellum instance, in this case `viewer` (see [custom controls example](https://pannellum.org/documentation/examples/custom-controls/)), use `viewer.loadScene(sceneid)`, where `sceneid` is the scene ID in the Pannellum configuration, e.g. `circle` or `house` in the [tour example](https://pannellum.org/documentation/examples/tour/).

If your application does not allow you to include all of the scenes in one configuration file, you can also add a new scene to the configuration using the `addScene` method and then switch to it using `loadScene`.

**Comment by BetaStacks** [comment]
That was super helpful, thank you!

It's only one scene at the moment but If you say "show house" it will change the scene. :)
https://codepen.io/BrandonCorlett/pen/weKLBJ?editors=1111

Now to find a way to get it to work with a VR headset =P
