### ISSUE TITLE
pannellum size

### ISSUE THREAD

**Issue by ingenuous67** [mpetroff/pannellum#408]
hi
i want to hide size of viewer when loading...
can i do this?

**Comment by mpetroff** [comment]
I have no idea what you're asking.

**Comment by ingenuous67** [comment]
when viewer is load show capacity like: 
loading 2.4mb
i want to remove size!

**Comment by mpetroff** [comment]
That would degrade the user experience, so it's not supported. If you want to modify things yourself, the relevant code starts at [`pannellum.js` line 366](https://github.com/mpetroff/pannellum/blob/c89710c031f35cbc4f03a8c65f3cf1865b9523c0/src/js/pannellum.js#L366).
