### ISSUE TITLE
Create tiles with PHP or Imagic

### ISSUE THREAD

**Issue by ai-tushar** [mpetroff/pannellum#411]
can i create tiles with raw PHP or Imagic ? 
what is the algorithm of creating tiles ? like google explained how an image should be sliced for their custom street view [(here)](https://developers.google.com/maps/documentation/javascript/streetview#TilingPanoramas) , so is there any explanation to slice image for pannellum ?
the python script cannot be executed in the server because all servers does not have python installed. and i want this image slicing to be a automatic process. please help.

Thanks

**Comment by mpetroff** [comment]
It's not my fault that you can't run Python on your server. The source code of `libpannellum.js` and `generate.py` is the documentation. You're more than welcome to port the Python script to another language, but you're on your own.

**Comment by ai-tushar** [comment]
i know its a long time, but eventually wanted to tell for a long time that, afterall its your library you can do whatever you want to, but sir the answer you gave to my question was **rude and egoistic**. i didnt said it was your fault. just asked for help, if you cant help, you didnt have to be **rude** or show your **ego**. whatever, thanks for the lesson.

**Comment by strarsis** [comment]
Also note that a `nona` equivalent in PHP is also needed.
