### ISSUE TITLE
Change LoadButton Text

### ISSUE THREAD

**Issue by maxleistner** [mpetroff/pannellum#416]
I would like to change to Load Button Text which at the moment is "Click to Load Panorama". How can this be achieved? I tried `loadButtonLabel` but it is not working. 

Version: 2.3

Thanks!

**Comment by mpetroff** [comment]
The `loadButtonLabel` parameter was added on February 5 in 624c1c11244fc8ad3310a1315c944f94c915ef6e (implementing #334). It's not in a release yet (version 2.3.2 was released November 20). Either manually change the text in your copy, or use the development version.

**Comment by Protomancer** [comment]
Version 2.4.0 parameter `loadButtonLabel` is not adjusted when used.  Cannot change "Click to Load Panorama".
Maybe I'm doing something Incorrectly? Everything works so far except 'loadButtonLabel'
```
pannellum.viewer('panorammaFoo', {
        "type": "cubemap",
        "autoLoad": false,
        "loadButtonLabel" : "Start Tour",
        "cubeMap": [
            //urls excluded in this example, cube map works great
        ]
    });
```

**Comment by strarsis** [comment]
@Protomancer: You may find the translation strings feature interesting. 
You can pass custom strings for each UI text.

**Comment by mpetroff** [comment]
The translation strings feature (`strings` parameter) that @strarsis mentioned made this option redundant. Since it was never in a release, there were no compatibility issues with removing it.
