### ISSUE TITLE
How to get the video reference to use Pannellum API functions? 

### ISSUE THREAD

**Issue by leonbaichi** [mpetroff/pannellum#420]
i use the video example code
var v1 = videojs('pan1', { loop: true, plugins: { pannellum: { "hfov": 120 } } });
i want to use the api 'toggleFunction',
but after i use
` v1.pnlmViewer.toggleFullscreen();

 v1.pannellum.toggleFullscreen();
             	    					
 v1.pnlm.toggleFullscreen();

 v1.pnlmViewer.toggleFullscreen(); `
all don't work! the console output below

Cannot read property 'toggleFullscreen' of undefined

what‘s the right code to make the right reference。。。。need help!

**Comment by mpetroff** [comment]
Are you using a new version of `utils/video/videojs-pannellum-plugin.js`? The ability to reference the Pannellum object was added March 30 in e0a108a50440ccbe095e46551657a13ee682280f. With the latest version of the plugin, `v1.pnlmViewer.toggleFullscreen();` should work.

**Comment by leonbaichi** [comment]
thx,petroff, it works ,and i can access to the pnlmViewer. 
 i finally toggle fullscreen using the videojs api ,cause the videojs player's fullscreen function acts a little different with pnlmViewer's toggleFullscreen() . i can't tell. 
thx!!!
