### ISSUE TITLE
three.js?

### ISSUE THREAD

**Issue by strarsis** [mpetroff/pannellum#421]
Would it make sense writing pannellum on top of three.js? 
Could this solve compatibility issues and reduce regressions?

**Comment by mpetroff** [comment]
**Absolutely not.** Pannellum was originally written using three.js, but I transitioned away from it years ago. Using three.js, the library would be ~10 times its current size, would have awful looking looking artifacts at the nadir and zenith for equirectangular images from using a geometric approximation of a sphere like the plethora of viewers made using three.js, and would have needless abstraction making the multires renderer much more complicated than necessary.
