### ISSUE TITLE
What features does Pannellum require?

### ISSUE THREAD

**Issue by jhall39** [mpetroff/pannellum#426]
I'd like to use something like Modernizr to detect if these are supported and if not, show a friendly message to the user why it won't work in their browser.

**Comment by mpetroff** [comment]
It requires WebGL. There are some browsers that support WebGL but don't support the full screen API, but this is already handled seamlessly. I don't there's any newer JavaScript being used that isn't supported by some browsers that do support WebGL, but I can't say for certain.
