### ISSUE TITLE
Pannellum loaded

### ISSUE THREAD

**Issue by strarsis** [mpetroff/pannellum#427]
The viewer variable can be used to access the standalone player pannellum viewer instance.
However, even after the frame has been loaded (load event), the viewer variable is still not initialized because Pannellum hadn't finished initializing.
Can some kind of event be emitted on the window or viewer variable made a callback so an external script is able to wait until Pannellum viewer became ready?

**Comment by strarsis** [comment]
I modified the standalone.js and added a line that triggers a custom event:
```js
[...]
            viewer = pannellum.viewer('container', configFromURL);
            window.dispatchEvent( new Event('pannellum-ready') );
[...]
````

Now one can wait for the frame having been loaded and pannellum instance being ready:
```js
var pannellumWait = function(iframe, cb) {
  var iframeReady = function() {
    var pannellumWindow = this.contentWindow;

    pannellumWindow.addEventListener('pannellum-ready', pannellumReady.bind(this, pannellumWindow));
    if(pannellumWindow.window.viewer) { // if pannellum already initialized
      pannellumWindow.removeEventListener('pannellum-ready', pannellumReady.bind(this, pannellumWindow));

      pannellumReady(pannellumWindow);
    }
  };

  var pannellumReady = function (pannellumWindow) {
    var viewer = pannellumWindow.window.viewer;
    cb(viewer);
  };


  iframe.addEventListener('load', iframeReady);
  if(iframe.contentWindow) { // if iframe already loaded
    iframe.removeEventListener('load', iframeReady);
    iframeReady.apply(iframe);
  }
};


// in document.ready...
var iframe = $(this).find('.pannellum-panorama')[0];
    pannellumWait(iframe, function(viewer){
        alert(viewer);
    });
````

**Comment by mpetroff** [comment]
If you want to interact with the viewer using JavaScript, you should use the API directly, not the standalone viewer.

**Comment by strarsis** [comment]
@mpetroff: So in these cases I would use pannellum.js and pannellum.css and initialize pannellum viewer myself?

**Comment by mpetroff** [comment]
Yes
