### ISSUE TITLE
Load new config file

### ISSUE THREAD

**Issue by strarsis** [mpetroff/pannellum#429]
Is it possible to use an existing Viewer instance and let it load a completely new config file?
The standalone viewer got a method (https://github.com/mpetroff/pannellum/blob/master/src/standalone/standalone.js#L9) 
for parsing the window (iframe) src - but not an argument or way for changing the config parameter.

**Comment by mpetroff** [comment]
As with #427, this should be done using the API, not the standalone viewer. If you want to reinitialize the viewer, `destroy` the old viewer and create a new one.
