### ISSUE TITLE
rotate not working

### ISSUE THREAD

**Issue by umbreak** [mpetroff/pannellum#43]
I'm using a JSON configuration as follows:

	default: {
		minHfov: 50,
		maxHfov: 145,
		hfov: 122,
		autoRotateInactivityDelay: 5000,
		autorotate: 5,
		firstScene: "R0010178-_-JPG",
		autoLoad: true,
	},
        ....

And using scenes with `type cubemap`
And it actually does not autorotate. Did I understand something wrong?

**Comment by mpetroff** [comment]
It should be `autoRotate`, not `autorotate` (this changed in version 2.1).

**Comment by umbreak** [comment]
Oh! You are right. 
And how can I stop autorotate from javascript?

Cause I would like that the autorotate stops after a certain time if the user haven't done anything

**Comment by mpetroff** [comment]
Closing since deleted comment suggests this issue was resolved.
