### ISSUE TITLE
viewer.loadScene not working on IE 11

### ISSUE THREAD

**Issue by BasSilderhuis** [mpetroff/pannellum#430]
Hi,

I have made a virtuel tour with your great 360 viewer and users are able to switch image with hotspots of with a small tumbnail below. When clicking a hotspot of a tumbnail the hole things stops in Internet Explorer 11. Its working in Chrome, Firefox and also in the Microsoft Edge browser. 

I am using cubemaps.

Below a screenshot of my scenes object

![schermafbeelding 2017-07-13 om 11 08 12](https://user-images.githubusercontent.com/25772359/28158825-44a56cd4-67bb-11e7-8089-887cf732d639.png)

So I think it is yust a bug in IE 11. Is this a know problem?

**Comment by mpetroff** [comment]
Your screenshot doesn't really tell me anything. Is there some sort of error logged to the console?

**Comment by BasSilderhuis** [comment]
Oke, My bad. 

Maybe its better to see for yourself if you have Internet Explorer 11. An online sample where the virtuel tour "stops"  when clicking on a hotspot of a tumbnail image.

https://www.gemeentewijzer.nl/zederik/business/184902/kroon-vloeren-in-steen-in-meerkerk/?tabblad=rondkijken

**Comment by mpetroff** [comment]
To fade between scenes, image data is extracted from the WebGL canvas and inserted into an image, the new scene is loaded, and the image is faded out. To avoid flicker (see #158), an `onload` callback is used on this image to start the transition. However, IE 11 wasn't returning image data from the WebGL canvas, so the `onload` event never happened, so the transition didn't start.

In 8cb5902e1eca3d78994c46a8151f2646d49b36e7, I added a check to continue without a fade is there isn't image data, which should fix this issue.
