### ISSUE TITLE
Error while adding hot spot: "TypeError: C is undefined"

### ISSUE THREAD

**Issue by pjoerke** [mpetroff/pannellum#432]
Hi guys!

I get an error when trying to add a hot spot to the panorama: "TypeError: C is undefined". The error occurs in pannellum.js:67:406. I also attached a minimal example resulting in this error.

Thanks for your help!

Cheers,
Pascal

[index.zip](https://github.com/mpetroff/pannellum/files/1148040/index.zip)

**Comment by mpetroff** [comment]
It was throwing an error because the panorama wasn't loaded yet. I made changes to allow hot spots to be added before the panorama is loaded in 0dda044374a15a7bb9d8ef1090405c5f5e4a175d, to fix this.
