### ISSUE TITLE
Question: Support for google's photo sphere

### ISSUE THREAD

**Issue by jochem4207** [mpetroff/pannellum#433]
How is the support for google's photo sphere (it has some odd dimensions).

**Comment by mpetroff** [comment]
It's fully supported.

**Comment by pegues** [comment]
How to load google's photo sphere images? I've tried the equirectangular and multires types, and the result comes out horribly. Can someone please share an example configuration for loading google panos that have a folder structure such as: pano/__WNYkII_ZVn1HebX4Y7XA/0/0 with images 0.jpg, 1.jpg, 2.jpg, and 3.jpg ? I'd greatly appreciate it.
