### ISSUE TITLE
Image storage for multires tour

### ISSUE THREAD

**Issue by MathiasMeuleman** [mpetroff/pannellum#436]
Hi, 

Just wanted some advice on a project I'm working on.
I'm trying to get multires tours working, but I'm having some trouble figuring out what would be the best way to store the images. Users on my platform should be able to upload equirectangular images and I'll use the `generate.py` script to transform them into multires, that all goes well. But, where would be the best place to store these multires images? I can store them directly on my server, but that would probably use too much space as soon as there is a significant amount of users (not to mention, the security issues, I want to provide the users the possibility to store their tours with some decent amount of security). I could switch to a CDN (something like Cloudinary), but how would I fix the multires URLs? Correct me if I'm wrong, but multires config takes a folder and does some underlying magic to fix the panoramas right? The problem with a CDN is that I probably can't get folder URLs, only specific image URLs. Did you by any chance put any thought in this? Any help/comments/remarks would be highly appreciated.

**Comment by mpetroff** [comment]
The whole advantage of multires panoramas is the fact that they're composed of multiple files, so the whole image doesn't need to be downloaded. This isn't feasible without standardized file names, as the alternative would be to include thousands of image URLs in the configuration file.

All the CDNs I've used supported user-defined directory structures, so maybe you should look at a different CDN. At the very least, you need to be able to set the image name; setting the `multiRes`:`path` setting to something like `/prefix_%l_%s%y_%x` would allow you to place all of the images in the same directory.

**Comment by MathiasMeuleman** [comment]
Alright, thank you for your quick response. I will have a look at some other CDNs then, see what the possibilities are
