### ISSUE TITLE
Panorama to big on Firefox 54.0.1

### ISSUE THREAD

**Issue by doublewebnl** [mpetroff/pannellum#441]
On my firefox browser the panorama is not shown.
It says the device only supports up to 4096px. Chrome works fine though.
How come firefox doesn't support this?
If there isn't a fix for this, then is there a method to find out that the image is too big for the browser/device so I can load a smaller image?

Thanks in advance.

**Comment by mpetroff** [comment]
Supported image sizes are determined by a combination of the browser, graphics driver, and graphics card and how they interact with each other. There's nothing to fix.

You can check supported image sizes before initializing Pannellum. See https://github.com/mpetroff/pannellum/issues/199#issuecomment-234676481.
