### ISSUE TITLE
Content of Variable »sceneId« needed

### ISSUE THREAD

**Issue by HorstlMats** [mpetroff/pannellum#443]
Hello to all!
I tried to find a solution for very long time, but – and I'm very sorry about this – without any success. So I need to ask for a little help:

I need the Content of the variable »sceneId« in a little script, to show some overview-plan in a complete tour. But my skills in JavaScript are less than low. I tried it with:

<script>
document.write(pannellum.viewer.sceneId);
</script>

but the result is only »undefined«.
Maybe someone here suspects my intensions an is able to help.

Many thanks in advance
Horstl

**Comment by mpetroff** [comment]
I'm not really sure what you're trying to do, since `sceneId` is a configuration parameter, not a variable. The scene IDs are the keys to the `scenes` dictionary in the JSON configuration. For example, in the [tour example](https://pannellum.org/documentation/examples/tour/), the scene IDs are `circle` and `house`.

**Comment by HorstlMats** [comment]
In this example I would need to load »circle.png« when the tour is there and »house.png« when the tour is on this place...

**Comment by mpetroff** [comment]
I still don't follow. There are no PNG images in the example I linked to, nor are there any image files with `circle` or `house` in the image name.

**Comment by HorstlMats** [comment]
I am very sorry. My english is this bad, that it seems, I used the wrong word. I used »plan«, which is the german word for »map«.

My little problem: with 10 and more scenes, you sometimes don't know, where you are...

So my idea was to place a overview-map in the left-bottom-corner in every single scene – marked with the current position on it. This I put on the server with the same name as the equirectangular JPG, but in the format PNG. So in your example, there would exist the »circle.png« and the »house.png« – but both made by me and all in the same directory. (Or even named: »from-tree.png« and »bma-0.png«)

CSS was no problem, the map is there where it should be – and it's looking nice.
But now I need the name of the scene (or some other unique name) for changing the map-pics together with the scene...

I hope, this is a little better explained now...   :-)

Thanks for your efforts

**Comment by mpetroff** [comment]
Now I think I understand what you're asking&mdash;you want a way to retrieve the ID of the current scene.

The API has a [`getScene`](https://pannellum.org/documentation/api/#getscene) function for doing this. You can also add a [`scenechange`](https://github.com/mpetroff/pannellum/blob/master/doc/events.md#scenechange) event handler using the API's `on` function that is called whenever the scene is changed and passes the ID of the new scene to the event handler.

If you create the Pannellum instance using `viewer = pannellum.viewer('divid', {JSON configuration});`, you can get the current scene ID using `viewer.getScene();`. An example of an event handler is as follows
```javascript
viewer = pannellum.viewer('divid', {JSON configuration});
viewer.on('scenechange', function(id) {
  console.log('The new scene is: ' + id);
});
```

**Comment by HorstlMats** [comment]
Oh, I understand (almost) – now I'm close to the solution...

Thanks a lot!!

**Comment by HorstlMats** [comment]
puh... it's a fact: my JS-skills needed to be improved enormously!  :-)
But with your help it works now (in a bit ugly code, but it works).

Many thanks for your big help and a nice weekend!

**Comment by ShenLoong99** [comment]
Greetings, is it possible to get the scene ID of the targeted scene. For example, if I click on a hotspots which redirects me to the second scene, am I able to get the second scene ID?

**Comment by mpetroff** [comment]
@ShenLoong99 I assume you're using a custom `clickHandlerFunc` function. In that case, set the target scene ID as part of the `clickHandlerArgs` parameter, which is passed to the `clickHandlerFunc` function.

**Comment by ShenLoong99** [comment]
> @ShenLoong99 I assume you're using a custom `clickHandlerFunc` function. In that case, set the target scene ID as part of the `clickHandlerArgs` parameter, which is passed to the `clickHandlerFunc` function.

Oh I see. Thank you for telling me. I have already resolve my issue.
