### ISSUE TITLE
Support for non-Spherical panorama?

### ISSUE THREAD

**Issue by edent** [mpetroff/pannellum#447]
Is it possible to display regular 360 panoramas?

I've an image like this:

![640](https://user-images.githubusercontent.com/837136/29075518-88de502a-7c4a-11e7-87b2-423d90b0d2e1.jpg)

It displays, but the perspective is skewed incorrectly.

(I'm assuming the answer is no - but wanted to check before giving up hope)

**Comment by mpetroff** [comment]
That really depends what you mean by "regular" panoramas. If the image has an equirectangular projection, it can be displayed even if it isn't fully spherical (other projections, e.g. cylindrical, aren't supported). See the [partial panorama example](https://pannellum.org/documentation/examples/partial-panorama/). Use the `haov`, `vaov`, and `vOffset` parameters to set the proper limits. Alternatively, if [Photo Sphere XMP metadata](https://developers.google.com/streetview/spherical-metadata) is present, it will automatically be used. The `minYaw`, `maxYaw`, `minPitch`, and `maxPitch` parameters can be used to restrict the viewer's movement extents. There's also a `backgroundColor` parameter for setting the color where there isn't image data (defaults to black).

**Comment by edent** [comment]
Aha! That works perfectly :-)

Thank you.
