### ISSUE TITLE
WebGL error on IE 11 with cubemap

### ISSUE THREAD

**Issue by danielnaber** [mpetroff/pannellum#45]
IE 11 (version 11.0.9600.17501) runs into the WebGL error ("Your browser does not support WebGL"), even though WebGL seems to be enabled (e.g. when visiting get.webgl.org - it says support is experimental). The console log says:

    WEBGL11003: INVALID_VALUE: texImage2D

in pannellum.html line 626, Column 17 (...one of these per image...), and then

    WEBGL11122: drawArrays: Texture is not cubemap complete. Alle cubemaps faces must be defined and be the same size.

in pannellum.html, line 730, column 13 (probably caused by the errors above)

Debugging show that the error code from gl.getError() is 1281 (GL_INVALID_VALUE).

Each cube is 1142x1142 pixels and it works with Firefox and Chrome. Maximum size is not the problem (maximum size is about 16,000).

Test URL: http://danielnaber.de/tmp/pannellum/ (yes, it's the same image for all six surfaces)

You can probably reproduce this with browserstack.com (saucelabs browsers don't seem to have WebGL enabled).

The documentation at https://msdn.microsoft.com/en-us/library/ie/dn302435%28v=vs.85%29.aspx has different parameters (e.g. width and height), but I have no clue about WebGL so I'm not sure if this is relevant.

**Comment by mpetroff** [comment]
After doing some testing in a VM, this seems to be a bug in IE's WebGL support; specifically, IE 11 doesn't support non-power-of-two cube map textures (I was able to find [another reference to this IE bug](https://github.com/AnalyticalGraphicsInc/cesium/issues/1616#issuecomment-46722716)). What's even more troubling is that IE 11 doesn't report the error through the JavaScript API, so Pannellum can't display an error message. The new Edge engine in the Windows 10 Technical Preview engine still doesn't support the NPOT textures, but it at least reports the error to Pannellum.

**Comment by mpetroff** [comment]
Safari under iOS has a similar issue with NPOT cubemaps not working but no error being generated (tested on iPhone 5c / iOS 8.1.3).

**Comment by mpetroff** [comment]
I just added a user agent check to display an error for NPOT cubemaps in IE 11. While this is generally bad practice as one should check for features instead, IE 11 claims to have the feature, but it doesn't actually work. The only other way to check for this would be to build in a WebGL conformance check to see if it actually worked, but that's much too complex for something like this, in my opinion.

**Comment by umbreak** [comment]
What about this: https://www.khronos.org/webgl/wiki/WebGL_and_OpenGL_Differences#Non-Power_of_Two_Texture_Support

**Comment by mpetroff** [comment]
To be standards compliant with WebGL, NPOT textures without mipmaps need to be supported. Firefox and Chrome support this, but IE 11 and Safari on iOS both don't support any NPOT cubemap textures. Additionally, they don't throw an error.
