### ISSUE TITLE
Wrapper for all controls/surface

### ISSUE THREAD

**Issue by strarsis** [mpetroff/pannellum#450]
I added additional HTML elements to the pannellum container element.
These are shown, even in fullscreen - however, event handlers are attached to container element 
hence also to the additional HTML elements (noticeable the scroll event).
Also the UI controls can't be constrained, they overlap the additional HTML elements.
It would be great if all UI controls and surface for scroll/touch are summarized in an additional HTML wrapper element inside the pannellum container.

**Comment by strarsis** [comment]
PR ready: https://github.com/mpetroff/pannellum/pull/452

**Comment by mpetroff** [comment]
I merged the pull request.
