### ISSUE TITLE
Re-attach handlers?

### ISSUE THREAD

**Issue by strarsis** [mpetroff/pannellum#451]
The handlers (e.g. mousewheel) are attached to the container element.
However, this interferes with elements inside, e.g. scrolling inside the container element.

How can I let Pannellum attach these handlers to an element inside?
Can I manually detach + re-attach these handlers from an outside script (as workaround)?

**Comment by mpetroff** [comment]
Is this still an issue now that #452 has been merged in?

**Comment by strarsis** [comment]
With all UI related elements/handlers separated, this issue has been also resolved. Thanks.
