### ISSUE TITLE
Like the example the image tites，What I need to use What tool to generate？

### ISSUE THREAD

**Issue by qwe5788319** [mpetroff/pannellum#453]
https://pannellum.org/

**Comment by qwe5788319** [comment]
generate.py 。。。Can only be generated six textrues

**Comment by qwe5788319** [comment]
generate.py 。。。Can only be generated six textrues

**Comment by mpetroff** [comment]
The example on the pannellum.org homepage use multiresolution images, which are generated using `generate.py`.
