### ISSUE TITLE
Loading... message using custom clickHandlerFunc

### ISSUE THREAD

**Issue by sijpkes** [mpetroff/pannellum#461]
I'm using panellum with a 360 video using your video.js plugin and it works like a charm. 

I've succesfully added custom hotspots which load a youtube video via `clickHandlerFunc` and temporarily pause and hide the panellum video.  

After exiting the youtube video I want users to be able to continue watching the 360 panellum video by calling `play()` on the panellum player.

I, however, cannot find in the documentation anywhere covering how to fire a 'loaded' or 'loadComplete' event back to the panellum player to tell it the clickHandlerFunc has loaded and completed successfully.  

After calling `play()` I can hear the audo continuing in the background but the video itself is frozen with the **Loading...** message.

**Comment by sijpkes** [comment]
OK, I worked it out. I had a 'sceneId' on the tooltip, this was not a link to a scene so it was opening the `infoDisplay.load.lbox` every time I clicked it.

**Comment by mpetroff** [comment]
The Video.js plugin should automatically take care of this, so I'm not sure why it's not. Try calling `setUpdate(true)` on the Pannellum instance after calling `play()` on the video.

**Comment by sijpkes** [comment]
Nice timing! :-)

**Comment by cadradsp** [comment]
Hi
I am unable to add click handler on hotspot by using "clickHandlerFunc" attribute. 
Please suggest me, how can I add a basic click event.
My requirement is to fetch image data on load of image or on click of hotspot.

Thanks in advance!

**Comment by cadradsp** [comment]
@mpetroff 
Sir.... it would be great if I can get help from you as soon as possible.
Anyone who can guide me.
