### ISSUE TITLE
mousedown / mouseup for touch?

### ISSUE THREAD

**Issue by strarsis** [mpetroff/pannellum#462]
I need an event that fires on all kind of user interactions that changes the view (yaw/pitch/roll (sensor?)) - mousedown / mouseup are already available for mouse interaction -but not for touch/sensor changes.

Edit: Just found out that this has been already implemented - but not documented yet on the website.

Current docs: https://github.com/mpetroff/pannellum/blob/1e61a22be633a5c297fceaa89fd81b969977a097/doc/events.md

Website docs: https://pannellum.org/documentation/reference/#api-events

**Comment by mpetroff** [comment]
It's not documented on the website since it isn't in a release yet. The website will be updated when there's a new release.
