### ISSUE TITLE
[perf] Container vs iframe

### ISSUE THREAD

**Issue by strarsis** [mpetroff/pannellum#464]
For some purposes and for convenience, sometimes a container element and Pannellum library is used instead the iframe standalone.html. I think I noticed that the performance is better with the iframe based viewer though this requires more objective measurement. Can the separate document context be the reason? Is this a browser-specific micro-optimization or a fundamental advantage? 
Maybe the Pannellum library could insert an iframe for achieving the same advantage while still offering API access?

**Comment by mpetroff** [comment]
I've never noticed a performance difference, and I can't think of a good reason of why there would be a difference.
