### ISSUE TITLE
`1`/`0` instead `true`/`false` in url configuration?

### ISSUE THREAD

**Issue by strarsis** [mpetroff/pannellum#465]
Can Pannellum also be made supporting `1` and `0` instead `true` and `false` in url configuration?
It would be nice if boolean parsing is improved so Pannellum can also handle these.

**Comment by strarsis** [comment]
Edit: I adjusted the code that uses `'on'`/`'off'` instead of booleans so it uses booleans now.

**Comment by mpetroff** [comment]
Strict parsing is used to avoid ambiguity. This isn't going to be changed.

**Comment by strarsis** [comment]
@mpetroff: I just had an issue with jquery extend and lodash.merge, because both apparently treat the boolean as string in the final object.
