### ISSUE TITLE
open hotspot url in popup div, not a new blank window or page

### ISSUE THREAD

**Issue by vrcreator** [mpetroff/pannellum#466]
By default, an info hotspot with url, will open in a new browser window or a new tab (target="_blank").

Now I would like to create a popup-div, showing the url content. Or even open the url in the same window/tab.

Can this be done? If so, how? 

I have seen plenty of '_blank' code in the js file. But I'm no js expert... I've tried to change some of the '_blank' code into '_self' and '_top'. But sadly without any succes.
Any help would be greatly appreciated!

Thanks in advance for your efforts :-)

**Comment by mpetroff** [comment]
If you use the `clickHandlerFunc` and `clickHandlerArgs` hot spot parameters and use a custom click handler, you can do this.
