### ISSUE TITLE
destroy and los

### ISSUE THREAD

**Issue by lehmannwebdev** [mpetroff/pannellum#468]
libpannellum.js > destroy() you can try catch code:

try{
            var extension = gl.getExtension('WEBGL_lose_context');
            if (extension)
                extension.loseContext();
}catch(e){
            console.log(e);
}

because IE crash there.

**Comment by mpetroff** [comment]
Which version of IE / Windows? What's the error?

**Comment by lehmannwebdev** [comment]
Windows 7 
IE 11 (11.0.9600.17801, update v: 11.0.19 KB3049563)

Error:
SCRIPT5022: NotFoundError
File: pannellum.js, row: 22, col: 466 (marked below as <ERROR_HERE>)

"...
this.destroy=function(){$!==g&&(v!==g&&<ERROR_HERE>$.removeChild(v),R!==g&&$.removeChild(R));if(a){var d=a.getExtension("WEBGL_lose_context");d&&d.loseContext()}}
..."

After try catch, object DOMException:
{  
         [functions]: ,
         __proto__: { },
         ABORT_ERR: 20,
         code: 8,
         constructor: { },
         DATA_CLONE_ERR: 25,
         DOMSTRING_SIZE_ERR: 2,
         HIERARCHY_REQUEST_ERR: 3,
         INDEX_SIZE_ERR: 1,
         INUSE_ATTRIBUTE_ERR: 10,
         INVALID_ACCESS_ERR: 15,
         INVALID_CHARACTER_ERR: 5,
         INVALID_MODIFICATION_ERR: 13,
         INVALID_NODE_TYPE_ERR: 24,
         INVALID_STATE_ERR: 11,
         message: "NotFoundError",
         name: "NotFoundError",
         NAMESPACE_ERR: 14,
         NETWORK_ERR: 19,
         NO_DATA_ALLOWED_ERR: 6,
         NO_MODIFICATION_ALLOWED_ERR: 7,
         NOT_FOUND_ERR: 8,
         NOT_SUPPORTED_ERR: 9,
         PARSE_ERR: 81,
         QUOTA_EXCEEDED_ERR: 22,
         SECURITY_ERR: 18,
         SERIALIZE_ERR: 82,
         SYNTAX_ERR: 12,
         TIMEOUT_ERR: 23,
         TYPE_MISMATCH_ERR: 17,
         URL_MISMATCH_ERR: 21,
         VALIDATION_ERR: 16,
         WRONG_DOCUMENT_ERR: 4
}

**Comment by mpetroff** [comment]
This had nothing to do with the WebGL lose context extension. It was happening because you were calling `destroy()` more than once, which was trying to remove a DOM element that had already been removed the first time. I added an extra check to fix this in 508a21044fed3bfb3d1283b6fab2751ba103e0ff.

**Comment by lehmannwebdev** [comment]
Ok. Thanks!
