### ISSUE TITLE
Scene change sequentially

### ISSUE THREAD

**Issue by choiyoonho2** [mpetroff/pannellum#469]
I want to change multiple scenes sequentially like animation when the tour button is clicked.
I used "viewer.loadScene("Scene1"); viewer.loadScene("Scene2"); viewer.loadScene("Scene3");". 
But there is an error in change. I just want to change scene's panorama image quickly. What should i do?

**Comment by mpetroff** [comment]
Could you elaborate on the error you see?

JavaScript is generally asynchronous, as is the Pannellum API, so the `loadScene` function returns immediately, not when the scene has finished changing. You need to use an event listener to see when the scene has actually changed before changing to the next scene, e.g.

```javascript
viewer.on('load', function() {
  window.setTimeout(function() {
    viewer.off('load');
    viewer.on('load', function() {
      window.setTimeout(function() {
        viewer.off('load');
        viewer.loadScene('Scene3');
      }, 3000);
    });
    viewer.loadScene('Scene2');
  }, 3000);
});
viewer.loadScene('Scene1');
```
will load `Scene2` three seconds after `Scene1` finishes loading and then load `Scene3` three seconds after `Scene2` finishes loading.

**Comment by choiyoonho2** [comment]
There is not console error. But scene image changing does not work properly. But when I drag mouse, only hot spot buttons move.The code you provided works well. But I want to use setTimeout function in for loop.  
ex) var sceneList = ["Scene1","Scene2","Scene3"];
for (var i .... sceneList length)
{
viewer.loadScene(sceneList[i]);
}
How do I fix the code?

**Comment by DStillingfleet** [comment]
Hi Matthew

Quick question.  

What's the purpose of the line
`viewer.off('load');`
in the code above?

Only asking because of problems with on(load) firing early, and maybe there is a potential solution for me here.

Best wishes


Derek

**Comment by mpetroff** [comment]
In this example, the goal was to replace the original event listener with a new one. Thus, `viewer.off('load')` is called to remove the old load event listener before adding the new one, so each event listener is only fired once.
