### ISSUE TITLE
orientationOnByDefault - Desktop

### ISSUE THREAD

**Issue by byValle** [mpetroff/pannellum#471]
I found out that setting "orientationOnByDefault" to true it also stops "autoRotate" on desktop browsers. It makes sense stopping it on mobile devices since the rotation depends on the orientation of the device, but this should not affect desktop browsers I think.

Thanks once more for this awesome tool

**Comment by mpetroff** [comment]
Are you using the 2.3 release or the development version? I can only reproduce this in the 2.3 release. I think this was fixed with #337.

**Comment by byValle** [comment]
You are right, I'm using 2.3.2. I fixed it anyways using Mobile Detect.
