### ISSUE TITLE
The right Resolution

### ISSUE THREAD

**Issue by MiMoWe** [mpetroff/pannellum#474]
Hi,
on other issues i read that I should use a width of 4096 Pixel to reach all Devices and I saw a tip how I can find out the MAX_TEXTURE_SIZE. When I try this my smartphone will show a MAX_TEXTURE_SIZE of 4096 pixel, but when I use a pano-image with 8192 px width, it will be shown. Why it works?
I do not understand this. I would like to use higher resolutions but I would not lock (m)any devices.
Is it state of the art, that I reach no so much users when I use 8192 px images?

On this occation: thank you for pannellum!

**Comment by mpetroff** [comment]
Pannellum explicitly checks the max texture size before trying to show an image: https://github.com/mpetroff/pannellum/blob/508a21044fed3bfb3d1283b6fab2751ba103e0ff/src/js/libpannellum.js#L249

If your phone is displaying 8192px wide equirectangular images with Pannellum, it's reporting its `MAX_TEXTURE_SIZE` as 8192 or larger. If you want to display larger images, you need to use Pannellum's [multiresolution feature](https://pannellum.org/documentation/examples/multiresolution/).

**Comment by MiMoWe** [comment]
Ok, it seems that on my test there was the small version of the pano in the cache and i thougt ther is the big one loaded on my smartphone with a MAX_TEXTURE_SIZE of 4096.
Sorry, this question was unnecessary.
