### ISSUE TITLE
Can't use base64 data for panorama image.

### ISSUE THREAD

**Issue by trockefeller** [mpetroff/pannellum#475]
I was trying to set up the viewer to use base64 data, and when it attempted to load the image the viewer crashed and locked the browser tab I was running in (running Chrome Version 60.0.3112.113) . In the application I'm working on we are downloading image data from a server as base64 data, and we do not have urls that we can use for the images.

    let viewer = pannellum.viewer('panorama', {
        "type": "equirectangular",
        "panorama": [putting base64 image data here causes bad things to happen]
      });

**Comment by mpetroff** [comment]
See https://github.com/mpetroff/pannellum/issues/256#issuecomment-259442510. Data URIs don't work in Chrome, and it's not something I plan on fixing, because [Blob objects](https://developer.mozilla.org/en-US/docs/Web/API/Blob) are much better suited for passing around image data client-side.
