### ISSUE TITLE
setYaw rotation direction problem still occurs.

### ISSUE THREAD

**Issue by choiyoonho2** [mpetroff/pannellum#476]
I had asked about this problem. #473 
I tested latest two pannellum.js code (https://cdn.pannellum.org/2.3/pannellum.js and uploaded code)
Two javascript files still have a direction problem. The cdn code seems to have modified the yaw range.
But still has problem. And also occurs in the Custom controls example.
Test yaw value :
cdn : Change yaw from 175 to -175. And yaw from 175 to 184.
uploaded js file code : Change yaw from 175 to -175.
Both are caused by the same problem. I am sorry, please check  it.

**Comment by mpetroff** [comment]
Pannellum 2.3 is the last release, not the development version. It has been fixed in the development, as I said before.
