### ISSUE TITLE
Gyroscope custom icon

### ISSUE THREAD

**Issue by alketii** [mpetroff/pannellum#477]
Is it possible to customize gyroscope icon like other ones ?
https://pannellum.org/documentation/examples/custom-controls/

Thanks.

**Comment by mpetroff** [comment]
That depends on what you're trying to do. The custom controls example creates a set of buttons that call API functions; while not done in the example, these buttons could be placed outside of the viewer. However, the device orientation control toggle is not exposed via the API.

If you just want to change how the buttons inside the viewer look, you can override the CSS (see `.pnlm-orientation-button`).

**Comment by alketii** [comment]
Thanks for the reply.
Yeah, An API call for toggling the device orientation could be awesome.

Thanks again.

**Comment by mpetroff** [comment]
I just added `isOrientationSupported()`, `startOrientation()`, and `stopOrientation()` functions to the API.

**Comment by alketii** [comment]
Thank you very much.
