### ISSUE TITLE
Change panorama without reset position

### ISSUE THREAD

**Issue by DavidEscalante** [mpetroff/pannellum#485]
I made this demo:
https://d26dzxoao6i3hh.cloudfront.net/items/0O2f1c192L2y101w0Y3D/ScreenFlow.mp4

Im trying to achieve the same results with panellum, but im facing the problem that each time a new viewer is loaded, the whole "camera" position is reset to the default state, im trying to change the picture without altering the rotation position.

**Comment by mpetroff** [comment]
The `loadScene` method optionally takes `pitch`, `yaw`, and `hfov` parameters; you just need to use the current values when calling it:

```javascript
viewer.loadScene('newSceneId', viewer.getPitch(), viewer.getYaw(), viewer.getHfov());
```

where `viewer` is the Pannellum instance, and `newSceneId` is the scene ID of the scene you're switching to.
