### ISSUE TITLE
could you please tell me why my hotspots floating？ 

### ISSUE THREAD

**Issue by bingery** [mpetroff/pannellum#494]
sometimes one iusse come like 
when mousedown, the hotspots float to another place, when mouseup， they float back...

**Comment by bingery** [comment]
hotspots floating

**Comment by bingery** [comment]
![Uploading 微信图片_20171027114832.png…]()
also 'ctrl' key can change the position of the hotspots  keyup keydown

**Comment by bingery** [comment]
![down](https://user-images.githubusercontent.com/28039195/32087326-acf4433c-bb0d-11e7-8e1f-0510a6c0dddd.png)
![up](https://user-images.githubusercontent.com/28039195/32087327-ad2a68ae-bb0d-11e7-83fb-6c9469f45e06.png)

also 'ctrl' key can change the position of the hotspots, keyup, keydown

**Comment by mpetroff** [comment]
There's probably something wrong with the CSS you're using to change the hot spots.

**Comment by bingery** [comment]
hi, I found the point.  it's changing scene too fast,   does the pannellum has a callback when renderhotspots is  done ?

**Comment by mpetroff** [comment]
There's no callback for that. If you're changing scenes fast enough that there isn't time to render a single frame, you're using Pannellum in a way it wasn't designed for.

**Comment by bingery** [comment]
ok. I found I had used the wrong way to change Scene, I destroyed the viewer and add a new one.  It should use loadScene, thanks for your reply
