### ISSUE TITLE
Resolution is low on iOS device [equirectangular mode]

### ISSUE THREAD

**Issue by liujerry1992** [mpetroff/pannellum#496]
Hi, 

When I use the equirectangular mode, pano images on iPhone (especially the 6+ and 7+ device) is really blurry, you can see it below. This problem didn't happen when I use Panolens. For some limitation (can't be igonred), I have to use the equirectangular mode. Can you please help me solve this problem? really appreciate. By the way is there a method that can keep deviceorientation control and will not disabled when I do dragging? Really need that, thanks! 

* The image size is 4096*2048

![ddd](https://user-images.githubusercontent.com/20920917/32264690-dd58499a-bf1a-11e7-9058-edd574210d5f.PNG)
![img_0002](https://user-images.githubusercontent.com/20920917/32264702-e90770ae-bf1a-11e7-9387-7cb86ea2e79d.PNG)

Here is my html code, really sorry for using image, I tried to post in character and the composing is chaos:

![screenshot of sublime text 01-11-2017 3-57-23 pm](https://user-images.githubusercontent.com/20920917/32265309-7573b168-bf1d-11e7-9f43-f1c6adf953d9.png)
![screenshot of sublime text 01-11-2017 4-00-12 pm](https://user-images.githubusercontent.com/20920917/32265378-c41cf478-bf1d-11e7-843d-6abcb4f3940a.png)
![screenshot of sublime text 01-11-2017 3-57-46 pm](https://user-images.githubusercontent.com/20920917/32265327-80a3354a-bf1d-11e7-98c7-8278ba80816f.png)
![screenshot of sublime text 01-11-2017 3-57-46 pm](https://user-images.githubusercontent.com/20920917/32265332-8632545a-bf1d-11e7-8d77-2045edbc72f2.png)
![screenshot of sublime text 01-11-2017 3-57-54 pm](https://user-images.githubusercontent.com/20920917/32265336-88861e9e-bf1d-11e7-94c2-2bdf61985324.png)

**Comment by nikitades** [comment]
Hello @liujerry1992 !
Did you succeed with the bad quality on the iPhone and equirectangular panorama?

**Comment by nikitades** [comment]
Hello @mpetroff!
Is there any way to make the equirectangular panorama look better on iPhone?

**Comment by MirstrKot** [comment]
I have the same issue =(

**Comment by liujerry1992** [comment]
@nikitades @MirstrKot After two days trying, I find it's impossible for me at least to edit source code to solve this problem.

**Comment by mpetroff** [comment]
This a duplicated of #484. However, I can't reproduce it in Safari on an iPhone 5c running iOS 10.3.3.

**Comment by liujerry1992** [comment]
The problem only happens obviously on big screen iPhone. Problem on small screen iPhone like (iPhone6 or 5c) might not as obvious as big one. I guess Matthew can borrow a big screen to check the issue.

Best Regards
Yours Jerry
________________________________

**Comment by MirstrKot** [comment]
iPhone 5s looks ok, but iPhone 6s and iPhone 8 (iOS 11) can reproduce it. So, it’s not only “Plus” size issue.

**Comment by liujerry1992** [comment]
Thanks! That’s the correct situation.

Best Regards
Yours Jerry
________________________________

**Comment by risonsimon** [comment]
@mpetroff this is still a problem. :( Any pointers on how to solve this? I'm testing on iPhone 6.

**Comment by nikitades** [comment]
Well, this probably is up to the JS canvas issue. Some low-level stuff that prevents the panoram from looking good.

Anyway, a multires approach is definitely better, while a bit more difficult. The main trouble for me (but I'm sure not only me) is that `generate.py` is written in Python.

@mpetroff Could you please add to your development plan to make a pure JS or PHP clone of `generate.py`? 
(In case if it is not deeply bound with some python image manipulation libraries. But as far as I know, there are similar libraries in almost every wide-spread language)

**Comment by risonsimon** [comment]
I'm trying to understand what calculation issue is happening just for iPhone 6 and above.

**Comment by mpetroff** [comment]
@nikitades I have no intention of rewriting `generate.py` in anything other than Python.

**Comment by mpetroff** [comment]
I may have fixed this pixelation issue in 59893bcea4629be059ad3e59c3fa5bde438d292b. See https://github.com/mpetroff/pannellum/issues/725#issuecomment-482757714.
