### ISSUE TITLE
custom buttons for fullscreen

### ISSUE THREAD

**Issue by cswebdev** [mpetroff/pannellum#497]
Hey,

it would be nice if there were methods like:

isFullscreenSupported
startFullscreen
stopFullscreen

for custom fullscreen button

**Comment by mpetroff** [comment]
There's already a `toggleFullscreen` method. Detecting whether or not fullscreen is supported and whether or not fullscreen is active can be easily done using the standard [Fullscreen API](https://developer.mozilla.org/en-US/docs/Web/API/Fullscreen_API).

**Comment by cswebdev** [comment]
thank you for your answer.

i thought it would be better if you provide the line 235

if (document.fullscreenEnabled || document.mozFullScreenEnabled || document.webkitFullscreenEnabled || document.msFullscreenEnabled) {...}

in an api method like isFullscreenSupported() to reuse it. (you also did something like that for the orientation check, so i wonder why not the same structure for fullscreen)

but of course, i will use the Fullscreen API and implement it in my part of code.

thank you

**Comment by mpetroff** [comment]
Checking for device orientation support is much more complicated and involves actually testing the event.

**Comment by tikky** [comment]
I am with the same question. How to start full screen or 100% width and height.
I can set 100% width, but how to set 100% height.

I am trying <html height="100%">, <body height="100%"> but what shoul be in style to start 100% height. At the mment my settings are:
<style>
    #panorama {
        width: 100%;
        height: 800px;
    }
    </style>
