### ISSUE TITLE
isOrientationSupported

### ISSUE THREAD

**Issue by cswebdev** [mpetroff/pannellum#499]
Hello,

what is the best way to get the orientation support state?
i read in source code that the value will be set after a first window orientation event was triggered.

it would be great if there were a way to control this async change of state true/false

any ideas?

**Comment by mpetroff** [comment]
There's no other way to reliably detect device orientation support. The delay isn't noticeable; it's what used to display the device orientation control button.

**Comment by mpetroff** [comment]
(I assume based on the issue title that you've already seen the `isOrientationSupported()` API method.)
