### ISSUE TITLE
[Question]  only render half  height of a frame

### ISSUE THREAD

**Issue by arpu** [mpetroff/pannellum#500]
can i only render the half height of a frame (for stereo 3d video) 

![bildschirmfoto von 2017-11-04 16-24-33](https://user-images.githubusercontent.com/14173/32406671-dda08f0c-c17c-11e7-9b70-51fe6d43cb4a.png)

so on normal video player (desktop) the pannellum videojs should only render the mono part 
is this possible?

**Comment by mpetroff** [comment]
That's not possible as things are currently written.  If you really wanted to do this, you could change the [texture lookup line of the fragment shader](https://github.com/mpetroff/pannellum/blob/f0a7fcf02c8851124fad7c437e23f51b1e8a3f40/src/js/libpannellum.js#L1290). Serving two different video files would be better though, from a bandwidth perspective.

**Comment by rawnsley** [comment]
Implemented as suggested in this PR https://github.com/mpetroff/pannellum/pull/976
