### ISSUE TITLE
how convert equirectangular panorama into Pannellum's multiresolution

### ISSUE THREAD

**Issue by Bibbowski** [mpetroff/pannellum#504]
I did not understand how to convert an equirectangular panorama into Pannellum's multiresolution ... someone who explains to me? use windows

**Comment by Bibbowski** [comment]
C:\Users\abc>py c:\generate.py -n C:\Program Files\Hugin\bin\nona.exe c:\photo\1.jpg ... 
error: unrecognized arguments: c:\photo\1.jpg....

**Comment by Bibbowski** [comment]
C:\Users\abc>py c:\photo\generate.py C:\photo\1.jpg -n C:\photo\nona.exe
I copied the nona.exe content and the dlls into the photo folder, now when i boot I get an error, the program can not write the files because they already exist ...

**Comment by mpetroff** [comment]
You need to place the path to `nona.exe` in quotation marks. The way you wrote it, the path to `nona` is `C:\Program`, the image path is `Files\Hugin\bin\nona.exe`, and `c:\photo\1.jpg` is an extra unrecognized argument, hence the error message.

**Comment by Bibbowski** [comment]
thanks for responding, now i managed to run the generate.py only i can not write, i give this error "FileExistsError: [WinError 183] ..."

**Comment by Bibbowski** [comment]
ok, I managed to generate files ... now I try to put them in the project!

**Comment by Bibbowski** [comment]
I was trying to write to a folder on which my windows user did not have write permissions ... changing the folder and putting one on the desktop wrote the files

**Comment by DavisGuohua-xie** [comment]
Hello @Bibbowski  @mpetroff 
Can you share a bit how many pictures are needed to achieve the same goal, converting equirectangular panorama into Pannellum's multiresolution ? 
any hint or step are really appreciated.
