### ISSUE TITLE
Pannellum example not working in IE but in Chrome

### ISSUE THREAD

**Issue by SeppPenner** [mpetroff/pannellum#509]
Hi,

I tried to use the pannellum example to provide a panorama example on my Tomcat webserver.
Example code can be found here: https://github.com/SeppPenner/PannellumTest

The problem occurring now is that the page is displayed correctly in Chrome but not in IE.

Chrome has the version: Version 62.0.3202.94 (Official build) (64-Bit)
IE has the version: 11.0.9600.18837 with update version 11.0.48
Tomcat web server has the version: 8.0.32

Could you take a look at the example provided if there is any issue in it to cause this problem, please? The https://pannellum.org/ website with the library view works on both browsers (That's what looks a bit strange to me).

**Comment by mpetroff** [comment]
Your repository appears to just have code that's copied verbatim from Pannellum, so I'm guessing it has something to do with how your server is configured or where the files are located on it.

Does the IE developer console display an error message?

**Comment by SeppPenner** [comment]
> Your repository appears to just have code that's copied verbatim from Pannellum, so I'm guessing it has something to do with how your server is configured or where the files are located on it.

That's correct. Well, the developer console doesn't Show any errors. Nevertheless, I figured out what was the issue.

Setting the document mode to "Edge" like described here https://stackoverflow.com/questions/10975107/forcing-internet-explorer-9-to-use-standards-document-mode works:

`<meta http-equiv="X-UA-Compatible" content="IE=Edge">`

**Comment by mpetroff** [comment]
I'm guessing IE 11 was using its "Compatibility View" for your page, causing it to act like an older, unsupported version of IE.

**Comment by SeppPenner** [comment]
Strange behaviour, yes. I hope that Microsoft forces to use the Edge browser soon and disables the IE forever :D

**Comment by mpetroff** [comment]
Since you have things working, may I close this issue?

**Comment by SeppPenner** [comment]
Yes, this can be closed.
