### ISSUE TITLE
External config file can not load panorama

### ISSUE THREAD

**Issue by carlsteinhilber** [mpetroff/pannellum#51]
Using ?config= no longer seems to be able to load the pano image.

Very simple ex:
```
<iframe title="pannellum panorama viewer" width="400" height="350" allowfullscreen style="border-style:none;" src="/lib/pannellum/pannellum.htm?config=/panorama/test.json"></iframe>
```

test.json:
```
{
    "autoload": true,
    "panorama": "/images/panorama.jpg",
    "showFullscreenCtrl" : false
}
```

The config file is located, because the `showFullscreenCtrl` parameter is interpreted (false and the control does hide, true and it shows) but the actual image never loads, and watching the console shows the error

"Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check http://xhr.spec.whatwg.org/."

at line 72 of pannellum.htm

Using URL parameters
```
<iframe title="pannellum panorama viewer" width="400" height="350" allowfullscreen style="border-style:none;" src="/lib/pannellum/pannellum.htm?panorama=/images/panorama.jpg&amp;amp;autoLoad=true"></iframe>
```

works just fine. Image auto loads. But of course I don't have control over the appearance of the Full Screen control (which, btw, does not seem to work in Chrome v.40) or the h/vaov that I need. The console does report "Resource interpreted as Image but transferred with MIME type text/html", though the image is correctly loaded.

**Comment by mpetroff** [comment]
1. In the JSON, `autoload` should be `autoLoad`. Changing this should hopefully fix things for you.
2. The message about the synchronous XMLHttpRequest is a deprecation warning, which doesn't affect anything.
3. I just tested in Chromium 40, and the fullscreen control still works for me.
4. The MIME type text/html warning suggests that your server is misconfigured and claims in the response headers that the image is an HTML document (again this doesn't affect how Pannellum works).
