### ISSUE TITLE
Can I disable the loading bar

### ISSUE THREAD

**Issue by peterycyeh** [mpetroff/pannellum#511]
I have multi panorama in  a div which has id="panorama"
And I set the view will be changed when I clicked a button as following function.
However, it will show the loading bar every time when I click the button.
Does it possible to disable the loading bar, or any other trick to hide it. 
(load each view at initially and show the selected view which is loaded when button clicked.)
Thank you for your help, and the wonderful plugin.

```
setPanorama(index) {
    this.viewer = pannellum.viewer('panorama', {
    type: 'equirectangular',
    panorama: this.levels[index].image,
    autoLoad: true,
    })
}
```

**Comment by mpetroff** [comment]
If you use multiresolution images, the loading bar is not displayed. That's currently the only way to disable the loading bar.

While it's not currently the case, there's no need for a loading bar when `blob:` URLs are used, so not showing a loading bar when they're used would be a good feature to add. With this featured added, images could be pre-loaded with external code, `blob:` URLs could be created for each, and then these URLs could be used with Pannellum.

**Comment by strarsis** [comment]
You could try to just hide it using CSS:
```css
#load_box {
  display: none;
}
````
But these styles must apply to the pannellum viewer inside the iframe –
or you have to initialize pannellum on a DIV instead (and don't embed it using an iframe).

**Comment by peterycyeh** [comment]
Thank you for both of your reply.
It gets me some inspiration to hide the loading bar.
I just change some css style in the class which name is 'pnlm-load-box'.
And it works fine to me now.
Thank you so much!

**Comment by periman2** [comment]
If anyone still interested what worked for me was the following css :

.pnlm-load-box {
  z-index:-999;
  opacity: 0;
}
