### ISSUE TITLE
Question: How to load a scene?

### ISSUE THREAD

**Issue by zzseba78** [mpetroff/pannellum#512]
Hi there. Great plugin! Using it for first time.
I have to load distinct views of apartments in a modal window.
I try but can´t get the result ( i pretty basic in js knowledge 😄  )

Sorry for put this question here, but i don´t find another way to ask. Any help it´s welcome. Thanks!
```
// Set the scenes
pannellum.viewer('panorama', {
  		"scenes": {
  			"AptoD": {
	        "type": "equirectangular",
		     "panorama": "panorama/360_MON_D_COCINA.jpeg",
		     "autoLoad": true,
		     "autoRotate": -2
	    	},
	    	"AptoB": {
	        "type": "equirectangular",
		     "panorama": "panorama/360_MON_B_COCINA.jpeg",
		     "autoLoad": true,
		     "autoRotate": -2
	    	}
  		}
	});
// On modal shown load the view
$('#panorama-1').on("shown", function () {
	// load scene "AptoD"
});
```

**Comment by mpetroff** [comment]
You need to first assign the viewer to a variable by changing the first line to `var viewer = pannellum.viewer('panorama', {`. You can then change the scene using the [`loadScene`](https://pannellum.org/documentation/api/#loadscene) method, e.g. `viewer.loadScene('AptoD')`.

**Comment by zzseba78** [comment]
Amazing! Works great, thank you! Closing this.

**Comment by prosenba** [comment]
Hi,
I'm excited to be using 360 pictures in my websites but I'm having issues with dragging the picture around, the mouse cursor shows a circle with a slash in it.  The only pictures I can get to work on the sample images from the examples page. The picture was taken with Nikon KeyMission 360.

Thanks
