### ISSUE TITLE
Can I slow down rotation speed when I drag it by using touchscreen

### ISSUE THREAD

**Issue by peterycyeh** [mpetroff/pannellum#514]
When I run dev version on my pc. The rotation speed looks good. (not auto rotate)
however, when I build it, and put it on mu touchscreen, the rotation speed is too sensitive.
The views move quite quickly, is there anyway to slow them down a bit? 
Thank you!

**Comment by peterycyeh** [comment]
I just did it by changing the value of touchmovePanSpeedCoeff in function onDocumentTouchMove. Thank you!

**Comment by bsdshneg** [comment]
How you did it?
