### ISSUE TITLE
Add option for setting `crossOrigin` to `use-credentials`

### ISSUE THREAD

**Issue by afriedle** [mpetroff/pannellum#515]
I'm loading multires tiles inside a web application from the same origin over a proxy (Load balancer). This works for Chrome, Internet Explorer, Edge and Firefox, but not for Safari (Desktop and Mobile). All browsers except Safari send their cookies in the header file (Which is needed for validating the session).

Changing crossOrigin="anonymous" to crossOrigin="use-credentials" in pannellum solved this issue for Safari. Would it be possible to make this the new default crossOrigin behavior for fetching tiles?

Thanks!

**Comment by afriedle** [comment]
Setting it as an option in the config.json would be a nice workaround (Default could still be `crossOrigin` set to `anonymous`). I already got it to work with the manual change, but that's always a dangerous game with future framework updates.

In any case, appreciating your work, the viewer works great :)

**Comment by mpetroff** [comment]
I added a `crossOrigin` configuration parameter in 2de1706be087930fb0e7cf6f13026e5dcd87aba5.
