### ISSUE TITLE
Share URL of a specific scene inside a tour

### ISSUE THREAD

**Issue by robertdrost** [mpetroff/pannellum#519]
Hey,

i want to give the users the ability to copy the URL of a specific scene inside the tour, so that they can share it with other users. Is there an easy way to do it? 

Thanks,
Rob

**Comment by mpetroff** [comment]
Set the `firstScene` URL parameter to the scene you want.

**Comment by robertdrost** [comment]
Hi and thank you for the quick response.
It might be, that I did not understand you correctly, but doesn't that mean, that I have to change the `firstScene` URL parameter every time a user changes the scene?
To clarify my problem: Imagine the first scene/start position of my tour is "house #1". A user clicks a tour-hotspot at "house #1" to change the scene/position to "house #2". Now the user wants to send a link to this position to his buddy. He copies the URL out of the browsers adress bar and sends it to his buddy. The buddy now clicks the link he got and automatically starts the tour at "house #2". 
At the moment every link I could send, starts at the first scene "house #1". 

It is important for me to have this function, because I've got a tour with 28 scenes and I want to make it possible to send my friends a link to every scene like "lets meet at this place: -URL of the scene/position-"

**Comment by mpetroff** [comment]
The URL does not automatically update. If you want this functionality, you'll have to write your own page using the API instead of using `pannellum.htm` and use a `scenechange` event handler to update the URL. You then need to parse the URL when the page is loaded to appropriately set the first scene in the configuration.
