### ISSUE TITLE
z-index problem in fullscreen

### ISSUE THREAD

**Issue by jimblue** [mpetroff/pannellum#520]
Hi there!

First thanks for your nice plugin, I've tested all of panorama plugin and  yours is from far number one!

I can't say my problem is a bug as your demo don't have it... but you'll probably be able to help me out.

As explain in the title I'm having issue configuring z-index on full screen. Even if I change the css to give pannellum container the higher z-index, some element of my design still show up on top of the panorama.

You can see this problem on the live website under projects section. (click on 360 and choose a panorama)

https://goo.gl/ruxjWb

Hope you have a solution or maybe a hint.

Cheers

**Comment by MmmDee** [comment]
Great photography and website Jim. I didn't see any evidence of the problem you describe; however, I did note losing the ability to pan the image when in full screen mode. I'm using Chrome  63.0.3239.84 on Linux Mint 18.2.

This is the only message I see on the Developer's console:

Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://www.youtube.com') does not match the recipient window's origin ('https://immersion-pictures.com').
f.C @ www-widgetapi.js:114

**Comment by jimblue** [comment]
Hello @MmmDee !

Thank you for your comment 😄 !

The overlay you notice on chrome is the overlay of the landing fullscreen video...
I don't understand how pannellum fullscreen works as even if I change the z-index of pannellum to be superior to this overlay it's always visible... (you can try from the console)

In safari it's even worst as pannellum doesn't show up on full screen!

PS: also could you remove the url of my website in your comment please, it's not good for SEO. thank you 😄 !!

**Comment by MmmDee** [comment]
@jimblue 

Deleted the link per your request. It appears Firefox works as you intend, but Safari and Chrome (latest version on Linux) do not.  Safari on an iPhone 8+with IOS 11.1.1 shows the "small" pan-able image, but won't switch to full-screen.

Again, great website, good luck to you.

**Comment by strarsis** [comment]
Please note that for `z-index` having any effect the element must be either `position`ed `absolute` - or `relative`. `z-index` is ignored for defaut `position: static`.

**Comment by mpetroff** [comment]
I'm closing this issue since there's no link for me to look at.

**Comment by jimblue** [comment]
Sorry @mpetroff here is a link: https://goo.gl/ruxjWb

**Comment by jimblue** [comment]
@strarsis yes I use absolute position and z-index... Still it doesn't seems to have effect.

**Comment by mpetroff** [comment]
This appears to be a bug in Chrome itself. I can make other elements on the page that don't have Pannellum fullscreen and still show the issue, e.g. open the lightbox for one of the videos and run `document.querySelector('.project-wrapper').webkitRequestFullScreen()` in the browser console. I found something that suggests it might have to do with the CSS animation: https://stackoverflow.com/questions/44321110/youtube-full-screen-video-behind-html-content
