### ISSUE TITLE
QUESTION: Custom button for orientation toggle

### ISSUE THREAD

**Issue by danburns3** [mpetroff/pannellum#522]
I am creating custom controls as described on page https://pannellum.org/documentation/examples/custom-controls/

Is there way to implement orientation when user is in mobile similar to the other buttons?
```javascript
document.getElementById('fullscreen').addEventListener('click', function(e) {
    viewer.toggleFullscreen();
});
```
something like?
```javascript
document.getElementById('gyroscope').addEventListener('click', function(e) {
    viewer.toggleGyroscope();
});
```

new to jQuery so not sure how to identify correct function

**Comment by strarsis** [comment]
https://github.com/mpetroff/pannellum/blob/f0a7fcf02c8851124fad7c437e23f51b1e8a3f40/src/js/pannellum.js#L238

**Comment by danburns3** [comment]
Thanks again for the guidance @stratis

I have used the following code but it is not working for me.

```javascript
document.getElementById('orientation').addEventListener('click', function(e) {
    if (orientation)
        stopOrientation();
    else
        startOrientation();
});
```

The button that has #orientation is viewable even if user is using CPU rather than a device that rotates.

I have also tried the following code as well

```javasrcipt
document.addEventListener('click', function(e) {
    if (orientation)
        stopOrientation();
    else
        startOrientation();
});
document.addEventListener('mousedown', function(e) {e.stopPropagation();});
document.addEventListener('touchstart', function(e) {e.stopPropagation();});
document.addEventListener('pointerdown', function(e) {e.stopPropagation();});
document.className = 'ctrl-orientation';
var orientationSupport, startOrientationIfSupported = false;
function deviceOrientationTest(e) {
    window.removeEventListener('deviceorientation', deviceOrientationTest);
    if (e && e.alpha !== null && e.beta !== null && e.gamma !== null) {
        controls.container.appendChild(controls.orientation);
        orientationSupport = true;
        if (startOrientationIfSupported)
            startOrientation();
    } else {
        orientationSupport = false;
    }
}
if (window.DeviceOrientationEvent) {
    window.addEventListener('deviceorientation', deviceOrientationTest);
} else {
    orientationSupport = false;
}

```

Any additional guidance would be greatly appreciated.

**Comment by mpetroff** [comment]
You need to edit your first snippet to call the function on the viewer object, e.g. `viewer.startOrientation();`. As this API function was added after the 2.3.2 release, you'll have to use the Git `master` branch instead (see #477 for when this was added).
