### ISSUE TITLE
Detect Control Method On Mobile (Device/Manual Swipe)

### ISSUE THREAD

**Issue by emaglic** [mpetroff/pannellum#524]
Is there a way to detect whether the user is using manual swipe controls or the device orientation controls on mobile? 

Note:
I did notice that on mobile at div class 'pnlm-orientation-button' I can check for the following additional classes:
With Device Orientation Controls ON: pnlm-orientation-button-active (this class is present)
With Device Orientation Controls OFF: pnlm-orientation-button-active (this class is NOT present)

Also, I see that I can use orientationOnByDefault if it's available, but it doesn't tell me which control method is active at any given time.

While checking for the pnlm-orientation-button-active class seems like it will work in theory, I was wondering if there was a standard Pannellum method that I was missing.

Also Matthew, thank you for providing such great support for people with questions, it is greatly appreciated, you are awesome!

**Comment by mpetroff** [comment]
There's no way to detect this using the API. What's the use case? I can add an API method if the use case seems generally applicable.

**Comment by emaglic** [comment]
So this is probably not that common of a use case, but in the project I'm working on I have multiple Pannellum instances on a single page. As the user scrolls through the page and engages with a different Pannellum instance, I was hoping that I could make some of their chosen params, like device orientation / swipe controls, zoom value, etc carry over from one Pannellum instance to another. That way if they do view on mobile and use device controls, each instance will use the device controls or vice versa.

**Comment by strarsis** [comment]
@mpetroff, @emaglic: Yes, an API for retrieving the user/UI settings would be a nice addition! (+1)

**Comment by mpetroff** [comment]
That's sounds reasonable. I'll see about adding it.

**Comment by mpetroff** [comment]
I just added an `isOrientationActive()` method in 14a7032a525560b310f7db4ba0ec454bbc78bca8.
