### ISSUE TITLE
Hotspots disappearing after changing scenes

### ISSUE THREAD

**Issue by ajorquera** [mpetroff/pannellum#529]
Following your example of a tour, https://pannellum.org/documentation/examples/tour/

If you create the hotspot dynamically  with addHotSpot method, the hotSpot disappears after changing scenes. The workaround I did, was to load the pano hotSpots on the onload event every time the scene changes.

**Comment by mpetroff** [comment]
The `addHotSpot` method adds the hot spots to the current view but doesn't modify the configuration, so this is the expected behavior.

**Comment by ajorquera** [comment]
so there is no way to change the configuration once the viewer has been instantiated? This would be necessary if you want to create tours dynamically

**Comment by mpetroff** [comment]
There's no directly modify the configuration, but it's possible to create tours dynamically, since scenes can be added with the `addScene` method.

**Comment by ajorquera** [comment]
Yes, but as you explain earlier addHotSpot doesn't change the configuration. I imagine addScene would work the same way. Every time a scene has loaded, these methods will need to be called again. I'll close this ticket as this is the expected behavior.

**Comment by ajorquera** [comment]
Closing

**Comment by mpetroff** [comment]
The `addScene` method is persistent between scene changes.
