### ISSUE TITLE
Hi Resoloution tiles

### ISSUE THREAD

**Issue by kyoukhana** [mpetroff/pannellum#530]
I was wondering how can I get Hi Resolution tiles.    When I create my tiles they look all washed out and low resolution. 

```
python generate.py -n /Applications/Hugin/HuginStitchProject.app/Contents/MacOS/nona GNXA2748.JPG
```

**Comment by mpetroff** [comment]
That shouldn't be the case. Do you have an example or screenshot that shows the issue?

**Comment by kyoukhana** [comment]
When I run the following command 

```
python generate.py 

```

I need a example on -q for quality.
