### ISSUE TITLE
Couldn't able to scroll in mobile

### ISSUE THREAD

**Issue by dsushmasagar** [mpetroff/pannellum#531]
user couldn't able to scroll when user is on the 360 image in mobile. when pointer is on the image we could only able to drag through the image around 360 degrees.  How do I enable page scroll when user reaches to bottom end point of the image?

**Comment by mpetroff** [comment]
The Git `master` version has a `draggable` parameter that disables mouse and touch input. You can also make the viewer shorter, so there's room for the user to drag above and below the viewer.
