### ISSUE TITLE
How to change the default loading animation ? 

### ISSUE THREAD

**Issue by lajeet123** [mpetroff/pannellum#535]
I want to use my custom loading animation, instead of the default one i.e. using css. I want to use a custom file may be any gif file.

**Comment by mpetroff** [comment]
I assume you're using a cube map image, since equirectangular images use a loading bar. You'll want to modify the `pnlm-loading` class in that case.

**Comment by lajeet123** [comment]
Yes. Exactly. But do I need to go change the library for that, or I can achieve it through my javascript code also ? It will be helpful if you show me an example of that.

**Comment by mpetroff** [comment]
You can either modify the library's CSS or override it (using `!important`).
