### ISSUE TITLE
Black image showed

### ISSUE THREAD

**Issue by xtrabcn** [mpetroff/pannellum#539]
Hello. First congratulation for this apport.

You can see [example](http://subastacar.com/vehiculo/BMW-X4-xDrive-20d-A-(F26)/d8da5105fb)

Click on Foto 360 buttom

Im calling the pannellum viewer like that
```javascript
$('.ver360').click(function(){

	var foto=$(this).attr('foto');
	var titulo=$(this).attr('titulo');
	var car=$(this).attr('codigo');
						
	//if(typeof(visor360) != "undefined"){ visor360.destroy(); };
		
	var visor360=pannellum.viewer('panorama', {   
		"type": "equirectangular",
		 "panorama": "http://subastacar.com/img/img_g/"+foto,
		"preview": "http://subastacar.com/img/img_p/"+foto,
		"autoLoad":true,
		"title":titulo,
		"autoRotate":15,
		"autoRotateInactivityDelay":3000,
		"pitch":-40
	});
)}
```

But one time the image is charge the first time, when i close the window and i try to open again, the windows is black, only i can see the project working if i see in full screen.

The problem is that I wanna have a container "panorama" and charge different images from different buttom.

Can you take a look , thanks!!

**Comment by mpetroff** [comment]
I can close and reopen the window without any issue. I'm not really sure what else you're asking.
