### ISSUE TITLE
Too many active WebGL contexts. Oldest context will be lost.

### ISSUE THREAD

**Issue by xuantps** [mpetroff/pannellum#540]
i get this error "Too many active WebGL contexts. Oldest context will be lost." when i have alot of pano loading, pls give me guide to fix it, i use version 2.3
Thanks

**Comment by mpetroff** [comment]
What do you mean by having a lot of panoramas loading? Are you trying to open dozens of viewers on the same page? Web browsers limit the number of simultaneous WebGL contexts, so only a few different panoramas can be displayed at once.

**Comment by xuantps** [comment]
yep , thank for your info
