### ISSUE TITLE
WKWebview (used wihtin ionic 3.9.2) not showing image - stops at loading with loading done 100%

### ISSUE THREAD

**Issue by dwegzero** [mpetroff/pannellum#542]
Hi,
in an ionic app using WKWebview (plugin version 1.1.16 - cordova engine for ios 4.5.4) the loading panel is shown with the cubes in the background and you can see the progress until it is finished for example "694.4 / 694.4 kB". Nothing else happens - there is even no output to the console. Any ideas?
Thank you

**Comment by mpetroff** [comment]
Ionic reimplements `FileReader` in a non-standards compliant way. See #284.

**Comment by dwegzero** [comment]
Thanks,

so here is what I did to to resolve this issue for me:
I've simply added addEventListener in my components constructor as an extension to cordovas FileReader like this:

`    window.FileReader.prototype.addEventListener = function (type, listener) {
      console.log('FileReader patch');
      if (type === 'loadend') {
        console.log('FileReader patch for loadend');
        this.onloadend = listener;
      }
    };
`
Works like charm now!

**Comment by einfochips1** [comment]
Hello @dwegzero ,

I am new in ionic-3 technology, Please help me to solve the issue:
`[ts] Property 'FileReader' does not exist on type 'Window'.`

my Ionic info:
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 7.1.0 

local packages:

    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : android 6.3.0 ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    ios-deploy        : 1.9.2 
    Node              : v9.6.1
    npm               : 5.6.0 
    OS                : macOS High Sierra
    Xcode             : Xcode 9.2 Build version 9C40b 

Thanks,
Punita

**Comment by dwegzero** [comment]
Hello @einfochips1 ,

This is an excerpt of what I've done:


`import { Component, OnInit, OnDestroy, Input, ViewChild, ElementRef } from '@angular/core';
import 'pannellum/build/pannellum.js';
declare var pannellum: any;
declare var window: any;

@Component({
  selector: 'pano',
  templateUrl: 'pano.html'
})
export class PanoComponent implements OnInit, OnDestroy {
  @ViewChild('container') container: ElementRef;
  @Input() src: string;
  @Input() options: Object;
  viewer: any;
  id: string;

  constructor() {
    // patch FileReader to be standard compliant beacuse it get's used this way in pannellium viewer
    // cordova's cordova-plugin-file (native file) overwrites the standard implementation for FileReader
    // console.log('FileReader.addEventListener test:', window.FileReader.prototype.addEventListener);
    if (!window.FileReader.prototype.addEventListener) {
      window.FileReader.prototype.addEventListener = function (type, listener) {
        if (type === 'loadend') {
          this.onloadend = listener;
        }
      };
      console.log('FileReader patch for loadend injected');
    }

    this.id = 'panoid'; // Math.random().toString(36).substring(2);
  }
  ngOnInit(): void {
    const defaultOptions = {
      "type": "equirectangular",
      "panorama": this.src
    };
    const combinedOptions = Object.assign({}, defaultOptions, this.options);
    // Panellum
    this.viewer = pannellum.viewer(this.container.nativeElement, combinedOptions);
  }

  ngOnDestroy(): void {
    this.viewer.destroy();
  }
}
`

**Comment by einfochips1** [comment]
Thanks, @dwegzero  @mpetroff 
Image loading issue is fixed now.

But now facing CORS issue. Check everything at server CORS settings and sent crossorigin parameter on options, but still facing the same CORS issue. Ionic app worked perfectly on Chrome browser and Android Platform. But CORS issue on iOS only.

Image URL: https://poquito-local.s3.amazonaws.com/uploads/vimeo_upload/file_name/200/hepsumvx.jpg
Please help!!

ngOnInit(): void {

    console.log('in ngOnInit() Image URL::::===>' + this.src);
    const defaultOptions = {
      "type": "equirectangular",
      "panorama": this.src,
      "autoLoad": true,
      "autoRotate": 1.5,
      "crossOrigin": "anonymous"
    };
    const combinedOptions = Object.assign({}, defaultOptions, this.options);
    // Panellum
    this.viewer = pannellum.viewer(this.container.nativeElement, combinedOptions);
  }

This sample worked perfectly:
https://cdn.pannellum.org/2.4/pannellum.htm?panorama=https://poquito-local.s3.amazonaws.com/uploads/vimeo_upload/file_name/200/hepsumvx.jpg


Thanks,
Punita

![Uploading Screen Shot 2018-04-12 at 7.59.53 PM.png…]
![screen shot 2018-04-12 at 8 09 14 pm](https://user-images.githubusercontent.com/13536916/38684474-65d64dde-3e8d-11e8-9816-80be5c32351c.png)
()

**Comment by dwegzero** [comment]
Did you solve the issue?
loading the image https://poquito-local.s3.amazonaws.com/uploads/vimeo_upload/file_name/200/hepsumvx.jpg shows me:
```
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>3EDA2947EA967853</RequestId>
<HostId>
boCTgB3LkbV1de4kgs9R4X4EziaNNT0rHKgL3q1+SC86FRWOKVajju8Tw1winnkbjOmZm0HKTVc=
</HostId>
</Error>
```
...

**Comment by einfochips1** [comment]
Thank You @dwegzero 

Yes CORS issue Fixed.
But facing one new [issue#590](https://github.com/mpetroff/pannellum/issues/590)

Please give your valuable feedback, if you are facing or not same issue.

Thanks,
Punita
