### ISSUE TITLE
Bootstrap Modals

### ISSUE THREAD

**Issue by zhill123** [mpetroff/pannellum#543]
Hi, 
Is there an easy way to trigger a bootstrap modal by clicking on the hotspot?  

Triggering a modal in bootstrap is pretty straightforward:
`<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">`

How would I get data-toggle and data-target attributes into the hotspot html div?

Thanks for your help.

**Comment by mpetroff** [comment]
Use the [JavaScript method of opening modals](http://getbootstrap.com/docs/4.0/components/modal/#via-javascript) via the [`clickHandlerFunc` and `clickHandlerArgs`](https://pannellum.org/documentation/reference/#createtooltipfunc-function-and-createtooltipargs-object) hot spot configuration parameters.

**Comment by kokoruz** [comment]
for the items in my hotSpots array I am using the clickHandler listed above
`"clickHandlerFunc": videoModal,
"clickHandlerArgs": "video1"`

that calls the function videoModal
`function videoModal(hotSpotDiv, args) {
    var modalID = args;
    console.log(modalID);
    if (modalID == "video1") {
        $('#video1').modal();
    } else {
        $('#video2').modal();
    }  
}`
this triggers the bootstrap modal to fade in the modal div with the id that is passed.  In my case it will be one of 2 videos playing in the modal.

What I hope someone can explain to me is why the args is the second parameter in my function and what would the first parameter be used for.  Right now my first parameter does nothing.  I discovered the args needed to be the second parameter by trial and error.  I'd love to have a better understanding of what the first parameter could be used for and if the documentation show the args as the second parameter.  Thank You

**Comment by mpetroff** [comment]
@kokoruz You already posted virtually the same comment in #400. Posting the same comment twice is not constructive. Please don't do this again.

**Comment by kokoruz** [comment]
I apologize for that.  When I posted the question in the other thread I did not realize it was closed.  I went to delete it but then did not see it so I made the assumption that my post to a closed thread was removed.  Thank you for explaining that the first argument was 'click'.  can you provide a link to the documentation that explains that.  I have been using https://pannellum.org/documentation/reference/ but if there is something else I would appreciate that as well.  Thanks again for you fast response and apologizes for the double post.

**Comment by mpetroff** [comment]
The documentation you linked to *does* explain that. It's what I quoted in response to your comment on #400.
