### ISSUE TITLE
Is there a way to change out the 360 image without adding a scene and switching scenes?

### ISSUE THREAD

**Issue by trockefeller** [mpetroff/pannellum#545]
I have equirectangular jpgs, and I would like to update the current image displayed and have a sort of video playback, but with several individual jpg images rather than a video file.

The only way I see that I could do this is by adding and removing scenes and switching scenes. Is there a better way of handling this?

Thanks,
TJ

**Comment by mpetroff** [comment]
If there are only a few images, there's no need to add and remove the scenes. You would just need to change scenes.

You could also use the functionality included; for video support; see https://github.com/mpetroff/pannellum/issues/459#issuecomment-359195487.

**Comment by trockefeller** [comment]
Thanks for your help. Dynamic is what I was looking for, and I just didn't realize using dynamic with multiple images was so easy. The only dynamic example uses video.js, so it's set up very differently than the code you posted on that other issue.
