### ISSUE TITLE
Drawing Lines and labeling hotspots

### ISSUE THREAD

**Issue by KorecGroup-NeilGiddings** [mpetroff/pannellum#547]
Hiya, 

I am looking into Pannellum and wanted to know how I could go about doing the following:
a) join hotspots up with lines a bit like join the dots.
b) change the hotspot icon dynamically
c) actually be able to draw objects

Are these possible and any hints on the best approach?

Neil

**Comment by mpetroff** [comment]
a) No
b) Hot spots are styled via CSS (see [custom hot spots example](https://pannellum.org/documentation/examples/custom-hot-spots/)), so this should be possible by dynamically changing the CSS
c) No

**Comment by KorecGroup-NeilGiddings** [comment]
thanks for that pity about a and c would have been nice to have done those two elements.
