### ISSUE TITLE
scenechange: sceneId argument different

### ISSUE THREAD

**Issue by strarsis** [mpetroff/pannellum#550]
When changing the scene using the Pannellum API (by clicking a hotspot),
the `scenechange` gets the scene ID as parameter.

However, when using `loadScene` for changing a scene, 
the scene object is inexplicably passed as parameter to the `scenechange` handler instead.
Also, there is no scene ID in scene object (the scene object is assigned as key to `scenes`).
`getScene()` returns `undefined`.

**Comment by mpetroff** [comment]
I don't see any way this can happen unless you're passing an object as the `sceneId` argument to `loadScene` instead of a string. The `sceneId` argument is passed to the `scenechange` handler without any modification.

**Comment by strarsis** [comment]
@mpetroff: Indeed, I passed a scene object. Adding more assertions to these functions could make detection of these issues earlier?
