### ISSUE TITLE
iframe on android go to the top of image

### ISSUE THREAD

**Issue by Leonardone** [mpetroff/pannellum#551]
Matthew, first of all, thank you for everything...Pannellum is really good!
But when i see a page (with iframe) on mobile, and try to move in some direction, the viewer go on top of the view automatically and after another "tap" on screen it goes always on top. 
I try also on your example (https://pannellum.org/documentation/examples/simple-example/) and do the same.
If i turn on fullscreen all goes very well.
There's something I can do? 
Or there's a way to add automatically fullscreen by clicking on the "load panorama" button?
Thank you in advance!

**Comment by mpetroff** [comment]
I have no idea what you mean by "the viewer go on top of the view automatically."

**Comment by Leonardone** [comment]
Sorry, i'm not so able to explain. So i've added a video on dailymotion to "display" my question.
Hope it'll be more clear!
http://www.dailymotion.com/video/x6f6o7t
thank you in advance!

**Comment by mpetroff** [comment]
Now I can see what you mean, and I'm also able to reproduce it. I'll look into it.
