### ISSUE TITLE
Firebase Storage File Could Not Be Accessed

### ISSUE THREAD

**Issue by Plinpod** [mpetroff/pannellum#552]
Hey!

I was trying to use pannellum with a Firebase Storage url but it gives a File Cannot Be Access error. I know the permissions on the is open to all since I can view it in browser and upload it via url to imgur etc. Anyone know how to fix or troubleshoot this error properly? 

Thanks!

**Comment by mpetroff** [comment]
I'm sure your browser's developer tools will tell you why you can't access the file. The issue is almost certainly a configuration issue.

**Comment by Plinpod** [comment]
Thank you, you were right it was a cross origin header issue and was fixed by following the steps here
https://stackoverflow.com/questions/37760695/firebase-storage-and-access-control-allow-origin
