### ISSUE TITLE
Make `usedKeyNumbers` configurable

### ISSUE THREAD

**Issue by dmorgenstern-init** [mpetroff/pannellum#554]
In some cases, it would be useful, to define, which keys should be used and which not.
For example, if you would like to enable the user to control the viewer via keyboard, but want to disable `shift` and `ctrl` keys, or you want to navigate the camera with arrow keys but disable the control via WASD, it would be a very simple solution, to make the `usedKeyNumbers` array configurable, so that one can explicitly define which keys should be actually used.

**Comment by mpetroff** [comment]
Thanks! I renamed it to `capturedKeyNumbers` in 46b6b9c07379d0453d739d45331fce524fda7fdf to make it more descriptive, since now that it's configurable, it's no longer necessarily the keys that are used.

**Comment by dmorgenstern-init** [comment]
Cool! Thank you for merging my changes and the renaming hint! ;)
