### ISSUE TITLE
Tour Pitch and Yaw

### ISSUE THREAD

**Issue by Meeett** [mpetroff/pannellum#560]
Sorry if this is a double Issue...

If I create a tour and switch the Scene with '"type": "scene",' the Pitch and Yaw will always reset to the original Values.
I write some JS to get the Pitch,Yaw and Hfov of the old scene to the new to keep the Orientation.

```javascript
var tmpYaw = 0;
var tmpPitch = 0;
var tmpHfov = 110;
$(document).on("click", ".pnlm-hotspot-base", function() {
	tmpYaw = viewer.getYaw();
	tmpPitch = viewer.getPitch();
	tmpHfov = viewer.getHfov();
});
$(document).on("touchstart", ".pnlm-hotspot-base", function() {
	tmpYaw = viewer.getYaw();
	tmpPitch = viewer.getPitch();
	tmpHfov = viewer.getHfov();
});
function sceneChangeListener() {
	viewer.setYaw(tmpYaw,0);
	viewer.setPitch(tmpPitch,0);
	viewer.setHfov(tmpHfov,0);
	viewer.setHfov(110);
};
viewer.on('scenechange', sceneChangeListener);
```

But is there a better way to solve this problem?

**Comment by mpetroff** [comment]
Hot spots have optional `targetPitch`, `targetYaw`, `targetHfov` parameters. If these are set to `same`, the current values are used for the new scene, which seems to be what you're trying to accomplish.
