### ISSUE TITLE
OSError: cannot write mode RGBA as JPEG

### ISSUE THREAD

**Issue by omek77** [mpetroff/pannellum#561]
I get some errors. I think it has to do with the pillow installation.  I have os x with Brew Python 3 and pip3 and Pillow 5.0.0
`macbook-pro:multires omek$ python generate.py -n /Applications/Hugin/Hugin.app/Contents/MacOS/nona /Users/omek/Desktop/a.jpg
Processing input image information...
Generating cube faces...
Generating tiles...
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/PIL/JpegImagePlugin.py", line 605, in _save
    rawmode = RAWMODE[im.mode]
KeyError: 'RGBA'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "generate.py", line 128, in <module>
    tile.save(os.path.join(args.output, str(level), faceLetters[f] + str(i) + '_' + str(j) + extension), quality = args.quality)
  File "/usr/local/lib/python3.6/site-packages/PIL/Image.py", line 1930, in save
    save_handler(self, fp, filename)
  File "/usr/local/lib/python3.6/site-packages/PIL/JpegImagePlugin.py", line 607, in _save
    raise IOError("cannot write mode %s as JPEG" % im.mode)
OSError: cannot write mode RGBA as JPEG
`

**Comment by strarsis** [comment]
Yes, you have to flatten the input images first, alphatransparency causes issues.
Ideally the underlying issue is fixed instead. On the other hand: What color should be used for the alphatransparent parts? White? Black? Magenta?

**Comment by omek77** [comment]
Da ist kein alpha Kanal.
![bildschirmfoto 2018-03-03 um 17 10 42](https://user-images.githubusercontent.com/35834654/36936447-01893356-1f06-11e8-8ae5-2e40518460ed.png)

**Comment by strarsis** [comment]
https://github.com/python-pillow/Pillow/issues/2609

**Comment by mpetroff** [comment]
You seem to be using an outdated version of the `multires.py` script (at least the line numbers don't match). This appears to be a duplicated of #455, which was fixed in 972e7e4f3da421850ac870ef18a137489fa8091f.

**Comment by omek77** [comment]
It works, thank you
