### ISSUE TITLE
loadScene with a Google-Map gradient, like a go forward effect

### ISSUE THREAD

**Issue by bingery** [mpetroff/pannellum#568]
could pannellum realize a go forward effect when load next scene, like Google-Map move forward the next scene ?

**Comment by mpetroff** [comment]
No; this involves 3D geometry that needs to both be created and rendered, two tasks that are outside Pannellum's scope. You might want to take a look at [OpenSfM](https://github.com/mapillary/OpenSfM), which does this for both normal rectilinear images and panoramas, although its viewer isn't particularly polished.
