### ISSUE TITLE
loading different configs in same viewer

### ISSUE THREAD

**Issue by heremias22** [mpetroff/pannellum#569]
Hello, first of all thanks for this awesome viewer its really great so far 👍 

We are using it in our school for a small project and i have run into a error when trying to change between 2 different configs(json with default and all the scenes) in the same viewer.
Right now we have a free roam tour and a guided tour in the second one its all automatic and the biggest difference in the json config is that you dont see any hotspot.

when i go from free roam to tour guided, the hotspots from freeroam comes to the guided too, and they stay there floating bugged and the only think you can do to fix it is to refresh the webpage.

I guess that i need to destroy and create a viewer everytime i load a different json.  Can you show me just a little bit how that would look?
right now when im in one tour and i want to change to another i load a different json(default,scenes..etc) with ajax and everything its cool except for the floating hotspots.

i dont know if i explained myself, sorry if theres anything weird, english is not my main language.
in resume im asking how to destroy and create a viewer with one big json that has all the scenes of the tour.

**Comment by mpetroff** [comment]
I take it you're initializing multiple viewers with the same `div` container, e.g. running `pannellum.viewer('yourpanoramadiv', {your config here});` twice but with different configurations?

If this is the case, you need to keep a reference to the viewer, e.g. `var yourViewer = pannellum.viewer('yourpanoramadiv', {your config here});`, and then call the destructor before creating the new one, e.g. `yourViewer.destroy();`.

**Comment by heremias22** [comment]
Thanks for answering my issue, i was doing what you told me but still had a few problems, now its solved.
