### ISSUE TITLE
getConfig of all viewer

### ISSUE THREAD

**Issue by ElDrToicno** [mpetroff/pannellum#574]
Hi! i am developing a simple web page where the user can build its own tour, at this point the user can add hotspots scenes etc, but i had a problem, how can i store the whole configuration of the viewer? first i think of get the all configuration of the viewer and serializated with a stringfy and store the string then retriving the data put the json string in the init of the viewer

**Comment by mpetroff** [comment]
The API's `getConfig` function returns the current configuration. I'm not sure what else you're asking.
