### ISSUE TITLE
Image under compass

### ISSUE THREAD

**Issue by Bruschetta** [mpetroff/pannellum#575]
Hello, i would like to know if it's possible to place an image under the compass in some way instead of having a blank background.
It could be usefull to help people to navigate in closed spaces.
Thank you for the time and , eventually, answer.

**Comment by mpetroff** [comment]
This is possible if you override the `.pnlm-compass` CSS class.

**Comment by Bruschetta** [comment]
I followed your hints and now is working like intended.Thank you  for your time and your library :)
