### ISSUE TITLE
On HotSpot rendered event

### ISSUE THREAD

**Issue by lehmannwebdev** [mpetroff/pannellum#576]
I would like to draw some line from one to other hotSpot.
Can you add some event trigger when HotSpot/s will be rendered?

function renderHotSpot(hs) {
...
if ((hs.yaw <= 90 && hs.yaw > -90 && z <= 0) ||
      ((hs.yaw > 90 || hs.yaw <= -90) && z <= 0)) {
        hs.div.style.visibility = 'hidden';
    } else {
        var yawSin = Math.sin((-hs.yaw + config.yaw) * Math.PI / 180),
        ...
        **hs.coord = coord;**
        **if(typeof hs.onRenderedEnd === 'function') hs.onRenderedEnd(coord, hs);**
    }
}

AND 

function renderHotSpots() {
    config.hotSpots.forEach(renderHotSpot);
    **fireEvent('onRenderedHotSpotsEnd', config.hotSpots);**
}

**Comment by mpetroff** [comment]
This would be no different than a "render" event, making this a duplicated of #310.
