### ISSUE TITLE
Custom Control not work with dynamic

### ISSUE THREAD

**Issue by siddharthsinh** [mpetroff/pannellum#579]
First, I have load the viewer object with one image and custom controls.
Now, I want to load another image in the viewer so, I have destroy the viewer object and reload with another image.(my scenario is to destroy the object not use the scene.)

so the custom controls are going into the DOM.

**Comment by mpetroff** [comment]
What's the question? I don't see one.

**Comment by siddharthsinh** [comment]
I want the custom control on viewer like left, right, up, down etc.

so I have integrated your custom control code from your example.

In my scenario there are thumbnail below the viewer and click on any thumbnail then load a selected picture on the viewer, so i was used the destroy method for delete the viewer object and recreate the object with a newly selected Image.

here when I'm destroying the object then reinitialize with a new image then custom controls are also gone.

**Comment by mpetroff** [comment]
Destroying and recreating the viewer is the wrong approach. You should have each thumbnail correspond to a "scene" and call the `loadScene` method to change to the correct scene when the thumbnail is clicked (linking the scenes with hot spots is not necessary).

**Comment by siddharthsinh** [comment]
Gotcha Thankx for helping, it's work
