### ISSUE TITLE
Going back to previous scene-Pannellum Tour

### ISSUE THREAD

**Issue by DingoGhatr** [mpetroff/pannellum#581]
In Pannellum tour it has the feature of moving scene1->scene2->scene3->....etc.Is there any option for moving to previous scene in tour?Like scene1->scene2->scene1->scene2->scene3->...

**Comment by mpetroff** [comment]
You just need to add appropriate hot spots to link back to the previous scene. This is done in the [tour example](https://pannellum.org/documentation/examples/tour/).
