### ISSUE TITLE
autoRotateInactivityDelay only works with json config file ?

### ISSUE THREAD

**Issue by secarica** [mpetroff/pannellum#582]
I'm trying to set a simple equirectangular panorama and make use of autoRotate and autoRotateInactivityDelay parameters. However, the autoRotateInactivityDelay gives "An invalid configuration parameter was specified: autoRotateInactivityDelay".

For instance, adding autoRotateInactivityDelay directly at the end of the existing working example
https://cdn.pannellum.org/2.4/pannellum.htm?panorama=https://pannellum.org/images/jfk.jpg&autoRotate=-2&autoRotateInactivityDelay=1000

This parameter is only valid if used within a json config file ?
(the same seems to apply also to autoRotateStopDelay parameter)

**Comment by mpetroff** [comment]
The URL configuration parameters are [clearly documented](https://github.com/mpetroff/pannellum/blob/master/doc/url-config-parameters.md). As the error message states, `autoRotateInactivityDelay` is not one of them.
