### ISSUE TITLE
Cubemap doesn't work in IE 11 on Win10

### ISSUE THREAD

**Issue by asmagin** [mpetroff/pannellum#583]
https://pannellum.org/documentation/examples/cube-map/
If you open URL above in IE 11 it will show error with following content:
```
SCRIPT5007: Unable to get property 'drawingBufferWidth' of undefined or null reference
pannellum.js (31,171)
```
![screenshot_1](https://user-images.githubusercontent.com/1803342/38228882-6b559900-36cb-11e8-9705-6951cfebd7e4.png)

**Comment by mpetroff** [comment]
Do the the other examples work? Best I can tell, this is a regression in the fallback renderer (introduced in aa8636227dc27a472add94b265a9911d4be93226), not an IE 11 specific bug. If my suspicion is correct, this should be fixed now in c471a06c32cecaa5e2d3c68bdbc73f9d1adb8739. Feel free to reopen the issue if this is not the case.

**Comment by asmagin** [comment]
Cubemap works from me in Edge and other browsers.
Panorama rendering works in IE 11 as well.

**Comment by mpetroff** [comment]
I checked on IE 11 (under Windows 7), and my suspicion was correct. IE 11 silently fails with NPOT cubemaps such as the cubemap example, so I force the use of the CSS 3D transform-based fallback renderer to prevent this. This triggered the regression in the fallback renderer, but that's now fixed.

**Comment by asmagin** [comment]
Is it possible to update NPM with those fixes?

**Comment by mpetroff** [comment]
Sure, it's possible, but I don't plan on doing so. IE 11 has <3% market share, and this bug only affects NPOT cube maps, which are poorly supported by IE 11 anyway.

**Comment by IanSimpson** [comment]
I get this same error on Chrome under OSX. Running a 2011 MBP.
