### ISSUE TITLE
set northOffset in pannellum.viewer but how to get Rotation Degrees from compass functionality

### ISSUE THREAD

**Issue by sannysoni123** [mpetroff/pannellum#584]
I am having trouble while using set northOffset in pannellum.viewer
passing value 200 and getting response data 180 from compass that is not suitable.
> 

newViewer = new pannellum.viewer(parent, {
      "type": "equirectangular",
      "panorama": url,
      "autoLoad": true,
      "compass": true,
      "northOffset":200,
      "autoRotate": 0
    });

> 
var angle2 = getRotationDegrees($(".pnlm-compass.pnlm-controls.pnlm-control"));

function getRotationDegrees(obj) {
      var matrix = obj.css("-webkit-transform") ||
      obj.css("-moz-transform")    ||
      obj.css("-ms-transform")     ||
      obj.css("-o-transform")      ||
      obj.css("transform");
      if(matrix !== 'none') {
          var values = matrix.split('(')[1].split(')')[0].split(',');
          var a = values[0];
          var b = values[1];
          var angle = Math.round(Math.atan2(b, a) * (180/Math.PI));
      } else { var angle = 0; }
      return (angle < 0) ? angle + 360 : angle;
    }

angle value not matched during calculation of 360 of rotation degrees functionality so is there any idea of relevant functionality.

**Comment by mpetroff** [comment]
You shouldn't be extracting a datum from the CSS; you should be using `newViewer.getYaw()` instead. To get the compass value, you should then add the north offset to the result.

**Comment by sannysoni123** [comment]
thanks for responding and i used newViewer.getYaw() it got me 0 in response. can you tell me how to i get compass value

**Comment by mpetroff** [comment]
I just told you. You add the north offset to the value returned by `getYaw()`. I don't know how I can be any clearer. If `getYaw()` returned `0`, it means the the current yaw pointing is `0`; the compass position is the yaw pointing plus the north offset.

**Comment by sannysoni123** [comment]
ok got it.. thanks a lot... :-)
