### ISSUE TITLE
Is it possible to find the deviation of the camera horizontally and vertically? 

### ISSUE THREAD

**Issue by fix2015** [mpetroff/pannellum#586]
Hello, you have a very good product, and we are actively using it, but we have a problem. Some users take pictures from a camera with an uneven surface. So the question is whether it is really possible to find the deviation of the camera? For example if we will use corners on the walls?

**Comment by fix2015** [comment]
for example for this image
![equirectangular](https://user-images.githubusercontent.com/3988392/38373983-417a8366-38fb-11e8-86bb-6b9260f71270.jpg)

**Comment by mpetroff** [comment]
What kind of camera is being used? Do you have an example image that includes EXIF/XMP metadata?

Ricoh's Theta series of cameras include horizon pitch / roll metadata (from an internal accelerometer) that Pannellum uses to automatically correct the horizon. With an example image with metadata, I could see if something similar is stored for the camera you're using.

These parameters can also be manually set using the `horzionPitch` / `horizonRoll` configuration parameters.

**Comment by fix2015** [comment]
samsung gear 360 i will try find

**Comment by fix2015** [comment]
@mpetroff yep found
![image](https://user-images.githubusercontent.com/3988392/38609219-31adc986-3d86-11e8-9732-d14c2efd01c8.png)
but its only if user load origin image, and as i notice some of cameras do not have this info. So i start thinking , what if user will draw line.
For example we have image with:
       **horizonPitch: -3.6,
       horizonRoll: 2.2**
And than user show correct corner in the room like this, 
![image](https://user-images.githubusercontent.com/3988392/38609477-d7121b02-3d86-11e8-8d52-e627b9e9070e.png)
Can we found horizonPitch and horizonRoll from this 3 points?

**Comment by fix2015** [comment]
seems its impossible

**Comment by mpetroff** [comment]
Whether or not it's possible, it's outside the scope of Pannellum.

**Comment by fix2015** [comment]
@mpetroff ok thx)
