### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by jonnysp** [mpetroff/pannellum#587]
how can fix it?

var [r,g,b] = params.backgroundColor ? params.backgroundColor : [0, 0, 0];

**Comment by mpetroff** [comment]
This is a regression that was introduced in 0c92d85b11e4b8f3dccc82ccd3e466f95b88f744. I just fixed it in 9f335100204464daeb787d7e077f27016d7ee1a2.

**Comment by jonnysp** [comment]
thanks Matthew
