### ISSUE TITLE
WebGL Error in Firefox on Android

### ISSUE THREAD

**Issue by JanBluePix** [mpetroff/pannellum#588]
Pannellum worked very well in Firefox on Android 5 in the past. After a browser update, I'm getting only a WebGL error message for weeks in Firefox and Firefox 60 Beta. Chrome continues to work very well. Last Tests with Panellum v.2.4.1.

**Comment by mpetroff** [comment]
Does https://get.webgl.org/ work?

**Comment by JanBluePix** [comment]
webgl.org does't work with Firefox 59.0.2 or 60 Beta. The same with some other PanoViewer. But Marzipano works well... but it's google - and no option for me. (In Chrome webgl.org works well.)

**Comment by JanBluePix** [comment]
webgl.org works with the Safari Browser too.

**Comment by mpetroff** [comment]
Since the WebGL demo doesn't work, your issue is a browser issue, not a bug in Pannellum.

Marzipano is probably using a CSS 3D transform based fallback. Pannellum has a similar fallback for cube map and multires panoramas; WebGL is required for displaying equirectangular images, though.
