### ISSUE TITLE
Panoviewer too slow when loading pano for the first time. can we pre-load those images in pannellum feature.

### ISSUE THREAD

**Issue by sannysoni123** [mpetroff/pannellum#589]
Hi Matthew Petroff,
pannellum.viewer too slow when loading pano images for first time. can i pre-load images. 
"I used Preview option for displaying static image while pano images loading but that also took time for displaying static image well."
Please give me alternative solution for not loading too much time. all images from amazon server.
Image sizes can be in 4 or 6 or 8 MB.

Regards
Sanny Soni

**Comment by mpetroff** [comment]
If you're worried about load times, you should use the [multiresolution panorama](https://pannellum.org/documentation/examples/multiresolution/) feature. This allows the panoramas to be loaded incrementally as needed.

**Comment by sannysoni123** [comment]
Hi Matthew Petroff,

I think you getting me wrong.. i have pan_images not to have simple images for making one pan_image.
i want to alternative solutions for collection of pan_images to displaying into slider. i used multiresolution panorama and created folder of client side for collection of images. that would not be proper solution for more than pan images from another server.

Regards
Sanny Soni

**Comment by einfochips1** [comment]
Hi, @sannysoni123 have you found any solution loading issue for the single Panorama image. I am facing same.
Please help me
Thanks,
Punita
