### ISSUE TITLE
Option to log pitch and yaw of mouse click to console to aid with positioning hot spots

### ISSUE THREAD

**Issue by mpetroff** [mpetroff/pannellum#59]
Currently, positioning hot spots is rather inconvenient, often devolving to trial and error. To make this process easier, a configuration option should be added that logs the mouse's pitch and yaw position values when the mouse button is clicked. Obviously, this option shouldn't be used in production.

**Comment by mpetroff** [comment]
There's now a `hotSpotDebug` option that, when set to `true`, logs the mouse pointer's pitch and yaw coordinates to the console when the mouse button is clicked.

**Comment by hhkaos** [comment]
Great! thx! :D

**Comment by saricden** [comment]
Just found this!!!!!!!!! Saves so much time!!!!!!! >=D
