### ISSUE TITLE
want to do create preview image of pan viewers - get center portion of preview stuff

### ISSUE THREAD

**Issue by sannysoni123** [mpetroff/pannellum#591]
Hi Matthew Petroff,
I am using Pannellum library. it is very excellent and appreciate library usability.
I have one query for preview things. please check this url - 
https://pannellum.org/documentation/examples/preview-image/

https://pannellum.org/images/tocopilla.jpg
https://pannellum.org/images/tocopilla-preview.jpg
here are two url one is for panviewer and another is static image so my question is - 
How to i get center portion for preview image of Pan Viewers?
Suppose i have to create preview image for pan viewers, what to do on next step?

Regards
Sanny Soni

**Comment by mpetroff** [comment]
I don't understand your question. The preview image is just a static image that is displayed before loading the panorama. You can create it however you like.

**Comment by sannysoni123** [comment]
suppose i am working on server side coding and upload pan viewer images, taking screen-shot for static image so how can i take exact portion of pan viewer which you mentioned on preview image of your example.  
is there any way for taking exact portion like zoom-in and crop center portion of the functionality?

**Comment by mpetroff** [comment]
You could probably script something using [Hugin](http://hugin.sf.net/) or possibly [Selenium](https://www.seleniumhq.org/), but it's out of Pannellum's scope.
