### ISSUE TITLE
mouse nav not working at 2.4.0 and 2.4.1

### ISSUE THREAD

**Issue by zwnk** [mpetroff/pannellum#593]
Hi there,

i'm using 2.3.2 and the mouse drag and zoom is working just fine. now i wanted to update to 2.4.x and found that the mouse dragging and zooming is not working. even if i set both to true at the scene definition. only the keyboard controls are working. i get no error what so ever at the console so i'm really clueless what is going wrong.
i tried the latest firefox and chrome.

cheers,
david

**Comment by mpetroff** [comment]
Does mouse control work for you in the [pannellum.org examples](https://pannellum.org/documentation/examples/simple-example/)?

**Comment by zwnk** [comment]
it does.

**Comment by zwnk** [comment]
i found the problem. the css has to be updated also ;) looks like div names etc. are different.
