### ISSUE TITLE
Responsive

### ISSUE THREAD

**Issue by charlesravndal** [mpetroff/pannellum#595]
Thanks for this wonderful script! I'm just wondering how to make it responsive.

**Comment by charlesravndal** [comment]
Thank you! Though I noticed that you have to specify the height in pixels or else it won't appear. Right?

**Comment by mpetroff** [comment]
You need to specify both a height and a width, but you can use something like `max-width` or `max-height` instead of `width` or `height` to make it responsive.

**Comment by charlesravndal** [comment]
Ok I will do that :) Thank you again!

**Comment by mpetroff** [comment]
The resize method doesn't change the field of view; it just resizes the canvas.

**Comment by yomomano** [comment]
I see. What would be the best way to fix the FOV when the aspect ratio of the container changes?

**Comment by yomomano** [comment]
you are right. my bad. called resize() before the container was actually resized. thanks for your support!

**Comment by Vardges777** [comment]
How can I correctly make responsive pannelum?
