### ISSUE TITLE
decompression bomb error

### ISSUE THREAD

**Issue by danieltroger** [mpetroff/pannellum#596]
Hi, I get the following error with an image (20992*10496):

```
Traceback (most recent call last):
  File "../generate.py", line 100, in <module>
    origWidth, origHeight = Image.open(args.inputFile).size
  File "/usr/local/lib/python3.6/site-packages/PIL/Image.py", line 2577, in open
    im = _open_core(fp, filename, prefix)
  File "/usr/local/lib/python3.6/site-packages/PIL/Image.py", line 2568, in _open_core
    _decompression_bomb_check(im.size)
  File "/usr/local/lib/python3.6/site-packages/PIL/Image.py", line 2507, in _decompression_bomb_check
    (pixels, 2 * MAX_IMAGE_PIXELS))
PIL.Image.DecompressionBombError: Image size (220332032 pixels) exceeds limit of 178956970 pixels, could be decompression bomb DOS attack.
```

Is it possible to turn off such bulls**t? I tried to edit `/usr/local/lib/python3.6/site-packages/PIL/Image.py` and remove the check, but it resulted in some tiles missing which stopped pannellum from loading further tiles. It doesn't matter what format the input image has (jpg, tif, png) and I'm on Python 3.6.5.

Any help appreciated.

**Comment by mpetroff** [comment]
Per the [Pillow 5.0.0 release notes](https://github.com/python-pillow/Pillow/blob/master/docs/releasenotes/5.0.0.rst), this can be disabled by setting `Image.MAX_IMAGE_PIXELS = None`. I made this change in ed05162933fbb9f9f1fbeba9168a102fa0d17aef.

**Comment by danieltroger** [comment]
That's amazing @mpetroff ! Sorry for not spotting the change.

**Comment by danieltroger** [comment]
Are you sure you're using the newest version of generate.py and everything?

**Comment by 5680christophe** [comment]
Everything works
Thank you

<http://www.buy3Dglasses.fr>

2018-05-12 13:05 GMT+02:00 Daniel <notifications@github.com>:

**Comment by mpetroff** [comment]
@5680christophe Advertising in this issue tracker is entirely unacceptable. As is emailing me 15 minutes after opening this issue with the exact same question, because clearly I should be helping you instantly.
