### ISSUE TITLE
cordova usage of this library

### ISSUE THREAD

**Issue by jmrezayi2** [mpetroff/pannellum#598]
Hello,

Thanks a lot for this awesome library. This works perfectly for the project I am working on.

However, I was wondering if you know how it can be used with cordova file? Currently I have access to a local file through cordova file plugin, but have not been able to give pannellum that file. I have tried giving the URI, filesystem URL, and also giving it as a file..
None seems to work..

Thanks a lot!

**Comment by mpetroff** [comment]
I've never used Cordova and have no intention of doing so. You might want to search previous issues, e.g. #542 might be helpful. Apparently, Cordova implementation of the FileReader API is not standards compliant.

**Comment by jmrezayi2** [comment]
Hey,

Thanks a lot for your reply. Yes I did look at the other issues, but they are all loading from a server, which I can successfully do. I am trying to reference a local file. Would there be any option to pass the image as a base64 url?

Thanks!

**Comment by mpetroff** [comment]
I'd recommend using a [Blob object](https://developer.mozilla.org/en-US/docs/Web/API/Blob); base64 data URIs only work in some cases (e.g. not in Chrome).

**Comment by jmrezayi2** [comment]
Thanks a lot mpetroff,

So if I pass in a blob instead of the image src it should be able to pick it up?

**Comment by mpetroff** [comment]
If you pass it the blob URI, something of the form `blob:d3958f5c-0777-0845-9dcf-2cb28783acaf`, instead of a normal URL, it should work (at least it does in normal web browsers).
