### ISSUE TITLE
Image implementing

### ISSUE THREAD

**Issue by velemaki** [mpetroff/pannellum#599]
Hi
Is there any way to implement image within hotspots 
example when mouse cursor pass over hotspot image opens
Sorry on my bad english
cheers

**Comment by mpetroff** [comment]
You can make the hot spots any way you like by using the `createTooltipFunc` and `createTooltipArgs` parameters to set a custom hot spot creation function. See the [custom hot spot example](https://pannellum.org/documentation/examples/custom-hot-spots/).
