### ISSUE TITLE
removeHotSpot does nothing when hotspot is not in current scene

### ISSUE THREAD

**Issue by DavidvRamboll** [mpetroff/pannellum#601]
Possible bug.  Pannellum: viewer.removeHotSpot() does nothing if the hotspot is not in the current scene.

The user invokes my javascript which uses viewer.addHotSpot() to create a hotspot.  If the user invokes my javascript which uses viewer.removeHotSpot() then the hotspot is removed ok.

On the other hand, this other scenario has a problem.  The user is in Scene A and invokes my javascript which uses viewer.addHotSpot() to create a hotspot (let's call it Hotspot A).  The user follows a scene-type hotspot (Hotspot B) defined in pannellum.viewer('panorama', {"scenes": {}}) and is now viewing Scene B.  The user then invokes my javascript to do a viewer.removeHotSpot() on Hotspot A.  When the user follows other scene-type hotspots to return to Scene A, they find Hotspot A still there!

I am sending hotspot ids to console.log() when creating and removing them, and my javascript for removing the hotspot is the same function in both scenarios.

I'm using Pannellum v2.4.0, which I downloaded today, running Chrome on a Windows7 computer and an Android mobile phone.  This behaviour also occurred in Pannellum v2.3.2.

**Comment by DavidvRamboll** [comment]
Calling removeHotSpot() on these hotspots in a scene other than the current scene returns false

**Comment by mpetroff** [comment]
The `removeHotSpot` method only supported the current scene. When the user switched to a different scene, no hot spot with the specified ID existed, so the method returned false.

I added an optional second argument to the `removeHotSpot` method in c94815ee317f926c97f4bb9544d1853e1f200ffe to allow the scene to be specified, which will allow you to remove hot spots from non-active scenes.
