### ISSUE TITLE
Can't set up two pannellum viewer together.

### ISSUE THREAD

**Issue by poghosyanarthur** [mpetroff/pannellum#602]
First of all I'd like to say thank you for the good tool :1st_place_medal: :1st_place_medal: :1st_place_medal: :1st_place_medal: 
I am setting up two viewers:

        viewer1 = pannellum.viewer("firstViewer", {
            "default": {
                             "firstScene": "defaultScene",
                             "autoLoad": true,
                             "showControls": true,
                            "sceneFadeDuration": 1000
                          },
            scenes:     "defaultScene": {
                                       "type": "multires",
                                       "pitch" : 0,
                                       "hfov": 120,
                                       "maxHfov": 120,
                                       "minHfov": 30,
                                       "yaw": 0,
                                       "dynamic": true,
                                       "multiRes": {
                                                           "basePath":"/images/default_pano",
                                                           "path": "/%l/%s%y_%x",
                                                           "fallbackPath": "/fallback/%s",
                                                           "extension": "jpg",
                                                           "tileResolution": 512,
                                                           "maxLevel": 4,
                                                           "cubeResolution": 2288,
                                        }
    }
 });

and the second one 

        viewer2 = pannellum.viewer("secondViewer", {
            "default": {
                             "firstScene": "defaultScene",
                             "autoLoad": true,
                             "showControls": true,
                            "sceneFadeDuration": 1000
                          },
            scenes:     "defaultScene": {
                                       "type": "multires",
                                       "pitch" : 0,
                                       "hfov": 120,
                                       "maxHfov": 120,
                                       "minHfov": 30,
                                       "yaw": 0,
                                       "dynamic": true,
                                       "multiRes": {
                                                           "basePath":"/images/default_pano",
                                                           "path": "/%l/%s%y_%x",
                                                           "fallbackPath": "/fallback/%s",
                                                           "extension": "jpg",
                                                           "tileResolution": 512,
                                                           "maxLevel": 4,
                                                           "cubeResolution": 2288,
                                        }
    }
 });

then I'm adding new scene to both viewers  

viewer1.addScene(someUniqueId, pano);
viewer2.addScene(someOtherUniqueId, pano);

everything works fine in therms of I can see the images and navigate, the problem is when I am comparing the outputs of "viewer1.getConfig().scenes" and "viewer2.getConfig().scenes" they are equal and contains the scenes from viewer1 and viewer2.

**Comment by mpetroff** [comment]
Please don't write everything in **bold**; it's almost as bad as writing everything in ALL CAPS.

If you're using the same variable to add scenes to both viewers, your assigning the same JavaScript object to both. Any changes to the object will then be applied to both viewers.

**Comment by poghosyanarthur** [comment]
Thanks guys for your response.
I've fixed the bold texts :)
@mpetroff could you please give an short example how should be done to have two viewers running simultaneously.
Thanks in advance.

**Comment by mpetroff** [comment]
As I said before, don't reuse JavaScript objects. If you post your code, I can probably tell you what the issue is.
