### ISSUE TITLE
how to handle Curved 360° images while load the scene?

### ISSUE THREAD

**Issue by pvvsridhar** [mpetroff/pannellum#603]
Hi,

Would it be possible to use 360° curved  image in Pannellum?
can Pannellum handle this kind of images while scene load?

The 360° curved  image was not taken horizaontally. i have tried with this image, but while moving in the scene, the whole scene was moving horizontally & vertically as per the image.

Can anyone suggest me about this how to do ,thanks in advance.

Sridhar

**Comment by mpetroff** [comment]
I have no idea what you mean by a "360° curved image." I don't think anyone will be able to help without an example.

**Comment by strarsis** [comment]
You have to straighten the panorama first. There are specific separate tools that can do this.
