### ISSUE TITLE
look in opposite direction possible?

### ISSUE THREAD

**Issue by macsimski** [mpetroff/pannellum#604]
I want to make 360 views of objects, not spaces. so the viewer always looks to the same point, but from different positions, so you can see the top, bottom, back and front of a object. how do you name this projection and is this possible with Pannellum?

**Comment by zwnk** [comment]
you can view 360 images. there the position of the image is fixed and you can rotate and zoom your field of view.
you are looking for something where you have your object at the center and rotate around it.

depending on your type of data, https://threejs.org/ or http://www.potree.org/ is something for you.

**Comment by macsimski** [comment]
this is from actual 3d data. i was looking for something were you don't generate a 3d model, but use a lot of pictures where you can choose what picture to look at by dragging your mouse, giving the idea that the object is rotated.

**Comment by mpetroff** [comment]
What you're describing is not a panorama and is thus outside the scope of Pannellum. I'm sure there are tools for displaying such data sets, but Pannellum in not the appropriate tool.

**Comment by strarsis** [comment]
@macsimski: You are looking for a 3D object viewer (like https://github.com/CodyHouse/360-degrees-product-viewer).

**Comment by macsimski** [comment]
thanks for al the tips. indeed I was mistaken. I thought that you could stitch it all together, but obvious you cant as the object can have different shapes and in a panorama, everything is at the same distance to the observer. it only looks closer or further away.

codyhouse looks promising, albeit it only does horizontal pans. but the 3d object viewer search phrase will help me a lot.

thanks all
