### ISSUE TITLE
Set initial zoom

### ISSUE THREAD

**Issue by Flobin** [mpetroff/pannellum#606]
This is an idea for a feature: to be able to set the initial zoom position. Coupled with disabling zoom altogether, this could be used to make the parts that an image doesn't cover invisible for images that don't cover an entire sphere.

**Comment by mpetroff** [comment]
Did you read the documentation or look at the examples? The initial zoom and pointing can be set with the `hfov`, `pitch`, and `yaw` parameters. See the [initial view](example). Zooming can be disabled using a combination of the `keyboardZoom`, `mouseZoom`, and `showControls` parameters.
