### ISSUE TITLE
Change z-index of hotSpots

### ISSUE THREAD

**Issue by Bibbowski** [mpetroff/pannellum#609]
Hi, can i change z-index of hotspots? I have to place an image between the scene and the hotspots...

**Comment by Bibbowski** [comment]
can you place an image above the scene that does not interfere with the touch?

**Comment by strarsis** [comment]
@Bibbowski: You can make an element completely 'invisible' to user interaction (including touch) by setting its CSS [`pointer-events`](https://developer.mozilla.org/en/docs/Web/CSS/pointer-events) property to `none`

**Comment by mpetroff** [comment]
You can set the z-index of hot spots by setting the z-index of `.pnlm-hotspot`.

**Comment by Bibbowski** [comment]
thank! :)

**Comment by Bibbowski** [comment]
@strarsis: using "pointer-events property to none", it does not interfere if the touch started outside the image area ... but if the touch starts on the image it does not work ...

**Comment by Bibbowski** [comment]
I solved by putting the image in a container div and setting pointer-events: none; on div
