### ISSUE TITLE
Zooming out jerky on Chromium

### ISSUE THREAD

**Issue by danielnaber** [mpetroff/pannellum#61]
Zooming out with the mouse wheel is jerky with Chrome. It looks like it zooms out and then in again a bit. The problem is this code in `pannellum.js` I think:

	if (event.detail) {
		if (event.detail > 0) {
			zoomSpeed = 1;
		} else {
			zoomSpeed = -1;
		}
	} else {
		if (event.detail < 0) {
			zoomSpeed = 1;
		} else {
			zoomSpeed = -1;
		}
	}

Just as with the code that comes before this code in `pannellum.js`, I think the else part needs to check for `event.wheelDelta`. That improves zooming with Chrome for me (no pull request as not tested with IE).

**Comment by mpetroff** [comment]
You're absolutely right; the previous code didn't make any sense. I had seen the issue but hadn't tracked it down. Thanks!
