### ISSUE TITLE
Sometimes works and sometimes hangs on loading

### ISSUE THREAD

**Issue by clzola** [mpetroff/pannellum#612]
I have integrated this plugin into my Ionic application, and when I run it on physical device (Huawei Mate 10 Pro), plugin sometimes work and sometimes it does not. There is no error in console, it just hangs on "Loading..."

Here is the image:
![screenshot_20180603-221852](https://user-images.githubusercontent.com/1807911/40890818-66530a64-677c-11e8-873b-a2e336f4fb8a.jpg)

This the code I use to run plugin:

```
import { Component, ViewChild, ElementRef } from '@angular/core';
import { NavController, NavParams } from 'ionic-angular';
import { Restaurant } from '../../../data/models/Restaurant';

declare var pannellum: any;
declare var window: any;


@Component({
    selector: 'page-virtual-tour',
    templateUrl: 'virtual-tour.html',
})
export class VirtualTourPage {
    config: any;
    restaurant: Restaurant;

    @ViewChild("panorama") panorama: ElementRef;

    constructor(public navCtrl: NavController, public navParams: NavParams) {
        this.config = this.navParams.get('config');
        this.restaurant = this.navParams.get('restaurant');

        // patch FileReader to be standard compliant beacuse it get's used this way in pannellium viewer
        // cordova's cordova-plugin-file (native file) overwrites the standard implementation for FileReader
        // console.log('FileReader.addEventListener test:', window.FileReader.prototype.addEventListener);
        if (!window.FileReader.prototype.addEventListener) {
            window.FileReader.prototype.addEventListener = function (type, listener) {
                if (type === 'loadend') {
                    this.onloadend = listener;
                }
            };
            console.log('FileReader patch for loadend injected');
        }
    }

    ionViewDidLoad() {
        pannellum.viewer(this.panorama.nativeElement, this.config);
    }

}
```

I have no idea why this happens...

**UPDATE**:
What I have found out, well, I decided to put `console.log([this, window.FileReader])` inside ` window.FileReader.prototype.addEventListener` function, just before `if` and sometimes it prints FileReader instance for this, and sometimes gives this:

![screenshot from 2018-06-03 23-34-52](https://user-images.githubusercontent.com/1807911/40891502-fa17af66-6786-11e8-9009-5bdf42612ea7.png)

Based on what I see, is this is some problem with angular and its zones, which I do not know how to solve ...

**UPDATE 2**
I have downloaded pannellum production .js, modified it so instead of `k.addEventListener('loadend', ...)` looks like `k.onloadend = function() {...}` but still same thing, sometimes work and sometimes not ...

**Comment by mpetroff** [comment]
As I've said in numerous previous issues with people having issues with Ionic / Cordova, only web browsers are officially supported.
