### ISSUE TITLE
Draw over the 3D Canvas

### ISSUE THREAD

**Issue by RubMart** [mpetroff/pannellum#614]
I am interested in drawing directly on the 3D canvas, for example to allow a user to draw regions over the pano image, draw lines or polygons, or something similar (click events to draw directly in the canvas).

Do you have in mind to implement this functionality in the future? Drawing interactions directly?
If not, any recommendations or basic webgl examples of how to carry out these operations based on core Pannellum webgl implementation?.

Thank you for pannellum, very interesting and very detailed library.

**Comment by mpetroff** [comment]
I have no intention of ever including anything like that. I'd recommend overlaying another canvas to add that sort of annotation.

**Comment by priyanka931** [comment]
@RubMart I also intend to have a functionality like this. Did you get any solution? It would be great if you could help me out with this.
