### ISSUE TITLE
Question - make iframe responsive

### ISSUE THREAD

**Issue by RobBlash** [mpetroff/pannellum#615]
I'm using pannellum embedded in my own site. I've tried a few ways to make the iframe responsive but it always winds up around 150px in height. I am in no way a web dev, I understand just enough to hack my way through but I am trying solutions that seem to work for other people. However I always get the same result (150px) unless I explicitly declare the frame height. Is there something underlying that's impacting this? Any advice would be appreciated, thanks!

**Comment by brunoamaral** [comment]
I think that may fall outside the scope of Pannellum. It depends on how your css is configuring the Iframe and although you can set an implicit height, that value needs to be recalculated if the viewport changes or is loaded on mobile.

**Comment by strarsis** [comment]
Ratio padding technique or `vw`/`vmin`/`vmax` units come to mind.

**Comment by mpetroff** [comment]
This is not the appropriate forum for asking how to set the size of an `iframe`.

**Comment by RobBlash** [comment]
Hi,

Thanks for creating pannellum, I am finding this to be a useful tool. I
also appreciate the need to moderate the issues listed, however I was not
asking how to set the iframe size. I was asking if there is something in
the underlying code that's causing my iframes to default to 150px high when
I try to set the height in a responsive manner. If you have any ideas or
pointers please let me know.

Thanks,

Rob

**Comment by RobBlash** [comment]
Hi Matthew,

Thanks for creating pannellum, I am finding this to be a useful tool. I also appreciate the need to moderate the issues listed, however I was not asking how to set the iframe size. I was asking if there is something in the underlying code that's causing my iframes to default to 150px high when I try to set the height in a responsive manner. If you have any ideas or pointers please let me know.

**Comment by mpetroff** [comment]
The content of an `iframe` do not affect its size. The 150px default height is a browser default.
