### ISSUE TITLE
Tile service with factor of 3 not working

### ISSUE THREAD

**Issue by kushu493** [mpetroff/pannellum#616]
Hi,

Currently your viewer doesn't support a tile service with max zoom level of 3 and factor is 3. i.e.

at zoom level 1 - there is one tile for each face
at zoom level 2 - there is 9 tiles for each face (row =3 and col =3)
at zoom level 2 - there is 81 tiles for each face (row =9 and col =9)

What changes i would have to make to support this type of tile service? I am using multires mode. I think you only support the tile service with a factor of 2

Thank you.

**Comment by mpetroff** [comment]
The only tiles officially supported are those generated by the included `generate.py` script. However, most other tiles with a "factor of 2," per your nomenclature, should work. Supporting the tile scheme you're describing would require extensive changes to the `testMultiresNode` method in `libpannellum.js`. You're free to make the changes, but I have no intention of ever including such support.
