### ISSUE TITLE
Convert x y coordinates to pitch and yaw

### ISSUE THREAD

**Issue by MarinaCode** [mpetroff/pannellum#619]
If I have  x and y coordinates, how can I convert it to pith and row ?

**Comment by mpetroff** [comment]
If you're getting the coordinates from a `MouseEvent`, you can get pitch and yaw from the `mouseEventToCoords` function.

**Comment by MarinaCode** [comment]
When I move the one hotspot I want to move the others along the first one.  So I have only x y coordinates for others. Is it possible to convert them to yaw pitch?

**Comment by mpetroff** [comment]
You have the original `MouseEvent`. Just add the offsets to the event's `clientX` and `clientY` properties.

**Comment by MarinaUI** [comment]
I added the difference between old hot info position and new hot info positions to the others and  it works , thank you
