### ISSUE TITLE
Translation JSON resource by URL

### ISSUE THREAD

**Issue by strarsis** [mpetroff/pannellum#623]
It would be great if the pannellum standalone viewer supports a parameter for passing the URL to a pannellum-translations JSON resource. Currently it doesn't seem to be possible, or at lest not documented.

**Comment by mpetroff** [comment]
You need to use the API. I don't intend to add it to the standalone viewer.

**Comment by strarsis** [comment]
@mpetroff: Going even further, in my opinion, the standalone viewer, as it is meant to be standalone,
should ship with all the translations and pick the right one by UA language.

**Comment by mpetroff** [comment]
As mentioned in https://github.com/mpetroff/pannellum/pull/486#issuecomment-332384366, I have no desire to maintain a set of translations, so what you're suggesting is never going to happen.

As for the original question, I spoke too soon about having to use the API. You can include translations in a JSON configuration file passed to the standalone viewer. It won't be a separate option, though.

**Comment by strarsis** [comment]
@mpetroff: Thanks. So I can indeed pass the translation strings in the tour config file.
This is an option, though ideally the content (tour) and UI (translation strings) shouldn't be mixed.
