### ISSUE TITLE
How do I know what values to use for tileResolution and cubeResolution?

### ISSUE THREAD

**Issue by parliament718** [mpetroff/pannellum#625]
I tried setting cubeResolution to the pixel width of the original equirectangular image and tileResolution arbitrarily to 512, but the multires image does not get stitched together correctly.

How do I derive the ideal values to set for tileResolution and cubeResolution?

**Comment by mpetroff** [comment]
The `generate.py` script outputs these values, and you shouldn't need to change them. You can look at the source code of that script if you want to see how they're calculated.

**Comment by parliament718** [comment]
Oh sorry, I missed that output. Stitches perfect now, thanks.
