### ISSUE TITLE
How can I use this in React.js application?

### ISSUE THREAD

**Issue by ThunderBoltEngineer** [mpetroff/pannellum#627]
Can I use this in my React.js application?

I see there is node module package of this library, but not sure if I can use in React.

**Comment by mpetroff** [comment]
You need to include the minified `pannellum.js` script in the page and the `pannellum.css` style sheet. I have no idea how this is normally done in React, since I've never used it.

**Comment by ThunderBoltEngineer** [comment]
@mpetroff  Thank you for your reply.

I resolved this by importing pannellum scripts and css in the head of `public/index.html`.
After that, I can access window.pannellum.viewer in any components.

**Comment by saidmoya12** [comment]
You can use also my fork
``
npm install --save github:saidmoya12/pannellum
``
then import 

```
import pannellum from "pannellum";
...

let viewer = pannellum.viewer('panellum', [config]);
```

I hope will be useful

**Comment by MrSandManSy** [comment]
@ThunderBoltEngineer 

``
<html>
<head>
    <meta charset="UTF-8">
    <title></title>
    <link type="text/css" rel="Stylesheet" href="./src/components/vr/css/pannellum.css"/>
    <script type="text/javascript" src="./src/components/vr/js/pannellum.js"></script>
</head>
<body>
    <div id='App'/>
    <script type="text/javascript" src="build/bundle.js"></script>
</body>
</html>
``
``
import React from 'react';
import { render } from 'react-dom';
import App from './App';

render((
  <App/>
), document.getElementById('App'));
``
``
import React from 'react';

class App extends React.Component {

  render() {
    console.log(window.pannellum)
    console.log(window.pannellum.viewer)
    return (
      <div>
        <a>Learn pannellum</a>
      </div>
    );
  }

}

export default App;
``
I'm sorry to trouble you, but I want to know how you use it in react.
When i use it like above, it doesn't work.
