### ISSUE TITLE
Fullscreen stretched in Safari

### ISSUE THREAD

**Issue by mpetroff** [mpetroff/pannellum#629]
In Safari, the aspect ratio is not set properly when switching to fullscreen mode, causing the viewer to be stretched. It appears that the `onFullScreenChange` method isn’t being called, which means the `fullscreenchange` event isn’t firing.

Browser: Safari Version 11.1.1 (13605.2.8)
Machine: 27" iMac

Copied from comment on: https://mpetroff.net/2018/01/pannellum-2-4/

**Comment by mpetroff** [comment]
I can confirm this issue using Sauce Labs. Unfortunately, the issue goes away with the developer tools open, which will make debugging extremely difficult.

**Comment by strarsis** [comment]
@mpetroff: A heisenbug :-) . The developer tools in Chrome can be opened as separate window:
Three-dot menu (at the upper right corner), 'Dock side': 'Undock into separate window'. 
This may help if the reduction of viewport width/height by the developer toolbar gets around the issue.

**Comment by mpetroff** [comment]
It seems that f0af9d07bfe46200ebe4b1bf81eb5658a0653cf5 fixed this, at least for Safari 12.1.
