### ISSUE TITLE
generate.py Output directory already exists

### ISSUE THREAD

**Issue by rcilia** [mpetroff/pannellum#634]
Hi, 

I'm using the `generate.py` script to generate multires images, and I was wondering why you decided to exit the program if the output directory exists?

My use case is the following: 
- download original image in a folder
- generate multires assets in this same folder
- upload everything to a server.

Removing lines 97 and 98 of generate.py seem to work fine, but I wanted to make sure that wouldn't break anything else before making a PR?

Thanks, 
Remy.

**Comment by mpetroff** [comment]
It exists to avoid accidentally overwriting existing files or mixing files from multiple panoramas together. As I feel this safeguard is worth the slight loss in flexibility, I have no intention of changing this behavior.
