### ISSUE TITLE
Switch between scenes without autoloading them

### ISSUE THREAD

**Issue by coding22** [mpetroff/pannellum#636]
Hi,

i have multiple scenes, each of them having their own preview:
```
var viewer=pannellum.viewer('panorama',  {   
    "default": {
    "autoload":false,
   "type": "equirectangular",	
  "firstScene": foo,
   "scenes": {
        "foo": {
            "title": "foo",
            "type": "equirectangular",
            "panorama": "foo-panorama.jpg",
	    "preview": "foo-preview.jpg"
            
        },
	 "bar": {  
            "title": "bar",
            "type": "equirectangular"",
            "panorama": "bar-panorama.jpg",
	    "preview": "bar-preview.jpg"
            
        },
```
I'd like to switch between scenes in a way, that the new scene isn't automatically loaded, but rather with a preview and "click to load" notice shown each time.  So basically that the user sees, what he's about to load.
The user changes scenes with buttons, and if I use loadScene for changing the scenes, like
```
jQuery( "#changeToBar").click(function() {
viewer.loadScene('bar');
});
```
 the scene gets changed instantly without showing the preview image and asking the user "click to load" - even if autoLoad is set to false, but I guess that doesn't matter, as autoLoad applies only for first scene.

Is there a non-hacky way to achieve this? The only solution that comes to mind is to destroy and create an instance of pannellum on each button click, where `firstScene` would be the chosen scene...

Thanks!

**Comment by mpetroff** [comment]
This isn't supported.

An alternative to the work-around you suggest would be to have your code create an overlay over the viewer, similar to the initial load button display. When the load button is pressed, your code would call the `loadScene` method and hide the overlay.

**Comment by coding22** [comment]
Thanks for the answer, I've done it wihout an overlay and it takes like three lines of code. 
Working example, if someone will need this functionality it in the future: [jsfiddle](https://jsfiddle.net/uso3tf07/ )
