### ISSUE TITLE
Latitudinal Rotation, what is it?

### ISSUE THREAD

**Issue by Hydrowind** [mpetroff/pannellum#641]
Hello, thanks for your great library **Matthew Petroff**!. I was impressed you created this library using **WebGL** & **Javascript**!
thanks for sharing this one!

I'm not so good at math, but can you explain a little more about **latitudinal rotation**? as i know, the **point position vector** gives you a direction from the camera position right? but what is **latitudinal rotation** and why you should multiply it with **point position vector**? and can i convert the **yaw & pitch** of the camera to **x,y,z coordinates**?

thanks in advance!

**Comment by mpetroff** [comment]
This isn't an appropriate forum for math questions. Something such as Stack Exchange would be better suited to this.
