### ISSUE TITLE
Custom UrL

### ISSUE THREAD

**Issue by MohammaddReza** [mpetroff/pannellum#649]
hi,
im using tour viewing of your library,
i want to create external aerial map to select cleck and load quickly, how can i do that?

**Comment by mpetroff** [comment]
I have no idea what you're asking.

**Comment by MohammaddReza** [comment]
i'm going to make a 8 floor building tour viewing, i want to know to jump between floor (for example i'm in first floor and want to jump to the last floor) if i want to do it in regular way, i have to click 7 scenes to going to the last floor.
is there any way to make them separate and going to that floor by a single click? or make a list for the floors like the firstScene?

**Comment by mpetroff** [comment]
Using the API's `loadScene` method, you can create buttons to load whatever scene you want.
