### ISSUE TITLE
Change the scene arrow image

### ISSUE THREAD

**Issue by thecrazyfellow** [mpetroff/pannellum#65]
Hello Matt,

Really an amazing html5 player for panorama.

Was wondering if we can change the image of the arrow to any other image as a config change?

Also the same for the info image.

Cheers,
Adam

**Comment by mpetroff** [comment]
You can by using the `header` parameter, the contents of which are inserted into the document header. Try this (inserting the appropriate URLs or Data URIs):

```html
<style>
.hotspot.info {
    background: url(...);
}
.hotspot.scene {
    background: url(...);
}
</style>
```

The images are 26px by 26px.

**Comment by thecrazyfellow** [comment]
Thanks Matt,

The picture need to change perspective based on the user behavior but for now I'm happy with that.

Is there any way to define to go backwards in the panorama.

For example if I'm in pano1 and I'm heading to pano2 the I go from pano 2 to pano1, the view is different than when I started in pano1

For example, if I want to go back I will see a different view in a particular pano than if I go forward.

Just a way to define the POV (Point of View) for the user.

Something like google business virtual tour:

https://www.google.com.au/maps/place/SMOKE.+on+Cherry+Street,+1542+E+15th+St,+Tulsa,+OK+74120/@36.140403,-95.970008,20.91z/data=!4m2!3m1!1s0x87b6ec96df9c31c1:0x8ce3797619c4bd5e?hl=en-AU

Cheers,
_adam

+61 40222 9001

**Comment by mpetroff** [comment]
Under the hot spot configuration, you can use the `targetPitch` and `targetYaw` parameters to specify the pitch and yaw of the target scene.

**Comment by thecrazyfellow** [comment]
Thank you

**Comment by el3shry** [comment]
Thanks A lot , this conversation was very helpful
