### ISSUE TITLE
Resize does not seem to work in some cases.

### ISSUE THREAD

**Issue by elliotsabitov** [mpetroff/pannellum#653]
Hello, and thank you so much for this library, it is excellent and super helpful, great work! 

I am having a slight issue with the resize functionality however. The container / wrap div that surrounds the pannellum is being resized and I am calling the resize function on the pannellum instance. This is working fine. My configuration has `autoRotate: -2` so the image is automatically slowly rotating, and resizing correctly.

The problem arises after the user clicks and drags the pannellum to look around the image. After they do so, the resize function no longer resizes the image correctly and after the container resizes the image appears warped. 

Any suggestions on how I can resolve this?

**Comment by mpetroff** [comment]
Do you have an example with which I can try to reproduce this?

**Comment by elliotsabitov** [comment]
Sure, no problem. Please take a look here - https://codepen.io/elliotsabitov/pen/OBLwOK. As you can see, if you first load the page, **do not drag the image around**,  when you click on the width change buttons, the `pennulum.getRenderer().resize();` gets called at the end, and the resize happens and it looks good. However, after you drag the image around, then clicking the width buttons, the resize() function does not work as it previously did. The image ends up being being warped..

Let me know if there is anything else I can do to help resolve this issue. This library is wonderful and I hope we can resolve this problem!

**Comment by mpetroff** [comment]
You're calling the wrong resize function. Call `pennulum.resize()` instead (the renderer functions generally shouldn't be called directly).

**Comment by elliotsabitov** [comment]
that works, thank you!!
