### ISSUE TITLE
Video controls not usable (regression)

### ISSUE THREAD

**Issue by rtsaaq** [mpetroff/pannellum#654]
The video example (https://pannellum.org/documentation/examples/video/) does not seem to work accordingly to announced Browser Compatibility (https://pannellum.org/features/). Although everything works fine with Google Chrome,
- Player controls bar does not work in Firefox and Safari;
- Player and panorama don’t work in Internet Explorer 11 or Edge.

Is this a known issue? Is there a quick fix or workaround?

**Comment by mpetroff** [comment]
It appears to be a regression introduced in Pannellum 2.4. I fixed it, for Firefox at least, in 4d1c54f248d9fdf2eeabc42b2c9a39f146429dfd (just an update to `videojs-pannellum-plugin.js`) and pushed the changes to pannellum.org. Could you please test to see if the fix also works for IE / Edge?

**Comment by rtsaaq** [comment]
Thanks for your diligent support, it now works fine with Safari, Firefox and Edge.

I however get the following message on IE11 : "Your browser does not have the necessary WebGL support to display this panorama.", even though this website indicates the browser is WebGL compatible (experimental) : https://get.webgl.org/. Any idea?

**Comment by mpetroff** [comment]
What is printed to the browser's developer console (F11)?

**Comment by rtsaaq** [comment]
<img width="568" alt="ss-ie11-w81" src="https://user-images.githubusercontent.com/42848490/45568337-580a3000-b82a-11e8-8ac7-79d0cf087ab4.png">

**Comment by mpetroff** [comment]
IE11 doesn't support the use of video textures in WebGL (I had forgotten about this). See #607.

**Comment by jongmoon** [comment]
@mpetroff I can solve it using canvas. video textures can be supported via canvas.

  - video -> canvas 
  - use canvas instead of video when ie11.

I think performance issues can be compromised.
hope it helps.
