### ISSUE TITLE
How to maintain automatic rotation and gyroscopes effective

### ISSUE THREAD

**Issue by fxss5201** [mpetroff/pannellum#656]
Hello, it is excellent.

How to set up can still rotate automatically or keep the gyroscope effective when touching operation?

I have an auto-rotating switch button that turns on auto-rotation, but after touching it, auto-rotation is disabled, but I hope it can still be auto-rotation.The same is true for gyroscopes.

**Comment by mpetroff** [comment]
Does setting the `draggable` configuration parameter to `false` accomplish what you want?

**Comment by fxss5201** [comment]
You have misunderstood me.

I hope that when I touch the Pannellum, it can still auto-rotation.
Or when I touch the Pannellum, the gyroscope is still effective.

**Comment by mpetroff** [comment]
You didn't answer my question. Please try setting the configuration parameter I mentioned and report back as to whether or not it accomplishes what you want.

When `draggable` is set to `false`, touches / clicks do not interrupt auto-rotation or device orientation control, which as far as I can tell is what you're asking about.

**Comment by fxss5201** [comment]
So sorry.

Setting the `draggable` configuration parameter to `false` can't meet my needs.

When draggable is set to false, I can't operate Pannellum by touching/ clicking it.
I hope touches / clicks operation and auto-rotation / device orientation control do not affect each other, and can work simultaneously.

I have thought of the solution. I know the rotation state of pannellum before touches, so add the `touchend` events, 

```
var panoImg = pannellum.viewer('panorama', {
    "type": "equirectangular",
    "panorama": "https://pannellum.org/images/alma.jpg"
});

panoImg.on("touchend", function(){
    if(rotationState == 1){ // rotationState: 1-->>pannellum auto-rotation
        panoImg.startAutoRotate();
    }
});
```

Device orientation control can be solved with the above methods.

Finally, thank you very much for your help.
