### ISSUE TITLE
Unable to use some controls.

### ISSUE THREAD

**Issue by snblg** [mpetroff/pannellum#659]
Hello, 

I cannot use some controls :
mouseZoom showControls showZoomCtrl
return an error message : "an invalid configuration parameter was specified : ..."

Other controls like
yaw pitch hfov
are Ok

I'm using your latest 2.4.0 download files.
Are these parameters ok for you ? What could I do wrong ?

Thanks in advance.

**Comment by mpetroff** [comment]
As clearly stated in the documentation, only a subset of the possible configuration parameters can be used as [URL parameters](https://github.com/mpetroff/pannellum/blob/master/doc/url-config-parameters.md). You're trying to use parameters that can only be used in JSON configuration files.

**Comment by snblg** [comment]
@mpetroff : thank you very much. 

It works now. I did not understand that only some functions were used as URL parameters !

I had a look at your exemple-cube.htm and started playing with example-cube.json.
Then I made my first json file with equirectangular picture.

You did a great job.

**Comment by snblg** [comment]
And ... solved !
