### ISSUE TITLE
Video: Hotsopt URL Load another video in same player

### ISSUE THREAD

**Issue by OmarNegm** [mpetroff/pannellum#660]
Hi there,

I'm using the following script for declaring hotspots and info on my 360 video and everything works fine:

`<script>
        videojs('panorama', {
            loop: true,
            autoplay: true,
    plugins: {               
        pannellum: {
            "title": "Cars",
            "hotSpots": [
                {
                    "pitch": 0.0,
                    "yaw": -0.5,
                    "type": "scene",
                    "text": "Go Inside!",
                    "URL": "index2.html", // <-- Switching to another video in the same player rather than load another html page                
                }, {
                    "pitch": -9.4,
                    "yaw": 222.6,
                    "type": "info",
                    "text": "Street."
                }, {
                    "pitch": -0.9,
                    "yaw": 144.4,
                    "type": "info",
                    "text": "My hatchback car ;)"
                }
            ],            
        }
    }
});
    </script>`

Now i'm trying to make the hotsopt load another 360 video in the same player rather than load another webpage, Is there is a way to do that the same way in panorama?

I tried to set the vider link to the URL attribute but nothing it doesn't work with me.

Thanks

**Comment by mpetroff** [comment]
This isn't supported. However, you could probably get something to work by using a `clickHandlerFunc` for the hot spot.

**Comment by OmarNegm** [comment]
Thanks for your answer mpetroff

But really I couldn't understand what you mean 'by using a clickHandlerFunc for the hotspot', would you please tell me more about the idea?!

It would be great if you mention an example that's will much better clear. :)

Thanks in advance

**Comment by mpetroff** [comment]
Here's the relevant documentation:
https://github.com/mpetroff/pannellum/blob/master/doc/json-config-parameters.md#clickhandlerfunc-function-and-clickhandlerargs-object

You can define a JavaScript function that is called when the hot spot is clicked.

**Comment by OmarNegm** [comment]
Hi mpetroff, 

Thanks for sharing the link, But i tried both of the next two ways it doesn't work with me:

Way 1:
`var element = document.getElementById("panorama");
        element.addEventListener("clickHandlerFunc", myhandler());
        videojs('panorama', {
            loop: true,
            autoplay: true,
            plugins: {
                pannellum: {
                    "title": "Elibre",
                    "hotSpots": [
                        {
                            "pitch": -3,
                            "yaw": 129,
                            "type": "scene",
                            "text": "Dining Room",
                            "URL": "/index3.html", // <-- Switching to another video in the same player rather than load another html page
                            "click": "hotspotClicked()"
                        }, {
                            "pitch": -0.9,
                            "yaw": 79.5,
                            "type": "scene",
                            "text": "Marocco Bath",
                            "URL": "index2.html",
                            "click": "hotspotClicked()"
                        }, {
                            "pitch": -0.9,
                            "yaw": 136.5,
                            "type": "scene",
                            "text": "Home Theatr",
                            "URL": "index4.html",
                            "click": "hotspotClicked()"
                        }
                        , {
                            "pitch": -0.9,
                            "yaw": 185,
                            "type": "scene",
                            "text": "Living",
                            "URL": "index5.html",
                            "click": "hotspotClicked()"
                        }
                    ],
                }
            }
        });
        function hotspotClicked(args) {
            console.log("Hello from hotspot click!");
        }`
Way 2:
`var element = document.getElementById("panorama");
        element.addEventListener("clickHandlerFunc", myhandler());
        videojs('panorama', {
            loop: true,
            autoplay: true,
            plugins: {
                pannellum: {
                    "title": "Elibre",
                    "hotSpots": [
                        {
                            "pitch": -3,
                            "yaw": 129,
                            "type": "scene",
                            "text": "Dining Room",
                            "URL": "/index3.html", // <-- Switching to another video in the same player rather than load another html page
                            "clickHandlerFunc": "hotspotClicked()"
                        }, {
                            "pitch": -0.9,
                            "yaw": 79.5,
                            "type": "scene",
                            "text": "Marocco Bath",
                            "URL": "index2.html",
                            "clickHandlerFunc": "hotspotClicked()"
                        }, {
                            "pitch": -0.9,
                            "yaw": 136.5,
                            "type": "scene",
                            "text": "Home Theatr",
                            "URL": "index4.html",
                            "clickHandlerFunc": "hotspotClicked()"
                        }
                        , {
                            "pitch": -0.9,
                            "yaw": 185,
                            "type": "scene",
                            "text": "Living",
                            "URL": "index5.html",
                            "clickHandlerFunc": "hotspotClicked()"
                        }
                    ],
                }
            }
        });
        function hotspotClicked(args) {
            console.log("Hello from hotspot click!");
        }`

As I asked you before, Sharing an example here will solve the mystery :)

Waiting ur replay

**Comment by OmarNegm** [comment]
Now it works after some search :)

`var pannellumObj = {
            "title":"360 Video",
            "author": "eten",
            "hotSpots": [
               {
                   "pitch": -8,
                   "yaw": 157,
                   "type": "scene",
                   //"text": "Reception",
                   //"URL": "index2.html",
                   "cssClass": "custom-hotspot",
                   "createTooltipFunc": hotspot,
                   "createTooltipArgs": "Reception",
                   "clickHandlerFunc": hotspotClick,
                   "clickHandlerArgs": "/index2.html"
               }]};`

Now I'm able to pass both of MouseEvent object and clickHandlerArgs  -which is "/Index2.html" in the example above- to the "hotsoptClick" function and that's what I want to do.

But it's very important to have the same way of Panorama Tour's senses transition by clicking Hotspot in Video as well.

Thanks

**Comment by mpetroff** [comment]
Do you still have a question, or may I close this issue? It's unclear to me whether or not there's a question in your last sentence.
