### ISSUE TITLE
Video hotspot: Changing hotspots icons

### ISSUE THREAD

**Issue by OmarNegm** [mpetroff/pannellum#661]
Hi there,

I'm using the `type` attribute of `hotsopt` object for specify the type of the hotspot `info` or `scene`, Can i assign a new icons for any type of hotsopts rather than the default icons used in the video player?

![image](https://user-images.githubusercontent.com/21000109/46076040-ad303500-c18c-11e8-90ed-1cc48e867ef0.png)

Thanks

**Comment by mpetroff** [comment]
This is supported via the `cssClass` hot spot parameter. See the [custom hot spots example](https://pannellum.org/documentation/examples/custom-hot-spots/).
