### ISSUE TITLE
Video controls: Add panorama zoom-in/out buttons to the video player

### ISSUE THREAD

**Issue by OmarNegm** [mpetroff/pannellum#662]
Hi there,

Can i add the panorama player zoom-in & zoom-out buttons to the video player?

![image](https://user-images.githubusercontent.com/21000109/46076247-465f4b80-c18d-11e8-82f1-1bb5334071ff.png)

Thanks

**Comment by mpetroff** [comment]
Edit the `videojs-pannellum-plugin.js` file and remove / comment out the `config.showZoomCtrl = false;` and `config.showFullscreenCtrl = false;` lines.
