### ISSUE TITLE
autoRotateStopDelay does not stop rotating ?

### ISSUE THREAD

**Issue by aspiringguru** [mpetroff/pannellum#666]
excellent package, I'm impressed and thankful.

tried using autoRotateStopDelay.
https://pannellum.org/documentation/reference/

pannellum.viewer('panorama', {
    "type": "equirectangular",
    "panorama": "blah.jpg",
    "autoLoad": true,
    "autoRotate": 6,
    "autoRotateInactivityDelay": 1000,
    "autoRotateStopDelay": 1000
});

any suggestions? must be something obvious I've missed. have tried changing the direction of rotation to ensure it's not a caching issue. 

also: is there a way to auto change from one scene to another scene when no user input?

**Comment by mpetroff** [comment]
You also set `autoRotateInactivityDelay`, which automatically starts auto rotation, canceling the effect of `autoRotateStopDelay`. Remove the `autoRotateInactivityDelay`, and auto rotation should stop on its own.

You can programmatically change scenes with external code using the `loadScene` method.
