### ISSUE TITLE
Am I able to put a gif in the panorama scenery? - Question

### ISSUE THREAD

**Issue by Malcolm-Movement** [mpetroff/pannellum#667]
Much like how we are able to put images in as custom hotspots, can we put Gifs in and have them in motion? As in playing but not moving along with the viewport?

**Comment by mpetroff** [comment]
I'm not really sure what you're asking. Your can set a custom hot spot to be a GIF the same way you can make it a still image.

**Comment by Malcolm-Movement** [comment]
Hi again!
It seems as though the way I was referencing the gif was totally wrong, and the size of the gif asset needs to be readjusted. Thanks for the response though.
Malcolm
