### ISSUE TITLE
Video: Programmatically Zoom-in/Zoom-out Videos (Mouse Wheel Effect)

### ISSUE THREAD

**Issue by OmarNegm** [mpetroff/pannellum#669]
Hi mpetroff,

Is there is a way to programmatically Zoom-in or Zoom-out videos?

I mean the same effect when we scrolling the mouse wheel over the video player?

I successfully activated the Zoom-in and Zoom-out controls in the Video player but it's not working smoothly like the mouse wheel effect even after calling the .click() method of the Zoom-in button many times within a loop.

Any ideas?!

**Comment by mpetroff** [comment]
The [custom controls example](https://pannellum.org/documentation/examples/custom-controls/) includes an example of how to change the zoom programmatically.
