### ISSUE TITLE
How do I set a partial video panorama?

### ISSUE THREAD

**Issue by ErfolgreichCharismatisch** [mpetroff/pannellum#671]
First: your framework is intuitive and robust and I am really thinking about donating coffee :-)

Having done your tutorials, I am now at the last one with video. It works.

I thought about using a GoPro-Video for that. Problem is, it is a partial panorama encoded in a fisheye image. The partial parameters do not work for video. How do I set a partial video panorama?

**Comment by mpetroff** [comment]
I've never tried to use a partial video panorama, but I see no reason why it wouldn't work.

However, a GoPro video isn't going to work with reprojecting it, since only equirectangular video is supported. If you convert the video to equirectangular projection, it should work.
