### ISSUE TITLE
multiple panorama images in 1 page?

### ISSUE THREAD

**Issue by radenayu** [mpetroff/pannellum#677]
Hi there!

First thanks for the awesome pannellum!
I got a question, is it possible to show more than 1 panorama images in the same page?

**Comment by mpetroff** [comment]
Yes. Just create multiple viewers.

**Comment by bachirelkhoury** [comment]
I was able to overlay multiple viewers without a problem. 
@mpetroff I have multiple 360's I would like to keep the rotation in sync.
However the touch/click is only captured by the top viewer. Is there a way to get the viewer at the back also handle the click and drag, so both viewers would rotate at the same time?

**Comment by mpetroff** [comment]
There's no good way to do that. You could use the pitch / yaw get / set methods, but there's no good way to trigger calling them.

**Comment by bachirelkhoury** [comment]
@mpetroff thanks for the prompt response. I was able to use the pitch and yaw as you've suggested, and using the 'mouseup' as the trigger to update.
