### ISSUE TITLE
Taking a screenshot of the current view

### ISSUE THREAD

**Issue by bagus-setyawan** [mpetroff/pannellum#680]
Hey, thanks to awesome lib, i was using since 2016.
I need take a screenshot current view angle, im using <iframe> method to load the panorama images, that i have done is using dom to image library, html to canvas,  they can not render the image. When im using canvas, the downloaded image just showing the control and the view is black.
So is it possible to take screenshot to the current view without using browser plugin ?
Thanks so much

**Comment by mpetroff** [comment]
The view is black because the WebGL context's `preserveDrawingBuffer` parameter is `false` (there's a performance penalty for having it set to `true`).

To save the rendered view, you need to use the API. Something like:
```javascript
var viewer = pannellum.viewer(...);
...
var img = viewer.getRenderer().render(viewer.getPitch() / 180 * Math.PI,
                                      viewer.getYaw() / 180 * Math.PI,
                                      viewer.getHfov() / 180 * Math.PI,
                                      {'returnImage': true});
```
will return the current view as a base64-encoded PNG data URI.

Also see #448 and #672.

**Comment by bagus-setyawan** [comment]
Thanks for answering my question, i can get the image now. I want to ask something again, i make new control button like in the bottom pic to take the current view screenshot. Soon, i add click the listener that will run savePanoImage(viewer_id) function in the body element script scope.
`/**
 * Take panorama snapshot.
 * @private
 */
function takeSnapshot() {
    if (loaded) {
        savePanoImage(config.viewer_id);
    }
}`
`var pano1 = pannellum.viewer('panorama', {
    "type": "equirectangular",
    "panorama": "pano.jpg",
	"viewer_id": "pano1"
});
function savePanoImage(id){
	var viewer = eval(id);
	var img = viewer.getRenderer().render(viewer.getPitch() / 180 * Math.PI,
                                      viewer.getYaw() / 180 * Math.PI,
                                      viewer.getHfov() / 180 * Math.PI,
                                      {'returnImage': true});
	var link = document.createElement('a');
        link.download = 'my-image-name.jpeg';
        link.href = img;
        link.click();
	console.log(img);
}`
I need doing this because i have several panorama dynamically loaded. It's works but is there another method i can use to achieve the same, like getting the rendered image directly in the takeSnapshot listener's function. Sorry for the bad english explanation. Thanks

![image](https://user-images.githubusercontent.com/12988812/47901980-d6db2b00-deb3-11e8-8505-f993887e60f7.png)

**Comment by mpetroff** [comment]
It's best to not added anything to `pannellum.js` (using the unmodified file makes maintenance and updates easier). Thus, I'm not going to recommend anything that uses Pannellum's internals, which are also subject to change.

Instead, you should move the `takeSnapshot` function to your main script and use `if (pano1.isLoaded())` instead of `if (loaded)`.

**Comment by bagus-setyawan** [comment]
ahh... I see, i should use the custom controls then, for adding my custom screenshot button. I wish someday there is built in snapshot function, if there will not have any performance issues :grin: .This issue can be closed. Thanks for the answer and awesome lib :+1:
