### ISSUE TITLE
Next/previous scene arrows

### ISSUE THREAD

**Issue by HekkeySE** [mpetroff/pannellum#681]
I'm trying to recreate the krpano viewer but i cannot get the next/previous 360 image arrow to work. 
I want to achieve like this (thumbnails below in tour):

https://krpano.com/tours/corfu/

**Comment by mpetroff** [comment]
Take a look at the `loadScene` API method (and maybe also the [custom controls example](https://pannellum.org/documentation/examples/custom-controls/)). You could create thumbnails and add click handlers to them that call the `loadScene` method with the corresponding scene ID.
