### ISSUE TITLE
Picture distortion！！！Sawtooth！！

### ISSUE THREAD

**Issue by FannieGirl** [mpetroff/pannellum#683]
the image is jagged in the panorama preview after it is scaled down
（5376*2688  => 4096*2048）
（英语不好，我用中文表达一下；因一体机拍出来的全景图片是5376*2688,由于webGL 4096 的限制；不得不把图片等比例压缩至4096*2048；压缩后的图片在移动端查看，有很明显的像素，也就是锯齿。还有一个问题pannellum 图片跟原图 不一样 想是加了滤镜（light 灯光原因吗？））
![image](https://user-images.githubusercontent.com/19258229/47912452-b1f6b000-ded3-11e8-8698-70f4be370979.png)

**Comment by mpetroff** [comment]
This issue tracker is in English. I don't speak Chinese.

It looks like you did a bad job scaling down the image. I'd recommend using bicubic or Lanczos rescaling algorithm.

**Comment by FannieGirl** [comment]
Using Lanczos rescaling algorithm. not solved
I want to change a method
"This panorama is too big for your device! It's 5376spx wide, but your device only supports images up to 4096px wide......."  
Before this error ，Load other images link
Is there any way?

**Comment by mpetroff** [comment]
There are a few options:

- If you use the Git `master` branch, the pixel limits are doubled, so you can use images up to 8192px wide without rescaling (this will be in the next release).
- If you convert the image to a [multiresolution panorama](https://pannellum.org/documentation/examples/multiresolution/) or a [cube map panorama](https://pannellum.org/documentation/examples/cube-map/), you can use higher resolution.
- You can check the maximum supported WebGL texture size before loading the panorama. See https://github.com/mpetroff/pannellum/issues/472#issuecomment-330059690 for details.

**Comment by FannieGirl** [comment]
thank you very much

**Comment by mpetroff** [comment]
I may have fixed this pixelation issue in 59893bcea4629be059ad3e59c3fa5bde438d292b. See https://github.com/mpetroff/pannellum/issues/725#issuecomment-482757714.
