### ISSUE TITLE
Switching to a dynamic scene doesn't work - always stuck in 'loading...'

### ISSUE THREAD

**Issue by nedt** [mpetroff/pannellum#686]
For a new project I need to be able to switch from a static image version of a panorama to a dynamic video version. I've already created two separate versions, one with the image, the other using a video element as `config.panorama` and `config.dynamic = true` (based on the videojs example).

I've now merged them having two scenes, one for the image and one for the video and use `loadScene()` and `setUpdate(true)` to switch to the video version (depending on device, if video has loaded, and so on). But I always got stock in 'Loading ...' after switching to the video scene.

Going through the code I've  discovered, that `renderInitCallback()` is removing the loading screen, which gets called by `renderer.init()` in `renderInit()`. But `renderInit()` never gets called, because `setUpdate()`, would only do so if there is no renderer yet (via `onImageLoad()`).

So I guess `loadScene()` should either call `onImageLoad()`, if the new scene is dynamic, or `setUpdate()` needs to check for a scene change.

**Comment by mpetroff** [comment]
I've never previously tested trying to switch to a dynamic scene, so it's not particularly surprising that it didn't work. I think I fixed this issue in a05721198901cf2554e560f5029184ee897b4fc1.
