### ISSUE TITLE
`addScene` and `addHotSpot` examples

### ISSUE THREAD

**Issue by rahultandon2007** [mpetroff/pannellum#687]
I am trying to add scene dynamically using viewer.addscene but it is not working properly.

My purpose is to provide dynamic configuration insted of using hard coded configuration.I also want to add hot spot dynamically.
Please share addscene and addhotspot example using loops.

**Comment by mpetroff** [comment]
I don't have any such examples readily available.

**Comment by rahultandon2007** [comment]
Is it possible to create configuration automatically?

**Comment by mpetroff** [comment]
Depending on what you're trying to do, it should be possible to write code to do so.
