### ISSUE TITLE
Crosshair option?

### ISSUE THREAD

**Issue by strangerism** [mpetroff/pannellum#691]
Hello, 

is there an option to add a crosshair in the UI that always points to the center of the panorama?

many thanks

Massimo

**Comment by strarsis** [comment]
@strangerism: Yes, it is already there, you can enable it with the [`hotSpotDebug`](https://pannellum.org/documentation/reference/#hotspotdebug-boolean) option.

**Comment by strangerism** [comment]
thanks a lot!!
