### ISSUE TITLE
Not works on iPhone, iPad and Windows Edge browser

### ISSUE THREAD

**Issue by EdwardSEM** [mpetroff/pannellum#692]
When I open a web page with 360 images on iPhone (Safari), it is reloading and then I got a message "Website throws an error"
It is working on Android and Desktop chrome
Fullscreen mode not working for Windows Edge browser

**Comment by mpetroff** [comment]
Can you please be more specific? Which web page? What browser version?

"Website throws an error" is not a Pannellum error message, so this sounds like a bug in Safari. I cannot reproduce this with the pannellum.org examples on an iPhone 5c with iOS 10.3.3.

Full screen works for me in Edge 42.17134.1.0 for the pannellum.org examples.
