### ISSUE TITLE
Can Pannellum get custom plugin ?

### ISSUE THREAD

**Issue by pagongamedev** [mpetroff/pannellum#693]
If i want use degree of compass for create mini map plugin for pannellum.

how i can get it. or how i can create plugin for pannellum?

//Sorry for my wording. I can write English little bit

//custom plugin look like https://forgejs.org/plugins. it plugin for forge.js

**Comment by pagongamedev** [comment]
now i have solve of get angle value

viewer = pannellum.viewer(...)
viewer.getPitch()

sorry for my poor question.

**Comment by mpetroff** [comment]
Were you able to answer your own question?
