### ISSUE TITLE
What is the difference between Viewer and Render?

### ISSUE THREAD

**Issue by DStillingfleet** [mpetroff/pannellum#694]
Hi Matthew

Might be a stupid question, but what is the difference between Viewer and Render in the API, and when should one or the other be used?

I've only ever used Viewer.

Many thanks

Derek

**Comment by mpetroff** [comment]
The renderer is just the WebGL portion that actually renders the view (`libpannellum`); it doesn't include any of the navigation or user input portions. You should stick to the viewer unless you're doing something specific that requires access to the lower-level rendering capabilities.

**Comment by DStillingfleet** [comment]
Thank you Matthew.
