### ISSUE TITLE
Error: WebGL warning: <SetDimensions>: Exceeded 16 live WebGL contexts for this principal, losing the least recently used one.

### ISSUE THREAD

**Issue by DStillingfleet** [mpetroff/pannellum#695]
Hi Matthew

Thank you for your help earlier this week.  Another question for you.

I have VR tour that uses six pannellum instances that are in turn destroyed and replaced with new instances.  Over a period of time, and seemingly at random, Firefox is reporting .....

Error: WebGL warning: <SetDimensions>: Exceeded 16 live WebGL contexts for this principal, losing the least recently used one.

There is no loss of performance, but I suspect that the same issue is causing safari on my iPhone crash.

So I have been doing some testing.  Firefox copes with up to 16 pannellum instances open on one page (until the browser is refreshed).  Any more and the WebGL warning appears.

In my tour I'm using the .destroy() function in the API, so I tried to use this command. Creating the first 8 pannellum instances, destroying the first 4, and then creating another 8 pannellum instances.

The .destroy() removes the pannellum instance, but the WebGL warning still appears.

I even tried using javascript to remove the DIV in which the pannellum instance is loaded, but with the same WebGL warning.

Can you suggest any way to overcome this?

Perhaps the .destroy() call has not completed it's work before I load the new pannellum view.  Is there a way to test if the pannellum has been destroyed before loading it's replacement?

Kind regards

Derek

**Comment by mpetroff** [comment]
There's no way to avoid the warning, as far as I know. Just reloading the same page more than sixteen times causes it (including the [WebGL test page](https://get.webgl.org/)), so it seems to be related to how Firefox handles WebGL instances internally (I first came across this warning years ago).

Generally, I wouldn't recommend creating a large number of viewers (or any sort of WebGL context) on the same page simultaneously, due to the performance and battery usage implications. Although I haven't done any rigorous testing, I think it's better to reuse an existing Pannellum instance when possible instead of destroying it and creating a new one.

**Comment by DStillingfleet** [comment]
Thank you Matthew for quick reply.

I'll experiment with dynamically adding and removing tour scenes. 

Kind regards


Derek

**Comment by kresimirfijacko** [comment]
@DStillingfleet @mpetroff 
i am having same issue and i resolved it by manually releasing webgl context.

this should help:
document.getElementById('myCanvas').getContext('webgl').getExtension('WEBGL_lose_context').loseContext();

tested in chrome task manager by looking at GPU memory resources. 

btw i solved this in vanillaJS but later implemented in angular7 app

**Comment by DStillingfleet** [comment]
Thank  you for offering a suggestion on this kresimirfijacko.  

I've currently worked around this problem by dynamically adding scenes so as not to reach the 16 webgl canvas limit.

**Comment by ProgrammingLife** [comment]
@DStillingfleet any progress there?

**Comment by DStillingfleet** [comment]
Hi Matthew

 

 

Great to hear from you.  Hope you and all yours are well.

 

I worked around this problem.  Instead of creating new Pannellum viewers and destroying old Pannellum viewers, I am dynamically adding scenes to a tour.  

 

This works well with six Pannellum instances.

 

I’m curious why you ask, is there something new you are working on?

 

 

Best wishes

 

 

Derek
