### ISSUE TITLE
long mouse dragging on the maxYaw, makes viewer to jump to minYaw and vice versa

### ISSUE THREAD

**Issue by farminf** [mpetroff/pannellum#698]
Hi, this is maybe is not exactly an issue but the effect.
when you set min and max yaw and the difference is not much (-140 , 180) at the min and max point of viewer if you do long mouse drop, it jumps to the otherside.
this is the base issue that someone mentioned on my repo : https://github.com/farminf/pannellum-react/issues/48

**Comment by mpetroff** [comment]
This would happen when the mouse drag was quick / long enough that the yaw difference for the next frame was larger than the prohibited yaw range, causing it to jump to the other side. I fixed it by applying the yaw limits before wrapping the yaw range instead of after.
