### ISSUE TITLE
Customize the progress bar

### ISSUE THREAD

**Issue by DevelopSmith** [mpetroff/pannellum#700]
Is there a way to customize the progress bar which appears while the panorama is loading?

I know that I can do that by changing the `pannellum.css` file. But it would be great if there is a built-in method to do that.

**Comment by mpetroff** [comment]
Altering the CSS is the only way to do it. However, instead of modifying the `pannellum.css` file, I'd recommend using an additional CSS file to override it (using `!important` if needed), since doing so makes it easier to keep track of the modifications.

**Comment by DevelopSmith** [comment]
@mpetroff Thank you very much. I did what you have suggested it it worked fine.
