### ISSUE TITLE
Image distortion: hotspots behavior

### ISSUE THREAD

**Issue by Stephan811D** [mpetroff/pannellum#701]
Hey,

I'm using custom hotspots which look like rectangles (css-custom hotspot).

I have the problem that when I'm looking around the panorama the hotspots are not on the right place anymore because of the image distortion.

Hotspots look like this:
![bildschirmfoto 2018-12-29 um 12 37 22](https://user-images.githubusercontent.com/37579239/50537885-89530580-0b66-11e9-8289-9dac536184d6.png)

Is there any way to set up "hotspots" or areas on the panorama like a html use map? to set exact coordinates? 
or 
is there any way to add points in the panorama which are fix and sum up an area? 

do you have any ideas? 

greetings

**Comment by mpetroff** [comment]
No projection is applied to hot spots, so while their centers track specific locations in the panorama, they will not change in size or shape. There's no way to define an "area" hot spot.

**Comment by willcalderbank** [comment]
Its far from perfect, but it is possible to modify the library to scale the hotspot based on the center points location and hfov. For small hotspots it works well enough:

[https://github.com/willcalderbank/pannellum/commit/c2ae380f110ba3bbb48e880f699dabaef03cde37](url)
