### ISSUE TITLE
TypeError: d is undefined  pannellum.js:68:490

### ISSUE THREAD

**Issue by DStillingfleet** [mpetroff/pannellum#702]
Hi Matthew

I'm trying to overcome the 16 webgl canvas limit by dynamically adding, loading and removing scenes to a series of six Pannellum panorama, V2.4, rather than destroying and recreating them.

My javascript works up to a point until it stops working on some Pannellum panorama but continues to work with others.  

The turning point occurs at the same time the browser reports an error "d is undefined, pannellum.js:68:490".

One of the Pannellum instance then locks up (cannot be rotated), and the scene change fails to occur, even though I'm requesting it loads with a scene it already has in the tour.

Adding a seventh Pannellum instance causes the error to happen sooner.

Any idea from this error message as to what I might be doing wrong?

Kind regards and happy new year

Derek

**Comment by DStillingfleet** [comment]
Good idea.

So with the unminified version 2.4.1,  the error is now...

TypeError: current is undefined, pannellum.js:175519:19

then on trying to continue...

TypeError: current is null, pannellum.js:175519:19

**Comment by mpetroff** [comment]
That isolates it to this line: https://github.com/mpetroff/pannellum/blob/ea2a501eab6ca8a8f49d68ead98a7f3dd0ada342/src/js/pannellum.js#L1755

I'm not entirely sure how `current` ended up being undefined, but I added checks in 19b020dbc72b9aeb5d6e3faca95bb55ce5418bb5 and 34cb1a409ef169167536bef199a2a95d2642ab19 to make sure it is defined before trying to work with it.

**Comment by DStillingfleet** [comment]
Thank you Matthew.

Different errors reported this time round..

NotFoundError: Node was not found, pannellum.js:1791

When I expand the error notes I see

destroyHotSpots   ...../pannellum.js:1791:17
loadScene    ....../pannellum.js:2273:5
loadScene/fadeImg.onload     ..../pannellum.js:2244:17
openRemotePrompt    jar:file:///C:/Program Files (x86)/Mozilla Firefox/omni.ja!/components/nsPrompter.js:507:5
openPromptle     jar:file:///C:/Program Files (x86)/Mozilla Firefox/omni.ja!/components/nsPrompter.js:541:17
alert   jar:file:///C:/Program Files (x86)/Mozilla Firefox/omni.ja!/components/nsPrompter.js:614:9
HideVRModePart2  .../TourControlV30.js:658:4
HideVRMode          .../TourControlV30.js:647:2
onclick    ..../TourControlV30-001.html:1:1


and

TypeError: hs.div is undefined[Learn More] pannellum.js:1811:9
renderHotSpot

When I expand the error notes I see

renderHotSpot   ....../pannellum.js:1811:9
forEach self-hosted:262:13 
renderHotSpots   ....../pannellum.js:1845:5
render    ....../pannellum.js:1468:9
animate    ....../pannellum.js:1352:5
animateInit   ......./pannellum.js:1344:5
onDocumentMouseDown ....../pannellum.js:718:5

**Comment by DStillingfleet** [comment]
Hi Matthew

I've been doing some further testing.
The configuration data for the pannellum instances are contained in three javascript objects like this..

```
	RightPanoLow.addScene(CurrentLocation, PanoDataLowRes);
	RightPanoLow.loadScene(CurrentLocation);
	
	RightPanoIntermediary.addScene(CurrentLocation, PanoDataIntermediary);
	RightPanoIntermediary.loadScene(CurrentLocation);
	
	RightPanoHi.addScene(CurrentLocation, PanoDataFullNew);
	RightPanoHi.loadScene(CurrentLocation);
	
	// Load left hand panoramas
	if(VRMode==="On")
	{ 
	LeftPanoLow.addScene(CurrentLocation, PanoDataLowRes);
	LeftPanoLow.loadScene(CurrentLocation);

	LeftPanoIntermediary.addScene(CurrentLocation, PanoDataIntermediary);
	LeftPanoIntermediary.loadScene(CurrentLocation);
	
	LeftPanoHi.addScene(CurrentLocation, PanoDataFullNew);
	LeftPanoHi.loadScene(CurrentLocation);
	}
```

PanoDataFullNew is the only javascript object that contains hotspot information.  

I've noticed that whilst the first time the pannellum instances are loaded (right hand only) the hotspots are in the correct place.  

The second time the pannellum instances are loaded, the hotspot for the left hand side is shown, but not plotted in the correct place, and the hotspot in the right hand pannellum is not shown at all.  Which is perhaps why it is not being removed and the above errors are showing.  It's trying to remove hotspots that are not there to remove.

If I do not include hotspots, the scene removal process works fine and there are no errors. I can add and remove scenes all day.

**Comment by DStillingfleet** [comment]
Hi Matthew

The more detailed error messages have helped me track down what's going on.  

Somewhere in my code the object "PanoDataFullNew" that contains the pannellum configuration data is being corrupted.  So no need for any further assistance on this one. 

Once again, many thanks


Derek
