### ISSUE TITLE
Does Pannellum support non-360 image viewer?

### ISSUE THREAD

**Issue by shubhada-antapurkar** [mpetroff/pannellum#704]

**Comment by mpetroff** [comment]
Yes, as long as the image is in equirectangular projection. See the [partial panorama example](https://pannellum.org/documentation/examples/partial-panorama/).

**Comment by LitoMore** [comment]
@mpetroff What about the wide angle photo?

![image](https://user-images.githubusercontent.com/8186898/51514484-f21e5c80-1e4a-11e9-8606-b8d2111fdd94.png)

**Comment by mpetroff** [comment]
You need to reproject it to equirectangular projection.
