### ISSUE TITLE
Cube map image quality on iphone

### ISSUE THREAD

**Issue by DStillingfleet** [mpetroff/pannellum#708]
Hi Matthew

I've noticed a significant difference in the quality of an image when using cubemaps on an iphone when compared to android or a PC for that matter.

This first screen shot is from an iPhone 6s iOS 12.1.2 safari browser.  The left hand image is a 4096 pixel wide equirectangular.  The right hand side the same image, but 5376 pixels wide as a cube map. But it actually looks a lot worse.

<img width="375" alt="iphone_screenshot" src="https://user-images.githubusercontent.com/12188812/51499006-93140580-1dc0-11e9-8138-a012f0f48efa.png">

The same images can be seen here on an android phone.  You can see that the image quality from left to right is similar.

<img width="360" alt="android_screenshot" src="https://user-images.githubusercontent.com/12188812/51499027-a0c98b00-1dc0-11e9-9c27-635f1fad62a2.png">

Here's another good example from the iPhone where the left hand side is again a 4096 pixel wide equirectangular, and the right hand side a cube map image originally 8192 pixels wide.  

<img width="375" alt="iphone_screenshot2" src="https://user-images.githubusercontent.com/12188812/51498892-239e1600-1dc0-11e9-8d2e-40a4ce249938.png">

This time you can see the benefits of the higher resolution cube map in nearly everything but in the horizontal detailing of the van doors.  On an Android device or PC, you don't see this pixelization.

Any ideas as to what might be causing the degradation of the cub map image on the iPhone? Or is it something iPhone users will have to live with?

Best wishes

Derek

**Comment by mpetroff** [comment]
There seems to be something strange going on with the interpolation. I can't reproduce the issue under iOS 10.3.3, which suggests that it is due to a more recent change on Apple's part. My guess is that's it's either a bug in Safari or part of an ill advised attempt by Apple to improve performance / battery life by taking shortcuts when doing the interpolation. I'm not sure there's much that can be done about it either way, although without knowing the exact cause, I can't make such a claim with much certainty.

**Comment by DStillingfleet** [comment]
Understood Matthew, I appreciate you looking at t.

I tried to make a comparison on my old iPhone 4S which is sat on iOS 9.3.5, but it seems to to load cubemaps at all.

Best wishes


Derek

**Comment by DStillingfleet** [comment]
Hi Matthew

That’s very interesting, and explains why cube map generators default to power of two conversation. I’ll have to give some thought as to how best to use cube maps.

Many thank


Derek

**Comment by mpetroff** [comment]
I may have fixed this pixelation issue in 59893bcea4629be059ad3e59c3fa5bde438d292b, although I can't be sure in this case, as I was not able to reproduce it. See https://github.com/mpetroff/pannellum/issues/725#issuecomment-482757714.

**Comment by DStillingfleet** [comment]
Hi Mathew

Just tested the fix, it works beautifully, thank you.

Best wishes


Derek

**Comment by DStillingfleet** [comment]
Hi Matthew

I thought I would share a screen shot of the same view as above after the fix you introduced.

![IMG_1355](https://user-images.githubusercontent.com/12188812/57072122-8282fd80-6cd4-11e9-826a-26adc44bed38.PNG)

Again from an iPhone 6s, where the left hand side is again a 4096 pixel wide equirectangular, and the right hand side a cube map image originally 8192 pixels wide.

Both images have been dramatically improved, though the higher resolution image is obviously clearer.

I'm really pleased and impressed.

Many thanks


Derek
