### ISSUE TITLE
Pannellum is leaking DOM Nodes and event listeners after destroy

### ISSUE THREAD

**Issue by vially** [mpetroff/pannellum#710]
It looks like the `viewer.destroy()` method does not clean up everything properly and it's leaking DOM nodes and events listeners. This seems very similar to the problem reported in #506.

### Demo project

I've created a [very small demo](https://github.com/vially/pannellum/blob/leaks-demo/src/standalone/leaks_demo.html) which reproduces the problem (the `leaks_demo.html` file needs to be copied and run from inside the `standalone` directory).

### Performance monitor graph

![pannellum_leaks](https://user-images.githubusercontent.com/433598/51989417-4c509a80-24a7-11e9-8c98-1f084c292607.png)

Running the demo and repeatedly creating and then destroying the Pannellum viewer (by pressing the `Toggle Pannellum` button) generates the above graph. The staircase pattern seems to suggest the `destroy()` method does not clean up properly.

**Comment by mpetroff** [comment]
Three event listeners added to the root container element weren't being removed properly, which was preventing the viewer from being fully garbage collected. I've now fixed this.

#506 has to do with event listeners that are only used with multiresolution panoramas, so it's not quite the same thing.

**Comment by vially** [comment]
Awesome, thanks for the very quick fix. This seems to address the issue we were having.
