### ISSUE TITLE
Orientation on: Pitch changes slightly

### ISSUE THREAD

**Issue by skzind** [mpetroff/pannellum#715]
On my Android 9 phone with latest Chrome/Firefox, images have a slight pitch to the right when orientation by sensor is on. If I turn it off, the horizon is horizontal again. Can you shed some light on this behavior? Thank you so much!
![screenshot_20190226-095927](https://user-images.githubusercontent.com/41060987/53400626-8e89d080-39ae-11e9-9388-e4155ccccbe1.png)

**Comment by mpetroff** [comment]
If your phone is tilted, Pannellum will tilt the horizon to match in device orientation mode. If this doesn't match the actual tilt of your phone, your phone is probably reporting erroneous values via the Device Orientation API.
