### ISSUE TITLE
Question: Build tools

### ISSUE THREAD

**Issue by tantayota** [mpetroff/pannellum#716]
Can you help me with this.  after i downloaded the source code i  tried to build  pannellum using the requirements in the utils/build folder and it keeps closing after i open it. Maybe this is a stupid question because im a beginner in building using python. thanks :)

**Comment by tantayota** [comment]
![image](https://user-images.githubusercontent.com/48040060/53464158-3b824d00-3a84-11e9-9559-b6943e3d6602.png)
i put pause on the build.bat and this is the result

**Comment by mpetroff** [comment]
In general, the build script expects to be in a Git repository and requires the Git executable; you don't have Git on your path, hence the error. This can be bypassed by calling `python3 build.py release` (the only difference between development and release builds is the version numbering). Either way, `java` must be on your path.

**Comment by tantayota** [comment]
thankyou for your answer :) my main reasons of editing from source code is to change the appearance of the User interface. I am new to this kind of development and i cannot find the answer to the internet so i reach out to you . thank you very much

**Comment by strarsis** [comment]
For changes that are too specific for being added to upstream (this) repository, 
I forked pannellum repo locally and use a separate branch.
