### ISSUE TITLE
React - hotspotDebug and getPitch()

### ISSUE THREAD

**Issue by tarambuka** [mpetroff/pannellum#717]
In react I have hotspotDebug enabled and by click on Panorama I got 

`Pitch:28.48029716294338, Yaw: -167.8056808426881, Center Pitch: 10, Center Yaw: 180, HFOV: 110`
I have listener onMousedown and get a lot of info like `clientX: 505, clientY: 113` but cannot get Pitch & Yaw. 
I tried to use  this.refPannellum.getViewer().getPitch() but I got as result value '10', which is Center Pitch I guess. I'm not sure if I do something wrong or there is no way to add hotspot by getting position on click on Panorama.

**Comment by mpetroff** [comment]
Use the [`mouseEventToCoords`](https://pannellum.org/documentation/api/#mouseeventtocoords) method to convert the mouse coordinates to pitch / yaw. As you surmised, `getPitch` returns the pitch of the center of the view, as is mentioned in [the documentation](https://pannellum.org/documentation/api/#getpitch).

**Comment by tarambuka** [comment]
Hello @mpetroff , thank you very much! mouseEventToCoords works fine :)
