### ISSUE TITLE
Is FLV can't play with video API?

### ISSUE THREAD

**Issue by ZhengYongHe** [mpetroff/pannellum#721]
thx for ur open-source pannellum 
  I'm trying to  use the flv in ur api, but it seens doesn't work and say "No compatible source was found for this media.". I  wonder know what format else can be supported except mp4?

**Comment by ZhengYongHe** [comment]
I have tried turn the flash on in chrome and it still plays the same.

**Comment by mpetroff** [comment]
Flash videos aren't compatible with HTML5 video elements. Any HTML5-supported video format is supported, e.g., WebM.
