### ISSUE TITLE
CSS Module not found: Can't resolve 

### ISSUE THREAD

**Issue by kelvinhalim13** [mpetroff/pannellum#722]
after i updated to the newest version  
i got errors of 
```
./node_modules/pannellum-react/es/elements/Pannellum.js
Module not found: Can't resolve '../pannellum/css/pannellum.css' in '\node_modules\pannellum-react\es\elements'
```

after i saw the modules path, css folder are not exist.

**Comment by mpetroff** [comment]
This is an issue with the React package you're using. Try opening an issue at https://github.com/farminf/pannellum-react.
