### ISSUE TITLE
Password for 360° Images

### ISSUE THREAD

**Issue by LaraLandolt** [mpetroff/pannellum#724]
Hi Matthew! Is it possible to protect the 360° Images with a password? Contrasting to other examples I saw, my panoramas are hosted on our own server.

**Comment by mpetroff** [comment]
I don't see how this has anything to do with Pannellum. This is a web server configuration question. You'd password protect the image file just like you'd do for any other file on your server, and you need to handle the authentication outside of Pannellum.
