### ISSUE TITLE
Display Modal over fullscreened panorama

### ISSUE THREAD

**Issue by Sclur** [mpetroff/pannellum#726]
Hello there, i dont know, if i've miss something, but i can't really find a way to display a modal box over the viewer. What i'm trying to achive, is to make the modal pop up, when you doubleclick somewhere on the panorama. It does pop up, but you cant see it until you close the fullscreen view. Is there any solution for that? If so, can you help me out, what should i look for?
Best regards.

**Comment by mpetroff** [comment]
If I correctly follow what you're saying, although I'm not sure that I do, you have code that makes a modal pop up, but it's only shown when you're not in full screen? If this is the case, you need to add your modal as a child element of Pannellum's container element (the element passed as the first argument to the `pannellum.viewer` constructor), since this is the element that is made full screen.

**Comment by xhit** [comment]
Hello, I have this issue. sometimes modal is created in javascript like SweetAlert2. The best option is exit of fullscreen and call the function that show a modal.

How I can solved it?

In pannelum.js (not the minified) I created the function **exitFullscreen()**

```
function exitFullscreen() {
    if (fullscreenActive) {
        if (document.exitFullscreen) {
            document.exitFullscreen();
        } else if (document.mozCancelFullScreen) {
            document.mozCancelFullScreen();
        } else if (document.webkitCancelFullScreen) {
            document.webkitCancelFullScreen();
        } else if (document.msExitFullscreen) {
            document.msExitFullscreen();
        }
    }
}
```

And I call this function  in **toggleFullscreen()**  when **fullscreenActive** variable is true (only replace the code calling **exitFullscreen()**) and in function **createHotSpot()** before:

`hs.clickHandlerFunc(e, hs.clickHandlerArgs);`
**Put**
`if(fullscreenActive) exitFullscreen();`

**Comment by mpetroff** [comment]
@xhit I have no idea what you're asking, and I have no idea what "SweetAlert2" is.

**Comment by xhit** [comment]
@mpetroff is a solution for @Sclur problem, in Pannellum I created a new object in clickHandler for exit fullscreen mode when a function needed like one that show a modal. Some modals library are JS only and you can't add your modal as a child element of Pannellum's container element, so exit fullscreen is the ideal solution if a function needed.
