### ISSUE TITLE
iOS 12.2 blocks Safari from reading gyro and accelerometer

### ISSUE THREAD

**Issue by DStillingfleet** [mpetroff/pannellum#727]
Hi

This is a note to all in the "Pannellum Community".

When Apple introduced iOS 12.2 a week or so ago, they disabled Safari from reading the iphone gyro and accelerometer.

There is no warning, and the user will have to go into the Safari settings to enable website to use the gyro and accelerometer.

The upshot is that your pannellum tours may stop working as designed, and the user will not know why.  You may wish to add some extra lines of code to tell them.

Here's the other thing.  Even if the user allows Safari to access the gyro and accelerometer, it's my experience that they still will not be read from a website without a security certificate.  I've not been able to read this anywhere else, but I found out the hard way.

Best wishes to all

Derek

**Comment by mpetroff** [comment]
The HTTPS part is not particularly surprising; there have been deprecation warnings about the device orientation API on unsecured connections in various browsers for more than a year.
