### ISSUE TITLE
Is it available to zoom out in default and scrolling available in 180° only ?

### ISSUE THREAD

**Issue by cytyler** [mpetroff/pannellum#729]
Can pannellum sets to zoom out to the max in default ? And the image scrolling only limited to 180° instead of 360° ?

**Comment by mpetroff** [comment]
You can configure the default zoom using the `hfov` parameter (horizontal field of view is well defined, unlike "zoom"). You can limit the yaw panning range with the `minYaw` and `maxYaw` parameters. This is all documented in the [configuration reference](https://pannellum.org/documentation/reference/).
