### ISSUE TITLE
Changing fast from panorama crashes the actual image

### ISSUE THREAD

**Issue by umbreak** [mpetroff/pannellum#73]
Hello,

Changing too fast from panoramas is causing the the player to crash. I fixed some small undefined errors in the setTimeout: https://github.com/mpetroff/pannellum/pull/72

but it wasn't only that.

**Comment by umbreak** [comment]
I guess it happens when `sceneFadeDuration` is set and you try to change the image while the transition is in process.

For the player to be robust, either the click is deactivated while transition takes place, or the new clicked image has to be displayed.

**Comment by mpetroff** [comment]
The undefined error you mentioned in #72 meant that the fade image was never being removed, so the new scene couldn't be seen. Your change in #72 removed the error message but didn't fix the source of the problem. It should work properly now.
