### ISSUE TITLE
API Event for Hotspot Mouseover

### ISSUE THREAD

**Issue by john-davies** [mpetroff/pannellum#730]
I'm experimenting with integrating a Pannellum tour with a separate map ( using Leaflet.js ). So far it works fine, I can navigate through the tour using Pannellum and get map markers to update on a scene change and vice versa.

However there's one extra feature that I'd like to add and I can't see a way of doing it at the moment. When I mouseover a hotspot on the Pannellum window I get a pop up giving me details about that link. What I'd like to do is to add a similar popup on the corresponding marker in the map window to give the user more information about where that link will go. My initial thought is that it would need something like the "scenechange" API event but I can't find anything suitable. Is there another way of achieving this?

My initial experiment can be found at https://thereteng.appspot.com/fan_brycheiniog_pano.html if it helps.

**Comment by mpetroff** [comment]
You can achieve this by using a custom hot spot tooltip function. Below is an example function that uses the tooltip code copied from Pannellum, so the tooltip would be the same, but adds a `mouseover` event listener:
```javascript
function customTooltipFunction(div, createTooltipArgs) {
    div.classList.add('pnlm-tooltip');
    var span = document.createElement('span');
    span.innerHTML = createTooltipArgs[0];
    div.appendChild(span);
    span.style.width = span.scrollWidth - 20 + 'px';
    span.style.marginLeft = -(span.scrollWidth - div.offsetWidth) / 2 + 'px';
    span.style.marginTop = -span.scrollHeight - 12 + 'px';
    div.addEventListener('mouseover', function(e) {
        var markerName = createTooltipArgs[1];
        // Do something here to highlight map marker
    }, 'false');
}
```

You'd then define the hot spot configuration as:
```javascript
{
    "pitch": 0.0,
    "yaw": 0.0,
    "createTooltipFunc": customTooltipFunction,
    "createTooltipArgs": ["hot spot text", "marker name"]
}
```

The [custom hot spots example](https://pannellum.org/documentation/examples/custom-hot-spots/) also demonstrates how this could be use to tweak the tooltip, using a different CSS class in its case.

**Comment by john-davies** [comment]
Thanks, I'll give it a go.

**Comment by john-davies** [comment]
This works very well thanks. One small note, I added a `mouseout` listener as well to remove the map highlight when the user moves off the link.

**Comment by john-davies** [comment]
Sorry I should have closed this some time ago
