### ISSUE TITLE
Multiresolution partial panoramas fail to load completely

### ISSUE THREAD

**Issue by karl-johnson** [mpetroff/pannellum#732]
I've just started using pannellum, so forgive me if this is due to some misunderstanding on my part. 
I have a high resulution partial panorama I'd like to show on my website - as such, I've been using the generate.py script to generate the tiles for the multiresolution panorama:

     python3 generate.py -H 24.721 -V 6.512 -o 20190515/output 20190515/Stitch_panotest.jpg 

All the tiles seem to be generated properly; however, when I upload the output folder and try to implement the panorama, using this:

```
    <!DOCTYPE HTML>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Karl J - Panorama Viewer</title>
    <link rel="shortcut icon" type="image/png" href="/format_images/title_icon.png" />
    <link rel="stylesheet" href="https://cdn.pannellum.org/2.4/pannellum.css"/>
    <script type="text/javascript" src="https://cdn.pannellum.org/2.4/pannellum.js"></script>
    
    <style>
    html, body {
        height: 100%;
        overflow: hidden;
    }
    #panorama {
        width: 100%;
        height: 100%;
        
    }
    </style>
</head>
<body>

<div id="panorama"></div>
<script>
pannellum.viewer('panorama', {
    "type": "multires",
    "multiRes": {
        "basePath": "output-old",
        "path": "/%l/%s%y_%x",
        "fallbackPath": "/fallback/%s",
        "extension": "jpg",
        "tileResolution": 512,
        "maxLevel": 7,
        "cubeResolution": 18968
    }
});
</script>

</body>
</html>
```
   [This is the resulting page](http://ka.rljohnson.net/photos/Panoramas/20190515/index-bad.html). The panorama works at the lowest resolution, but zooming in does not improve resolution. In addition, checking Chrome's developer console shows 404 errors - Pannellum is requesting the 'u0_0', 'b0_0', 'd0_0,' tiles, which were not generated because the partial panorama has no information in these regions. Also, the leftmost low-resolution tile of the panorama doesn't load until you spin the view around a bit. After having these problems, I found [this thread](https://github.com/mpetroff/pannellum/issues/184), which seems to say that multiresolution partial panoramas aren't supported, and simply embedding a partial panorama in a full panorama of black is the correct way to do this. [This does work](http://ka.rljohnson.net/photos/Panoramas/20190515/), but it does use more disk space and makes the python script take longer to run. 
    That issue thread was written over 3 years ago, so I don't know if mpetroff's comments in it are still accurate. So, since the python script supports multiresolution partial panoramas, does pannellum support them or not? If it does, what am I doing wrong/is there any workaround to these errors?

**Comment by mpetroff** [comment]
Partial panorama multi-resolution support was added to the viewer in pull request #570, which is also when support was added to the `generate.py` script. However, this was after v2.4 was released, which is why the output isn't working with said version of the viewer. Thus, the comments in #184 still apply to the v2.4 release but do not apply to the Git `master` / development version; the changes will also be in the next release.

**Comment by karl-johnson** [comment]
Thanks for the clarification - it shouldn't be a problem for me to simply use the padding method until the next release comes out.
