### ISSUE TITLE
Caching images

### ISSUE THREAD

**Issue by guizmo01** [mpetroff/pannellum#739]
Hi,

I have a viewer with multiple scenes which each has the same images but different colours.

I was wondering where we do:

"panorama": "image1.jpg", is there a way to cache the images into a sort of data set rather than loading the image from url? 
We trying to do this so that it reduces loading times in between scenes.

**Comment by mpetroff** [comment]
If your server properly sets expiration and caching headers on your images, the browser should automatically handle this for you.

There's no way to control this explicitly through Pannellum, although you could do so externally by loading the images into [Blob](https://developer.mozilla.org/en-US/docs/Web/API/Blob) objects and using the `blob` URLs in the Pannellum configuration. I'd recommend leaving it to the browser, however.

**Comment by omkarajagunde** [comment]
> If your server properly sets expiration and caching headers on your images, the browser should automatically handle this for you.
> 
> There's no way to control this explicitly through Pannellum, although you could do so externally by loading the images into [Blob](https://developer.mozilla.org/en-US/docs/Web/API/Blob) objects and using the `blob` URLs in the Pannellum configuration. I'd recommend leaving it to the browser, however.



> If your server properly sets expiration and caching headers on your images, the browser should automatically handle this for you.
> 
> There's no way to control this explicitly through Pannellum, although you could do so externally by loading the images into [Blob](https://developer.mozilla.org/en-US/docs/Web/API/Blob) objects and using the `blob` URLs in the Pannellum configuration. I'd recommend leaving it to the browser, however.

@mpetroff Hello sir i tried to create a new instance of var image  = new Image(); and then made image.src = "externalImageURL" and gave this variable to the configuration key panomora: image then it gave me the error as a.slice is not a function, i also tried to get blob as a response and used URL.createObjectURL(blob) and passed the result to configuration key panomora then it was displaying the message as WEBGL not supported....

Can you please tell me the correct way of loading image in memory(blob) and passing it to pannellum configuration??

THANKS IN ADVANCE, WAITING FOR YOUR RESPONSE??

**Comment by mpetroff** [comment]
Check your browser's developer console for errors; it should give you a more specific error message that the WebGL not supported message. You haven't provided enough information for me to help. However, the `a.slice is not a function` error suggests that you didn't properly pass the `Image` object.

Also, please don't use ALL CAPS; I don't appreciate being yelled at.

**Comment by mpetroff** [comment]
> Check your browser's developer console for errors

As I said before, please post the logged error message.
