### ISSUE TITLE
renderer is undefined when sceneFadeDuration is setted in certain cases

### ISSUE THREAD

**Issue by xhit** [mpetroff/pannellum#741]
### **EDITED 2019-06-07:**

> Sorry, this edition explain the issue, my mistake

When **sceneFadeDuration** is setted and I add the scenes via API with **addScene** function, throw the error that **renderer is undefined**.

The error is in the function **loadScene** setting **data** variable.

The code:

```
 var v = pannellum.viewer("panorama", {
                    "orientationOnByDefault": false, 
                    "scenes": [],
                    "sceneFadeDuration": 1000,
                    "author": "Test"
});

v.addScene("13",{
                   "type": "equirectangular",
                   "panorama": "images-360/tour-8/1559784853.jpg",
                   "title": "Pasillo 1"
});

v.addScene("14",{
                   "type": "equirectangular",
                   "panorama": "images-360/tour-8/1559784877.jpg",
                   "title": "Pasillo 2"
});

v.loadScene("13");
```

- If **sceneFadeDuration** is setted, throw the error.
- If scenes are in **scenes** object instead calling with **addScene**. throw the error.

For avoid the error the scenes need to be setted in **scenes** object in **viewer** and **firstScene** object need to be setted in **default**,  and **loadScene** not be called.

Working Code:

```
var v = pannellum.viewer("panorama", {
       "scenes":{"13":{
                               "type": "equirectangular",
                                "panorama": "images-360/tour-8/1559784853.jpg",
                                "title": "Pasillo 1"
                    },"14":{
                               "type": "equirectangular",
                               "panorama": "images-360/tour-8/1559784877.jpg",
                               "title": "Pasillo 2"
                    },
         "default": {
                    "orientationOnByDefault": false, 
                    "sceneFadeDuration": 1000,
                    "autoLoad":true,
                    "author": "Test",
                    "firstScene":"13"
                       }
           }
);
```

Is an API limitation cause because **scenes** is empty and there isn't a **firstScene** and you can't load after with **loadScene** if **scenesFadeDuration** is setted.

Note: this affect only scenes. I can use the code above and add hotspots via API with **addHotspot** with no problem.

**Comment by mpetroff** [comment]
While there's a `sceneFadeDuration` configuration parameter, there is no API method regarding it. As with your previous issue comments, I don't know what you're trying to say.

**Comment by xhit** [comment]
Issue edited with example code. My mistake.

**Comment by mpetroff** [comment]
When `sceneFadeDuration` is set, the viewer takes a snapshot of the previous scene's view and uses that to fade to the new scene. However, there was no check to make sure that the previous scene was actually loaded before doing so, which caused an error if a previous wasn't already loaded. I added such a check in 107b2a180dc3a85cf30dbb80d52001a4d75e6b53, which should fix the issue.
