### ISSUE TITLE
clickHandlerArgs not working

### ISSUE THREAD

**Issue by paul53181** [mpetroff/pannellum#742]
I cannot figure out how to pass an argument with the "clickHandlerFunc" for a hotspot. Perhaps I'm doing it wrong? or maybe its broken? 

`'hotSpots' : [
        {
            "pitch": 35,
            "yaw": -50,
            "cssClass": "tce-hotspot",
            "clickHandlerFunc": tceSpotClick,
            "clickHandlerArgs": 'testing123'
        }
    ]`

**Comment by mpetroff** [comment]
Do you have a minimum example of what doesn't work? `clickHandlerArgs` works fine for me. In your configuration snippet, `'testing123'` would be passed as the second argument to the `tceSpotClick` function, e.g.
```javascript
function tceSpotClick(event, handlerArgs) {
    console.log(handlerArgs);
}
```
would log `testing123` to the console.

**Comment by paul53181** [comment]
Thank you mpetroff! Your code code was very helpful. I was missing the event argument.
