### ISSUE TITLE
Multiple image overlay support??

### ISSUE THREAD

**Issue by guizmo01** [mpetroff/pannellum#743]
Hi,

I was wondering if it is possible to have multiple panoramic overlayed on top of each other in the same scene??

**Comment by mpetroff** [comment]
This isn't directly supported, but it should be possible to implement using the API by first compositing the images on a separate `<canvas>`. If the overlay doesn't need to change after loading the panorama, you can use the `<canvas>`'s [`toBlob` method](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toBlob) to create a `Blob` object and call `URL.createObjectURL` on it to get an object URL to pass to Pannellum. If it needs to change, set the `dynamic: true` configuration option and pass the `<canvas>` object directly (see [Video.js plugin for example](https://github.com/mpetroff/pannellum/blob/master/utils/video/videojs-pannellum-plugin.js)); you'll probably want to use the `setUpdate` method to make selectively turn on and off updating to make things more efficient.

**Comment by VV-PennyB** [comment]
I managed to get the drawing using a dynamic canvas working, thank you.

I was wondering if I could set up scenes to use the dynamic canvas so that I could do the drawing in a different canvas attached to another scene then fade that scene in?

**Comment by mpetroff** [comment]
You should be able to configure two different scenes to use two different `<canvas>` elements and switch between them like you would for normal images (I haven't tested this). After switching, you'll need to manually turn updating back on using `setUpdate` unless you set `dynamicUpdate: true` in the configuration (this was added in a05721198901cf2554e560f5029184ee897b4fc1, after the last release).

**Comment by VV-PennyB** [comment]
I did try that, but when I call loadScene to switch the scenes, it does not appear to work (the loading bar appears and just stays there with no progress)

**Comment by mpetroff** [comment]
You previously needed to manually call `setUpdate` to fix that (the dynamic scene support was developed in the context of the Video.js plugin, which does that on its own).

The need for the manual call to `setUpdate` was an oversight, which I addressed in 1b92bf32b4b35ea0327cae022f658759c1f843fd.
