### ISSUE TITLE
Broken example on pannellum.org

### ISSUE THREAD

**Issue by arevalirio** [mpetroff/pannellum#746]
Hello Mr. Petroff,

I am trying to access the standalone simple example https://cdn.pannellum.org/2.4/pannellum.htm#panorama=https://pannellum.org/images/alma.jpg but the browser complains about "your connection is not private" and it shows a 404 page if the warning is ignored.

Thanks for your help and for that piece of art called pannellum.

**Comment by mpetroff** [comment]
There were some issues with the CDN. This should now be resolved.
