### ISSUE TITLE
UI for adding hotpots

### ISSUE THREAD

**Issue by truszko1** [mpetroff/pannellum#747]
I am trying to figure out how to dynamically add hotpots with a UI. I'm looking to be able to click to add an anchor onto the viewer, and be able to move it around, but it would move around being "stuck" at a certain yaw and pitch. Did anyone do something like this before? I'm assuming the library doesn't offer anything that would let me to this?

I was thinking to add a div as a child of pnlm-render-container and make it drag-gable (simple JS). I am struggling with coming up with code to transform X and Y so that this div gives the illusion of being anchored at a yaw and a pitch, just like the hotpots that are hardcoded in a json config.

I hope I am being clear.. The question is: does library support adding hotpots through a UI? If not, what is the logic that pannellum uses to transform translateX and translateY so that the div gives the illusion of being anchored at a yaw and a pitch?

Edit: Perhaps, the easiest would be to point me to where in code the library does this. I know it already does, because it renders a json-defined hotspot, and it has logic to keep the hotspot in place if I move around the scene. It's okay if this is not exposed in any event or api.

**Comment by mpetroff** [comment]
Here's the code that renders the hot spots:
https://github.com/mpetroff/pannellum/blob/1c6c26fd48ec774d2a93f18ea0113546d58df825/src/js/pannellum.js#L1804-L1844

It's not exposed via the API, although the reverse operation is, via the `mouseEventToCoords` function. Using that function, you could use a click handler to add hot spots (along with the `addHotSpot` method), but it wouldn't handle moving an existing hot spot around. Someone has previously implemented such dragging functionality, although I haven't looked at the details as to how it was done: https://github.com/NiHoel/cirspecte

**Comment by truszko1** [comment]
Ah, this is great information. Thanks so much!!

**Comment by mpetroff** [comment]
It looks like it was implemented by adding a hot spot dragging feature in this branch: https://github.com/NiHoel/pannellum/tree/cirspecte-releases

A number of other changes were also made in that branch, so it isn't straightforward to create a diff.

**Comment by truszko1** [comment]
`mouseEventToCoords` is _exactly_ what I tried to come up with myself with pen and paper, but my trig was failing me. Thanks so much for this.
