### ISSUE TITLE
generate.py cube issue on ubuntu but not macOS

### ISSUE THREAD

**Issue by josh3333332** [mpetroff/pannellum#748]
A strange issue I have run into when using generate.py to create multiresolution panoramas from 360x180 JPGs from PTGui. When I generate the multiresolution panorama within macos, the panorama displays fine. The same process in ubuntu creates multiresolution panoramas that I am unable to view correctly with pannellum. The ubuntu output displays correctly for a split second upon opening, I assume this is either when LOD 1 or the fallback tiles are loaded.

The macOS output has 6 levels of detail, whilst the ubuntu output has 5. Any suggestions as to what might be causing this?

<img width="973" alt="Screen Shot 2019-07-03 at 3 45 38 pm" src="https://user-images.githubusercontent.com/34226643/60566347-05decf00-9daa-11e9-945c-4897acaf67c7.png">
<img width="978" alt="Screen Shot 2019-07-03 at 3 46 25 pm" src="https://user-images.githubusercontent.com/34226643/60566372-11ca9100-9daa-11e9-9463-16612ab5a3df.png">

**Comment by josh3333332** [comment]
I have found the issue, when run in ubuntu cubeResolution: 7352 but when run in macOS cubeResolution: 8432. If I force cubeResolution in ubuntu with **-c 8432** then the multiresolution panorama is generated as expected. I have had a look at how generate.py calculates the cubeResolution and it seems that the issue is likely originating from image size limitation built into PIL. I wrote a simple test script to get the image width & height with PIL and receive an error in return on both macOS & Ubuntu.

**_PIL.Image.DecompressionBombError: Image size (267267200 pixels) exceeds limit of 178956970 pixels, could be decompression bomb DOS attack._**

I am unable to explain why the generate.py script is able to calculate the correct value in macOS when the above error can be observed in both environments. I am not sure on the best workaround for this but was thinking of using exiftool to get the image width & height instead of PIL?

Image Size: 23120x11560

**Comment by josh3333332** [comment]
I see this has been reported previously, and a fix already implemented into generate.py via `Image.MAX_IMAGE_PIXELS = None` apologies for not seeing this before my previous message. I am no longer sure where this error is originating from!

**Comment by mpetroff** [comment]
Can you check the generated files to see whether or not the clear artifacts that are in your second screenshot are in the image tiles?

**Comment by josh3333332** [comment]
> Can you check the generated files to see whether or not the clear artifacts that are in your second screenshot are in the image tiles?

The generated tiles look fine and if you look at this gif frame by frame you can see that on refresh it loads normally for a fraction of a second before turning bad, only with the ubuntu output. 

![panorama-load 2019-07-04 07_52_30](https://user-images.githubusercontent.com/34226643/60627214-bb546580-9e30-11e9-971d-a5e8e850f621.gif)

**Comment by josh3333332** [comment]
Thanks for the response, however the only issue here is my incompetence! I had the cubeResolution value hard coded in my html/js rather than getting the values from each panoramas config.json 

All is working well, thank you for the fantastic project 👌
