### ISSUE TITLE
Is there support for partial / cylindrical panoramas?

### ISSUE THREAD

**Issue by fuzzybabybunny** [mpetroff/pannellum#75]
Does this support partial panoramas such as 270 degree panos that also don't extend completely to the top or bottom?

**Comment by mpetroff** [comment]
There is support for partial panoramas, but only if they are in an equirectangular projection. See the `haov`, `vaov`, and `vOffset` [parameters](https://github.com/mpetroff/pannellum/blob/master/doc/json-config-parameters.md#haov).

**Comment by DDvO** [comment]
I meanwhile managed to adapt the `generate.py` script to support cylindrical input and the JavaScript sources to support partial panoramas (from both equirectangular/spherical and cylindrical input) without wasting space by tile files that represent areas never shown. I can share the details if you're interested.

Here is [an example partial cylindrical pano](http://gallery.davoh.de/Seebensee/dsc_3927-3933.html) generated this way.

**Comment by jens-eggers** [comment]
Hi @DDvO ,
I really like your work on cylindrical panoramas for pannellum looking at your page! 
I also have a lot of these source files, did you manage to enable pannellum to accept these? How can I adapt these changes, that would be very interesting. Can you please share the details?

**Comment by DDvO** [comment]
Hi @jens-eggers , pleased to hear.
All right, today I've started setting up a series of pull requests that touch various more or less independent aspects of the extensions I made for supporting partial panoramas of cylindrical and other types. Here is the first of them: https://github.com/mpetroff/pannellum/pull/562

**Comment by DDvO** [comment]
I've just extended my PR #570 which concludes the additions needed to support partial / cylindrical panoramas.

**Comment by jens-eggers** [comment]
Hi David, sorry for my late reply. I will have a deeper on what you have
mentioned during next week. In the meantime I "cheated" a little having a
look at the example you provided, which already helped me a lot on creating
a full 360° cylindrical view. Understanding the parameters was the key.

Thank you very much for your reply, I appreciate it!

Best regards,
Jens

David von Oheimb <notifications@github.com> schrieb am Sa., 17. März 2018,
20:15:

**Comment by DDvO** [comment]
Hi Jens, meanwhile the pull request mentioned above is merged, so in my view partial / cylindrical panoramas can now be considered officially supported.

Talking of parameters, the key options of  `generate.py` for cylindrical input are 
- `--cylindrical` (which selects the projection code `f4` rather than `f1` when configuring `nona`) and 
- `--horizon` to state the offset of the horizon counted from the middle of the image (which sets the `e` option of `nona`), which is needed to avoid bending the horizon.
