### ISSUE TITLE
stopOrientation, startOrientation, huge performance drop

### ISSUE THREAD

**Issue by truszko1** [mpetroff/pannellum#750]
I started using "orientationOnByDefault" set to True, but I noticed that the fps drops significantly after 6-10 transitions to a new scene. I am actually able to reproduce it by simply having one scene and adding this simple code:

    viewer.on('touchend', function(event) {
        viewer.stopOrientation();
        viewer.startOrientation();
    });

Drag the viewer a bit, and stop. Drag the viewer a bit, and stop. Do this 5-10 times and the fps drops to almost freezing. I tried looking at the lib code, but I couldn't notice anything obvious as to why this would be happening. 

Can anyone else reproduce this, or know why this is happening?

**Comment by mpetroff** [comment]
Which version of Pannellum are you using, and which browser / browser version? I was unable to reproduce this behavior under Android 9 with either Firefox 67.0.3 & Pannellum Git `master` or Chrome 75.0.3770.101 & Pannellum 2.4.1.
