### ISSUE TITLE
Add 'authorURL' config option

### ISSUE THREAD

**Issue by hubick** [mpetroff/pannellum#751]
I've setup Pannellum to display using 100% of the page, but users linked directly to one of my photos then have no way to navigate to the rest of my website. It would be nice if I could supply an 'authorURL' config param that would make the author info displayed by Pannellum into a clickable link that would open in a new window.

Much Thanks for the great software and your consideration of this enhancement.

**Comment by mpetroff** [comment]
I implemented this in de08b9d7a814dc7238c11cec30dcc3b9d64a7da0.

If you want more control over this type of display, you could also use custom overlays, as demonstrated by the [custom controls examples](https://pannellum.org/documentation/examples/custom-controls/).

**Comment by hubick** [comment]
Woah, thanks! :-)
