### ISSUE TITLE
LoadingScene after failed panorama id does not work,

### ISSUE THREAD

**Issue by martinlombana** [mpetroff/pannellum#755]
Providing you register 2 scenes with ids: ["2", "3"] in the initial config, if you do this:

(You can use timeout or buttons with an event to reproduce, I am not executing this at the same time).

```
this.viewer.loadScene("3", 0, 0, 90); //-> loads the scene 3. Correct

this.viewer.loadScene("2", 0, 0, 90); //-> loads the scene 2. Correct

this.viewer.loadScene("44", 0, 0, 90); //-> Shows error: Panorama couldn't be loaded. Correct

this.viewer.loadScene("2", 0, 0, 90); //-> Does nothing and the panorama does not change.
```

**Comment by mpetroff** [comment]
Fixed in ebc31b7239dd06d0c25dd9b44441d05d6c023157.

**Comment by martinlombana** [comment]
Thanks a lot!
Updated to the dev version, and confirmed the fix it's working.

**Comment by martinlombana** [comment]
Hi, this seems to be happening again, after an image can not be accessed. I am using always the latest version from git-hub:

(in my package.json -> "pannellum": "github:mpetroff/pannellum#master").

And I did remove the node_modules folder and re-installed again today:
*npm install mpetroff/pannellum#master*

It can not recover after not being able to load the image. If the first image that is passed to the viewer is missing, it is unable to load any more.

**Comment by mpetroff** [comment]
I had previously only handled a specific failure, a file access error after the first scene. I made the recovery more general in e1d4c9a5e523f6ea06db6c29a07c406a15b82490, so it should now also work for the first scene, as well as for other errors.
