### ISSUE TITLE
Glitched image on equirectangular mode

### ISSUE THREAD

**Issue by babeone** [mpetroff/pannellum#757]
Hi,
I get the issue in the attached image randomically and I don't understand why. Can someone help me?
![Screenshot_20190722-105309](https://user-images.githubusercontent.com/19651563/61619426-1c709b80-ac6f-11e9-8fb9-1b29614ec1d0.jpg)
![Screenshot_20190722-105006](https://user-images.githubusercontent.com/19651563/61619428-1c709b80-ac6f-11e9-985e-ea99c55187c7.jpg)
![Screenshot_20190722-105003](https://user-images.githubusercontent.com/19651563/61619429-1c709b80-ac6f-11e9-86d8-3c0304e81aa6.jpg)

<body>

    <div id="panorama"></div>
    <script>
        function getUrlVars() {
            var vars = {};
            var parts = window.location.href.replace(/[?&]+([^=&]+)=([^&]*)/gi,
                function (m, key, value) {
                    vars[key] = value;
                });
            return vars;
        }
        var yaw = new URLSearchParams(window.location.search).get("yaw");
        var panorama = new URLSearchParams(window.location.search).get("panorama");

        var viewer = pannellum.viewer('panorama', {
            "type": "equirectangular",
            "panorama": panorama + '.jpg',
            "yaw": yaw,
            "hfov": 120,
            "autoLoad": true,
            "orientationOnByDefault": true
        });

    </script>

</body>

</html>

**Comment by mpetroff** [comment]
What version of Pannellum are you using? What browser / browser version / operating system? Are any messages printed to the browser's developer console?

This looks very similar to #323, which seemed to be due to a graphics card / driver related issue.
