### ISSUE TITLE
viewer not loading in dynamically appended div 

### ISSUE THREAD

**Issue by LabebaTahsin** [mpetroff/pannellum#762]
I am trying to add pannellum viewer on dynamically appended div. But it is not loading.
```javascript
$('.btn')..on('click', function(e) {
         $('#oldDiv').append('<div id="newDiv"></div>');

pannellum.viewer('newDiv', {
    "type": "equirectangular",
    "panorama": "https://pannellum.org/images/alma.jpg",
    "autoLoad": true

});

});
```

Can you please suggest a way?
![Screenshot_9](https://user-images.githubusercontent.com/41112206/61949963-46f38900-afce-11e9-9610-cbb0424b5f7a.png)

**Comment by mpetroff** [comment]
Is there a message in your browser's developer console? You have not provided enough information for me to help you. A minimum example that exhibits the issue would be ideal.
