### ISSUE TITLE
Slow performance after change panorama

### ISSUE THREAD

**Issue by HectorFenoma** [mpetroff/pannellum#763]
Hi, first of all, congrats for such a great library. I've been using it lately and I have this issue.
I have a equirectangular panorama and some buttons that change that panorama. After change 3 or 5 times the panorama, the performance become slow and the browser stop working. I think is related with the method that I'm using to change the panorama. I use jquery "empty()" to empty the container and then i add a new pannellum.viewer() with the new image URL. I don't know if that is the correct approach to do it, or I should use other method? I think when I empty the container, for some reason some cache get bussy and after certain amount is full and make the browser slow. I was looking for a way to use the same viewer and set the panorama image everytime (so I don't need to empty the container and create again the viewer) but I don't know how to do it and I'm not sure if it would work. Any idea what can i do? Thanks!!

**Comment by mpetroff** [comment]
At the very least, you should call Pannellum's `destroy()` method. If there are any dangling references to the viewer, it won't be garbage collected, and your resource usage will continue to grow with each change.

The better approach would be to keep the same viewer. If you have a fixed set of panoramas, you should set up a [tour](https://pannellum.org/documentation/examples/tour/) but without any hot spots. You can then use the `loadScene` method to switch between panoramas. If you don't know the set of panoramas ahead of time, you can add a new panorama / scene dynamically using the `addScene` method and then switch to it using `loadScene`; after the scene is switched, you could use the `removeScene` method to remove the original scene from the configuration, but failing to do this is unlikely to cause any problems.

**Comment by HectorFenoma** [comment]
Hi Matthew, that worked like a charm!! As im using PHP to load the images dinamically, I used the Addscene and removeScene method and worked perfect. 

Thank you so much for everything, you are a genius! 

If someone needs the code (ajax call with jquery to php and mySql) just ask!

Cheers

**Comment by hassanalbudairi** [comment]
Hi Matthew and Hector
I am trying to use addScene, load Scene and removeScene for changing between a dynamic set of panoramas using JS and PHP. The addScene and loadScene works fine but when I use removeScene to remove previous scene I got a false return (which means the current loadScene has not finished and thus the previous scene still consider as a current scene) and ended up with multiple scenes in the viewer.
This is my code:
`ar viewer = pannellum.viewer('panorama',{'scenes':{},"compass":true});
viewer.addScene(a[1],{"type": "multires","northOffset":a[6],"pitch":p,"yaw":y,"multiRes":{"basePath":a[3],"path": "/%l/%s%y_%x","fallbackPath": "/fallback/%s","extension": "jpg","tileResolution": 512,"maxLevel": 4,"cubeResolution": 3496},"hotSpots":hotspots});
viewer.loadScene(a[1]);
var rmv = viewer.removeScene(current_scene);
current_scene = viewer.getScene();`

where current_scene is a global variable I used to store the scene id.
I tired to use Promise.prototype.then() but got an error (loadScene is not a function). Also tried timeout function but does not work. Any idea how to ensure addScene is finished before removeScene?

Thanks

**Comment by mpetroff** [comment]
Use the `viewer.on` method to add an event listener for the `load` event, which will fire when the scene has finished loading.

**Comment by hassanalbudairi** [comment]
Many thanks for your reply Matthew, I tried this code
`viewer.on('load'),function(){
console.log('inside isLoaded');
var rmv = viewer.removeScene(current_scene);
console.log(rmv);
current_scene = viewer.getScene();
}`
but it looks something wrong in my code as it does not work. colud you please tell me waht is wrong?
Cheers

**Comment by mpetroff** [comment]
You're going to have to be a bit more specific than "my code doesn't work." Is the load listener executed? What is the return value for `removeScene`? Both snippets look fine.

**Comment by hassanalbudairi** [comment]
Hi Matthew
it seems the code does not fire any of viewer.on methods (see my code below where I tried load, scenechange, error and when run the code none of the text inside these methods are printed in the console (see the screenshot below where two direction hotspots are shown after I move a one step forward from scene 1 to 2 ) as you can see from current_scene varaible which is initially null.
the only method works is for fullscreenchange.


`viewer = pannellum.viewer('panorama',{'scenes':{},"compass":true});
viewer.addScene(a[1],{"type": "multires","northOffset":a[6],"pitch":p,"yaw":y,"multiRes":{"basePath":a[3],"path": "/%l/%s%y_%x","fallbackPath": "/fallback/%s","extension": "jpg","tileResolution": 512,"maxLevel": 4,"cubeResolution": 3496},"hotSpots":hotspots});

viewer.loadScene(a[1]);

if(current_scene != null){
console.log(current_scene);
new_scene = viewer.getScene();
console.log(new_scene);
}
viewer.on('load', function(){
	console.log("Load done");
	var rmv = viewer.removeScene(current_scene);
	console.log(rmv);
});

viewer.on('scenechange',function (){
        console.log("Scene changed");
    });

viewer.on('error', function(){
	console.log("Error occured");
});

//VR button only on full screen
viewer.on('fullscreenchange', function(isFullscreen) {
    if (isFullscreen) {
		//var newFrame = document.createElement("a-frame");
	//var asky = document.createElement("a-sky");
	//	asky.src = a[3];
		//echo"<a-sky src="a[3];
		$("#vr").css('display','block');
    } else {
		$("#vr").css('display','none');
    }
});

current_scene = viewer.getScene();
`


![image](https://user-images.githubusercontent.com/32450991/75617206-e627c280-5b53-11ea-9a06-4fda22c68b4a.png)

**Comment by mpetroff** [comment]
You're adding the listeners after you load the scene. Of course they're not going to fire.

**Comment by hassanalbudairi** [comment]
Thanks Matthew
I now updated the code to
`viewer = pannellum.viewer('panorama',{'scenes':{},"compass":true});
viewer.addScene(a[1],{"type": "multires","northOffset":a[6],"pitch":p,"yaw":y,"multiRes":{"basePath":a[3],"path": "/%l/%s%y_%x","fallbackPath": "/fallback/%s","extension": "jpg","tileResolution": 512,"maxLevel": 4,"cubeResolution": 3496},"hotSpots":hotspots});

viewer.on('load', function(){
	console.log(current_scene);
	var rmv = viewer.removeScene(current_scene);
	console.log(rmv);
});

viewer.loadScene(a[1]);
current_scene = viewer.getScene();
console.log(current_scene);
`

but still got viewer.removeScene false (please see the below screenshot

![image](https://user-images.githubusercontent.com/32450991/75632740-0c526e80-5bf7-11ea-8950-cb1a45fac239.png)

**Comment by hassanalbudairi** [comment]
I also noticed the the view.on ('load', ....) is fire even before the multi-res image completely loaded. Could this be the reason why it does not reomve the old scene and gives this false return

![image](https://user-images.githubusercontent.com/32450991/75633031-97ccff00-5bf9-11ea-9a1b-d2c0543c6458.png)

**Comment by mpetroff** [comment]
There are two and only two ways that `removeScene` can return `false`; either you're trying to remove the current scene or you're using a `sceneId` that doesn't match any of your scenes. It has nothing to do with the the multiresolution image, which fires the `load` event immediately, since the image tiles are loaded dynamically by the rendering engine.

**Comment by hassanalbudairi** [comment]
Hi Matthew
I now setup a simple example to test removeScene. it’s a tour of 3 images (img_0, img_1, and img_2). default is img_0 and I used direction hotspots to call a function (dir_hs) that check if this direction is Forward then will send back img_1 otherwise its img_2. I used a window variable to store the currentScene. 
on calling viewer suing direction function, I first add the new scene (using the provided file name), setup load listener to remove the old scene and then load the new scene. Again, I still got a false return from removeScene function.  
please take a look into this code
`<!DOCTYPE HTML>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tour</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/pannellum@2.5.6/build/pannellum.css"/>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/pannellum@2.5.6/build/pannellum.js"></script>
    <style>
    #panorama {
        width: 600px;
        height: 400px;
    }
    </style>
</head>
<body>
<div id="panorama"></div>
<script>
window.current_scene = null;
function imageview(a){
	console.log(a);
	console.log(current_scene);
var hotspots = [];
var hotspot ={};
hotspot1 = {"pitch":-10,"yaw": 0 ,"id":'Forward',"type": "scene","text": "Forward","clickHandlerFunc":dir_hs};
hotspots.push(hotspot1);
hotspot2 = {"pitch":-30,"yaw": 180,"id":'Backward',"type": "scene","text": "Backward","clickHandlerFunc":dir_hs};
hotspots.push(hotspot2);
var viewer = pannellum.viewer('panorama',{"scenes":{},"autoLoad":true});
var path= '/pannellum_test/'.concat(a).concat('.jpg');
viewer.addScene(a,{"type": "equirectangular","panorama": path,"hotSpots":hotspots});
viewer.on('load', function(){
	if(current_scene !== null){
	var rmv = viewer.removeScene(current_scene);
	console.log(rmv);
	current_scene = viewer.getScene();
	}else{
	current_scene = viewer.getScene();	
	}
});
viewer.loadScene(a);
}
</script>

<script>

function dir_hs(){
if (this.id == "Forward"){
var a = 'img_1';
imageview(a);
}else{
a = 'img_2';
imageview(a);
}
}
</script>

<script>

var a = 'img_0';
imageview(a);
</script>
</body>
</html>
`

and here is a screen shot of the outcome
![image](https://user-images.githubusercontent.com/32450991/76228132-3b309c00-6218-11ea-8ef6-decf711c8608.png)

I am really struggling with making this work and would appreciate your help
Thanks

**Comment by mpetroff** [comment]
You create a new empty viewer each time you change the scene, so of course there's no previous scene to remove. You should not be creating the viewer or adding the `load` event listener in your `imageview` function; these actions should be done outside the function and should only be done once.

I don't want to sound mean, but I honestly have better things to do than debug your poorly written code for free. Your problems have all been with your own code, not Pannellum itself, and the problems have nothing to do with the subject of this GitHub issue. I'm locking this issue conversation.
