### ISSUE TITLE
Panorama progressive jpeg

### ISSUE THREAD

**Issue by lucaspojo** [mpetroff/pannellum#766]
Hello,

When developing a project, I need to display very high quality panoramas. 7MO per image.

Is it possible to use progressive JPG images for a more fluid display?

Thx !

**Comment by mpetroff** [comment]
That's what the [multiresolution mode](https://pannellum.org/documentation/examples/multiresolution/) is for. You can use a progressive JPEG, but it's not going to display any quicker.

**Comment by mpetroff** [comment]
While displaying a progressive JPEG as soon as enough of it is loaded is a reasonable idea and is something I've thought about before, there's unfortunately no good way to do so from JavaScript.
