### ISSUE TITLE
JoSS Review #1: Paper Comments

### ISSUE THREAD

**Issue by vsoch** [mpetroff/pannellum#769]
hey @mpetroff ! This is for the review at https://github.com/openjournals/joss-reviews/issues/1628. I'll be opening different issues to coincide with groups of comments and suggestions. This one is about the paper itself. Overall, great job on it!

----------------------------------------------------------

## Paper Comments

The introduction flows beautifully - opening with a description of the tool,
and just as I had finished reading the first paragraph (and was thinking "What other
tools have existed?") the second paragraph opens to describe the history of the technology.

 1. Could you describe more what an integration with maps would look like? Mousing over a map
and opening a panorama for a point, or (within a panorama) ascribing locations to things?
 2. What is a panoramic video?
 3. It might be interesting to tell the reader how the term "Pannellum" originated - what does it mean?

The paper is succinct and good. The one recommendation I'd suggest is to add (somewhere) in the text a link for the reader to easily jump to documentation, examples, etc. The JoSS Template automatically provides a link to the repository, but we would want to go directly to the documentation, or another reference in the paper (that isn't in the references, if appropriate).

**Comment by mpetroff** [comment]
Thank you for the detailed comments and quick response! I'll try to work through them this week.

>     1. Could you describe more what an integration with maps would look like? Mousing over a map
>        and opening a panorama for a point, or (within a panorama) ascribing locations to things?

I added a description and also added an extra reference, to a [blog post with an example](https://blog.openstreetmap.org/2018/07/03/bing-streetside-in-id/).

>     2. What is a panoramic video?

I added an explanation.

>     3. It might be interesting to tell the reader how the term "Pannellum" originated - what does it mean?

I had originally included this but decided to remove it as superfluous before submitting the manuscript; I added it back in.

> The paper is succinct and good. The one recommendation I'd suggest is to add (somewhere) in the text a link for the reader to easily jump to documentation, examples, etc. The JoSS Template automatically provides a link to the repository, but we would want to go directly to the documentation, or another reference in the paper (that isn't in the references, if appropriate).

I added a few links at the end of the paper.

The changes were made in fb918f1f36ced9c7f8c60d82ca27ad40a2074dc5: https://github.com/openjournals/joss-papers/blob/joss.01628/joss.01628/10.21105.joss.01628.pdf

**Comment by vsoch** [comment]
- The added example with Bing streetmaps (and your description) much better illustrates what an integration entails.
 - I'm glad that you added the explanation of the name back in - it's something that has chance to be forgotten, and it's interesting, and this will preserve the history of the tool.
 - The addition of the links to examples at the end is spot on what I had in mind:

![image](https://user-images.githubusercontent.com/814322/62623463-e2e69400-b8ee-11e9-8920-b3e073962bea.png)

The typical reader would finish reading, and then want to go see / experiment with the tool. This will take him or her right to it!

**Comment by vsoch** [comment]
You've addressed all my points here, closing issue.
