### ISSUE TITLE
JoSS Review #2: Repository Comments

### ISSUE THREAD

**Issue by vsoch** [mpetroff/pannellum#770]
This issue is for (superficial) comments about files / structure of the repository, again for https://github.com/openjournals/joss-reviews/issues/1628. Everything required is included, and the points I'd like to confirm are:

 1. if a CONTRIBUTING.md should be added in the .github folder to be programatically discoverable
 2. Choice for naming the LICENSE file "COPYING" ?
 
That's it. :) I still haven't reviewed the software itself - doing that now!

## Repository Comments

There isn't a CONTRIBUTING.md, but the author provides text in the README. In that 
 programmatic discovery can be done by including a CONTRIBUTING.md, I'd suggest to the author to consider adding one (with the content from the README) to the .github folder.

The LICENSE file isn't kept with the repository, but mentioned (and linked) with the README. It looks like the file is named COPYING. GitHub seems to detect it, so if this is the author's preference, it's okay to do. Most folks will look for a LICENSE, if that makes a difference.

I can confirm that @mpetroff has made the greatest contributions, and all others (total of 31) look like tiny bug fixes, etc. It's most appropriate that only he is the author.

**Comment by mpetroff** [comment]
>     1. if a CONTRIBUTING.md should be added in the .github folder to be programatically discoverable

I added this file in 5e682d0ff346687a7d98437e5d0b176c1b173075.

>     2. Choice for naming the LICENSE file "COPYING" ?

This is a fairly common / traditional naming choice used by most GNU projects, e.g., [GCC](https://gcc.gnu.org/git/?p=gcc.git;a=blob;f=COPYING;h=623b6258a134210f0b0ada106fdaab7f0370d9c5;hb=HEAD) or [Coreutils](https://github.com/coreutils/coreutils/blob/master/COPYING), as well as other common software such as [Git](https://github.com/git/git/blob/master/COPYING). It's also used by the first open source project I became involved with, [Hugin](https://sourceforge.net/p/hugin/hugin/ci/default/tree/COPYING.txt), which is the primary reason for the naming choice.

**Comment by vsoch** [comment]
Awesome - we have a CONTRIBUTING.md! It seems trivial, but (having done analysis of repositories for fun myself) it's really good to have it - people know to go looking for it.

For the LICENSE, this will be ok to leave as COPYING, since it's a standard that others follow (and I didn't know about!) and GitHub seems to pick it up. My concerns have been well addressed, thanks for the details @mpetroff.
