### ISSUE TITLE
JoSS Review #3: Getting Started

### ISSUE THREAD

**Issue by vsoch** [mpetroff/pannellum#771]
This is for https://github.com/openjournals/joss-reviews/issues/1628

As a user, I'm expecting to hit the README and be walked through a "getting started" set of instructions. This is here to some extent, but it's not made explicitly clear - you have beautiful documentation pages with examples, and tools to quickly generate panoramas, and the reader should know about them immediately! I would suggest adding a few lines that explicitly give the user choices, something like:

### Getting Started

 1. **Examples**: If you want to see the tool in action, we have a set of [examples](https://pannellum.org/documentation/examples/simple-example/) ready to go that you can view.
 2. **Test Your Own**: If you want to quickly test Pannellum with a panorama, try out our [quick tutorial](https://pannellum.org/documentation/overview/tutorial/).
 3. **Build Your Own**: To prepare your own server with Pannellum, follow the [instructions here](https://github.com/mpetroff/pannellum#how-to-use).

Right at the start of the README, after the About section.

**Comment by vsoch** [comment]
Also - for the third (Build your own) you mention a build/pannellum.htm - but glancing over the top level repository structure I don't see that. I think you would want to more explicitly walk the user through these steps, e.g.,:

```bash
git clone https://github.com/mpetroff/pannellum
cd pannellum/<some folder>

# steps for generating

# steps for previewing with python http.server or similar
```

**Comment by vsoch** [comment]
Following the instructions to use generate.py, I do the following:

```bash
 git clone https://github.com/mpetroff/pannellum
cd pannellum/

# I downloaded this from Google Photos, you might provide a wget command for the user to get an example
mv panorama.jpg utils/multires/
cd utils/multires/
python generate.py panorama.jpg 
```
This is the command provided in the README, but I'm being told that an argument is missing (that isn't documented in the help):

```bash
$ python generate.py panorama.jpg 
usage: generate.py [-h] [-C] [-H HAOV] [-F HFOV] [-V VAOV] [-O VOFFSET]
                   [-e HORIZON] [-o OUTPUT] [-s TILESIZE] [-f FALLBACKSIZE]
                   [-c CUBESIZE] [-b BACKGROUNDCOLOR] [-B] [-a] [-q QUALITY]
                   [--png] -n EXECUTABLE [-G] [-d]
                   INPUT
generate.py: error: the following arguments are required: -n/--nona
```

**Comment by vsoch** [comment]
I'll test out this "How to use" section when you've had a chance to fix it up a bit! :)

**Comment by Fil** [comment]
Same for me & I would add that the package.json file mentions "main": "build/pannellum.js", which is not there and doesn't get built automatically (at least I couldn't find how).

**Comment by vsoch** [comment]
@Fil it's hiding in the utils folder, and I think @mpetroff is going to clean this up a bit!

**Comment by Fil** [comment]
True :) and I found another copy in src/ which doesn't seem to need a build step.

Other than that, my review is complete and as soon as the installation / dependencies are cleaned up I'll check off the last items. 👍

Very nice seeing pannellum featured in JOSS!

**Comment by mpetroff** [comment]
I'll see about addressing this tomorrow.

**Comment by mpetroff** [comment]
I made some significant changes to the readme in 539fdc27493bd70fe5e9c8426c4e8b7b559a4e4e to try to address the concerns raised here. Addressing specific issues:

For the issue with the `generate.py` script:
The issue is due to `nona` (from [Hugin](http://hugin.sourceforge.net/)) not being found on the `$PATH`. When it isn't found, the `-n/--nona` flag is required to manually specify its location. This was previously documented in the readme, but I clarified it a bit more now. It was also documented in the help (`./generate.py --help`), so you must have missed it; to help with this, I added a more explicit error message for the missing parameter in f9749f9b5e4e4e421b52783c2f3b9297592fbb40.

For `build/pannellum.js`:
I added more explicit mentions to the files in the `build` directory and how they're created with the readme changes.

**Comment by Fil** [comment]
Thanks, it clarifies what I was missing.

**Comment by vsoch** [comment]
The getting started section is spot on! It provides the missing transition between reading the about and knowing what to do first.

For record, here is what was printed before updates to the client - if I run the generate.py it just tells me an argument is missing:
```
$ python3 generate.py panorama.jpg 
usage: generate.py [-h] [-C] [-H HAOV] [-F HFOV] [-V VAOV] [-O VOFFSET]
                   [-e HORIZON] [-o OUTPUT] [-s TILESIZE] [-f FALLBACKSIZE]
                   [-c CUBESIZE] [-b BACKGROUNDCOLOR] [-B] [-a] [-q QUALITY]
                   [--png] -n EXECUTABLE [-G] [-d]
                   INPUT
generate.py: error: the following arguments are required: -n/--nona
```
and then when I ask for help, it looks like nona was there, but it's after -n EXECUTABLE so I just missed it :P User error!

```
$ python3 generate.py --help| grep nona
  -n EXECUTABLE, --nona EXECUTABLE
                        location of the nona executable to use (default: None)
  -G, --gpu             perform image remapping by nona on the GPU (default:
```
Anyway let's test the fixed version now!

```
$ python3 generate.py panorama.jpg 
IMPORTANT: The location of nona must be specified with -n, since it was not
           found on the PATH!

usage: generate.py [-h] [-C] [-H HAOV] [-F HFOV] [-V VAOV] [-O VOFFSET]
                   [-e HORIZON] [-o OUTPUT] [-s TILESIZE] [-f FALLBACKSIZE]
                   [-c CUBESIZE] [-b BACKGROUNDCOLOR] [-B] [-a] [-q QUALITY]
                   [--png] -n EXECUTABLE [-G] [-d]
                   INPUT
generate.py: error: the following arguments are required: -n/--nona
```
Even though I don't know what nona is, the error message is loud and clear, and I can Google search, etc. to figure it out.

Okay just finished testing! What I wound up doing is hitting dependency issues on my host, and I built a container that runs it easily without a hitch! What I'm going to do is open a PR to add a simple Dockerfile to the generate folder, one the user can easily build and run the script without running into issue. Stay tuned!

**Comment by vsoch** [comment]
okay see https://github.com/mpetroff/pannellum/pull/779!

**Comment by mpetroff** [comment]
#779, which provided a Dockerfile, has now been merged.

**Comment by vsoch** [comment]
Looks great now! I've gone through each of the use cases in the getting started, and it's just what a new user would want for a gentle introduction. Closing issue!
