### ISSUE TITLE
JoSS Review #4: Examples Folder

### ISSUE THREAD

**Issue by vsoch** [mpetroff/pannellum#772]
This is for https://github.com/openjournals/joss-reviews/issues/1628

Are the examples intended to work with a local web server? I can cd into the examples folder, start the server:

```bash
$ python -m http.server 9999
```
And then go to the page, but I'm getting a 404:
![image](https://user-images.githubusercontent.com/814322/62551162-7c536e80-b839-11e9-9d04-9fdcb0cea6ed.png)

Is port 80 required, so a user wouldn't be allowed to test with python, etc.?

**Comment by mpetroff** [comment]
I added some clarifying instructions in 982242c7f9c5060fb02b684c25bd39ba02f797b9 for how to view the examples.

You encountered an error loading an `<iframe>` of a file in the `src/standalone` directory, since the web server was started from the `examples` directory, not the repository root. Port 80 is not required.

**Comment by vsoch** [comment]
We're in business! The examples instructions (for staying in the root) are easy to miss because you don't directly give the user something to copy paste. For example, you could do something like:

## Examples

Examples using both the minified version and the version in the src directory are included in the examples directory. These can be viewed by starting a local web server in the root of the repository:

```bash
python3 -m http.server
```
in the directory containing this readme file, and then navigating to the hosted HTML files using a web browser; note that the examples use files from the src directory, so **the web server must be started from the repository root, not the examples directory**.

-------------------------------------------------------

The above is just a tiny difference - but it gives the user the command off the bat, and then bolds the point about where they should be.

I tested all the examples - and for the most part, we are in business! There is one that still doesn't seem to work:

![image](https://user-images.githubusercontent.com/814322/62624014-255ca080-b8f0-11e9-8da9-0251c360ae8e.png)

**Comment by mpetroff** [comment]
I added this in ac72b8cabf90685d79e26f187d51190a12d3376e. Thanks for the helpful suggestion.

**Comment by vsoch** [comment]
okay, minified version is working after build!

![image](https://user-images.githubusercontent.com/814322/62704168-c1ea7580-b9b8-11e9-941b-45f0ffabcf85.png)

Is that Jordan Pond at Acadia National Park? I grew up in rural NH so we went there a few times, really beautiful :)

**Comment by mpetroff** [comment]
Yes, it is, circa 2009.
