### ISSUE TITLE
JoSS Review #5: Community Guidelines

### ISSUE THREAD

**Issue by vsoch** [mpetroff/pannellum#773]
This is for https://github.com/openjournals/joss-reviews/issues/1628

I mentioned possibly adding a CONTRIBUTING.md in #770 , and I'm looking over this checkpoint:

> - [ ] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

And I'd like to suggest adding a "Support" section to the README, where you state (and link) to your preferred method for users to ask questions, report bugs, etc. it's implied to be GitHub issues, but it's helpful to state it explicitly.

**Comment by mpetroff** [comment]
I added a `CONTRIBUTING.md` file in 5e682d0ff346687a7d98437e5d0b176c1b173075 and added a "Seeking support" section to the readme in 405bdc717de33da52e3c3a7b2ea5c37cf1c35fb7.

**Comment by vsoch** [comment]
Spot on! Closing issue.
