### ISSUE TITLE
JoSS Review #6: Automated Testing

### ISSUE THREAD

**Issue by vsoch** [mpetroff/pannellum#774]
This is for https://github.com/openjournals/joss-reviews/issues/1628

I'd like to see automated testing, to ensure that tests are run with every pull request and change (and for the user not to need to find / download a geckodriver to run them). CircleCI and Travis can handle headless testing, so you could check those out (or others that you have preference to use!)  The recipe should handle installing the necessary python packages, obtaining (or keeping a geckodriver with the code) and then ensuring that they pass.

**Comment by mpetroff** [comment]
WebGL unfortunately complicates headless testing, and I wasn't able to get it to work properly with Travis when I previously tried. I ended up setting it up using [Travis](https://travis-ci.org/mpetroff/pannellum) + Sauce Labs, which, unfortunately, doesn't work for pull requests due to security concerns, i.e., stealing the SauceLabs private API key, but does run for commits to `master`. I'll take another look at trying to get the tests to run directly on Travis.

**Comment by mpetroff** [comment]
Still no luck getting it to work. I'm out of ideas for getting it to work with Firefox. I guess I could try getting it to work with Chromium.

**Comment by vsoch** [comment]
hey @mpetroff - we have to keep trying! To help, I created a CircleCI configuration with tests using Chrome to run selenium headless. The passing test (can you see?) https://circleci.com/gh/vsoch/pannellum/15 and then the added configuration is [here](https://github.com/vsoch/pannellum/blob/master/.circleci/config.yml), and the testing script (with an argument parser) is [here](https://github.com/vsoch/pannellum/blob/master/tests/run_tests.py). The reason I haven't pull requested yet is because the screenshots weren't working for me, just locally, so I removed them to get basic tests working and then also working in the CI. If we can debug the screenshots, then you should have fully automated tests. :)

The error I get locally is:

```
    raise exception_class(value)
selenium.common.exceptions.WebDriverException: Message: unknown command: session/561f7791117f8823a289d498d9ffcf72/element/0.2280353649737068-1/screenshot
```  
And I'm about to test on CircleCI to see if it happens there too. Have you seen anything like this?

**Comment by vsoch** [comment]
Got it all working! See https://github.com/mpetroff/pannellum/pull/777

**Comment by mpetroff** [comment]
#777 was applied in a squashed commit in 13ceeb605601776a57c69f1ba00be70e5d968735 and applied to Travis in 6675d15d9db90b80fa91426ea636a80d3e56d42e. Continuous integration should now be working for both `master` and pull requests.

More discussion in https://github.com/mpetroff/pannellum/pull/777#issuecomment-519396603.

**Comment by vsoch** [comment]
Great! And here is the green testing, for future reference. https://travis-ci.org/mpetroff/pannellum I'm glad this is working, and glad to help :)
