### ISSUE TITLE
Perspective

### ISSUE THREAD

**Issue by gbarmus** [mpetroff/pannellum#78]
This is not so much an issue as a request. I'm in the process of making a tour of a factory. And so I made a quick diagram to show something that could possibly be implemented. 
Let's say you had a hallway with 4 rooms. And each room was linked via hotspot so that the next door you open, the default view of the pano would open facing the next door. As shown in the picture, the default view or orientation of the pano would open facing the door of the next room (shown in red). But once you reach the end of the hall and start returning to previous rooms, the pano would open with the view that would be facing the wrong direction. Instead, you would want the next room to open with the yellow perspective or default view.

I'm not a programmer or tech guy at all but would it be possible to have the perspective elements for the next room load with the hotspot? Then the perceived tour would be more natural... as if you were 'walking' into the next room with the correct orientation already in place. Cheers
![tour](https://cloud.githubusercontent.com/assets/12732943/8010853/db22d4fa-0b68-11e5-9d57-c09e3b28e24b.jpg)

**Comment by mpetroff** [comment]
This is already possible with the `targetPitch` and `targetYaw` hot spot [configuration parameters](https://github.com/mpetroff/pannellum/blob/master/doc/json-config-parameters.md#hotspots), which override the target scene's default pointing.

**Comment by gbarmus** [comment]
The first scene - is it possible to create a targetYaw for that one? And if so, what's the implementation?
Thanks!

**Comment by mpetroff** [comment]
Yes. Each scene can have a `pitch` and `yaw` specified that determine its default pointing, and each hot spot can have a `targetPitch` and `targetYaw` that override the default pointing.

```
"sceneName": {
    "panorama": "./pano1.jpg",
    "hotSpots": [
        {
            "pitch": 0,
            "yaw": 100,
            "targetPitch": 10,
            "targetYaw": 20,
            "type": "scene",
            "text": "Other Scene (with override)",
            "sceneId": "otherScene"
        },
        {
            "pitch": 10,
            "yaw": 100,
            "type": "scene",
            "text": "Other Scene (without override)",
            "sceneId": "otherScene"
        }
    ]
},
"otherScene": {
    "panorama": "./pano2.jpg",
    "pitch": 100,
    "yaw": 150
}
```

In this example, the scene's (not the hot spot's) `pitch` and `yaw` parameters specify the default pointing of the other scene. When the hot spot that specifies the `targetPitch` and `targetYaw` parameters is clicked, the other scene is loaded with an initial pointing of pitch 10 and yaw 20. When the hot spot that does not specify this override is clicked, the other scene is loaded with its default initial pointing of pitch 100 and yaw 150.
