### ISSUE TITLE
problem with draging on a hotspot

### ISSUE THREAD

**Issue by lefevrejeremy** [mpetroff/pannellum#784]
Hi, 
Maybe it can be an improvement of the library or there is a workaround, it is not possible to  drag the view with the mouse to move left, right, up and down, when you are pointing on a hotspot.
any idea how to solve this?

BR,
jerem

**Comment by mpetroff** [comment]
The hot spots have separate click handlers, to allow navigation and external link hot spots to work. Thus, you can't drag the view when pointed at a hot spot.
