### ISSUE TITLE
Not scrollable on touch devices even when config.draggable is false

### ISSUE THREAD

**Issue by valbewe** [mpetroff/pannellum#788]
Hello!  Thanks for this great panorama viewer! 

My problem is that I can not scroll over the pannellum-viewer with a touch screen device. I think the best solution would be to add an (optional) gesture handler similar to this: https://github.com/elmarquis/Leaflet.GestureHandling/
So if you want to draw the panorama, you have to use two fingers, if you only use one, than you can scroll over it.
Tha

**Comment by mpetroff** [comment]
The `draggable` set to false behavior has now been fixed in 406d003e5c10449aaa09cb9aadf3c68db9fe5ab1.

The behavior of Google Maps has already been brought up in https://github.com/mpetroff/pannellum/issues/360#issuecomment-323026648 and is tracked there.

**Comment by valbewe** [comment]
It works now. Thank you!
