### ISSUE TITLE
Automate Partial Pano Params

### ISSUE THREAD

**Issue by garand** [mpetroff/pannellum#790]
Hey! Love the project, thanks so much. I'm working on integrating this into a CMS where people can upload various pano's, some may be full equirectangular's, some may be iPhone style pano's that aren't full 360. I found issue #643 which was helpful for discovering `minYaw`, `maxYaw`, `minPitch`, and `maxPitch`, and I can dial them in specifically for the image I'm testing, however I would like to be able to automate those numbers. Are there any ways you know of to do that or can you share some insight into how those should be calculated?

Thanks!

**Comment by mpetroff** [comment]
Panoramas from an iPhone should include [Photo Sphere XMP metadata](https://developers.google.com/streetview/spherical-metadata), which Pannellum automatically recognizes for displaying the panorama. You could extract that data using something like [ExifTool](https://www.sno.phy.queensu.ca/~phil/exiftool/) and use that to the set the pitch and yaw limits. The XMP data defines everything in pixels, so the panorama dimensions need to be converted to degrees first; Pannellum does this internally at: https://github.com/mpetroff/pannellum/blob/b1794add898fac00f6265e30f316108d0aaf518c/src/js/pannellum.js#L565-L586

From the XMP limits, you can get the panorama edges and then set the edge of view limits as you like from that, e.g., exactly at the edge or with some sort of buffer.
