### ISSUE TITLE
Disable antialiasing on images

### ISSUE THREAD

**Issue by emmelleppi** [mpetroff/pannellum#793]
Hi, I'd like to know if there is a way to disable antialiasing on images loaded into the viewer in multires mode.
In my use case it is important to be able to zoom in up to a single pixel.

I tried disabling antialiasing in the webgl context with

`gl = canvas.getContext('experimental-webgl', {alpha: false, depth: false, antialising: false});`

and also disabling the image smoothing in the 2D context with

```
                gl.imageSmoothingEnabled = false; 
                gl.mozImageSmoothingEnabled = false; 
                gl.webkitImageSmoothingEnabled = false; 
                gl.msImageSmoothingEnabled = false; 
```

I also tried to load only 512x512 images (or power of 2 in general) hoping to avoid resizing.

None of these methods worked
Do you have any idea of a possible solution?

Thanks a lot

**Comment by mpetroff** [comment]
The issue isn't with anti-aliasing, which only affects geometry edges. You need to modify the texture interpolation.

Changing `gl.LINEAR` to `gl.NEAREST` here:
https://github.com/mpetroff/pannellum/blob/b1794add898fac00f6265e30f316108d0aaf518c/src/js/libpannellum.js#L1123-L1131

may help. If it doesn't, you'll have to modify the shaders; this blog post may help: https://csantosbh.wordpress.com/2014/01/25/manual-texture-filtering-for-pixelated-games-in-webgl/

**Comment by emmelleppi** [comment]
It works properly by changing gl.LINEAR to gl.NEAREST.

Thank you!
