### ISSUE TITLE
Hotspots 

### ISSUE THREAD

**Issue by Nabilcobain** [mpetroff/pannellum#794]
Hi Matthew  , I have a map when I lick on a point i get the image , but when I load hotspots (from database ) when I move to other photo the old hotspots are still showing in the viewer . do I have to intialize the viewer everytime ? if So how ? 
Thank you Sir

**Comment by mpetroff** [comment]
How are you loading the hot spots? The `addHotSpot` should only add hot spots to the current scene, so I can't be of much help without more information.
