### ISSUE TITLE
libpannellum is not defined at onImagLoad (pannellum.js:475)

### ISSUE THREAD

**Issue by peter-snr** [mpetroff/pannellum#796]
Hello,

I am trying to run the standalone from v2.5.4.

I have all the files in a directory running on ngix.

**/standalone**
  pannellum.htm (renamed to pannellum.html)
  standalone.css
  standalone.js
  myimage.jpg

**/standalone/js/**
  libpannellum.js
  pannellum.js
**/standalone/css/**
  pannellum.css

This is my html file
```html
<!DOCTYPE HTML>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Pannellum</title>
  <link type="text/css" rel="Stylesheet" href="css/pannellum.css"/>
  <link type="text/css" rel="Stylesheet" href="standalone.css"/>
</head>
<body>
<div id="container">
  <noscript>
    <div class="pnlm-info-box">
      <p>Javascript is required to view this panorama.<br>(It could be worse; you could need a plugin.)</p>
    </div>
  </noscript>
</div>


<script type="text/javascript" src="js/libpannellum.js"></script>
<script type="text/javascript" src="js/pannellum.js"></script>
<script type="text/javascript" src="standalone.js"></script>
</body>
</html>
```

I then navigate to this URL.

http://localhost/standalone/pannellum.html?panorama=/standalone/R0010501.jpg&title=My%20Test&author=Test&autoLoad=true

But I get this error in the console.
Uncaught ReferenceError: libpannellum is not defined
  at onImageLoad (pannellum.js:476)
  at Image.panoImage.onload(pannellum.js:392)

**If I replace**
```html
<script type="text/javascript" src="js/libpannellum.js"></script>
<script type="text/javascript" src="js/pannellum.js"></script>
```
**With...**
```html
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/pannellum@2.5.4/build/pannellum.js"></script>
```

**It works fine?**

I checked the network tab when loading with local files and all the includes from the index.html are found (no 404's)

Any suggestions please.

**Further information**
I have just downloaded a copy from the CDN https://cdn.jsdelivr.net/npm/pannellum@2.5.4/build/pannellum.js

and replaced the version I have from the repository, it works fine.

Seems there is a difference between the CDN version and the one in your repository here:

[https://github.com/mpetroff/pannellum/blob/master/src/js/pannellum.js](https://github.com/mpetroff/pannellum/blob/master/src/js/pannellum.jsl)

But I cannot diff them because the CDN is minified...

**Comment by mpetroff** [comment]
The CDN copy combines both the `src/js/libpannellum.js` and `src/js/pannellum.js` scripts, per the [utils/build/build.py](https://github.com/mpetroff/pannellum/blob/master/utils/build/build.py) build / minification script.

The error message suggests that the `libpannellum.js` script isn't being loaded, since the script tags are in the correct order, with `libpannellum.js` being included first. However, you state that there are no errors loading the files, so I'm at a loss as to what is happening.

**Comment by peter-snr** [comment]
Thank you for your reply everything is working fine now. Not really sure what I was doing wrong a gremlin on my part perhaps 

Kind regards 
Peter Goudman
