### ISSUE TITLE
keep the camera rotation when loading other panorama?

### ISSUE THREAD

**Issue by chendabo** [mpetroff/pannellum#798]
Hi,
I've been trying to create an experience using multiple cubemaps.
I'm using the example-tour.json as a starting point.

I need to keep the camera looking at the same direction after loading the new scene, instead of setting the camera to the default direction. (an experience similar to google street view, without the fancy tunnel vision effect)

I tried to set Pitch or Yaw by getting the current Pitch or Yaw, however, when clicking on the hotspot to load a new pano, I believe it is still using the old Pitch or Yaw when pannellum.viewer is first loaded.

Same for targetPitch and targetYaw for hotspots.

Can anyone provide some advices on how to achieve that?
Thank you!

**Comment by mpetroff** [comment]
Setting `"targetPitch": "same"` and `"targetYaw": "sameAzimuth"` on hot spots should achieve the effect you're after.

**Comment by chendabo** [comment]
Thank you! Will give that a try!!!
