### ISSUE TITLE
Incorrect orientation of the north | Heading / Yaw

### ISSUE THREAD

**Issue by lucaspojo** [mpetroff/pannellum#799]
Hi,

I'm trying to rotate the image to north. I use the **map.setYaw( HEADING)** function to rotate.
The rotation does this, but the north is not good.

Even if the north is not the right direction, the photo should be oriented in the same direction all the time.

I have 100 pictures on a trajectory.

and finally, the compass doesn't look in the same direction as the picture.

demo1 : https://i.imgur.com/lDiMKRj.jpg
demo2 : https://i.imgur.com/rfE8ZtU.jpg
demo3 : https://i.imgur.com/ZVBOpZo.jpg

```
for(k in indexFile) {

                let filename = indexFile[k].img;
                let roll = indexFile[k].roll;
                let pitch = indexFile[k].pitch;
                let heading = indexFile[k].heading;

                let marker = L.marker([indexFile[k].lat, indexFile[k].lng], {icon: greenIcon}).on('click', function(e) {

                    viewer = pannellum.viewer('panorama', {
                        "type": "equirectangular",
                        "panorama": "https://atgt.s3.eu-west-3.amazonaws.com/"+project_id+"/"+filename,
                        "autoLoad": true,
                        "compass": true,
                        "northOffset": heading
                    });

                    console.log(filename);
                    
                    viewer.setPitch(pitch);
                    viewer.setYaw(heading );

                    console.log(heading);
                });
}
```

What to fix? Thank you!

**Comment by mpetroff** [comment]
I see that you're setting a `northOffset`. The `setYaw` function calculates yaw based on image coordinates only (center of panorama is zero) and does not account for this offset, which is only used for the compass display (and `sameAzimuth` hot spot parameter). If you want to account for the north offset in setting the yaw, you'll need to do so manually.
