### ISSUE TITLE
google drive images

### ISSUE THREAD

**Issue by BirddogMan** [mpetroff/pannellum#800]
I am trying to pull images from google drive into pannellum using the google api. I have been able to send a successful get request however no image ever appears in the viewer. The loading div just keeps showing. There are no errors in the console and the get request returns a status code of 200. Do you have any ideas what could be going wrong? Any help is greatly appreciated. 

![image](https://user-images.githubusercontent.com/52586054/66578835-6ddb4900-eb41-11e9-8c58-2a30cd164646.png)
![image](https://user-images.githubusercontent.com/52586054/66578936-9a8f6080-eb41-11e9-9bdf-ea48b9892d10.png)
![image](https://user-images.githubusercontent.com/52586054/66579089-dfb39280-eb41-11e9-92a6-4e4727974624.png)

**Comment by mpetroff** [comment]
Have you looked at the response? The content type for the response is JSON, not an image.
