### ISSUE TITLE
Failed to execute 'readAsBinaryString' on 'FileReader': parameter 1 is not of type 'Blob'.

### ISSUE THREAD

**Issue by e1sep0** [mpetroff/pannellum#801]
Hi, i try to load image, but i get this error:
![image](https://user-images.githubusercontent.com/5094299/66652991-a8c3a680-ec3f-11e9-9bf3-52620b3eba11.png)
It happens sometimes, not always. Help please)

**Comment by mpetroff** [comment]
This is an issue with your web server or some other software on your computer interfering with your access to your web server. Chrome's HTTP request is failing. The closest I can find to this issue is this bug report: https://bugs.chromium.org/p/chromium/issues/detail?id=89

**Comment by blowROCK** [comment]
I think, this issue window image cache.
1. 5 megabytes image is work fine.
2. when the remaining capacity of the C drive is small, Problem encountered.
3. It's working well in Mac. 

solution
var img = new Blob([this.respones]);
xhr.responseType='arraybuffer'; 

works for me.

**Comment by blowROCK** [comment]
I think, this issue window image cache.
1. 5 megabytes image is work fine.
2. when the remaining capacity of the C drive is small, Problem encountered.
3. It's working well in Mac. 

solution
```
var img = new Blob([this.respones]);
xhr.responseType='arraybuffer'; 
```
works for me.
