### ISSUE TITLE
orientationOnByDefault not working

### ISSUE THREAD

**Issue by alegroSandermann** [mpetroff/pannellum#804]
Hi,
I set orientationOnByDefault to true but it is not working?
Testet on the newest iphone and on Pixel 4.
Am I doing something whrong?

**Comment by mpetroff** [comment]
Are you using an HTTPS connection? A secure connection is required for accessing device orientation in recent versions of Chrome, Safari, and Firefox. The use of an HTTP connection would be my best guess as to why it isn't working for you on a Pixel 4.

As for iOS, see #797 and #727.

**Comment by alegroSandermann** [comment]
Thats it. Didtn't know that a https connection is required. Now it works, thanks a lot.
