### ISSUE TITLE
Api "onMovement" event

### ISSUE THREAD

**Issue by orlandobj** [mpetroff/pannellum#806]
Hello, can you make an event to trigg a function when the viewer ison movement? I actually got this monitoring the compass style changes... I use this because i have 2 viewers, side by side, with the same panorama, but in different dates. It's for engineering purposes, to compare the two structures and see the changes along the timeline, but with the compass solution, i can't detect vertical-only movement, causing a little shake.

![Capturar](https://user-images.githubusercontent.com/53941005/68482479-73977d80-0218-11ea-83ba-ece455ac20ad.PNG)

**Comment by mpetroff** [comment]
The addition of a `render` event is tracked in #310. I'm closing this as a duplicate.
