### ISSUE TITLE
How to get pitch and yaw from position vectors i.e (X,Y,Z coordinates)

### ISSUE THREAD

**Issue by pratikbendale** [mpetroff/pannellum#808]
Hi
I am using pannellum for viewing 360 images and I want to display a hotspot on the image.
But I have position vectors i.e (X, Y, Z coordinates) of the hotspots to a place. I tried converting those to pitch and yaw.
But not getting an exact pitch and yaw for hotspot location. 
The image is format is equirectangular.
Please anyone can help me

**Comment by mpetroff** [comment]
You should be to use the standard [Cartesian-to-spherical conversion formulas](https://en.wikipedia.org/wiki/List_of_common_coordinate_transformations#To_spherical_coordinates) to get co-latitude and longitude / yaw. The co-latitude can then be converted to latitude / pitch by subtracting its value from 90 deg.
