### ISSUE TITLE
Error with current release MAX_TEXTURE_SIZE

### ISSUE THREAD

**Issue by martinlombana** [mpetroff/pannellum#809]
![image](https://user-images.githubusercontent.com/18351919/68877202-fb442700-0705-11ea-89ab-5a7b099d479b.png)

`Error: The image is too big; it's 5376px wide, but this device's maximum supported size is 0px.`

It's reporting the device maxium supported size as being 0px, por a PC with chrome Version 78.0.3904.97 (Official Build) (64-bit)

**Comment by mpetroff** [comment]
What does https://webglreport.com/ show as your maximum texture size?

I can't reproduce this using the same version of Chrome. Are you running some sort of anti-fingerprinting extension that might block reading the `MAX_TEXTURE_SIZE` value?

**Comment by martinlombana** [comment]
I inserted a trace here:
![image](https://user-images.githubusercontent.com/18351919/68999256-8c5dfe00-08be-11ea-890d-3f8091ac139b.png)

And I get this: Pretty weird.

![image](https://user-images.githubusercontent.com/18351919/68999253-7d774b80-08be-11ea-987b-fd921abcb3ae.png)

**Comment by martinlombana** [comment]
For starters, I think this line might be wrong:

```
 if (imageType == 'equirectangular') {
            maxWidth = gl.getParameter(gl.MAX_TEXTURE_SIZE);

```

Because this equals zero. Shouldn't it be just: 
```
maxWidth = gl.MAX_TEXTURE_SIZE;
```

(Note that I have no experience in the gl underlying structure, but I think this is a typo).

Moreover, what I don't understand is why I get that the gl.MAX_TEXTURE_SIZE, is 3379, while https://webglreport.com/, reports 16384.

**Comment by martinlombana** [comment]
Ah! I found the typo on your code!!

It should be:

```
gl.getParameter(MAX_TEXTURE_SIZE));
```

But you are using gl.MAX_TEXTURE_SIZE

See here:

![image](https://user-images.githubusercontent.com/18351919/68999384-b2d06900-08bf-11ea-81be-05514fbdb0ec.png)

**Comment by martinlombana** [comment]
If I change this line and a couple more, to:

```
gl.getParameter(MAX_TEXTURE_SIZE) it reports 16384. 
```

**Comment by martinlombana** [comment]
I deleted previous coments. Your code seems fine. I don't know what is going on.

**Comment by mpetroff** [comment]
To access `gl.MAX_TEXTURE_SIZE`, you need to use `gl.getParameter(gl.MAX_TEXTURE_SIZE)`; 3379 is the parameter ID for `MAX_TEXTURE_SIZE`.

**Comment by martinlombana** [comment]
Yes. I saw that I misjudged this, quite random, error. Sometimes I get it.
Otherwise I don't. I don't know what is going on. Sometimes I get the
mentioned error and some others I don't. Seems like a weid glitch. Your
code seems perfectly fine.

I will investigate further, and if I find something, I'll let you know.

You can close this bug report, and If I find something conclusive, I shall
re-open a new one.

Thanks!

>
