### ISSUE TITLE
Use Pannellum with Angular 8

### ISSUE THREAD

**Issue by alegroSandermann** [mpetroff/pannellum#810]
Does someone know how to use pannellum with angular 8?

First I did `npm i pannellum`

Than in my component I tried to import pannellum like `import * as pannellum from 'pannellum';`
Then VS Code says: Try `npm install @types/pannellum` if it exists or add a new declaration (.d.ts) file containing declare module 'pannellum';
Then I get the message: '@types/pannellum@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)

I also tried another import way, like `const pannellum = require('pannellum');`
..and setup the minimum to view a pano (pannellum.viewer...) in my ts file and a div with id in the html file but nothing is showing up.

Perhaps someone can help with this.

**Comment by mpetroff** [comment]
Pannellum has no TypeScript decorations, which is what causes the first issue. I have no experience with either TypeScript or Angular.

**Comment by martinlombana** [comment]
I can confirm that you can use it without problem. You will not have any type hints, because there is no TypeScript definitions, but it is usable. I am using it with full success. 

Just install it with npm, and then, in the page or component that you want to use it:

```
import 'pannellum/src/js/pannellum';
import 'pannellum/src/js/libpannellum'; 
``
And you must also include the CSS.

If you are using SASS, in your styles.scss or such:

``
@import "~pannellum/src/css/pannellum.css";
``

And then, just follow the great API documented by @mpetroff , wich is very clear and straight forward.

**Comment by debanjali7** [comment]
I tried this, also tried [https://bleepcoder.com/pannellum/277561961/use-in-angular2](url) 
unfortunately the viewer doesnt work on my angular app..
This is my component
`import { Component, OnInit } from '@angular/core';
// import 'pannellum/src/js/pannellum'; 
// import 'pannellum/src/js/libpannellum';

declare var pannellum: any;

@Component({
  selector: 'app-pano-view',
  templateUrl: './pano-view.component.html',
  styleUrls: ['./pano-view.component.css']
})
export class PanoViewComponent implements OnInit {

  constructor() { }
  

  ngOnInit(): void {

    // pannellum.viewer('panoramaContainer', {
    //   "type": "equirectangular",
    //   "panorama": "R0010012.JPG",
    //   "autoLoad": true,
    //   "compass": true
    // });

    pannellum.viewer('panorama', {   
      "default": {
          "firstScene": "view1",
          "sceneFadeDuration": 1000,
    "autoLoad": true
      },
  
      "scenes": {
          "view1": {
              "title": "360 Virtual Tour",
              "hfov": 120,
              "pitch": -10,
              "yaw": 180,
              "type": "equirectangular",
              "panorama": "R0010012.JPG",
              "hotSpots": [
                  {
                      "pitch": -10,
                      "yaw": 180,
                      "type": "scene",
                      "text": "Towards Buffet",
                      "sceneId": "view2"
                  },
          {
                      "pitch": -10,
                      "yaw": 90,
                      "type": "scene",
                      "text": "Outdoor",
                      "sceneId": "view4"
                  },
          {
                      "pitch": -10,
                      "yaw": 120,
                      "type": "scene",
                      "text": "Kitchen",
                      "sceneId": "view3",
            "targetYaw": 45,
                      "targetPitch": -5
                  }
              ]
          },
  
          "view2": {
              "title": "360 Virtual Tour",
              "hfov": 120,
              "yaw": 60,
        "pitch": -10,
              "type": "equirectangular",
              "panorama": "R0010013.JPG",
              "hotSpots": [
                  {
                      "pitch": 0,
                      "yaw": 10,
                      "type": "scene",
                      "text": "Reception",
                      "sceneId": "view1",
                      "targetYaw": 40,
                      "targetPitch": -10
                  },
          {
            "pitch": -10,
            "yaw": -148,
            "type": "info",
            "text": "Exit"
          },
          {
            "pitch": -10,
            "yaw": 155,
            "type": "info",
            "text": "Kitchen"
          },
          {
            "pitch": -10,
            "yaw": 58,
            "type": "info",
            "text": "Service"
          }
          
          
              ]
          },
  
          "view3": {
              "title": "360 Virtual Tour",
              "hfov": 110,
              "yaw": 0,
              "type": "equirectangular",
              "panorama": "R0010014.JPG",
              "hotSpots": [
                  {
                      "pitch": -10,
                      "yaw": 125,
                      "type": "scene",
                      "text": "Lobby",
                      "sceneId": "view1",
                      "targetYaw": -70,
                      "targetPitch": 0
                  }
              ]
          },
      "view4": {
              "title": "360 Virtual Tour",
              "hfov": 110,
              "yaw": 0,
              "type": "equirectangular",
              "panorama": "R0010015.JPG",
              "hotSpots": [
                  {
                      "pitch": 0,
                      "yaw": 190,
                      "type": "scene",
                      "text": "Outdoor Storage",
                      "sceneId": "view5",
                      "targetYaw": -200,
                      "targetPitch": 0
                  },
          {
                      "pitch": 0,
                      "yaw": 38,
                      "type": "scene",
                      "text": "Lobby",
                      "sceneId": "view1",
                      "targetYaw": -225,
                      "targetPitch": -5
                  },
          {
                      "pitch": 0,
                      "yaw": -58,
                      "type": "scene",
                      "text": "Outdoor Area 2",
                      "sceneId": "view6",
                      "targetYaw": 40,
                      "targetPitch": 10
                  }
              ]
          },
      "view5": {
              "title": "360 Virtual Tour",
              "hfov": 110,
              "yaw": 0,
              "type": "equirectangular",
              "panorama": "R0010016.JPG",
              "hotSpots": [
                  {
                      "pitch": 0,
                      "yaw": -56,
                      "type": "scene",
                      "text": "Entrance",
                      "sceneId": "view4",
                      "targetYaw": -70,
                      "targetPitch": 0
                  }
              ]
          },
      "view6": {
              "title": "360 Virtual Tour",
              "hfov": 110,
              "yaw": 0,
              "type": "equirectangular",
              "panorama": "R0010017.JPG",
              "hotSpots": [
                  {
                      "pitch": 0,
                      "yaw": 70,
                      "type": "scene",
                      "text": "Entrance",
                      "sceneId": "view4",
                      "targetYaw": 48,
                      "targetPitch": -5
                  }
              ]
          }
  
      }
  });
  
  }

}
`

This is my component html

`<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>

<div id="panorama"></div>


</body>
</html>`

and I have this on my angular.json
`"styles": [
              "src/styles.css",
              "node_modules/pannellum/src/css/pannellum.css"
            ],
            "scripts": [
              "node_modules/pannellum/src/js/pannellum.js",
              "node_modules/pannellum/src/js/libpannellum.js"
            ]`

**Comment by TheTrueTrooper** [comment]
So there was not a type definition, so you will need to define a type def for it all. Or at least what you are using to sate the compiler. You can do this in a .d.t or a .t as I ended up with in this case. This is admittedly this sounds easier than it is as examples only have a classic approach that assumes that you have access to any global types easy enough. Well not quite the case for type script. Especially if you are using strict typing. If you follow the the documentation it is easy enough to generate some types in rough as I have here.
`typescript
import 'pannellum/src/js/libpannellum'
import 'pannellum/src/js/pannellum'

export type PannellumPanoramaType = 'equirectangular' | 'cube' | 'multires';

export type PannellumCrossOrigin = 'anonymous' | 'use-credentials' ;

export type PannellumEventType = 'load' | 'scenechange' | 'fullscreenchange' | 'zoomchange' | 'scenechangefadedone' | 'animatefinished' | 'error' | 'errorcleared' | 'mousedown' | 'mouseup' | 'touchstart' | 'touchend';

export type EquirectangularConfig = {
  haov?: number | undefined
  vaov?: number | undefined 
  vOffset?: number | undefined 
  panorama: string | undefined
  ignoreGPanoXMP?: boolean | undefined
  dynamic?: boolean | undefined
  dynamicUpdate?: boolean | undefined
  type: 'equirectangular'
} & SharedConfig

export type cubeMapConfig = {
  cubeMap: string[] | undefined
  type: 'cube'
} & SharedConfig

export type multiresConfig = {
  path: string
  basePath: string
  fallback: string
  extension: string
  tileResolution: number
  maxLevel: number
  cubeResolution: number
  type: 'multires'
} & SharedConfig

export type SharedConfig = {
    hfov?: number
    publicminHfov?: number
    multiResMinHfov?: boolean
    pitch?: number
    minPitch?: number
    maxPitch?: number
    minHfov?: number 
    maxHfov?: number
    yaw?: number
    minYaw?: number
    maxYaw?: number
    roll?: number
    autoRotate?: boolean
    autoRotateInactivityDelay?: number
    autoRotateStopDelay?: number
    type: PannellumPanoramaType
    northOffset?: number
    showFullscreenCtrl?: boolean
    dynamic?: boolean
    dynamicUpdate?: boolean
    doubleClickZoom?: boolean
    keyboardZoom?: boolean
    mouseZoom?: boolean | 'fullscreenonly'
    showZoomCtrl?: boolean
    autoLoad?: boolean
    showControls?: boolean
    orientationOnByDefault?: boolean
    hotSpotDebug?: boolean
    backgroundColor?: [number, number, number]
    avoidShowingBackground?: boolean
    previewAuthor?: string
    preview?: string
    animationTimingFunction?: ((number: number)=>number)
    draggable?: boolean
    disableKeyboardCtrl?: boolean
    crossOrigin?: PannellumCrossOrigin
    touchPanSpeedCoeffFactor?: number
    capturedKeyNumbers?: number[]
    friction?: number
    compass?: boolean
    hotSpots?: hotSpot[]
    escapeHTML?: boolean
    basePath?: string
    strings?: stringsDictionary
    authorURL?: string
    author?: string
    title?: string
    sceneFadeDuration?: number

  }

  export type stringsDictionary = {
    [key: string]: any
  }

  export type Scenes = {
    [key: string]: EquirectangularConfig | cubeMapConfig | multiresConfig
  }

  export type hotSpot = {
    pitch: number
    yaw: number
    type: "info" | string //feel like there is more values here but I'm not sure and could not identify them so I'm leaving it open with a string for now but at least you have some help
    text?: string
    URL?: string
    attributes?: object
    sceneId?: string
    targetPitch?: number
    targetYaw?: number
    targetHfov?: number
    id?: any
    cssClass?: string | undefined
    createTooltipFunc?: ((createArgs: object)=> void)
    clickHandlerFunc?: ((createArgs: object)=> void)
    scale?: boolean
  }

  export type PannellumRender = {
    init(haov: number, vaov: number, voffset: number, callback: (()=>void), params: {horizonPitch : number, horizonRoll: number, backgroundColor: [number, number, number]}, image: HTMLImageElement | string[] | Object,  imageType: string, dynamic: boolean): void
    getCanvas(): HTMLElement
    isLoading(): boolean
    render(pitch: number, yaw: number, hfov: number, params: { roll: number, returnImage: boolean }): void | HTMLImageElement
    setPose(horizonPitch: number, horizonRoll: number): void
    resize(): void
    destroy(): void
  }


  export type PannellumViewer = {
    isLoading(): boolean
    getPitch(): number
    setPitch(set: number, animated: boolean | number, callback: ((callbackArgs: object)=>void), callbackArgs: object): PannellumViewer
    getPitchBounds(): [min: number, max: number]
    setPitchBounds(set: [min: number, max: number]): PannellumViewer
    getYaw(): number
    setYaw(set: number): PannellumViewer
    getYawBounds(): [min: number, max: number]
    setYawBounds(set: [min: number, max: number]): PannellumViewer
    getHfov(): number
    setHfov(set: number, animated: boolean | number, callback: ((callbackArgs: object)=>void), callbackArgs: object): PannellumViewer
    getHfovBounds(): [min: number, max: number]
    setHfovBounds(set: [min: number, max: number]): PannellumViewer
    lookAt(pitch : number, yaw: number, hfov: number, animated: number | boolean, callback: ((callbackArgs: object)=>void), callbackArgs: object): PannellumViewer
    getNorthOffset(): number
    setNorthOffset(set: number): PannellumViewer
    getHorizonRoll(): number
    setHorizonRoll(set: number): PannellumViewer
    getHorizonPitch(): number
    setHorizonPitch(set: number): PannellumViewer
    startAutoRotate(speed: number, pitch: number): PannellumViewer
    stopAutoRotate(): PannellumViewer
    stopMovement(): PannellumViewer
    getRenderer(): PannellumRender
    setUpdate(force: boolean): PannellumViewer
    mouseEventToCoords(event: MouseEvent):[pitch : number, yaw: number]
    loadScene(sceneId: string, pitch: number, yaw: number, hfov: number): PannellumViewer
    getScene(): string
    addScene(sceneId: string, config: EquirectangularConfig | cubeMapConfig | multiresConfig | Scenes): PannellumViewer
    removeScene(sceneId: string): boolean
    toggleFullscreen(): boolean
    getConfig():  EquirectangularConfig | cubeMapConfig | multiresConfig | Scenes
    getContainer(): HTMLElement
    addHotSpot(config: hotSpot): PannellumViewer
    removeHotSpot(hotSpotId: string, sceneId: string): boolean
    resize(): PannellumViewer
    isOrientationSupported(): boolean
    stopOrientation(): PannellumViewer
    startOrientation(): PannellumViewer
    isOrientationActive(): boolean
    on(type: PannellumEventType,callback: ((event: Event)=>void)): PannellumRender
    off(type: PannellumEventType,callback: ((event: Event)=>void)): PannellumViewer
    destroy(): void
  }

  declare global {
    interface Window { 
      pannellum: Factories
    }
  }

  export interface Window { 
    pannellum: Factories
  }

  export interface Factories {
    viewer(container: string | HTMLElement, config: EquirectangularConfig | cubeMapConfig | multiresConfig | Scenes): PannellumViewer;
    Renderer(container: HTMLElement): PannellumRender
  }

`
The next trick will be to understand where it is actually coming from. We can get a clue from the window.pannellum = (function(window, document, undefined) in the src files. It is actually in practice stored in the window object. This means you will need to access it from the window with a interface. The above lines:
`typescript  
declare global {
    interface Window { 
      pannellum: Factories
    }
  }

  export interface Window { 
    pannellum: Factories
  }
 `
 >will help with this. I opted to access though the global. You could inject the window as well as I have seen, but it is not necessary to 'declare' the global then. But given This is kind of a one off that can live in its own component then why put in the extra work for a injectable window. Next you will need to call the object and instants the viewers. After this the Docs will be pretty straight forward and access to the object should get you enough for anything more advanced. Here is an example of my component. Note that angular uses globalThis instead of a straight global to avoid conflicts in certain cases like with node.
 HTML Template:
 `<div class="map-container">
    <div class="map-frame">
      <div id="{{PanoramaId}}"></div>
      <img src="assets/OIP.jpg"/>
    </div>
</div>`
Component:
`import { AfterViewInit, Component, Input } from '@angular/core';
import { EquirectangularConfig, PannellumViewer  } from '../pannellum-type/pannellum'; // this is what I named my above file in the rough and may be name as you or your team see fit.

@Component({
  selector: 'pannellum-panorama',
  templateUrl: './pannellum-panorama.component.html',
  styleUrls: ['./pannellum-panorama.component.scss']
})
export class PannellumComponent implements AfterViewInit {
  @Input()
  PanoramaId: string = "panorama"
  @Input()
  PanoramaSrc: string = "panorama"

  private pannellumViewer: PannellumViewer | null = null

  private initMap(): void {
    this.pannellumViewer = globalThis.window.pannellum.viewer(this.PanoramaId, {
      type: "equirectangular",
      panorama: "https://pannellum.org/images/cerro-toco-0.jpg",
      autoLoad: true
    } as EquirectangularConfig)
  }

  constructor() { }

  ngAfterViewInit(): void {
    this.initMap();
   }
}`
After that I'm sure you have everything you need to get started with the docs and refine what I have here.

**Comment by TheTrueTrooper** [comment]
Honestly might want to open a definitely typed branch and do some sort of official typing. Its a great library that is quite extendable. Previous uses I had out of it I even managed to draw on the images. I have not used it since switching to typescript, but I would bet some people out there would really like to use it.

**Comment by StigNygaard** [comment]
Typescript types can be defined as JSDoc-annotations in plain vanilla .js javascript files.
Not that I have tried Typescript (or this approach with typeing in Typescript) myself.
But the type-annotations can also be used by other development tools like IntelliJ, WebStorm and VS without having to make it to a Typescript project.
