### ISSUE TITLE
allow minYaw greter than maxYaw (yawBounds)

### ISSUE THREAD

**Issue by bsakab** [mpetroff/pannellum#811]
currently yawRange only works if minYaw is smaller than maxYaw - what makes sense if just look on the variable name. You can set bounds by "setYawBounds" this way (minYaw >maxYaw ) but the yawRange feature does not work anymore. 
This would be nice cause then we are able to define yawBounds that work 360°.
Let me know if you need more details.

**Comment by bsakab** [comment]
![yawbound](https://user-images.githubusercontent.com/22796941/69166669-eabff200-0af3-11ea-9ba9-47c5e60336fe.jpg)
maybe this visualizes the issue more

**Comment by mpetroff** [comment]
I fixed this in f42e80facb41bb97321a0e2056d9ef5a4779e627, by allowing the yaw range to be set in the range of +/- 360 deg. Your second example can now be achieved by setting the min / max yaw range to [135, 225].
