### ISSUE TITLE
No loading of new Scene

### ISSUE THREAD

**Issue by JohanvandeKoppel** [mpetroff/pannellum#815]
I have been trying to create two buttons to switch between two scenes (and more in the future), but the loadScene command just doesn't want to work if you click on the buttons. The scene looks great, but the buttons don't work. Does anybody have an idea why? 

Thanks in advance, Johan

```// Just above the start of the script:
<div id="panorama" style="width:100%;height:750px;">
    <div id="controls">
        <div class="ctrl" id="Image_1">1</div>
        <div class="ctrl" id="Image_2">2</div>
    </div>
</div>

// Assigning actions to buttons:
document.getElementById('Image_1').addEventListener('click', function() {
    viewer.loadScene("Mudflat1");
});
document.getElementById('Image_2').addEventListener('click', function() {
    viewer.loadScene("Mudflat2");
});

To see the current version online:
https://people.zeelandnet.nl/jvdkoppel/Panos/BESE.html

**Comment by AlexMakss** [comment]
Hello, please change
#1 
pannellum.viewer('panorama', {
to 
myViewer = pannellum.viewer('panorama', {

#2 
viewer.loadScene("Mudflat1");
to 
myViewer.loadScene("Mudflat1");

**Comment by JohanvandeKoppel** [comment]
Ah, an object. It worked! Thanks
