### ISSUE TITLE
iframe doesnt render anymore

### ISSUE THREAD

**Issue by ClementGermain** [mpetroff/pannellum#816]
Hi, 

When using an iframe to render a panorama, the plain html content is being displayed instead of the 360 viewer.

![pannellum](https://user-images.githubusercontent.com/19923430/70193572-78424980-1764-11ea-9e2b-0d00b2782377.PNG)

I am pretty sure it was still working last week, but not anymore.

This is also happening with the standalone sample from the [documentation](https://pannellum.org/documentation/examples/simple-example/): 
https://cdn.pannellum.org/2.5/pannellum.htm#panorama=https://pannellum.org/images/alma.jpg

Trying to use the iframe sample from the documentation lead to the same issue.
`<iframe width="600" height="400" allowfullscreen style="border-style:none;" src="https://cdn.pannellum.org/2.5/pannellum.htm#panorama=https://pannellum.org/images/alma.jpg"></iframe>`

ouput from the documentation sample: [pannellum.txt](https://github.com/mpetroff/pannellum/files/3924569/pannellum.txt)

Tested on Chrome and Firefox, and on multiple machines.

Thanks

**Comment by mpetroff** [comment]
When I updated the CDN copy of `pannellum.htm` on November 26, it seems I accidentally set the content type to `application/x-javascript` instead of `text/html`. This has now been fixed. Thanks for reporting the issue.

**Comment by ClementGermain** [comment]
Awesome, it is working again. Thanks a lot
