### ISSUE TITLE
Disable Default Scene change if using clickHandlerFunc

### ISSUE THREAD

**Issue by martinlombana** [mpetroff/pannellum#819]
I am using a custom clickHandlerFunc for the Scene HotSpots. But I want to handle the change to the other scene completely by myself. Is there any native way to disable the default scene change if the clickHandlerFunc is defined?

Thanks,

**Comment by mpetroff** [comment]
Yes. If you don't define `sceneId` for the hot spot, it won't do anything by default (you can pass the scene ID via `clickHandlerArgs` to your own function).
