### ISSUE TITLE
Setting a scence's yaw value to a string in the config breaks the viewer

### ISSUE THREAD

**Issue by MorMundHS-MA** [mpetroff/pannellum#820]
pannellum version: 2.5.4

Related issues: #792

As mentioned in the title, setting the yaw value to a string breaks the viewer:
``` javascript
"scenes": {
        "main": {
          "type": "equirectangular",
          "panorama": "img/test.jpg",
          "autoLoad": true,
          "vaov": 45,
          "yaw": "50", // <--
          "ignoreGPanoXMP": true,
          "hotSpots": [{
         // [...]
```
The viewer starts out normal but once you start moving the camera it quickly turns either purely white or something like this: 
![Annotation 2019-12-28 153421](https://user-images.githubusercontent.com/23387065/71545160-0d151d00-2988-11ea-98e7-335eac0b77b9.png)

While the documentation clearly states that the yaw value should be a number, I think it should fail more gracefully.  
Thanks for making this great library!

**Comment by mpetroff** [comment]
Garbage in, garbage out. There's no input validation, since there are hundreds of ways the input can be invalid, and it's not practical to check everything. This isn't going to be changed.
