### ISSUE TITLE
Get Yaw and Pitch on mouse click

### ISSUE THREAD

**Issue by shtrudelsupport** [mpetroff/pannellum#821]
Hi there,

I tried to get Yaw and Pich using a call to viewer.mouseEventToCoords(e), as a result I got numbers array  that doesn't seem to be right 

As I read other comments/issues I understand I need to get the Developer version,

How do I get Developer version ?

**Comment by zhangyu1818** [comment]
i use mouseEventToCoords,it work for me

**Comment by zhangyu1818** [comment]
i found another config  ——  hotSpotDebug

When true, the mouse pointer’s pitch and yaw are logged to the console when the mouse button is clicked.

maybe it useful to you

**Comment by mpetroff** [comment]
The function should return an array. Here's an example:
```javascript
var viewer = pannellum.viewer(...);
viewer.on('mousedown', function(event) {
    // coords[0] is pitch, coords[1] is yaw
    var coords = viewer.mouseEventToCoords(event);
    // Do something with the coordinates here...
});
```
There is no "developer version."

**Comment by GiveEXP** [comment]
hey u can help me:
pannellum.viewer('panorama', {
    "type": "equirectangular",
    "panorama": "./Image/river.jpg",
    "autoLoad": true,
    "autoRotate": -2, 
    "hotSpots": [],  

    "onContextMenu": function (mouseEvent) {
 
        mouseEvent.preventDefault();

        var pitch = this.mouseEventToCoords(mouseEvent).pitch;
        var yaw = this.mouseEventToCoords(mouseEvent).yaw;


        var message = "Pitch: " + pitch + ", Yaw: " + yaw;
        showPopupMessage(message);
    }
});
