### ISSUE TITLE
creating multires panoramas

### ISSUE THREAD

**Issue by hassanalbudairi** [mpetroff/pannellum#823]
Hi,
I just started to use generate.py (via Docker) to create tiles for my panoramas (original size 11000x5500 pixels) which works fine and I got the tiles (which work my website) but also got the following messege when creating the tiles:
[swscaler @ 000001b4dbbf5ac0] eprecated pixel format used, make sure you did set range correctly

Also, on the pannellum viewer setting I used
```javascript
viewer = pannellum.viewer('panorama', {
    "type": "multires",
	"autoLoad": true,
	"compass": true,
	"autoLoad": true,
	"pitch":p,
	"yaw":y,
    "multiRes": {
        "basePath":current_img,
        "path": "/%l/%s%y_%x",
        "fallbackPath": "/fallback/%s",
        "extension": "jpg",
        "tileResolution": 512,
        "maxLevel": 4,
        "cubeResolution": 3496
    },
```

but the veiwed pannorama has less resolution than the original 360 images. Is there anything i need to change in the generate.py file (I downloaded it from this github) to match the size of my images? should I do any changes to the viewer settings above?
Thanks

**Comment by mpetroff** [comment]
I don't know where the `swscaler` warning came from; I've never seen it before. It's probably not an issue.

What do you mean by "the viewed panorama has less resolution than the original 360 images"? Note that the `cubeResolution` measures something different the equirectangular image width, so the two can't be directly compared; however, the value seems perfectly reasonable given the equirectangular image width.
