### ISSUE TITLE
How to load Pannellum fullscreen on click

### ISSUE THREAD

**Issue by minhphoenix** [mpetroff/pannellum#824]
Hi there, I know you can initialize the viewer on click and you can toggle full screen on click. But I am wondering can you have both in one swift action? 

I tried the below code but the toggleFullScreen doesn't trigger

    vm.viewer = window.pannellum.viewer('panorama', {
        "type": "equirectangular",
        "panorama": "https://pannellum.org/images/alma.jpg",
        "autoLoad": true
    });

    vm.viewer.toggleFullscreen();

**Comment by mpetroff** [comment]
You can accomplish this by adding a listener on the `load` event:
```javascript
vm.viewer.on('load', function() {
    vm.viewer.toggleFullscreen();
});
```

**Comment by mpetroff** [comment]
Note that that won't work is you have `"autoLoad": true` set, since browser security restrictions only allow for initiating full screen mode via user-initiated actions.
