### ISSUE TITLE
Disable Vertical actions 

### ISSUE THREAD

**Issue by minhphoenix** [mpetroff/pannellum#825]
The viewer is great, wondering if it's possible to only enable horizontal rotations and disable vertical rotations. Making it purely a panoramic viewer, not a panoramic 360 viewer.

**Comment by mpetroff** [comment]
Setting the `minPitch` and `maxPitch` configuration parameters to the same value disables vertical movement; if your panorama is centered on the horizon, you should set both to `0`.
