### ISSUE TITLE
Is there a way to determine pixel position given yaw and pitch coords?

### ISSUE THREAD

**Issue by Desmond-Campbell** [mpetroff/pannellum#826]
There's currently a ```mouseEventToCoords()``` that converts the clientX and clientY properties of the mouse click event to pitch and yaw coordinates. Is there something like a ```coordsToClientPosition()``` function to reverse that? As in, given a pitch and yaw, calculate the corresponding clientX and clientY positions that the coords would translate to.

**Comment by mpetroff** [comment]
No such function exists.

To write such a function, you'd need to follow the math used in the `renderHotSpot` function to position hot spots to get canvas coordinates:

https://github.com/mpetroff/pannellum/blob/15e0d09fec8d7ea56adb67f30736c81d46f1aa88/src/js/pannellum.js#L1855-L1894

You would then need to reverse what is done in the `mousePosition` function to go from canvas coordinates to page coordinates:
https://github.com/mpetroff/pannellum/blob/15e0d09fec8d7ea56adb67f30736c81d46f1aa88/src/js/pannellum.js#L693-L700

**Comment by Desmond-Campbell** [comment]
Your response was helpful. Thank you.
I created a ```coordsToClientPosition()``` function that used the math in ```renderHotSpot()```, with a zero-length imaginary hotspot. It worked.

**Comment by aproni34f** [comment]
> ction renderHotSpot(hs

Can you share that function please?
