### ISSUE TITLE
info spots

### ISSUE THREAD

**Issue by HubertK42** [mpetroff/pannellum#827]
Hi,
is there a way to change the info spot images? I couldn't find any post on this topic.

Great work so far, thanks for this !

**Comment by Desmond-Campbell** [comment]
Set the type to "custom", set a "tooltip" property on the hotspot and assign a handler [function] to it. If you need the image to be dynamic then set a "tooltipArg" property to transport the dynamic data.

```javascript
hotspot.type = 'custom';
hotspot.tooltip = {createHandler};
hotspot.tooltipArg = {data};

createHandler (hotSpotDiv, data) => {
    hotSpotDiv.innerHTML = '<img src="' + data.imageSrc + '" />';
}
```

Look: https://pannellum.org/documentation/examples/custom-hot-spots/

**Comment by HubertK42** [comment]
Hi,
thanks for quick response. I've got the image displayed, but the tooltip is not shown anymore and I'm not quite sure, which class variable should contain the info text. And i have no idea how to format the new icon.
I use this function to add info spots:


```
function addInfoSpot(AllScenes, sLocation, dPitch, dYaw, sInfoText)
{
	var InfoSpot = 
					{
						"pitch": dPitch,
						"yaw": dYaw,
						"type": "info",
					//	"cssClass": "custom-Infospot",
						"text": sInfoText	
					};

	if (bCustomInfospot)
	{
		InfoSpot["type"] = "custom-hotspot";
		InfoSpot["createTooltipFunc"] = createInfoHandler;
                InfoSpot["createTooltipArgs"] = {imageSrc:"./img/Info.png", sInfo:sInfoText};
	}
		
	AllScenes.scenes[sLocation].hotSpots.push(InfoSpot);
}
```

and the handler function looks like this:

```
function createInfoHandler (hotSpotDiv, data)
{
	console.log(data);
	var span = document.createElement('span');
        span.innerHTML = data.sInfo;
        hotSpotDiv.appendChild(span);
	console.log(hotSpotDiv);

	var sPath = '<img src="' + data.imageSrc + '" />';
	hotSpotDiv.innerHTML = sPath;

	hotSpotDiv.width = "50px";
	hotSpotDiv.height= "50px" ;
	
	//console.log("createInfoHandler:" + sPath);
}
```

There is a lot of debug stuff in it, so please be forgiving...

Bye the way how can I add hoover functionallity?

Thanks in advance

**Comment by Desmond-Campbell** [comment]
My understanding is that once you render a "custom" type hotspot, the hotspot.text prop is no longer used. Since you already can create the hotspot dynamically through a function handler and custom CSS class and even define the entire HTML markup, it's then up to you to use the HTML and CSS class to define everything about the hotSpotDiv and its children, including the image, including the tooltip. By default, there's a way to style the tooltip.

CSS defined here:
https://gist.github.com/Desmond-Campbell/cb9bf1a6359b3d73b5566584ce6731d4#file-pannellum-custom-hostspot-html-L19

CSS enlisted like this:
https://gist.github.com/Desmond-Campbell/cb9bf1a6359b3d73b5566584ce6731d4#file-pannellum-custom-hostspot-html-L84

If you want to use the image and on top of that add an icon, you can either: add two hotspots, which I think is smarter; or you can modify the HTML to add an icon to the div, in addition to the image. You can always use the "onmouseover" attribute and set an event handler, or attach a listener.

As you'd figure, I'm just trying to help you without any knowledge of what you're trying to achieve, so I'm as vague with the solution as you are with the problem definition.

**Comment by HubertK42** [comment]
Hi Desmond,
thank you very much for your answer. My aim is just to replace the Hotspot icons and Infospot icons with my own for my walkthrough. The replacement of the Hotspot are running fine. But the Infospots are still troubling me.
I don't have any clue, how the internal class structure of the tool tip should look like, and witch element or class contains the info text and what is when activiated on hover. Sadly, the HotSpot example didn't gave me more insight. But I tried to implement them. 

Currently in my code the old info sprite is shown on hover, but not the text...
Any help would be great ;)

This is my current creation and handler function
```
/**********************************************
 * add a new info spot to given scene into  to our walkthrough 
 * 
 * AllScenes: holds all scenes of our walkthrough
 * sLocation: name of location to add a new hotspot
 * dPitch: pitch coordinate of hotspot
 * dYaw: yaw coordinate of hotspot
 * sInfoText: text to be displayed for the hotspot
 * 
 * warning: "hotSpots": [] must already be set in the scene field
**********************************************/
function addInfoSpot(AllScenes, sLocation, dPitch, dYaw, sInfoText)
{
	var InfoSpot = 
					{
						"pitch": dPitch,
						"yaw": dYaw,
						"type": "info",
					//	"cssClass": "custom-Infospot",
						"text": sInfoText	
					};

	if (bCustomInfospot)
	{
		InfoSpot["type"] = "custom-hotspot";
		InfoSpot["createTooltipFunc"] = createInfoHandler;
		InfoSpot["createTooltipArgs"] = {imageSrc:"./img/Info.png", sInfo:sInfoText};
	}
		
	AllScenes.scenes[sLocation].hotSpots.push(InfoSpot);
}

/**********************************************
 * Handler for creating custom info hotspots
 * param: hotSpotDiv div element of hot spot
 * parm: data data object transfered from the info hot spot containing {imageSrc, sInfo}
 * */
function createInfoHandler (hotSpotDiv, data)
{
    hotSpotDiv.classList.add('custom-tooltip');
    var span = document.createElement('span');
    span.innerHTML = data.sInfo;
    hotSpotDiv.appendChild(span);
    span.style.width = span.scrollWidth - 20 + 'px';
    span.style.marginLeft = -(span.scrollWidth - hotSpotDiv.offsetWidth) / 2 + 'px';
    span.style.marginTop = -span.scrollHeight - 12 + 'px';

    var sPath = '<img  style = \"width:50px;\" src=' + data.imageSrc + ' />';
   hotSpotDiv.innerHTML = sPath;
}

```
and the corresponding css lines:

```
.div.custom-tooltip span 
{
  visibility: hidden;
  position: absolute;
  border-radius: 3px;
  background-color: #fff;
  color: #000;
  text-align: center;
  max-width: 200px;
  padding: 5px 10px;
  margin-left: -220px;
  cursor: default;
}

.div.custom-tooltip:hover span
{
  visibility: visible;
}

.div.custom-tooltip:hover span:after 
{
/*  content: '';*/
  position: absolute;
  width: 0;
  height: 0;
  border-width: 10px;
  border-style: solid;
  border-color: #fff transparent transparent transparent;
  bottom: -20px;
  left: -10px;
  margin: 0 50%;
}
```

**Comment by Desmond-Campbell** [comment]
You're welcome. The terms you use confused me a bit. Unless I missed part of the API docs, I refer to everything as "hotspot". In my head, your "infospot" would be a hotspot of type "info", the default. If I understand you correctly and you're just trying to find the internal structure of the HTML/CSS, then it's not a Pannellum issue. You can hunt down the markup and class names by running the example and inspecting the DOM elements with tools like Chrome Developer Tools. That's even easier than looking at the CSS loaded in the library, because visually you'd know right away what is where. Have you tried that, since your primary concern is HTML/CSS?

**Comment by HubertK42** [comment]
mhh.. ok I was confused when looking at the original code while inspecting the DOM elements ... my thinking is just  to complicated... Anyway, thanks for all the hints, that help a lot. Fore those who have the same problems figuring everything out, I'd like to share my resolution (which is mostly a reflection of the above comments). It will look like the original info spots from mpetroff:

I use a simple function to add a info hot spot to a given scene:

```
/**********************************************
 * add a new info spot to given scene into  to our walkthrough 
 * 
 * AllScenes: holds all scenes of our walkthrough
 * sLocation: name of location to add a new hotspot within
 * dPitch: pitch coordinate of hotspot
 * dYaw: yaw coordinate of hotspot
 * sInfoText: text to be displayed for the hotspot
 * 
 * warning: "hotSpots": [] must already be set in the scene field
**********************************************/

function addInfoSpot(AllScenes, sLocation, dPitch, dYaw, sInfoText)
{
	var InfoSpot = 
				{
				    "pitch": dPitch,
				     "yaw": dYaw,
				     "type": "custom-hotspot",
				     "text": sInfoText,	
                                     "createTooltipFunc" : createInfoHandler,
		                     "createTooltipArgs" : {sInfo:sInfoText};
	                        }
		
	AllScenes.scenes[sLocation].hotSpots.push(InfoSpot);
}
```
Then use the above mentioned creation-function: 'createInfoHandle':
```
/**********************************************
 * Handler for creating custom info hotspots
 * param: hotSpotDiv div element of info hot spot
 * param: data object from createTooltipArgs: {sInfo} the info text to be displayed
 * 
 */
function createInfoHandler (hotSpotDiv, data)
{
    hotSpotDiv.classList.add('Custom-Infospot');
    var span = document.createElement('span'); //--- span element to display the info text
    span.innerHTML = data.sInfo;
    hotSpotDiv.appendChild(span);

    //--- nice placement of the info text
    span.style.width = span.scrollWidth - 20 + 'px';
    span.style.marginLeft = -(span.scrollWidth - hotSpotDiv.offsetWidth) / 2 + 'px';
    span.style.marginTop = -span.scrollHeight - 12 + 'px';
}
```

The rest are some line css code:

```
/*-----------------------------------------------------*/
/* custom info spot */
.Custom-Infospot
{
  height: 50px ;
  width: 50px;
  background-repeat: no-repeat; /* Do not repeat the image */
  background-size: cover;
  
  background-image: url('../img/Info.png');
}

/* custom info spot : hover*/
.Custom-Infospot:hover
{
  height: 50px ;
  width: 50px;
  background-repeat: no-repeat; /* Do not repeat the image */
  background-size: cover;
 
 background-image: url('../img/Info_Hover.png');
}

/* custom info spot text area*/
.Custom-Infospot span
{
  content:'';
  visibility: hidden;
  position: absolute;
  border-radius: 3px;
  text-align: center;
  max-width: 200px;
  padding: 5px 10px;
  margin-left: -220px;
  cursor: default;
  color: #fff;
  background-color: rgba(0,0,0,0.7);
}

/* switch info hotspot visible on hover */
.Custom-Infospot:hover span
{
   visibility: visible;
}
```

that's all.  If anybody has any questions with problems this, just ask. I will be happy to help you.
