### ISSUE TITLE
Panorama over panorama

### ISSUE THREAD

**Issue by martinlombana** [mpetroff/pannellum#831]
I need to create a sandwidch between two panoramas: One that is transparent, with several things drawn in it, and the main one, behind it. The idea is that both should move at the same time, and, because I am going to draw things dinamically in the top one, I can not really merge them together.

What would be the leanest approach? Two panoramas, one on top of the other? One of them with all the events removed, and move it dynamically according to changes in the main one? Or is there another solution?

Thanks.

**Comment by priyanka931** [comment]
Hi @martinlombana, I intend to draw some shapes on the panorama. But while drawing the shapes, the panorama shouldn't move and once the shapes are drawn, I want the shapes to move along with the panorama as if the panorama image itself has some shapes on it. 
Do you have some idea to implement it.
