### ISSUE TITLE
Dragging an image onto the child element of a hotspot

### ISSUE THREAD

**Issue by mikhail7275** [mpetroff/pannellum#833]
Hi everybody!
Tell me how best to drag the picture from the outside of the container onto the child element (for example, div width: 50px height: 50px) of a hot spot?
Sorry for my bad English.

**Comment by mpetroff** [comment]
Unfortunately, I'm not really sure what you're asking.

**Comment by mikhail7275** [comment]
Thanks a lot. I figured it out myself)
