### ISSUE TITLE
Display HTML hotspot element in the top left corner of the panorama

### ISSUE THREAD

**Issue by mikhail7275** [mpetroff/pannellum#838]
Good afternoon! Created some hotspots with span elements with a frame. When viewing a panorama, a frame is displayed in the upper left corner as a span element of a hot spot. Is it possible to remove it somehow?
Sorry for my bad English

**Comment by mpetroff** [comment]
As with the last issue you opened, I'm not really sure what you're asking. If possible, please provide an example, screenshots, etc.
