### ISSUE TITLE
Change position of hotspot?

### ISSUE THREAD

**Issue by jeffsure** [mpetroff/pannellum#839]
New user here. I created an info hotspot and inserted the text, although the new text is much longer than the samples. I figured out how to reduce the font size (in the css file) but now the hotspot is positioned out of the frame. I tried to fix it within the css file, but without success. I see that there's an inline style for position assigned to the span, but I have no idea where those numbers are coming from or how to change them. I'm not a Javascript person, so I'm asking for help. I can provide a screen shot of the issue, but can't provide a link (it's on a protected server behind our firewall, for in-house testing only.) Thanks!

**Comment by mpetroff** [comment]
I'm not sure what you changed as far as CSS goes, but changing the tooltip font size should not affect the hot spot placement. Setting `div.pnlm-tooltip span {font-size: 10pt;}` produces the following:

![Screenshot from 2020-02-28 20-03-23](https://user-images.githubusercontent.com/1450212/75597782-818e3a00-5a65-11ea-8f8a-b2381af58c3c.png)

The numbers are calculated in the script. See the [custom hot spots example](https://pannellum.org/documentation/examples/custom-hot-spots/) for more details on customizing the tooltip appearance or to see where the number come from (the calculation in the example is the same as what's used by default).

**Comment by jeffsure** [comment]
To be honest, I'm not sure what I changed either, but I started with a clean copy of the css file and followed your instructions, and it worked. I guess I didn't realize I needed to add the font-size declaration to div.pnlm-tooltip span. Thanks for your help!
