### ISSUE TITLE
Error autoload

### ISSUE THREAD

**Issue by eard17** [mpetroff/pannellum#841]
Me podrías colaborar con este error.

https://drive.google.com/file/d/1F0UX_g-mDlfqX3ocBqjpMebGlwVLgPky/view?usp=sharing

![Captura de pantalla de 2020-03-09 10-50-12](https://user-images.githubusercontent.com/14313517/76232330-8f298980-61f4-11ea-9fc6-9fc4119540e6.png)

**Comment by mpetroff** [comment]
This issue tracker is in English. While I appreciate that you may not be fluent in English, please make an attempt to write in English, even if it's via something like Google Translate.

That being said, you have not provided any useful information about your issue. I have no idea what you're trying to show with your video, and a screenshot of an error message is not particularly informative without corresponding code.

Please provide a description of your issue and at least a code snippet of what triggers it; while a minimum working example would be ideal, a link to a live example could also work.
