### ISSUE TITLE
Unable to disable pinch zoom

### ISSUE THREAD

**Issue by odai-alali** [mpetroff/pannellum#842]
Thanks for the really good performance for a panorama on the web. 👍 

Please check the reproduction on jsfiddle. I am not able to disable zoom entirely. still able to zoom using pinch on touch screen.

http://jsfiddle.net/ahevbct7/1/

> BTW: it seems that the configuration option `doubleClickZoom` is not documented.

**Comment by odai-alali** [comment]
As a work around I used `setHfovBounds([value, value])`.

**Comment by mpetroff** [comment]
Yes, setting `minHfov = maxHfov = hfov` in the configuration or via the `setHfovBounds` function is the appropriate way to completely disable zoom.

I just documented the `doubleClickZoom` parameter in becd09681958bc268cc96816910f672bc111f3fe. Thanks for pointing out that is was missing.
