### ISSUE TITLE
how to upload (link) panorama on leaflet map 

### ISSUE THREAD

**Issue by sachinrke** [mpetroff/pannellum#843]
Hello sir,
i want to link leaflet map and panorama (pannellum) like google street view. when we move up and down the marker position should be update and new panorama on that position will be displayed.
please help me to do that.
i shall be grateful to you
Thank you.

**Comment by mpetroff** [comment]
You can add a listener for the `scenechange` API event to see when the scene changes and use those events to update your map. Conversely, you can use the `loadScene` API method to change the panorama when you click on a different map marker.

**Comment by valeriodeluca** [comment]
@sachinrke see here:
https://john-davies.github.io/
