### ISSUE TITLE
get hotspot id when click the hotspot.

### ISSUE THREAD

**Issue by 52cwalk** [mpetroff/pannellum#849]
i add some hotspots with id in my scene , i need know which hotspot is selected when the hotspot clicked . 
```
 {
                "id":"Shoerack",
                "pitch": -42.3,
                "yaw": -142.8,
                "type": "info"
 },
```

when i add the clickHandlerFunc function , but can't get the id . we need to do some different work when click(selected) different hotspots . 

```
 this.panoramaScene.hotSpots[i].clickHandlerFunc = function(obj)
 {
      console.log(obj);//the obj have not contain the id attr.
 }
```

**Comment by mpetroff** [comment]
As is clearly stated in the API documentation, the click event object and the value of `clickHandlerArgs` are passed as arguments to the `clickHandlerFunc` function. The `obj` variable in your code snippet is the browser's click event object, so of course it does not have an ID attribute. You need to provide the ID as the `clickHandlerArgs` parameter. Something like this should work:

```javascript
this.panoramaScene.hotSpots[i].clickHandlerArgs = this.panoramaScene.hotSpots[i].id;
this.panoramaScene.hotSpots[i].clickHandlerFunc = function(clickEvent, id) {
      console.log(id); // Prints the hot spot ID to the console
}
```
