### ISSUE TITLE
Get target hotspot id when click

### ISSUE THREAD

**Issue by 52cwalk** [mpetroff/pannellum#850]
i add some hotspots with id in my scene , i need know which hotspot is selected when the hotspot clicked . 
```
 {
                "id":"Shoerack",
                "pitch": -42.3,
                "yaw": -142.8,
                "type": "info"
 },
```

when i add the clickHandlerFunc function , but can't get the id . we need to do some different work when click(selected) different hotspots . 

```
 this.panoramaScene.hotSpots[i].clickHandlerFunc = function(obj)
 {
      console.log(obj);//the obj have not contain the id attr.
 }
```

**Comment by mpetroff** [comment]
Duplicate of #849.
