### ISSUE TITLE
avoidShowingBackground option set by "generate.py" result in black viewer

### ISSUE THREAD

**Issue by etieng** [mpetroff/pannellum#851]
**Hello**
First, I love Pannellum, thank you so much !

I just uploaded one of my multires panorama generated by _generate.py_ wich is a full equirectangular panorama (mean 360x180). It resulted in a black viewer, controls are shown but no tiles.
After some research, removing the **avoidShowingBackground** option turn the panorama back on.
Nothing is reported in Firefox's console.

**Step to reproduce :**
In _config.json_ of a full multires panorama add the option **avoidShowingBackground**
`"avoidShowingBackground": true,`

**More info :**
Using this method to display the panorama : `domain.tld/pa/pannellum.htm?config=multires/config.json`
Using pannellum 2.5.6
Confirmed on two different panoramas.

**What may be expected :**
Pannellum may handle the **avoidShowingBackground** option if the multires panorama is full equirectangular or _generate.py_ may avoid putting the option in the config.json file generated.

Let me know if you need link to the panoramas and config files.
Thx

**Comment by mpetroff** [comment]
The viewer issue was not `multires`-specific. It had to do with enabling `avoidShowingBackground` without defining `minPitch` and `maxPitch`, which resulted in a `NaN` value in the field of view calculation. I added a `NaN` check to fix the rendering issue in 28144ad30191575c6e1269f9c2bebb144738b7a4 and also added a check such that the `generate.py` script will no longer output configurations with the `avoidShowingBackground` parameter if the panorama covers the full sphere.
