### ISSUE TITLE
I want to set vertical fov.

### ISSUE THREAD

**Issue by pratikbendale** [mpetroff/pannellum#855]
Hi @mpetroff ,
I want to set vertical fov to the viewer when we load viewer in mobile or on the taller screen aspect ratio(1:1) 
How I can achieve that.

**Comment by mihailangelov** [comment]
Hi,
I had a similar problem on a mobile device, but I change the HFOV. Here is my solution:

// Defining function for the HFOV
function setSceneHfov(){
	// get current scene
	let curScene = viewer.getConfig().scenes[viewer.getScene()]
	let w = document.documentElement.clientWidth;
	let h = document.documentElement.clientHeight;

	if(curScene){
		// lower HFOV by half when device is in vertical position
		if(w < h){
			viewer.lookAt(undefined, undefined, curScene.hfov/2, false);
		}else{
			viewer.lookAt(undefined, undefined, curScene.hfov, false); 
		}
	}
}

// Attach event listener function to window's resize event and when a scene is loaded
window.addEventListener("resize", setSceneHfov);
viewer.on("load", setSceneHfov);

// Calling the function for the first time
setSceneHfov();

**Comment by pratikbendale** [comment]
Hi @mihailangelov ,
That works for me 
Thank you very much

**Comment by mpetroff** [comment]
Using the `viewer.setHfov` method is preferred to using `viewer.lookAt` with `undefined` for `pitch` and `yaw`.

You can calculate horizontal FOV from vertical FOV and the aspect ratio of the viewer, e.g., `var hfov = 2 * Math.atan(Math.tan(vfov * 0.5) * viewer.getCanvas().clientWidth / viewer.getCanvas().clientHeight);`.

**Comment by pratikbendale** [comment]
Thanks @mpetroff
