### ISSUE TITLE
Problem with dynamic=True

### ISSUE THREAD

**Issue by martinlombana** [mpetroff/pannellum#856]
I have this problem: When I try to pass a canvas and set a new scene and set the update=true and then false, I just get: "Unknown error" from pannellu and nothing else. No debug no nothing. 

I need to pass a hidden canvas in order to update it from time to time. I had it working in the past, but now it is not working at all and I've tried everything. But I can't think of anything else that might be wrong. If I just load a scene with an image, dynamic=false, and pass the image url, it works. 

I don't understand the problem.

Any help is welcome.

```
@Component({
	selector: 'app-pixelation-editor',
	template: `

        <div id="pixelationPanorama" #pixelationPanorama></div>

	`,

	styles: [`
        
        .hidden-canvas {
            display: none;
        }

	`],
})
export class PixelationEditorComponent implements OnInit, OnDestroy, AfterViewInit {
	public viewer: any;
	@ViewChild('pixelationPanorama', {read: ElementRef, static: true}) container: ElementRef;
	hidden_canvas;
	panorama_image;
	body;

	constructor(public events: Events) {
	}

	ngAfterViewInit(): void {
		this.body = document.getElementsByTagName("body")[0];

		let config: any = {};
		config.scenes = {}
		config.type = 'equirectangular';
		config.dynamic = true;
		config.sceneFadeDuration = 800;
		config.disableKeyboardCtrl = false;
		config.mouseZoom = true;
		config.showControls = false;
		config.draggable = true;
		config.strings = {
			'loadButtonLabel': 'Haz click para <br>cargar<br> el panorama.',
			'loadingLabel': 'Cargando...',
			'bylineLabel': 'by %s',
			'noPanoramaError': 'Panorama no encontrado.',
			'fileAccessError': 'El archivo %s no puede ser accedido.',
			'malformedURLError': 'La url del panorama no está bien formada.',
			'iOS8WebGLError': 'Debido a OS8 y su implementacion de WebGL, sólo se pueden usar JPGs codificados de forma progresiva.',
			'genericWebGLError': 'Tu navegador no tiene las características necesarias para ver este panorama.',
			'textureSizeError': 'Este panorama es demasiado grande! Tiene %spx de ancho, pero tu dispositivo sólo soporta %spx.',
			'unknownError': 'Error desconocido.'
		}
		this.viewer = pannellum.viewer('pixelationPanorama', config);
		this.loadPanoramaImage("http://127.0.0.1:8000/uploads/images/tours/scenes/scene_171.jpg");
		setTimeout(() => {
		}, 1000);
	}

	loadPanoramaImage(src: string) {

		this.panorama_image = new Image();

		this.panorama_image.onload = () => {
			this.hidden_canvas = document.createElement('canvas');
			this.hidden_canvas.id = "basecanvas";
			this.hidden_canvas.width = this.panorama_image.width;
			this.hidden_canvas.height = this.panorama_image.height;
			this.body.appendChild(this.hidden_canvas);
			let c: any = document.getElementById("basecanvas");
			let ctx = c.getContext("2d");
			ctx.drawImage(this.panorama_image, 0, 0);
			c.classList.add('hidden-canvas');

			this.viewer.addScene('scene1', {
				'type': 'equirectangular',
				'panorama': this.hidden_canvas
			});

			setTimeout(() => {
				this.viewer.loadScene('scene1', 0, 190);
				this.viewer.setUpdate(true);
				this.viewer.setUpdate(false);
				this.initContainerListeners();
			}, 500)
		}
		this.panorama_image.src = src;
	}

(...)
```

**Comment by mpetroff** [comment]
The code you provided isn't a complete example. If I try to replicate it, I get this:
```html
<!DOCTYPE HTML>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Canvas test</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/pannellum@2.5.6/build/pannellum.css"/>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/pannellum@2.5.6/build/pannellum.js"></script>
    <style>
    #panorama {
        width: 600px;
        height: 400px;
    }
    </style>
</head>
<body>

<div id="panorama"></div>
<script>
var viewer = pannellum.viewer('panorama', {
    'dynamic': true,
    'scenes': {}
});

var image = new Image();
image.onload = function() {
    var canvas = document.createElement('canvas');
    canvas.width = image.width;
    canvas.height = image.height;
    var ctx = canvas.getContext("2d");
    ctx.drawImage(image, 0, 0);

    viewer.addScene('scene1', {
        'type': 'equirectangular',
        'panorama': canvas
    });
    viewer.loadScene('scene1');
    viewer.setUpdate(true);
    viewer.setUpdate(false);
};
image.src = 'examplepano.jpg';
</script>

</body>
</html>
```

As this code works without any issues, I'm not why your code does not.

**Comment by martinlombana** [comment]
I had to modify your lib in order to see the bug in the console.log, because UnknownError was not displaying anything in the console:
![image](https://user-images.githubusercontent.com/18351919/81237934-1763b980-9001-11ea-8755-035b33799358.png)

And then I saw:

![image](https://user-images.githubusercontent.com/18351919/81237966-29ddf300-9001-11ea-8845-984ab34f14b9.png)

I will investigate further. Must be related to cross origin? But it's weid, because the canvas is in, indeed loaded in the screen (I can see the image) so it is not a problem with the image src per sé, rather with the canvas itself. 

Do you have any idea on why this is happening or how to prevent it?

**Comment by mpetroff** [comment]
Yes, that's a cross-origin issue. Once you perform any operation on a `<canvas>` that's based on data loaded from a different origin without CORS properly configured, you can't read from the `<canvas>` using JavaScript anymore since it's tainted with the cross origin data (but it's still displayed). You need to set the CORS attribute on the image before you set the `src`, e.g., `this.panorama_image.setAttribute('crossOrigin', 'anonymous')` for your code snippet.

Pannellum doesn't handle the error in the unknown error case, so there's no need to modify it to see the error in the console. The fact that you didn't see the error means that your own code was handling it in a way that hid it.

**Comment by martinlombana** [comment]
This can be closed. It was the crossOrigin. I don't know what is making the console not to display it though, but it's not related to pannellum. Thanks!
