### ISSUE TITLE
requestAnimationFrame not capitalized causing compile errors

### ISSUE THREAD

**Issue by seanggani** [mpetroff/pannellum#858]
build/index.js has a line require(./requestAnimationFrame) but the filename is RequestAnimationFrame which is causing compile errors. Capitalizing it allows the project to build fine.

**Comment by mpetroff** [comment]
There's neither a `index.js` file nor a `requestAnimationFrame` file, so I have no idea what you're referring to. The build / minification is done using a Python script.

**Comment by seanggani** [comment]
I'm using yarn to add panellum into my project and it creates a build folder like this. In the index.js it says require("./requestAnimationFrame"), but as you see here the file is named RequestAnimationFrame.js. Is there a new version I need be adding? 
![Screen Shot 2020-04-29 at 1 22 39 PM](https://user-images.githubusercontent.com/60366518/80626564-a2025280-8a1c-11ea-93dc-12d7c0ed041a.png)

**Comment by strarsis** [comment]
@seanggani: Are you sure you still need a polyfill for `RequestAnimationFrame` feature?
[All modern browsers support it now](https://caniuse.com/#search=requestanimationframe).

**Comment by mpetroff** [comment]
@seanggani Where did you install this from (and what version)? Pannellum hasn't included a `requestAnimationFrame` polyfill since version 2.5, and it has never had an `index.js` file nor a `libpannellum.js` file in the `build` directory.

**Comment by seanggani** [comment]
I'm using the version in the npm registry https://www.npmjs.com/package/pannellum. What is the best way to do this?

**Comment by mpetroff** [comment]
The files you're referring to aren't in the copy on npm. There are three files in the [`build` directory](https://unpkg.com/browse/pannellum@2.5.6/build/), `pannellum.js`, `pannellum.css`, and `pannellum.htm`.
