### ISSUE TITLE
Play sound archive

### ISSUE THREAD

**Issue by juchijaw** [mpetroff/pannellum#859]
Is there a way to play an audio file, for example mp3, when opening a scene?

**Comment by mpetroff** [comment]
Sure. You can use the API's `on` method to add a listener for `scenechange` events and use that to trigger custom code that plays an audio file.

**Comment by juchijaw** [comment]
Thank you! ... A client who owns a hotel asked me if I could add a voice that describes the rooms when the visitor enters each of them.
