### ISSUE TITLE
Flat-like image

### ISSUE THREAD

**Issue by redbaron76** [mpetroff/pannellum#860]
Hello, is there a way to play with the options in order to obtain the pan image similar to a flat one inside the canvas? Thanks.

**Comment by redbaron76** [comment]
No, I'm simply asking if, playing with params like hof, minHof, maxHof is it possible to obtain and display like a flattish image. My goal is to obtain a single image viewer able to display both flat and pan images, in order to keep HotSpot functionality over it.

Hope it's clearer now.
Thanks

**Comment by mpetroff** [comment]
In the limit of an infinitely small field of view, spherical geometry is equivalent to planar geometry. In that sense, it's possible, since something like a ~1deg field of view is close enough to flat. However, Pannellum was not designed for that, and I can't recommend using it for that.
