### ISSUE TITLE
Is there a way to change a scene image and reload it?

### ISSUE THREAD

**Issue by martinlombana** [mpetroff/pannellum#864]
Hi, 

Is there a native way (without using dynamic=True), to change a scene config, changing it's image, and instruct panellum to reload that scene with the new image url? I need it because I am pixel editing some images with python given different factors and user input and I need to reload the scene with the new image that the user is in, at the moment. If the url must stay the same, it could work, but I wanted to change the url to append a dummy urlparams to force the cache reload. 

Thanks,

**Comment by mpetroff** [comment]
You can use `viewer.addScene('currentSceneId', {new config});` followed by `viewer.loadScene('currentSceneId');`. Using `addScene` with an existing scene ID will overwrite the previous configuration, and calling `loadScene` will then reload the scene with the new configuration.

**Comment by martinlombana** [comment]
Ahá.
Simple and direct. I didn't know this was the default behaviour. Thanks a lot, I will try it out!
