### ISSUE TITLE
Record a video

### ISSUE THREAD

**Issue by truszko1** [mpetroff/pannellum#865]
I know this isn't strictly pannellum's responsibility, but what I want to achieve is based on pannellum. Do you have any suggestions on how I could go about recording a video file of the pannellum viewer? If I click around the panorama, moving it around, how would I project this maybe onto a canvas and record it? I tried to google some approaches, but I can't wrap my mind around how this would be done. Thanks!

**Comment by mpetroff** [comment]
I'm going to assume you want to do with programmatically (otherwise, a screen recorder would be the easiest thing to do). To record the view, you would need to call `var renderer = viewer.getRenderer()` and then `var img = renderer.render(viewer.getPitch(), viewer.getYaw(), viewer.getHfov(), {'returnImage': true})`. However, this is too slow to get a reasonable video frame rate in real-time but could work if you just wanted to animate a particular set of movements. I also have no idea how you'd convert a set of frames into a video in a browser, short of compiling FFmpeg to WebAssembly.

**Comment by mpetroff** [comment]
It looks like there might be a better way to do this, by using the `<canvas>` element's [`captureStream()`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/captureStream) method in conjunction with the [`MediaStream` Recording API](https://developer.mozilla.org/en-US/docs/Web/API/MediaStream_Recording_API). You can access Pannellum's `<canvas>` with `viewer.getRenderer().getCanvas()`.

**Comment by truszko1** [comment]
Thank you so much! I will try it all out.

**Comment by truszko1** [comment]
I was able to figure it out!

1. I took the canvas from Pannellum's viewer using your API, and then took its [MediaStreamTrack](https://developer.mozilla.org/en-US/docs/Web/API/MediaStreamTrack).
2. I then took the browser's audio MediaStreamTrack using regular WebRTC specs and APIs.
3. I then combined both tracks into a single WebRTC MediaStream.
4. The last element was taking the [RecordRTC](https://github.com/muaz-khan/RecordRTC) library that lets me record the combined stream and output it as a blob, which then I can take and do whatever.

Thank you, @mpetroff!

**Comment by mpetroff** [comment]
Great! Glad to hear it worked.

**Comment by nyngwang** [comment]
@truszko1: do you mean that pannellum can be used on streaming, i.g. the audience can change the viewpoint during the streaming?

**Comment by pandysong** [comment]
> I was able to figure it out!
> 
> 1. I took the canvas from Pannellum's viewer using your API, and then took its [MediaStreamTrack](https://developer.mozilla.org/en-US/docs/Web/API/MediaStreamTrack).
> 2. I then took the browser's audio MediaStreamTrack using regular WebRTC specs and APIs.
> 3. I then combined both tracks into a single WebRTC MediaStream.
> 4. The last element was taking the [RecordRTC](https://github.com/muaz-khan/RecordRTC) library that lets me record the combined stream and output it as a blob, which then I can take and do whatever.
> 
> Thank you, @mpetroff!

Is it possible to have repo to demo what you have done? Would it be possible to have an api for remote to steer and then provide a real time stream to remote.
