### ISSUE TITLE
open info hotspot in overlay

### ISSUE THREAD

**Issue by valeriodeluca** [mpetroff/pannellum#871]
Wanting it's possible by clicking on info hotspot and then open an overlay div? I mean to insert more text and image inside info.
Like this:
https://www.martinafrau.it/vt/museolanciani/
With overlay I mean this:
https://www.w3schools.com/howto/howto_css_overlay.asp
Tks

**Comment by mpetroff** [comment]
You can execute arbitrary JavaScript code on click using the [`clickHandlerFunc` and `clickHandlerArgs`](https://github.com/mpetroff/pannellum/blob/master/doc/json-config-parameters.md#clickhandlerfunc-function-and-clickhandlerargs-object) hot spot configuration parameters. You could use this to execute a function that opens an overlay.
