### ISSUE TITLE
Uncaught ReferenceError: DeviceMotionEvent is not defined

### ISSUE THREAD

**Issue by DamienSM** [mpetroff/pannellum#872]
When orientationOnByDefault is on, but the browser doesn't support device motion, pannellum throws an exception and movement breaks.

`"function" === typeof DeviceMotionEvent.requestPermission ? DeviceOrientationEvent.requestPermission().then(function(a) {...`

Checking for DeviceMotionEvent fixes the problem:

`DeviceMotionEvent && "function" === typeof DeviceMotionEvent.requestPermission ? DeviceOrientationEvent.requestPermission().then(function(a) {...`

**Comment by mpetroff** [comment]
This is a duplicate of #846, which has already been fixed (although I just fixed a typo in the original fix).
