### ISSUE TITLE
two or more hotpot in the scene

### ISSUE THREAD

**Issue by AbedSHP** [mpetroff/pannellum#873]
hello
In the example below,  we can add only one hotspot in the scene!
https://pannellum.org/documentation/examples/tour/
Is there a way we added double or more hotpot in the scene?

**Comment by JuhaSydanmaa** [comment]
`hotSpots` is an array, so it can contain more than 1 hotspot object
```
 "hotSpots": [
                {
                    "pitch": -2.1,
                    "yaw": 132.9,
                    "type": "scene",
                    "text": "1st hotspot",
                    "sceneId": "house"
                },
                {
                    "pitch": 5.123,
                    "yaw": 123.45,
                    "type": "scene",
                    "text": "2nd hotspot",
                    "sceneId": "something-else"
                },
]
```
or, you can add hotspot by using viewer's `.addHotspot` method

**Comment by mpetroff** [comment]
The [hot spots example](https://pannellum.org/documentation/examples/hot-spots/) shows multiple hot spots.

**Comment by AbedSHP** [comment]
thank you so much.
