### ISSUE TITLE
google chrome browser (android).

### ISSUE THREAD

**Issue by AbedSHP** [mpetroff/pannellum#874]
hello
I use type: 'cubemap', in the main scene. but I have a problem with google chrome (android).
"Your browser does not have the necessary WebGL support to display this panorama"
Another point there is no problem with Firefox (android version).
what is the problem?

**Comment by mpetroff** [comment]
Without more detailed information, such as the dimensions of the cube map images, the version of Chrome, the device it's running on, and the messages printed to the browser's developer console, I can't say.

**Comment by mpetroff** [comment]
Closing due to lack of response.
