### ISSUE TITLE
Toggle draggable/keyboard via API?

### ISSUE THREAD

**Issue by bengrabau** [mpetroff/pannellum#877]
I am hoping to enable/disable draggable and keyboard event via the API, while the scene is active.

I seem to be able to set the scene draggable property to false, but the event handlers have already been bound to the viewer. What's the preferred method for disabling panning the scene while it's currently loaded?

**Comment by mpetroff** [comment]
Your observation about the event handlers is correct; they're not designed to be toggled.

However, you can set the pitch and yaw limits to the current pitch and yaw via the API, which will also prevent panning.
