### ISSUE TITLE
Unable to get current zoom level of pano scene

### ISSUE THREAD

**Issue by jatin33** [mpetroff/pannellum#882]
Hello,

It looks like currently there is no way to get the current zoom level of a given pano scene. Could you please suggest a workaround to get the zoomLevel from current instance of pano scene object?

Please reach out to me at jatin.panjwani@aspecscire.com for more clarification.

**Comment by mpetroff** [comment]
The `getHfov` API method returns the current horizontal field of view, i.e., the current zoom level.

**Comment by jatin33** [comment]
Also it appears that the api doesnt expose click event on the scene object currently, could you please suggest some way to emulate the click event on current scene object?
 As per the current docs https://github.com/mpetroff/pannellum/blob/master/doc/events.md , click event doesnt seem to be in the list. 
Do we refer to click event by some other alias like (mouseClick, mousePressed, etc...)?
Please point me in the right direction here.

**Comment by mpetroff** [comment]
There's no support for emulating click events, and I see no reason why there should be. The whole point of having an API is such that you don't need to emulate user actions.

If you want to listen to click events, not emulate them, you can just add an event listener to the viewer's container element, just like you'd add an event listener to any other `<div>`, e.g., if you created the viewer with `pannellum.viewer('panoelement', {...})`, you could add a `click` event listener with `document.getElementById('panoelement').addEventListener('click', yourEventListener, false)`. All events supported directly by Pannellum are listed in the documentation; I don't know what gave you the idea that other, non-documented events would be supported by random aliases.

**Comment by jatin33** [comment]
Hey @mpetroff , thanks for the help. You can close this issue.
