### ISSUE TITLE
Pannellum just stopped working

### ISSUE THREAD

**Issue by vertsyeux** [mpetroff/pannellum#887]
I have a simple "360 Tours" page on a client's Opencart website, using an iFrame on an info page. The page opens with an outside view, the visitor can then select other areas to view by clicking links below. The viewer code pannellum.htm and all the panoramic images are hosted on the client's server with the viewer displayed in an iFrame based on Pannellum's examples.

This was trivial to get working and has operated correctly for months but recently stopped working, displaying nothing where the panoramas once were. I tried Chrome, Firefox & Safari under OSX, Windows and an iPad without Joy. Strangely, I noted that my Chromebook still worked perfectly, so I updated the Chromebook and it too stopped working. Nothing at my end has changed. I updated to the latest pannellum.htm to no avail.

A JS function load360() forms a url and assigns this to the .src property of the iFrame located by id. Originally, the working code looked like this:

let url=...
let frame=document.getElementById("mf-360");
frame.src=url;
frame.contentWindow.location.reload(true);

Searching reveals that reload is not required and simply assigning a new url to the .src property should be enough to force a refresh of the iFrame. Removing the reload had no effect, and in fact having it there stops the viewer from ever displaying. Assigning a blank string to .src first then the required url like this..

let url=...
let frame=document.getElementById("mf-360");
frame.src='';
frame.src=url;

..actually seems to work, but only every second time load360 is called.

Does anyone have any idea what's going on?? I'm more of an electronics-design/embedded guy and any help here would be most appreciated..

The site is https://www.davidcoils.com - click '360 Tours' at the top.

**Comment by mpetroff** [comment]
If I revert back to your original function, it works fine for me in Firefox 77 and Chromium 83 on Linux, so I'm not sure why it stopped working for you.

You're setting the `src` attribute of the `<iframe>` to something of the form`pannellum.htm#panorama=...`, which only changes the URL's location hash, not the URL itself. Thus, the `<iframe>` isn't automatically reloaded. If you change the `#` to a `?`, you'll instead specify the configuration as query parameters, which change the URL, so the `<iframe>` should automatically reload when you change the `src` attribute. As query parameters are unnecessarily sent to the server, I generally recommend that people configure Pannellum using the location hash, but the viewer will use parameters set by either method (and using query parameters should fix your issue).

I suspect that setting the `src` to a blank string and then immediately to the URL triggers some sort of race condition in the browser, but that's pure speculation on my part. Dealing with the quirks of different browsers is one of the downsides of doing web development (but on the upside, you don't need to worry about releasing magic smoke).

**Comment by mpetroff** [comment]
Closing due to lack of response.
