### ISSUE TITLE
issue with multires generator on ubuntu

### ISSUE THREAD

**Issue by pavanhl** [mpetroff/pannellum#89]
Thanks for the great work.
I just started with pannellum. I am using generate.py to generate panaroma viewer, but i am getting below error. Can you please help me with this.

![screenshot from 2015-09-22 06 30 46](https://cloud.githubusercontent.com/assets/12949881/10009026/4689fb98-60f4-11e5-8cad-2ff08f35afbd.png)

**Comment by mpetroff** [comment]
You're trying to create cube faces with a text editor, `nano`, when you should be using Hugin's stitcher, `nona`. On Linux, you shouldn't need the `-n` flag anyway. Make sure you have Hugin installed and try running `python generate.py 1.jpg`.
