### ISSUE TITLE
Make "Click to load panorama" a <button> element for better accessibility

### ISSUE THREAD

**Issue by adamjohnson** [mpetroff/pannellum#890]
Right now the "Click to load panorama" button is a `<p>` tag:

```html
<div class="pnlm-load-button">
  <p>Click to <br>
    Load <br>
    Panorama
  </p>
</div>
```

Making this a `<button>` tag will make it keyboard focusable which is [critical for accessibility](https://accessibility.18f.gov/checklist/).

## Proposed markup/changes:

```html
<div class="pnlm-load-button">
  <button>Click to <br>
    Load <br>
    Panorama
  </button>
</div>
```

Completing this change is a huge win for keyboard users and will allow people to use and explore Pannellum images.

At a quick glance, looks like you could change [pannellum.js line 2098](https://github.com/mpetroff/pannellum/blob/master/src/js/pannellum.js#L2098). You'll have to style the button and move focus back to `.pnlm-container`.

___________________________________________________________________________________________________

🙏  Thanks for the awesome library! 👍

**Comment by mpetroff** [comment]
I fixed this in 9df0b8bd98557c6ff197c5339289e67585c285e9. This is something I've known about for a while but needed someone asking about it prioritize fixing it.

**Comment by adamjohnson** [comment]
This is fantastic, Matt. Thank you! I cloned this project and built the CSS & JS from source, then included those files in our project. Works great!

If you get some time to push out a release, I'm sure a lot of folks would be grateful. Thanks again.

**Comment by mpetroff** [comment]
Based on my current schedule, I don't think I'll have time to get a release out in the next couple months, but there should be one before the end of the year.
