### ISSUE TITLE
Using a sliding thumbnail to access multiple panorama images?

### ISSUE THREAD

**Issue by m1llipede** [mpetroff/pannellum#892]
Hi, I've been messing around with Pannellum for a bit and trying to integrate Slick Slider with Pannellum. 

I'm using Slick Slider to build a thumbnail slider at the bottom of the screen, and hoping to use Pannellum to showcase and control the 360 views. I can easily add many thumbnail images to this to make an endless slider, but can't seem to figure out how to call up different 360 images, I've tried about 50 methods and all failed. I'm sure I'm missing something here. Any help would be great. I'm just learning HTML/CSS/Javascript so definitely a noob, here. Thank you!
Brian

Current code:

```html
<!DOCTYPE HTML>
<html>
<head>
    <meta charset="utf-8">
    <meta charset="viewport" content="initial-scale=1.0, maximum-scale=1.0, user-scalable=1">
   	<link rel="stylesheet" type="text/css" href="slick.css">
	<link rel="stylesheet" type="text/css" href="fadestyle.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/pannellum@2.5.6/build/pannellum.css"/>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/pannellum@2.5.6/build/pannellum.js"></script>
    <style>
    #panorama {
        width: 1024px;
        height: 768px;
    }
    </style>
</head>
<body style="padding:0px; margin:0px; background-color:#2E99C0;font-family:Montserrat,'Montserrat'">

<div class="slider_wrap">
<div class="banner_slider">
	

<div id="panorama"></div>
<script>
pannellum.viewer('panorama', {
    "type": "equirectangular",
    "panorama": "3447_9012_170901.jpg",
    "autoLoad": true,
    "border": false,
    "autoRotate": 5,
    "northOffset": 0,
    "backgroundColor": ([0,0,0]),
    "compass": false
    }); 
</script>   

     

</div>		
</div>




<div class="thumbnail_slider_area">
	<div class="container">
			<div class="row thumbnail_slider">
				<div class="col">
					<img src="3447_9012_170901-thumb.jpeg" alt="">
				</div>
				<div class="col">
					<img src="3447_9022_170901-thumb.jpeg" alt="">
				</div>					
			</div>	
	</div>
</div>


<script type="text/javascript" src="jquery-3.3.1.slim.min.js"></script>
<script type="text/javascript" src="slick.js"></script>
<script type="text/javascript" src="custom.js"></script>

</body>
</html>
```

**Comment by mpetroff** [comment]
Are you trying to make it load a different panorama when you click on each slider entry? I'm going to assume this is the case and proceed accordingly.

First, you need to assign the Pannellum viewer to a variable so you can control it, e.g., replace `pannellum.viewer('panorama',` with `var viewer = pannellum.viewer('panorama',`. Next, you need to use a tour configuration for Pannellum (see the [tour example](https://pannellum.org/documentation/examples/tour/) for details); however, you don't need to add any hot spots. Finally, you need to add click event handlers to your thumbnails to change the panorama displayed using Pannellum's `loadScene` API method, e.g., you could change `<img src="...-thumb.jpeg" alt="">` to `<img src="...-thumb.jpeg" alt="description of thumbnail" onclick="viewer.loadScene('scenex')">`, where `scenex` would be the scene corresponding to the thumbnail.

**Comment by m1llipede** [comment]
Hi, thanks so much for the quick response. Yes, I am trying to load a new panorama everytime. I'm going to dig into this right away. I'll let you know how it goes.

**Comment by m1llipede** [comment]
Hi Matthew,

I believe I followed your instructions correctly but getting some odd results. I got the thumbnails working OK but only the default scene and one other scene are loading. The others are only the html text on screen. If I make the default panorama 9012, then I can only click on the thumbnails for 9012 or 9042. All of the others just show text. But I've tested each image/scene for the panorama by making each the default scene, which will load those. I'm wondering what I may be missing here? Here's a link to what I'm seeing: http://playoptix.com/360views/360view.html

Here's a link to a dropbox with the HTML, images used in this example and js/css files if that helps?
https://www.dropbox.com/sh/gllxn8u7ng6bydt/AACbk5IB0Hex1NwzKxW0MoCza?dl=0

Thanks for any help you can offer,
Brian

<!DOCTYPE HTML>
<html>
<head>
    <meta charset="utf-8">
    <meta charset="viewport" content="initial-scale=1.0, maximum-scale=1.0, user-scalable=1">
    <link rel="stylesheet" type="text/css" href="slick.css">
    <link rel="stylesheet" type="text/css" href="fadestyle.css">
    <link rel="stylesheet" href="pannellum.css"/>
    <script type="text/javascript" src="pannellum.js"></script>
    <style>
    #panorama {
        width: 1024px;
        height: 768px;
    }
    </style>
</head>
<body style="padding:0px; margin:0px; background-color:#2E99C0;">


<div class="slider_wrap">
	<div class="banner_slider">  
	<div id="panorama"></div>

<script>
var viewer = pannellum.viewer('panorama', {
    "default": {
        "firstScene": "9032",
        "type": "equirectangular",
   		"autoLoad": true,
  		"border": false,
  		"autoRotate": 4,
    	"backgroundColor": ([0,0,0]),
   		"compass": false
    },

    "scenes": {
        "9012": {
  			"panorama": "3447_9012_170901.jpeg"
        },
        
        "9032": {
  			"panorama": "3447_9032_170901.jpeg"
        },
        
        "9042": {
  			"panorama": "3447_9042_170901.jpeg"
        },

        "9102": {
  			"panorama": "3447_9102_170901.jpeg"
        },
        
        "9112": {
  			"panorama": "3447_9112_170901.jpeg"
        },
        
        "9122": {
  			"panorama": "3447_9122_170901.jpeg"
        },
        
        "9132": {
  			"panorama": "3447_9132_170901.jpeg"
        },

        "9142": {
  			"panorama": "3447_9142_170901.jpeg"
        }
    }
});
</script>

	</div>      
</div>




<div class="thumbnail_slider_area">
    <div class="container">
            <div class="row thumbnail_slider">
                <div class="col">
                    <img src="3447_9012_170901-thumb.jpeg" onclick="viewer.loadScene('9012)">
                </div>
                
                <div class="col">
                    <img src="3447_9032_170901-thumb.jpeg" onclick="viewer.loadScene('9032')">
                </div>  
                     
                <div class="col">
                    <img src="3447_9042_170901-thumb.jpeg" onclick="viewer.loadScene('9042')">
                </div>
                
                <div class="col">
                    <img src="3447_9102_170901-thumb.jpeg" onclick="viewer.loadScene('9102')">
                </div> 
                    
                <div class="col">
                    <img src="3447_9112_170901-thumb.jpeg" onclick="viewer.loadScene('9112')">
                </div>
                
                <div class="col">
                    <img src="3447_9122_170901-thumb.jpeg" onclick="viewer.loadScene('9122')">
                </div>   
                   
                <div class="col">
                    <img src="3447_9132_170901-thumb.jpeg" onclick="viewer.loadScene('9132')">
                </div> 
                  
                <div class="col">
                    <img src="3447_9142_170901-thumb.jpeg" onclick="viewer.loadScene('9142')">
                </div>   
                    
            </div>  
    </div>
</div>


<script type="text/javascript" src="jquery-3.3.1.slim.min.js"></script>
<script type="text/javascript" src="slick.js"></script>
<script type="text/javascript" src="custom.js"></script>

</body>
</html>

**Comment by mpetroff** [comment]
You need to get rid of the "slider syncing" code, as that's what's causing the issue. The Pannellum viewer shouldn't be a "slider." I haven't tested it, but replacing the contents of your `custom.js` file with
```javascript
jQuery(document).ready(function($) {
	$('.thumbnail_slider').slick({
 	 slidesToShow: 5,
  	 slidesToScroll: 1,
 	 dots: false,
 	 arrows: false,
  	 centerMode: true,
 	 focusOnSelect: true
	});
});
```
should work.

**Comment by m1llipede** [comment]
You're a genius. It works perfectly now, thank you so much for the help! Do you have a Patreon or something, I'd love to contribute.

**Comment by mpetroff** [comment]
I don't have a Patreon account, but I do have a [Ko-fi page](https://ko-fi.com/mpetroff). I'm glad I could be of assistance.
