### ISSUE TITLE
Generate.py for multiple images or folder

### ISSUE THREAD

**Issue by SwennySGIS** [mpetroff/pannellum#895]
Hi,
Thank you for you work ! 

I was wondering if it's possible to run the "generate.py", to create multires panorama, in a folder or/and for multiple images at the same time. 
At least it would be cool. 

Thank you for your time.

**Comment by Riclim** [comment]
A simple shell script would do the job.

**Comment by SwennySGIS** [comment]
hey,
Thanks for the answer but yeah, i did a simple shell script and it worked pretty well. 
Thx

**Comment by mpetroff** [comment]
It's also possible by piping a few *nix commands together, e.g., `find . -type f -name '*.jpg' -print0 | xargs -0 -I % basename % .jpg | xargs -I % path/to/generate.py -o % %.jpg` will process all `.jpg` images in the current directory.
