### ISSUE TITLE
Help with Content Security Policy meta tag

### ISSUE THREAD

**Issue by antoniorodc** [mpetroff/pannellum#898]
Hi,

When try to use pannelum.js image not load because browser give this error:

Refused to load the image 'blob:https://www.mysite.com/36af20e2-bfdc-448d-828c-f8b029ce3215' because it violates the following Content Security Policy directive: "default-src https: data: 'unsafe-inline' 'unsafe-eval'". Note that 'img-src' was not explicitly set, so 'default-src' is used as a fallback.

I tried set the correct meta tag but I can't found it.

Can you help me with this error?

Regards.

**Comment by mpetroff** [comment]
You need to add `blob:` to your content security policy sources. You're currently allowing only `https:` and `data:` URIs.

**Comment by antoniorodc** [comment]
I already knew that that I need add blob: but my mistake was that I add in meta-tag http-equiv in webpage, in this way not work. I needed add header in nginx server and now work perfectly.

Thank you for your help, anyway.
