### ISSUE TITLE
image is very large,can it delay loading?

### ISSUE THREAD

**Issue by bozomoyy** [mpetroff/pannellum#899]
The panoramic image I need to load is very large,about 95Mb. It takes a long time to load. Can it delay loading? Or is there any other ways？

**Comment by mpetroff** [comment]
This is what Pannellum's [multiresolution format](https://pannellum.org/documentation/examples/multiresolution/) is for, which splits the image into many small tiles such that it can be quickly loaded as needed. An equirectangular image can be converted into this format using the [`generate.py`](https://github.com/mpetroff/pannellum/blob/master/utils/multires/generate.py) script.
