### ISSUE TITLE
Windows Edge Browser - Translate Z issue

### ISSUE THREAD

**Issue by pc9geek** [mpetroff/pannellum#90]
A small issue with positioning hotspots on windows Edge browser, the Translate Z value is too large and the translation does not occur so the hotspot is not shown.

suggested fix is to reduce the order of mangitude of the translation.

From this...
var transform = 'translate(' + (-canvas.width /
                hfovTan * Math.sin((-hs.yaw + config.yaw) * Math.PI / 180) *
                hsPitchCos / z / 2 + canvas.width / 2 - 13) + 'px, ' +
                (-canvas.width / hfovTan * (hsPitchSin *
                configPitchCos - hsPitchCos * yawCos * configPitchSin) / z / 2 +
                canvas.height / 2 - 13) + 'px) translateZ(1000000000px)';

to this...
var transform = 'translate(' + (-canvas.width /
                            hfovTan * Math.sin((-hs.yaw + config.yaw) * Math.PI / 180) *
                            hsPitchCos / z / 2 + canvas.width / 2 - 13) + 'px, ' +
                            (-canvas.width / hfovTan * (hsPitchSin *
                                    configPitchCos - hsPitchCos * yawCos * configPitchSin) / z / 2 +
                                    canvas.height / 2 - 13) + 'px) translateZ(10000px)';

may also like to reduce the value in the main css file too.

**Comment by mpetroff** [comment]
I have to check if the smaller value still works in Safari. The translation was introduced in 01d5352a5d4eea4972ee123729044c81ff025de7 to fix a Safari bug.

**Comment by mpetroff** [comment]
I made the translation absurdly large to be on the safe side since it didn't seem to have any negative effects at the time. Since 9999px still works in Safari while also fixing this issue, I changed it to that.
