### ISSUE TITLE
direction right-to-left makes hotspots move

### ISSUE THREAD

**Issue by k1p0d** [mpetroff/pannellum#903]
Hey,

I've spotted a bug.. I used pannellum(Its great by the way!) in a page which has CSS of "direction: ltr" and it seems like it ruin the translation 
of the location of the hotspots and as a result the user will experience a "moving hotspots"

**Comment by mpetroff** [comment]
I'm pretty sure you meant to write `direction: rtl`. I set `direction: ltr` on the Pannellum container element in 1d951e3d03ea7d5e8ebb5370514492edba147993 to avoid issues with positioning. If you want right-to-left text in hot spot tool tips, you can add `div.pnlm-tooltip:hover span{ direction: rtl; }` to your CSS.

**Comment by k1p0d** [comment]
whoops.. yes exactly "direction: rtl" 👍 
This is exactly how i dealt with the case. 
I thought it might help someone someday since it took me time to isolate the cause of the "moving hotspots"

**Comment by georgebrook** [comment]
Hi @mpetroff @k1p0d I am having some issues with this myself, I just want to ask, wehre are you passing that property? into the viewer like so?

`
        pannellum.viewer(id, {
          direction: 'rtl',
          type: effectType,
          panorama: imgSrc,
          pitch: virtualTourPitch,
          yaw: virtualTourYaw,
          hotSpots: hotspots,
        });
`

My hotspots are still flying around..

I'm using "pannellum": "^2.3.2"

**Comment by mpetroff** [comment]
No, it's CSS. You need to `div.pnlm-tooltip:hover span{ direction: rtl; }` to your CSS.

**Comment by georgebrook** [comment]
Thanks @mpetroff sorted it now!
