### ISSUE TITLE
Set Hot spots without new tab

### ISSUE THREAD

**Issue by Collab07** [mpetroff/pannellum#908]
Is it possible to set Hot spots without opening a new tab? 
When I set Hot spots as usual, the linked page opens as a new tab. But, I'd like to open it as same with the present page.

**Comment by mpetroff** [comment]
Set the hot spot `attributes` parameter to `{}`. By default, the `target` attribute is set to `_blank`, which opens the link in a new tab; this is done since Pannellum is frequently used in an `<iframe>`, so it doesn't make sense to load the link in the same place.

**Comment by Collab07** [comment]
Okay... So, what should I do? Can you show the example?

**Comment by mpetroff** [comment]
```json
{
    "type": "equirectangular",
    "panorama": "image.jpg",
    "hotSpots": [
        {
            "pitch": 14.1,
            "yaw": 1.5,
            "type": "info",
            "text": "hot spot",
            "attributes": {}
        }
    ]
}
```

**Comment by Collab07** [comment]
Thank you!!
