### ISSUE TITLE
Full screen button on iphone

### ISSUE THREAD

**Issue by lavarich** [mpetroff/pannellum#915]
Hi how to enable full screen view button on iphone? All devices have a button on Ipad, android mobile, desktop, but on iphone there is no button.

<img width="119" alt="Снимок экрана 2020-09-18 в 22 46 39" src="https://user-images.githubusercontent.com/68279318/93638986-f2e10a80-fa00-11ea-84e9-55f27d95e7f3.png">

**Comment by mpetroff** [comment]
Convince Apple to support the fullscreen API in Safari on the iPhone. For iOS, Safari only supports the fullscreen API for iPads: https://caniuse.com/fullscreen

**Comment by mpetroff** [comment]
Duplicate of #467, #313, #309, and #66.
