### ISSUE TITLE
Rotation is false - West is East

### ISSUE THREAD

**Issue by oberator** [mpetroff/pannellum#916]
Just saw that the orientation/rotation of the compass feature is incorrect. If you turn the image rightways it should show "east" but the compass shows west.
It's even wrong on your "library" example - https://pannellum.org

Thanks for your great work

**Comment by mpetroff** [comment]
No, it isn't. Here is the view facing east:
![Screenshot from 2020-09-19 11-20-08](https://user-images.githubusercontent.com/1450212/93670549-2a37d180-fa6a-11ea-9002-04b3dda16d67.png)

The compass correctly shows that the view is facing to the east; the needle points to the left, which is north.

**Comment by oberator** [comment]
Well that's embarrassing... 
You're absolutely right. 

Thanks for your quick response.
