### ISSUE TITLE
Mutiple custom tooltip styles

### ISSUE THREAD

**Issue by DStillingfleet** [mpetroff/pannellum#920]
Hi Matthew

I would like to be able to use multiple custom tooltip styles with a pannellum scene.

As an example, directional hotspots tooltip might have tooltips that are styled to look like direction signs on a highway. Whilst information hotspots tooltip might be styled to look like a heritage sign.

Is there already a way to do this that I've overlooked?

Best wishes

Derek

**Comment by mpetroff** [comment]
While the [custom hot spots example](https://pannellum.org/documentation/examples/custom-hot-spots/) only shows a single style, there's no limitation preventing use of multiple styles. If you provide a different `createTooltipFunc` and `cssClass` parameters to different hot spots, you should get different styles.

**Comment by DStillingfleet** [comment]
Thanks Matthew

 

I hadn’t  realised that multiple createTooltipFunctions could be used with Pannellum, but now you’ve told me it makes perfect sense, and yes it works.

 

 

Best wishes

 

 

Derek
