### ISSUE TITLE
Hugin yaw/pitch/roll values

### ISSUE THREAD

**Issue by Elbandi** [mpetroff/pannellum#921]
I try to write a mini script to export preview image from panorama. The starting point is found by pannellum (getYaw, getPitch).
But if i set this value in hugin, it's display different angle. I'm not familiar in geometry, can you help me how to calculate the hugin YPR values from pannellum yaw+pitch?

**Comment by mpetroff** [comment]
Pannellum uses intrinsic z-y′-x″ Tait–Bryan angles, while Hugin uses extrinsic z-y-x Tait–Bryan angles (I think). Here's a Python code snippet that will do this conversion:

```python3
import numpy as np
from scipy.spatial.transform import Rotation as R

# Convert Pannellum [yaw, pitch, roll] to Hugin [yaw, pitch, roll]
pnlm_ypr = [60, 30, 0]
hugin_ypr = R.from_euler('ZYX', pnlm_ypr, degrees=True).as_euler('zyx', degrees=True) * np.array([1, -1, 1])
```

I only tested a couple coordinates, so there may still be convention issues (sign or order).

**Comment by Elbandi** [comment]
Thx the info, ```* np.array([-1, -1, -1])``` gives meg the right signs.
