### ISSUE TITLE
select an area of panorama

### ISSUE THREAD

**Issue by neetudas24** [mpetroff/pannellum#923]
Hi @mpetroff !
Is it possible to select a square area in panorama and get the coordinates?
I have a requirement to select an area of panorama and use that area either for annotation or image editing. So please let me know if this is possible.

Thanks

**Comment by mpetroff** [comment]
Pannellum does not support selecting or annotating areas. Hot spots can only be added as point annotations.

**Comment by neetudas24** [comment]
Thanks @mpetroff !
