### ISSUE TITLE
Partial Panorama Problem

### ISSUE THREAD

**Issue by AlessioBarbanti** [mpetroff/pannellum#934]
Hi!

I am developing a project for the university and my tutor has asked me to visualize a partial panorama without seeing the black bands around the main image.
So I decided to change the hfov field in function of the resolution used by the device on which it is played (desktop or mobile), unfortunately I could not find a correlation between the correct hfov and the ratio between the height and width of the screen. 
What can I do?

```javascript
             "Hall1": {

                    "title": "Hall1",
                    "yaw": 0,
                     "minYaw": -179, //metà di haov //2 line for preventing 360° movement
                     "maxYaw": 179,
                    "minPitch": 0, //prevent scrolling y-axys
                    "maxPitch": 0,
                    "haov": 360, // this parameter is ok
                    "vaov": 86, //????
                    "hfov": 64, //???
                     "minHfov": 50, //seems fine (?)
                     "maxHfov": 100, //seems fine (?)
                      [...omissis...]

```
my css for #panorama is just "take the whole screen" 
p.s. I apologize for the bad English (i'm italian ^^") and for opening a question in the "issue" section.
Greetings, Alessio.

**Comment by mpetroff** [comment]
Setting the `avoidShowingBackground` configuration parameter to `true` should achieve the effect you're describing.
