### ISSUE TITLE
Error multires generate.py

### ISSUE THREAD

**Issue by josepgomes** [mpetroff/pannellum#936]
Hi,

I'm trying to generate a multires with generate.py tool.

Command: python3 generate.py -n /Users/josegomes/Desktop/3dexample/nona /Users/josegomes/Desktop/3dexample/background2.jpeg

I have the nona executable and the image in the same folder, from where i'm running the previous command. I cannot understand the error reason. Am i doing something wrong?

![image](https://user-images.githubusercontent.com/3487504/99611835-4c1ee780-2a0c-11eb-9bcf-adbe9c0dff69.png)

Many thanks!

**Comment by mpetroff** [comment]
This is a problem with your `nona` installation. You're using a dynamically-linked binary, but the `libhuginbase.0.0.dylib` library file is not somewhere where your system can find it. I don't use a Mac, so I can't help you with this. Regardless, it's an issue with the installation of a dependency, not an issue with the `generate.py` script itself.
