### ISSUE TITLE
open the hotspot link in a specified different frame/page

### ISSUE THREAD

**Issue by almarass1** [mpetroff/pannellum#937]
Hi,
I tried to open a link associated with a hotspot  in the same window of the displayed panorama.
The following code does not seem to work:    
 {
            "pitch": 6.35,
            "yaw": -41,
       	    "cssClass": "custom-hotspot",
            "text": "Corredi funerari",
	    "attributes": {},
            "URL": "vetrina3/frameR.html" 
        },

Which is the correct syntax for "attributes"? Is it possible to open the hotspot link in a specified different frame/page?
Thanks

**Comment by mpetroff** [comment]
The default in v2.5.6 is `{"target": "blank"}`, and the default in the `master` branch is currently `{"target": "blank", "rel": "noopener"}`.

The `attributes` parameter only allows you to set attributes for the [`<a>` element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a), so it only allows for behavior that a standard link allows. With this functionality, you can only open a link in a new tab, the current context, the parent context, or the top level context; you can't specify it to open in a specific frame. The alternative is to use the `clickHandlerFunc` parameter to specify a JavaScript function to execute, which gives you more flexibility.

**Comment by almarass1** [comment]
As a matter of fact, my code used 2.3 version. Now it uses 2.5.6 and attributes parameter behaves correctly.
The clickHandlerFunc parameter solved my problem to open the hotspot link in a specified different frame/page.
Thanks

**Comment by mpetroff** [comment]
Glad to hear you got it working. For reference, the `attributes` parameter was added in v2.5.0.
