### ISSUE TITLE
No way to control zoom friction the way we can with panning

### ISSUE THREAD

**Issue by ghost** [mpetroff/pannellum#946]
Currently when zooming in / out, friction property does not apply.

This gives me the problem that you cannot set the zoom to the desired level using mouse scroll, since it glides past that zoom level. There is not enough granularity, so it always drifts to the extremes, whereas I want to get back to more or less 90 hfov after zooming in / out.

Here are my min, max, and starting zoom levels (using horizontal field of view):
```
    hfov: 120,
    minHfov: 90,
    maxHfov: 150,
 ```
 
 I tried increasing friction but this only affected left/right/up/down panning.
 
 Thanks.

**Comment by mpetroff** [comment]
> I tried increasing friction but this only affected left/right/up/down panning.

I cannot reproduce this issue in Firefox 84 or Chromium 87 on Linux. Setting `friction: 1.0` completely disables any "gliding" when using the mouse wheel.

With the default value for friction, I agree that for extremely wide HFOV, it zooms out too fast. In 6afcee4, I made a change to scale up the friction for extremely wide HFOV to help with this.
