### ISSUE TITLE
Invoking orientation permission on Iphone

### ISSUE THREAD

**Issue by janeholson** [mpetroff/pannellum#948]
Gracefully thanking you for producing such an awesome viewer and opening up huge opportunities for people like me to learn and I'm sure many micro economies that have made a living as a result of this.

I'm using the player in my university project to make my coursework more interactive for assessment. 

I noticed IF the "autoLoad": true setting is used then the player will not request permission for orientation for IPhones -The user must invoke the permission request by clicking the toggle icon and then the permission request appears OR I must turn off the autoload and when clicking start it requests permission. 

Is there a way it can request it automatically or when auto loading the scene -I've enabled "orientationOnByDefault": true and of course it works as intended for all other mobiles except Iphones (I'm using SSL connection too).

I'm not exactly a programmer but can confidently implement suggestions that might make this work.

**Comment by mpetroff** [comment]
Apple explicitly disallows this. Requests for orientation permission must be initiated by a user action; it cannot be requested automatically.

**Comment by janeholson** [comment]
@mpetroff Yeah I get that.
I'll find a solution to conditionally set "autoLoad" to false for ios devices.

thanks anyway
