### ISSUE TITLE
Continuous rotation vertically

### ISSUE THREAD

**Issue by lmmurtuza** [mpetroff/pannellum#949]
Hi,

I have a Pannellum set up for one of my project and it is working brilliantly. I have just got a new requirement where holding down the Up/Down arrow buttons(not the keyboard button. But HTML button) should keep rotating the viewer vertically unless mouse is released. I tried using setTimeout() but it is not smooth. What should be the timeout interval or is there any better way to achieve this?

Note: I am very new to Pannellum.

Thanks

**Comment by mpetroff** [comment]
I'd simulate `keydown` and `keyup` events with JavaScript when the mouse button is clicked and released, which should trigger the same functionality in Pannellum that is used when the arrow keys are pressed.
