### ISSUE TITLE
Objects that align with the rotation

### ISSUE THREAD

**Issue by ingo-lorenz** [mpetroff/pannellum#951]
Hey there,

is there an way to align Div-Elements with the Rotation of den Panorama?

Like a Picture on the Wall?

Thanks in advance

Ingo

**Comment by mpetroff** [comment]
Yes, see the [custom hot spots example](https://pannellum.org/documentation/examples/custom-hot-spots/) and some further discussion in #942. However, this only adjusts the position, so you won't get perspective distortion like a picture on a wall in a panorama would.
