### ISSUE TITLE
Handler function name in json file (HotSpots)

### ISSUE THREAD

**Issue by ingo-lorenz** [mpetroff/pannellum#953]
Hi there,

i have trouble by setting an handler function name in a valid JSON-file. How can i do this. The configuration needs an value without quotes at this point.

Is there an solution to use JSON config with handler functions?

I can´t find any notes about it or an example for that.

Thank you

Bye

Ingo

**Comment by DietRedThunder** [comment]
Dont think you can. 

You got to use the CSS.

RT

https://www.sidingstudios.com/dap2021/pannellum.htm#config=https://www.sidingstudios.com/dap2021/tour.json&autoLoad=true

**Comment by mpetroff** [comment]
The `clickHandlerFunc` parameter requires a JavaScript function, not a function name. Thus, it can't be configured via JSON, since a JavaScript function can't be included in JSON.
