### ISSUE TITLE
Way To List Available Scenes

### ISSUE THREAD

**Issue by designcomputer** [mpetroff/pannellum#958]
I am looking for a way to list Scenes that are currently available in an active Viewer to be used with loadScene() function.

**Comment by mpetroff** [comment]
This will give you an array of scene names (`viewer` is the Pannellum instance):
```javascript
var currentScenes = Object.keys(viewer.getConfig().scenes)
```

**Comment by designcomputer** [comment]
Thanks so much Matthew! I'll give that a try tonight.

**Comment by designcomputer** [comment]
That worked great Matthew. Thanks for pointing me in the right direction.
