### ISSUE TITLE
Was there any implications of there being a duplicate `isLoaded` function?

### ISSUE THREAD

**Issue by DStillingfleet** [mpetroff/pannellum#959]
Hi Matthew

Hope all is well,

I've noticed you've removed a duplicate of the 'isLoaded' function. 

In which version was this introduced, and were there any unintended side effects?

Only asking because I've previously noticed that the onload function can trigger prematurely and wondered if this is the cause.

Kind regards and best wishes

Derek

**Comment by mpetroff** [comment]
The second copy replaced the first copy, so there shouldn't have been any side effects. I somehow added the second copy (c361255438f6cee6d000e6b1604e8083c91ec34a) three days after adding the original copy (685e89b2e4a3b21f1f6d7aa51d10479e815d02a7), so there were two copies pretty much the entire time the method existed.

**Comment by DStillingfleet** [comment]
Okay, good to know, thank you Matthew.
