### ISSUE TITLE
Overlay buttons not visible on Microsoft Edge

### ISSUE THREAD

**Issue by JapaMala** [mpetroff/pannellum#96]
Hotspot, zoom, and fullscreen buttons are not visible on Microsoft Edge. IE works fine.

**Comment by mpetroff** [comment]
I am unable to reproduce this bug. The buttons are all visible for me in Microsoft Edge, both with Pannellum 2.1.1 and the Git master.

**Comment by JapaMala** [comment]
I'll try updating to git master then. Probably a glitch in the version I
got.

**Comment by JapaMala** [comment]
Just checked, and yep, the version I pulled was before this fix:
f64390d4426e4a0dca8b8dfb17f6979982f5446c
