### ISSUE TITLE
Lighthouse score reduced due to target="_blank" without rel="noopener"

### ISSUE THREAD

**Issue by DStillingfleet** [mpetroff/pannellum#960]
Hi Matthew

A small issue that may be of concern to some users that I thought to share.

Lighthouse performance testing throws up a concern about the security of links when  target="_blank".  It advises that the code rel="noopener" is added.

By adding this to the pannellum.js script I was able to improve the best practice rating to 100%.  

Kind regards and looking forward to the next release.

Derek

**Comment by mpetroff** [comment]
`rel="noopener"` was added in 776775f1d821b6b032a4c4175ceff20e21d66f36, so this has already been fixed. See #929.

**Comment by DStillingfleet** [comment]
Okay, thank you.
