### ISSUE TITLE
How to create irregular shaped div for use as a hotspot?

### ISSUE THREAD

**Issue by epignosis567** [mpetroff/pannellum#967]
I tried searching for this but I don't know how best to word it.

How could I create an irregularly / unequally shaped div to use as a hotspot? Something like a quadrilateral:

Parallelogram
Rhombus
Trapezoid
Kite

I'm really enjoying pannellum!

**Comment by epignosis567** [comment]
Nevermind this seems to work just fine!
https://www.w3schools.com/howto/howto_css_shapes.asp

**Comment by epignosis567** [comment]
Actually this one doesn't seem to work. I'm guessing because it uses skew deg? Any ideas if there's a way to use it?
https://www.w3schools.com/howto/tryit.asp?filename=tryhow_css_shapes_parallel

**Comment by mpetroff** [comment]
This isn't a support forum for how to use CSS, so your question is off-topic. I'm happy to answer question related to Pannellum, but this is a question on how to use CSS styling.

**Comment by epignosis567** [comment]
Thank you!
