### ISSUE TITLE
createTooltipArgs is not updating args for each hot spot

### ISSUE THREAD

**Issue by epignosis567** [mpetroff/pannellum#968]
So I've created a function to use with the `createTooltipFunc` as you suggested, and then I added some text for the `createTooltipArgs`, and the argument is getting passed, but it's always the same argument that gets passed. 
Here's a sample:

`
               "hotSpots": [
                    {            
                        "type": "scene",
                        "sceneId": "hallChar",
                        "cssClass": "extWindowMan",
                        "pitch": -12,
                        "yaw": -112,                        
                        "createTooltipFunc": showText, 
                        "createTooltipArgs": "Symptmes de Ruine", 
                    },
                    {            
                        "type": "scene",
                        "sceneId": "threeBuildingsIce",
                        "cssClass": "extWindowBuilding",
                        "pitch": 15,
                        "yaw": 25,                        
                        "createTooltipFunc": showText, 
                        "createTooltipArgs": "The Office",
                    },
]
` 

The problem is that when I try to print out the argument it just keeps writing out the second argument, so:

`
        function showText(hotSpotDiv, args) {
            document.getElementById('textBeneath').innerHTML = args;
        }
`

Always writes "The Office" even if I'm hovering over the first hotspot.

**Comment by mpetroff** [comment]
The function is called when the hot spot is created, so when the scene is initialized. It is not called when the tooltip is shown.

Your function is display the argument for each hot spot in the same HTML element. Since the hot spots are all created at the same time, you just end up overwriting the content of the HTML element. If you use `console.log(args)` instead, you'll see that both arguments will be printed to the browser developer console.

**Comment by epignosis567** [comment]
Interesting. So I am assuming that I need to create an separate function for each hotspot then? I was thinking I could just use one function and one div and then a new argument would be passed to it each time.

**Comment by epignosis567** [comment]
Sorry I know this is moving into customization territory I think I'm just confused about the scrollWidth maybe. I would like to just use the code you posted in a previous question but customize it:

        function hotspot(hotSpotDiv, args) {
            hotSpotDiv.classList.add('tooltipStyle');
            
            var span = document.createElement('span');
            span.innerHTML = args;
            
            hotSpotDiv.appendChild(span);
            span.style.width = span.scrollWidth - 20 + 'px';
            span.style.marginLeft = -(span.scrollWidth - hotSpotDiv.offsetWidth) / 2 + 'px';
            span.style.marginTop = -span.scrollHeight - 12 + 'px';
            
            //add mouseover listener to hotspot div
            hotSpotDiv.addEventListener('mouseover', onHover, 'false');
            hotSpotDiv.addEventListener('mouseleave', onLeave, 'false');
        }

The issue is that no matter what I try the tooltip seems to be attached to the hotspot div (due to the appendChild on the span I assume) and it moves around with the panorama when I pan it. I would like to fix it to one position at the bottom of the the panorama or below it but nothing seems to work. 

        // custom hot spot creation function
        function hotspot(hotSpotDiv, args) {
            hotSpotDiv.classList.add('tooltipStyle');
            
            var span = document.createElement('span');
            span.innerHTML = args;
            
            var botDiv = document.getElementById("bottomDiv");
            botDiv.appendChild(span);
            span.style.width = span.scrollWidth - 20 + 'px';
            span.style.marginLeft = -(span.scrollWidth - botDiv.offsetWidth) / 2 + 'px';
            span.style.marginTop = -span.scrollHeight - 12 + 'px';
            
            //add mouseover listener to hotspot div
            hotSpotDiv.addEventListener('mouseover', onHover, 'false');
            hotSpotDiv.addEventListener('mouseleave', onLeave, 'false');
        }

**Comment by epignosis567** [comment]
Also, so all the args write at the exact same time on load? How is it that your tooltip function is able to only display the corresponding arg on hot spot div hover? No matter what I try all the the args write on load and and I can't just extract one and assign it to a corresponding hot spot div.

**Comment by epignosis567** [comment]
> Your function is display the argument for each hot spot in the same HTML element. 
So does your function though... the all go into a span element right?

>Since the hot spots are all created at the same time, you just end up overwriting the content of the HTML element. 
But why doesn't yours do that in the span?

**Comment by mpetroff** [comment]
I think this code snippet should do what you want. It's based on what I posted in https://github.com/mpetroff/pannellum/issues/962#issuecomment-791418036.
```javascript
viewer = pannellum.viewer('panorama', ﻿{
    ...
    "hotSpots": [
        {
            "pitch": 10.0,
            "yaw": 10.0,
            "type": "info",
            "createTooltipFunc": hotspot,
            "createTooltipArgs": "Your hot spot text"
        }
    ]
});

function hotspot(hotSpotDiv, args) {
    hotSpotDiv.classList.add('pnlm-tooltip');
    hotSpotDiv.appendChild(span);
    span.style.width = span.scrollWidth - 20 + 'px';
    span.style.marginLeft = -(span.scrollWidth - div.offsetWidth) / 2 + 'px';
    span.style.marginTop = -span.scrollHeight - 12 + 'px';
    
    hotSpotDiv.addEventListener('mouseover', function() {
        document.getElementById('textBeneath').innerHTML = args;
    }, 'false');
}
```

You were trying to use the hot spot creation function to trigger a `mouseover` event. This works for the hot spot tooltips, since they're displayed using the CSS `:hover` pseudoselector, but it won't work for updating an element elsewhere.

**Comment by epignosis567** [comment]
Thanks! I should have clarified that was the code snippet I was referencing. So you are saying that it is not possible to adapt the tooltip functionality in order to toggle a div outside of the panorama div correct? Or even to toggle a div inside the panorama div but at a fixed position near the bottom (ie won't pan with the panorama)?

Here's what I ended up putting together. I'm just creating a uniquely named function for each hotspot, but it's the exact same as the one before it. Let me know if you think there's an easier, less repetitive way of doing it by building on the code that already exists.

            "hotSpots": [
                {
                    "pitch": 10,
                    "yaw": 0,
                    "cssClass": "hotSpotStyle",
                    "text": "hello",
                    "createTooltipFunc": hotspot,
                    "createTooltipArgs": "The Office of Memory",
                },
                {
                    "pitch": 10,
                    "yaw": 40,
                    "cssClass": "hotSpotStyle",
                    "createTooltipFunc": hotspot2,
                    "createTooltipArgs": "Art Museum Drive"
                }
            ],
            "autoLoad" : true
        });

        // custom hot spot creation function
        function hotspot(hotSpotDiv, args) {        
            var span = document.createElement('span');
            span.innerHTML = args;

            var bottomDiv = document.getElementById("bottomDiv");       
            hotSpotDiv.onmouseover = function(){            
                bottomDiv.appendChild(span);
            }
            hotSpotDiv.onmouseleave = function(){            
                bottomDiv.removeChild(span);
            }
        ;}
        
        function hotspot2(hotSpotDiv, args) {        
            var span = document.createElement('span');
            span.innerHTML = args;

            var bottomDiv = document.getElementById("bottomDiv");       
            hotSpotDiv.onmouseover = function(){            
                bottomDiv.appendChild(span);
            }
            hotSpotDiv.onmouseleave = function(){            
                bottomDiv.removeChild(span);
            }
        ;}
        
And so on, creating duplicated functions for each new hotspot...

**Comment by mpetroff** [comment]
You don't need separate functions. Here's a complete tested example that displays text in an external `<div>` on mouse over:
```html
<!DOCTYPE HTML>
<html>
<head>
    <meta charset="utf-8">
    <title>Test Example</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/pannellum@2.5.6/build/pannellum.css"/>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/pannellum@2.5.6/build/pannellum.js"></script>
    <style>
    #panorama {
        width: 600px;
        height: 400px;
    }
    </style>
</head>
<body>

<div id="panorama"></div>
<div id="bottomDiv"></div>

<script>
// Create viewer
viewer = pannellum.viewer('panorama', ﻿{
    "panorama": "examplepano.jpg",
    "hotSpots": [
        {
            "pitch": -12,
            "yaw": 170,
            "type": "info",
            "createTooltipFunc": hotspot,
            "createTooltipArgs": "Test text 1"
        },
        {
            "pitch": -10,
            "yaw": -50,
            "type": "info",
            "createTooltipFunc": hotspot,
            "createTooltipArgs": "Test text 2"
        }
    ]
});

function hotspot(hotSpotDiv, args) {
    var span = document.createElement('span');
    span.innerHTML = args;
    hotSpotDiv.classList.add('pnlm-tooltip');
    hotSpotDiv.appendChild(span);
    span.style.width = span.scrollWidth - 20 + 'px';
    span.style.marginLeft = -(span.scrollWidth - hotSpotDiv.offsetWidth) / 2 + 'px';
    span.style.marginTop = -span.scrollHeight - 12 + 'px';
    
    var bottomDiv = document.getElementById('bottomDiv');
    var span2 = document.createElement('span');
    span2.innerHTML = args;
    hotSpotDiv.addEventListener('mouseover', function() {
        bottomDiv.appendChild(span2);
    }, 'false');
    hotSpotDiv.addEventListener('mouseleave', function() {
        bottomDiv.innerHTML = '';
    }, 'false');
}
</script>

</body>
</html>
```

**Comment by epignosis567** [comment]
Oh wow, very interesting! Ok I will try this and report back. I was no able to get this to work at all. Thanks so much!
