### ISSUE TITLE
pannellum isn't showing my image

### ISSUE THREAD

**Issue by terrafrost** [mpetroff/pannellum#969]
Here's my code:

```
<div id="demo"></div>

<script>
pannellum.viewer('demo', {
    'type': 'equirectangular',
    'panorama': '//terrafrost.sfo2.digitaloceanspaces.com/unnamed02/GS__0113.JPG',
    'autoRotate': 10,
    'autoLoad': true,
    'pitch': 0,
    'yaw': 0
});
</script>
```

Here's the code on JS fiddle:

https://jsfiddle.net/ob2gvu14/2/

Any ideas?

**Comment by mpetroff** [comment]
You're not specifying a size for your `<div>`. Thus, the browser uses the default size of 0px x 0px. You need to specify a height and a width for the `#demo` element.
