### ISSUE TITLE
disable the mouse interaction when click on a button 

### ISSUE THREAD

**Issue by AfnanBq** [mpetroff/pannellum#972]
Hello Matthew, 
Thank you for this amazing script! 
I would like to ask you if there is a possible way to disable the mouse interaction when I click on a button rather than set the value of draggable to false once I initialize the viewer?

**Comment by mpetroff** [comment]
No, not at the moment. It's currently only configurable on initialization.

**Comment by AfnanBq** [comment]
thanks for your response!
Well, I have last question can I fixed or freeze a scene in the cubemap, for example if i click on a button then the current scene is fixed?

**Comment by mpetroff** [comment]
You can extract the current view with:
```javascript
viewer.getRenderer().render(viewer.getPitch() / 180 * Math.PI, viewer.getYaw() / 180 * Math.PI, viewer.getHfov() / 180 * Math.PI, {returnImage: true});
```
where `viewer` is the Pannellum viewer instance; this returns the view as a PNG image encoded as a data URI. Alternatively, you can disable all interaction (not just mouse interaction) with:
```javascript
viewer.setPitchBounds([viewer.getPitch(), viewer.getPitch()]);
viewer.setYawBounds([viewer.getYaw(), viewer.getYaw()]);
viewer.setHfovBounds([viewer.getHfov(), viewer.getHfov()]);
```

**Comment by AfnanBq** [comment]
Thanks a million, dear Matthew. It works as I wanted:).
