### ISSUE TITLE
Hospot is overlapping with control UI

### ISSUE THREAD

**Issue by tokidoki11** [mpetroff/pannellum#975]
I find out that Control UI is being overlapped by hotspots
<img width="1552" alt="スクリーンショット 2021-03-24 18 12 13" src="https://user-images.githubusercontent.com/7564844/112284421-91aa3480-8ccc-11eb-9d5f-36f82ec160ee.png">

I came out with solution as well

- panellum-container should instead have these 2 div in this order

1. pnlm-render-container
2. pnlm-ui

- remove z-index of plnm-ui

<img width="1552" alt="スクリーンショット 2021-03-24 18 11 49" src="https://user-images.githubusercontent.com/7564844/112284452-9bcc3300-8ccc-11eb-9c04-ae1dc83f7659.png">
<img width="1552" alt="スクリーンショット 2021-03-24 18 11 34" src="https://user-images.githubusercontent.com/7564844/112284486-a4bd0480-8ccc-11eb-8fb6-b6247b48f833.png">

**Comment by tokidoki11** [comment]
As for now I override the css with this
```
div.pnlm-ui {
  z-index: auto;
  .pnlm-dragfix {
    z-index: 1
  }
  .pnlm-controls-container {
    z-index: 2
  }
}
```

**Comment by mpetroff** [comment]
Thanks for figuring this out! I noticed this issue last month, but my brief attempt at fixing it (ab423f66ea36e46d92d109e559818a0685971006) was unsuccessful.

**Comment by strarsis** [comment]
@mpetroff: Could a test be added to prevent this from happening again? Like an emulated drag/click on the hotspot to check whether the click "goes through"?

**Comment by mpetroff** [comment]
So while my first attempt at a fix didn't work, my second one (5f0a1d8662272cae87ad23d367ab041ca3a2d34a) did. I had forgotten about that. I just reverted the additional changes made in 7362f5c948e17370a9368ccc23895dd8a1e16668, since they aren't necessary in my testing.

@tokidoki11 Can you confirm that you don't see this issue in the current Git `master` branch? If you do still see the issue, please report the browser, browser version, and OS.

@strarsis Good idea! I added an additional unit test to check for this in 74b83191928fb0b39fb2888adb7be1f5daad1d0a.

**Comment by adrien44** [comment]
I hope it's okay to add this here, but I came across a very similar issue.
when a hotspot is clicked and its content is showing, it is overlapped by other hotspots.
one solution could be to have an active class on the clicked hotspot to give him a stronger z-index.
I tried to do it but my skills are limited and I can not find a way to do it.

**Comment by adrien44** [comment]
I did find a way, I think this is far from being a nice solution but it works
`
var zindex = 10;
function overlap(arg) {
  $(arg.toElement).css('z-index',zindex);
  zindex++;
}
`
And i call this function in the hotSpots arguments of my viewer 
`
"hotSpots": [
  {
    'pitch':pitch,
    'yaw':yaw,
    'type':type,
    'text':$.trim(text.replace(/[\t\n]+/g,' ')),
    'clickHandlerFunc': overlap
  },
  {
    'pitch':pitch,
    'yaw':yaw,
    'type':type,
    'text':$.trim(text.replace(/[\t\n]+/g,' ')),
    'clickHandlerFunc': overlap
  }
]
`
