### ISSUE TITLE
hotspot draggable not working

### ISSUE THREAD

**Issue by LiamS090** [mpetroff/pannellum#977]
firstly thanks for this awesome open source, I am currently build an app for users to configure virtual tours and without pannellum this wouldnt of happened.

But I think im missing something when it comes to making hotspots draggable, from what I have read that setting draggable: true, on the hotspot. Should be enough to make the hotspots able to be dragged into a new place, however I am struggling to get this to work. do I need to set  dragHandleFunc: and dragHandlerArgs: if anyone has more information on dragging hotspots it would be appreciated.

update it appears i am currently using the 2.5.6 2019 release which does not contain any of the dragHandler functions. so my new question is how can i use the js file 2021 not 2019

**Comment by mpetroff** [comment]
Yes, the draggable hot spot functionality has not yet made it into a release. You can either use the `src/js/pannellum.js`, `src/js/libpannellum.js`, `src/css/pannellum.css`, and `src/css/img/*.svg` files directly from the Git repository, or you can use the `utils/build/build.py` script to create combined minified files like those in the releases (see the _Building_ section of the readme).

**Comment by LiamS090** [comment]
Thank you

**Comment by patricklenert** [comment]
Is it now released?

**Comment by mpetroff** [comment]
No, there hasn't been a new release.
