### ISSUE TITLE
Problems with 'scenechange'

### ISSUE THREAD

**Issue by epignosis567** [mpetroff/pannellum#979]
Hi. I'm trying to have a unique ambient sound playing in each scene. I've tried using the method method referenced in a previous [question](https://github.com/mpetroff/pannellum/issues/964):

        viewer.on('scenechange', function(extWindow) {
            var extWindowAmbience = document.getElementById("extWindowSound");
            extWindowAmbience.play();
            console.log(extWindow);
        });

        viewer.on('scenechange', function(hallChar) {
            var hallCharAmbience = document.getElementById("hallCharSound");
            hallCharAmbience.play();
            console.log(hallChar);
        });

However, there are multiple problems. 
The first on 'scenechange' doesn't work because it's the first scene that is already loaded (I assume),
but then, oddly, the second one plays both sounds simultaneously and prints 'hallChar' to the console twice as well. 
Any ideas? It seems to just execute the function on ANY scene change, when I'm looking to execute specific functions when specific scenes are transitioned to.

**Comment by epignosis567** [comment]
I think what I'm really looking for (in order to avoid future issues) is a way to have a collection of functions per scene. Is something like that possible? Such as 
'in scene #1 play ambient sound #1 and on mousedown do function #1' 
then 
'in scene #2 play ambient sound #2 and on mousedown do function #2' etc...

**Comment by mpetroff** [comment]
Does https://github.com/mpetroff/pannellum/issues/964#issuecomment-813716543 not work? The other way would be to have a single `HTMLAudioElement` and change its `src` property in the event listener.

To handle clicks, you'd need a `mousedown` event listener. In it, you could call `viewer.getScene()` to get the current scene ID and act accordingly.

**Comment by epignosis567** [comment]
I’m still working on this and I’ll report back. Thanks

**Comment by epignosis567** [comment]
Still working on this I just got busy with my job. I'm hoping to be able to post back this weekend though.

**Comment by epignosis567** [comment]
Ok, I finally realized what you were suggesting, and that my way wasn't going to work at all. Here's what I ended up with. Please let me know if there's a smarter way to use getScene()

`
//scene sounds
viewer.on('scenechange', function () {
    bottomDiv.innerHTML = '';

    let sceneName = viewer.getScene();

    if (sceneName == 'hallChar') {
        ambientSounds.setAttribute('src', 'sounds/intdripping.mp3');
        ambientSounds.play();
        mouseDownSound.setAttribute('src', '');
    };
    if (sceneName == 'buildingsIce') {
        ambientSounds.setAttribute('src', 'sounds/extasylumquiet.mp3');
        ambientSounds.play();
        mouseDownSound.setAttribute('src', '');
    };
    if (sceneName == 'extFirePlane') {
        ambientSounds.setAttribute('src', 'sounds/ambientplane.mp3');
        ambientSounds.play();
        mouseDownSound.setAttribute('src', '');
    };
    if (sceneName == 'bigRoomIrene') {
        ambientSounds.setAttribute('src', 'sounds/steamtrainpassby.mp3');
        ambientSounds.play();
        mouseDownSound.setAttribute('src', '');
    };
    if (sceneName == 'stairs') {
        ambientSounds.setAttribute('src', 'sounds/intfootstepsreceeding.mp3');
        ambientSounds.play();
        mouseDownSound.setAttribute('src', 'sounds/musicboxsound.mp3');
    };
    if (sceneName == 'upstairsSom') {
        ambientSounds.setAttribute('src', '');
        ambientSounds.play();
        mouseDownSound.setAttribute('src', '');
    };
    if (sceneName == 'roofBirds') {
        ambientSounds.setAttribute('src', 'sounds/extsylumbirds.mp3');
        ambientSounds.play();
        mouseDownSound.setAttribute('src', '');
    };
    if (sceneName == 'windowWizard') {
        ambientSounds.setAttribute('src', 'sounds/littletune.mp3');
        ambientSounds.play();
        mouseDownSound.setAttribute('src', '');
    };

});
`

**Comment by mpetroff** [comment]
Your most recent code snippet is along the lines of what I was suggesting, calling `viewer.getScene()` in the event handler to get the current scene ID and then using it to choose which sound to play.
