### ISSUE TITLE
How do I fade out when switching scenes

### ISSUE THREAD

**Issue by SleepyShark709** [mpetroff/pannellum#983]
Hello Matthew, I have a question for you

I want the current scene to fade out when the scene is converted, and the second scene to fade in when the second scene is loaded

The current situation is that after switching the scene, the current scene will have no response, and then fade in and out after the second scene is successfully loaded. Is there any solution

**Comment by mpetroff** [comment]
If I correctly follow what you're asking, you want to know if it's possible to maintain interactivity in the first scene when switching to a new scene, not if it's possible to fade between scenes in general (which is already provided by the [`sceneFadeDuration` configuration parameter](https://pannellum.org/documentation/reference/#scenefadeduration-number)).

The rendering backend can only handle one scene at a time. Thus, for scene transition fades, a snapshot of the final view of the first scene is taken and overlayed on the renderer, the rendering backend is then switched to the new scene, and the snapshot is finally faded out once the new scene has loaded. As the rendering backend can only handle one scene at a time, maintaining interactivity is not possible with the current architecture.

**Comment by SleepyShark709** [comment]
Thank you for your reply. You are a great help to our project

I used HTML2Canvas to solve this problem by drawing the current scene onto Canvas and overlaying it on Pannellum

Thanks again for your reply and wish you all the best
