### ISSUE TITLE
Glitching in multires + tour

### ISSUE THREAD

**Issue by zootboy** [mpetroff/pannellum#99]
I've generated a multires pano with the python script. I'm using the same multires dir in two different pannellum instances: one just the single pano mode, and the other as part of a tour. The tour version exhibits some weird glitches in the pano, seeming like some textures are offset incorrectly. There's no visible gaps in the pano, however.

Attached screengrabs, and here's a set of links to my test pages:

http://seangreenslade.com/schroon/ (Tour, shows issue)

http://seangreenslade.com/panotest/ (Single, no issues)

![bad](https://cloud.githubusercontent.com/assets/4085499/12059175/1a1369f4-af24-11e5-8789-28fe7dadaaa7.png)

![good](https://cloud.githubusercontent.com/assets/4085499/12059177/1e4fe7c2-af24-11e5-9d15-201ee5967809.png)

**Comment by mpetroff** [comment]
In the tour, you have the cube resolution set to 8904, while in the standalone panorama, you have it set to 8640. If you correctly set the cube resolution in the tour to match the standalone panorama, I suspect the issue will go away.

**Comment by zootboy** [comment]
Wow, super quick response. Yep, that was it. Just a copy-paste error.

Thanks for making such a great pano viewer!
