### ISSUE TITLE
Help: Cartesian cooridinates from yaw and pitch radius

### ISSUE THREAD

**Issue by vlkpa** [mpetroff/pannellum#996]
Hello, in our admin web/browser app for creating static buttons in 360 images (for navigation/tour between 360 images) we use this tool Pannellum. In mobile app we use [React Viro](https://github.com/ViroCommunity/viro/blob/main/readmes/EXAMPLES.md#vr-examples) as a view of the tour = 360 images + buttons as links.
In Pannellum buttons/hotspots are positioned in 360 images with **yaw** and **pitch** (in radians).
ReactViro uses for positioning buttons Cartesian position as [x,y,z] .
Is there a way how to convert this yaw and pitch into Cartesian cooridinates?

**Comment by mpetroff** [comment]
This is a standard conversion between spherical coordinates and Cartesian coordinates (although the choice of radius is arbitrary). The Wikipedia page on spherical coordinates gives you the conversion formulas (in terms of the notation there, yaw is φ and pitch is θ): https://en.wikipedia.org/wiki/Spherical_coordinate_system#Coordinate_system_conversions
