### ISSUE TITLE
Calculate hFov to fit vertically a partial panorama knowing minYaw, maxYaw and the dimensions of the viewport 

### ISSUE THREAD

**Issue by arreumb** [mpetroff/pannellum#999]
Hello, 
I spent some time, without success, trying to calculate the hFov to fit vertically an equirectangular partial panorama to a viewport. Knowing minYaw, maxYaw, the dimensions of the panorama and the dimensions of the viewport how can I calculate the correct hFov to fit it exactly to the viewport hight ?

Many thanks in advance
Umberto

**Comment by mpetroff** [comment]
The `minYaw` and `maxYaw` parameters are irrelevant. You need to know the vertical field of view and the viewport width and height:

`hfov = Math.atan(Math.tan(vfov / 360 * Math.PI) * viewportWidth / viewportHeight) * 360 / Math.PI`

**Comment by arreumb** [comment]
Thanks a lot for your answer,  Matthew.
Umberto
